import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import { findBreedingResult, findParentPairs } from "../src/breeding.ts";
import { messages, messageCatalogs, translationProvenance } from "../src/i18n.ts";
import { resolveLocale } from "../src/config.ts";
import { expandRecipe, parseServerIni } from "../src/data.ts";
import { createAnalyticsTracker, installGtagQueue } from "../src/analytics.ts";

const data = await readFile("src/data.ts", "utf8");
const main = await readFile("src/main.ts", "utf8");
const featureStyles = await readFile("src/features.css", "utf8");
const config = await readFile("src/config.ts", "utf8");
const indexHtml = await readFile("index.html", "utf8");
const adsTxt = await readFile("public/ads.txt", "utf8");
const wranglerConfig = JSON.parse((await readFile("wrangler.jsonc", "utf8")).replace(/^\s*\/\/.*$/gm,""));
const palData = JSON.parse(await readFile("public/data/pals.json", "utf8"));
const itemData = JSON.parse(await readFile("public/data/items.json", "utf8"));
const imageManifest = JSON.parse(await readFile("public/assets/image-manifest.json", "utf8"));
const skillData = JSON.parse(await readFile("public/data/skills.json", "utf8"));
const mapImage = await readFile("public/assets/world-map.webp");

assert.match(data, /Math\.min\(32,\s*Math\.max\(1/, "server generator must clamp the official supported player range");
assert.doesNotMatch(data, /WorkSpeedRate|bEnablePlayerToPlayerDamage|bEnableDefenseOtherGuildPlayer/, "server generator must not emit parameters absent from the current official parameter list");
assert.match(data, /bIsPvP/, "server generator must use the current official PvP parameter");
assert.match(data, /bIsUseBackupSaveData/, "server generator must use the current official backup parameter");
const importedServer=parseServerIni("[/Script/Pal.PalGameWorldSettings]\nOptionSettings=(ServerPlayerMaxNum=12,bIsPvP=True,bIsUseBackupSaveData=False,UnknownKey=1)");
assert.deepEqual(importedServer.value,{players:12,pvp:true,backup:false},"server INI importer must parse supported keys");
assert.equal(importedServer.warnings.length,1,"server INI importer must warn about unsupported keys");
assert.match(data, /Recipe cycle/, "crafting engine must detect cycles");
assert.match(data, /Math\.ceil\(needed\s*\/\s*recipe\.output\)/, "crafting engine must round process counts up");
assert.match(main, /localStorage\.getItem\("pw-consent"\)!=="granted"/, "analytics and ads must require explicit consent");
assert.match(main, /import\.meta\.env\.PROD&&site\.adsenseClient/, "AdSense must be production-only and site-configured");
assert.match(main, /pagead2\.googlesyndication\.com\/pagead\/js\/adsbygoogle\.js\?client=/, "AdSense must use the authorized Google loader URL");
assert.match(main, /script\.crossOrigin="anonymous"/, "AdSense loader must use anonymous cross-origin mode");
assert.match(config, /G-FF7N186M72/, "Palworld Analytics measurement ID must be configured");
assert.match(config, /https:\/\/palworld-helper\.woofy\.blog/, "production origin must be configured");
assert.doesNotMatch(config, /palworld-helper\.example/, "placeholder production origin must not remain configured");
assert.doesNotMatch(config, /G-GPSMFR1377/, "superseded Analytics measurement ID must not remain configured");
assert.match(config, /vcYPQJf0I03LumjZIODPdq47ZnYMCRvD2ABcBFyBImQ/, "Palworld Search Console verification must be configured");
assert.match(config, /ca-pub-1986785092914105/, "owner-approved shared AdSense publisher must be configured");
assert.match(indexHtml, /name="google-site-verification" content="vcYPQJf0I03LumjZIODPdq47ZnYMCRvD2ABcBFyBImQ"/, "Search Console verification must exist in static HTML");
assert.match(indexHtml, /name="google-adsense-account" content="ca-pub-1986785092914105"/, "AdSense publisher metadata must exist in static HTML");
assert.equal(adsTxt.trim(),"google.com, pub-1986785092914105, DIRECT, f08c47fec0942fa0","ads.txt must use the exact owner-authorized account entry");
assert.equal(wranglerConfig.name,"palworld-helper","Wrangler project name must match the GitHub/project slug");
assert.equal(wranglerConfig.assets?.directory,"./dist","Wrangler must deploy only the verified static build output");
assert.equal(wranglerConfig.main,undefined,"static deployment must not introduce a Worker runtime");
assert.equal(wranglerConfig.assets?.not_found_handling,"single-page-application","collection and entity deep links must reuse the shared SPA document");
assert.match(main,/history\.replaceState\(\{\},"",localizePath\(locale,location\.pathname\)\)/,"unprefixed entry routes must normalize to the selected locale without another HTML document");
assert.doesNotMatch(main, /gtag\([^\n]*(search|pin|server|ini)/i, "analytics must not receive search, pin, or server free-form data");
assert.match(main, /send_page_view:false/, "SPA analytics must disable automatic page views to prevent duplicates");
assert.match(main, /installGtagQueue\(win\)/, "Analytics must install the official command queue before loading gtag.js");
assert.doesNotMatch(main, /gtag=\(\.\.\.args\)=>/, "Analytics must not queue ordinary arrays in place of Arguments commands");
assert.match(main, /collection_search",\{collection:/, "collection search may emit only a stable collection identifier");
assert.doesNotMatch(main, /trackEvent\([^\n]*(\.value|FormData|coordinate|query)/, "analytics events must not include free-form control values");

let analyticsConsent=false;
let analyticsPath="/en-US";
let analyticsLocale="en-US";
const analyticsTarget={};
const analytics=createAnalyticsTracker({
  consentGranted:()=>analyticsConsent,
  currentPath:()=>analyticsPath,
  currentLocale:()=>analyticsLocale,
  sender:()=>analyticsTarget.gtag
});
assert.equal(analytics.trackPageView(),false,"Analytics must not track before consent");
analyticsConsent=true;
assert.equal(analytics.trackPageView(),false,"Analytics must not consume the page before the sender is initialized");
installGtagQueue(analyticsTarget);
analyticsTarget.gtag("js",new Date(0));
analyticsTarget.gtag("config","G-FF7N186M72",{send_page_view:false});
assert.equal(analytics.trackPageView(),true,"consent initialization must emit the current page once");
assert.equal(analytics.trackPageView(),false,"same-path rerenders must not emit another page view");
analyticsPath="/en-US/pals";
assert.equal(analytics.trackPageView(),true,"a pathname change must emit one new page view");
assert.deepEqual(analyticsTarget.dataLayer.map(command=>Object.prototype.toString.call(command)),[
  "[object Arguments]","[object Arguments]","[object Arguments]","[object Arguments]"
],"every Google tag command must use an Arguments object");
assert.deepEqual(Array.from(analyticsTarget.dataLayer[2]),["event","page_view",{page_path:"/en-US",locale:"en-US"}],"the first consented page view must be queued with sanitized fields");
assert.deepEqual(Array.from(analyticsTarget.dataLayer[3]),["event","page_view",{page_path:"/en-US/pals",locale:"en-US"}],"SPA navigation must queue exactly one new page view");
assert.match(main, /fetch\("\/data\/pals\.json"\)/, "verified static Pal data must load from the same origin");
assert.equal(palData.meta.palCount, 299, "verified Pal count must remain stable for this game build");
assert.equal(palData.meta.palPortraitCount, palData.meta.palCount, "every published Pal must have a verified portrait");
assert.equal(palData.meta.localIdMatchCount, palData.meta.palCount, "every published Pal ID must match the local game export");
assert.equal(palData.pairs.length, 44851, "breeding table must remain complete for this source revision");
assert.equal(new Set(palData.pals.map(p=>p.id)).size,palData.pals.length,"Pal internal IDs must be unique");
assert.ok(palData.pals.every(pal=>pal.image===true),"every published Pal must retain its portrait flag after a Pal-data refresh");
for(const pal of palData.pals)await access(`public/assets/pals/${pal.id}.png`);
assert.equal(palData.workSuitabilities.length,12,"all currently published Pal work suitability types must have metadata");
assert.ok(palData.workSuitabilities.every(work=>Object.keys(work.names).length===17&&Object.values(work.names).every(Boolean)),"every work suitability must use all 17 official localized labels");
for(const work of palData.workSuitabilities)await access(`public${work.icon}`);
assert.equal(palData.pals.filter(pal=>pal.descriptions["en-US"]).length,296,"official English Paldeck long-description coverage must remain stable");
assert.equal(palData.pals.filter(pal=>pal.descriptions["ko-KR"]).length,296,"official Korean Paldeck long-description coverage must remain stable");
for(const pal of palData.pals)for(const description of Object.values(pal.descriptions)){
  assert.doesNotMatch(description,/<[^>]+>|Error_Code:|\|/,`${pal.id} descriptions must not expose game-runtime markup`);
}
assert.ok(palData.pals.every(pal=>!/이\(가\)|은\(는\)|을\(를\)|과\(와\)/.test(pal.descriptions["ko-KR"])),"Korean Pal descriptions must resolve selectable particles");
assert.match(palData.pals.find(pal=>pal.id==="PinkCat").descriptions["ko-KR"],/까부냥이 핥아/,"PinkCat description must resolve its localized name and Korean subject particle");
assert.match(palData.pals.find(pal=>pal.id==="LilyQueen").descriptions["ko-KR"],/태양 폭발/,"active-skill markup must resolve to the official localized skill name");
assert.match(main,/category==="habitat"\?!!habitatSelect\?\.value/,"selected Pal habitats must remain enabled independently from point layers");
const byId=new Map(palData.pals.map(p=>[p.id,p.i]));
assert.equal(findBreedingResult(palData.pairs,byId.get("Anubis"),byId.get("Anubis"),"WILDCARD","WILDCARD"),byId.get("Anubis"),"Anubis self-pair golden case must pass");
assert.equal(findBreedingResult(palData.pairs,byId.get("CatMage"),byId.get("FoxMage"),"FEMALE","MALE"),byId.get("CatMage_Fire"),"gender-specific special combination must take precedence");
assert.equal(findBreedingResult(palData.pairs,byId.get("CatMage"),byId.get("FoxMage"),"MALE","FEMALE"),byId.get("FoxMage_Dark"),"reversed gender-specific special combination must remain distinct");
assert.ok(findParentPairs(palData.pairs,byId.get("Anubis")).length>0,"target reverse lookup must return verified parent pairs");
assert.equal(itemData.meta.gameBuild,"24181527","item data must match the verified local game build");
assert.equal(itemData.items.length,1891,"only legal in-game items from this build must be published");
assert.equal(itemData.recipes.length,1286,"every recipe with legal product and ingredient references must be published");
assert.equal(itemData.meta.localeCount,17,"official item names must cover all supported interface locales");
assert.equal(imageManifest.gameBuild,itemData.meta.gameBuild,"image manifest must match the item data build");
const imagedItems=itemData.items.filter(item=>item.image===true);
assert.equal(imageManifest.itemCount,imagedItems.length,"item image manifest must match verified image flags");
for(const item of imagedItems)await access(`public/assets/items/${item.id}.webp`);
assert.equal(new Set(itemData.items.map(item=>item.id.toLowerCase())).size,itemData.items.length,"item IDs must be unique without case ambiguity");
const itemIds=new Set(itemData.items.map(item=>item.id));
assert.ok(itemData.items.every(item=>Object.keys(item.names).length===17&&Object.values(item.names).every(Boolean)),"every item must have all 17 official localized names");
assert.ok(itemData.recipes.every(recipe=>itemIds.has(recipe.productId)&&recipe.ingredients.every(i=>itemIds.has(i.itemId)&&i.count>0)&&recipe.output>0&&recipe.workAmount>=0),"every published recipe reference and numeric value must be valid");
assert.deepEqual(itemData.meta.caseCorrections,["FIber->Fiber","cloth->Cloth","cloth2->Cloth2","stone->Stone","wood->Wood"],"known source case differences must be explicit and deterministic");
const mega=itemData.recipes.find(recipe=>recipe.id==="PalSphere_Mega");
assert.deepEqual(mega?.ingredients,[{itemId:"Pal_crystal_S",count:1},{itemId:"CopperIngot",count:1},{itemId:"Wood",count:3},{itemId:"Stone",count:3}],"Mega Sphere golden recipe must match the extracted game table");
assert.deepEqual(itemData.map,{minX:-1099400,minY:-724400,maxX:349400,maxY:724400,width:8192,height:8192},"official map bounds and texture dimensions must remain stable for this build");
assert.equal(mapImage.subarray(0,4).toString("ascii"),"RIFF","published map must be a WebP container");
assert.equal(mapImage.subarray(8,12).toString("ascii"),"WEBP","published map must have the WebP signature");
assert.match(main,/fetch\("\/data\/items\.json"\)/,"verified item data must load from the same origin");
assert.match(main,/bounds\.minX.*bounds\.maxX.*bounds\.minY.*bounds\.maxY/,"map pins must be constrained to extracted official bounds");
assert.equal(resolveLocale("/ja-JP/database"),"ja-JP","an explicit URL locale must take precedence");
globalThis.localStorage={getItem:key=>key==="pw-locale"?"ko-KR":null};
assert.equal(resolveLocale("/database"),"ko-KR","stored locale must be used when the URL has no locale");
globalThis.localStorage={getItem:()=>null};
assert.equal(resolveLocale("/database"),"en-US","English must be the final default without browser-language detection");
assert.equal(Object.keys(messageCatalogs["ja-JP"]).length,Object.keys(messageCatalogs["en-US"]).length,"Japanese UI catalog must be complete");
assert.equal(translationProvenance["ja-JP"],"gpt","provisional Japanese UI translation provenance must be explicit");
assert.notEqual(messages("ja-JP").itemDatabase,messages("en-US").itemDatabase,"Japanese item UI must not silently fall back to English");
assert.equal(itemData.items.find(item=>item.id==="PalSphere_Mega")?.names["ja-JP"],"メガスフィア","official Japanese game terminology must remain in extracted data");
assert.doesNotMatch(main,/const ui=/,"user-visible item and crafting copy must use the message catalog");
assert.equal(translationProvenance["zh-CN"],"gpt","Simplified Chinese UI provenance must be explicit");
assert.equal(translationProvenance["zh-TW"],"gpt","Traditional Chinese UI provenance must be explicit");
assert.notEqual(messages("zh-CN").privacy,messages("zh-TW").privacy,"Simplified and Traditional Chinese UI must remain independently localized");
assert.equal(itemData.items.find(item=>item.id==="PalSphere_Mega")?.names["zh-CN"],"高级帕鲁球","official Simplified Chinese item terminology must remain extracted game data");
assert.equal(itemData.items.find(item=>item.id==="PalSphere_Mega")?.names["zh-TW"],"高級帕魯球","official Traditional Chinese item terminology must remain extracted game data");
for(const locale of ["fr-FR","it-IT","de-DE"]) assert.equal(translationProvenance[locale],"gpt",`${locale} UI provenance must be explicit`);
const megaSphere=itemData.items.find(item=>item.id==="PalSphere_Mega");
assert.equal(megaSphere?.names["fr-FR"],"Méga Sphère","official French item terminology must remain extracted game data");
assert.equal(megaSphere?.names["it-IT"],"Sfera mega","official Italian item terminology must remain extracted game data");
assert.equal(megaSphere?.names["de-DE"],"Mega-Sphäre","official German item terminology must remain extracted game data");
assert.match(messages("fr-FR").verifiedBody,/44 851/,"French large-number prose must retain the verified row count");
assert.match(messages("it-IT").rarity,/à/,"Italian accented characters must remain valid UTF-8");
assert.match(messages("de-DE").ownedMaterials,/Vorhandene Materialien/,"long German control copy must remain localized");
const completedLocales=["es-ES","pt-BR","ru-RU","id-ID","es-419","th-TH","tr-TR","vi-VN","pl-PL"];
for(const locale of completedLocales){
  assert.equal(translationProvenance[locale],"gpt",`${locale} UI provenance must be explicit`);
  assert.equal(Object.keys(messageCatalogs[locale]).length,Object.keys(messageCatalogs["en-US"]).length,`${locale} UI catalog must be complete`);
}
const officialMegaNames={"es-ES":"Megaesfera","pt-BR":"Esfera Mega","ru-RU":"Мегасфера","id-ID":"Mega Sphere","es-419":"Megaesfera","th-TH":"เมกาสเฟียร์","tr-TR":"Mega Küre","vi-VN":"Quả Cầu Mega","pl-PL":"Mega Sfera"};
for(const [locale,name] of Object.entries(officialMegaNames)) assert.equal(megaSphere?.names[locale],name,`${locale} official item terminology must remain extracted game data`);
assert.equal(Object.values(translationProvenance).filter(value=>value==="fallback").length,0,"release catalog must have no fallback locales");
assert.match(messages("ru-RU").privacy,/Конфиденциальность/,"Cyrillic UI text must remain valid UTF-8");
assert.match(messages("th-TH").language,/ภาษา/,"Thai UI text must remain valid UTF-8");
assert.match(messages("vi-VN").quantity,/Số lượng/,"Vietnamese diacritics must remain valid UTF-8");
assert.doesNotMatch(main,/Loading…/,"home page must not show a loading state for data it intentionally loads lazily");
assert.match(main,/data-clear-search="pal"/,"Pal search must expose a one-action clear control");
assert.match(main,/data-clear-search="item"/,"item search must expose a one-action clear control");
assert.match(main,/id="pal-empty"[^>]*hidden/,"Pal search must have an explicit empty state");
assert.match(main,/id="item-empty"[^>]*hidden/,"item search must have an explicit empty state");
assert.match(main,/filterCollection\(kind\).*input\.focus\(\)/,"clearing search must restore results and keyboard focus");
assert.equal(skillData.meta.gameBuild,"24181527","skill data must match the verified local game build");
assert.equal(skillData.elements.length,9,"all nine game elements must be published");
assert.equal(skillData.activeSkills.length,320,"active skill count must remain stable for this source revision");
assert.equal(skillData.passiveSkills.length,115,"only displayable standard passive skills with descriptions must be published");
assert.ok(skillData.passiveSkills.every(skill=>Object.keys(skill.descriptions).length===17&&Object.values(skill.descriptions).every(description=>description.trim().length>0)),"every passive skill must publish all 17 official localized descriptions");
assert.ok(skillData.passiveSkills.every(skill=>[-3,-2,-1,1,2,3,4,5].includes(skill.rank)),"every passive skill must map to an extracted rank icon");
assert.ok(skillData.elements.every(element=>Object.keys(element.names).length===17),"every element must have all supported localized names");
assert.ok(skillData.activeSkills.every(skill=>skillData.elements.some(element=>element.id===skill.elementId)),"every active skill must reference a published element");
assert.ok(palData.pals.every(pal=>Array.isArray(pal.guaranteedPassiveIds)),"every Pal must expose a deterministic guaranteed-passive list");
const passiveIds=new Set(skillData.passiveSkills.map(skill=>skill.id));
assert.ok(palData.pals.every(pal=>pal.guaranteedPassiveIds.every(id=>passiveIds.has(id))),"every guaranteed Pal passive must reference a published passive skill");
assert.match(main,/fetch\("\/data\/skills\.json"\)/,"versioned skill data must load from the same origin");
assert.match(main,/id="skill-element"/,"skill collection must support element filtering");
assert.match(main,/role="status"/,"collection result counts must be announced as status updates");
const convergingRecipes={A:{id:"A",output:1,ingredients:{B:1,C:1}},B:{id:"B",output:1,ingredients:{D:1}},C:{id:"C",output:1,ingredients:{D:1}},D:{id:"D",output:2,ingredients:{E:1}}};
assert.deepEqual(expandRecipe("A",1,convergingRecipes),{E:1},"converging demands must aggregate before process rounding");
assert.deepEqual(expandRecipe("A",1,convergingRecipes,{D:1}),{E:1},"owned intermediate stock must be consumed once after demands converge");
assert.deepEqual(expandRecipe("A",1,convergingRecipes,{E:1}),{},"owned raw material must reduce the final net requirement");
assert.deepEqual(expandRecipe("A",1,convergingRecipes,{A:1}),{},"owned target products must avoid all crafting requirements");
assert.throws(()=>expandRecipe("A",1,{A:{id:"A",output:1,ingredients:{B:1}},B:{id:"B",output:1,ingredients:{A:1}}}),/Recipe cycle/,"recipe cycles must fail closed");
assert.throws(()=>expandRecipe("A",0,convergingRecipes),/Invalid recipe target or quantity/,"zero target quantity must be rejected");
assert.throws(()=>expandRecipe("A",1,{A:{id:"A",output:0,ingredients:{E:1}}}),/Invalid recipe output/,"non-positive recipe output must be rejected");
assert.match(main,/\[\$\{esc\(recipe\.id\)\}\]/,"recipe selector must distinguish products with multiple recipe rows");
const productRecipeCounts=new Map();
for(const recipe of itemData.recipes)productRecipeCounts.set(recipe.productId,(productRecipeCounts.get(recipe.productId)||0)+1);
const selectedMega=itemData.recipes.find(recipe=>recipe.id==="PalSphere_Mega");
const unambiguousRecipes=Object.fromEntries(itemData.recipes.filter(recipe=>productRecipeCounts.get(recipe.productId)===1).map(recipe=>[recipe.productId,{id:recipe.id,output:recipe.output,ingredients:Object.fromEntries(recipe.ingredients.map(i=>[i.itemId,i.count]))}]));
unambiguousRecipes[selectedMega.productId]={id:selectedMega.id,output:selectedMega.output,ingredients:Object.fromEntries(selectedMega.ingredients.map(i=>[i.itemId,i.count]))};
assert.deepEqual(expandRecipe("PalSphere_Mega",1,unambiguousRecipes),{CopperOre:2,Pal_crystal_S:1,Stone:3,Wood:3},"Mega Sphere expanded BOM must match verified recipes while stopping at ambiguous recipe boundaries");
assert.deepEqual(expandRecipe("PalSphere_Mega",10,unambiguousRecipes,{Wood:10,Stone:10,CopperIngot:2}),{CopperOre:16,Pal_crystal_S:10,Stone:20,Wood:20},"Mega Sphere owned-material golden case must consume stock once and expand the remainder");
assert.match(main,/recipeCounts\.get\(recipe\.productId\)===1/,"recursive crafting must not guess among ambiguous intermediate recipes");
assert.match(main,/function enhancePalSelect/,"breeding Pal selectors must use an image-capable searchable combobox");
assert.match(main,/class=\"pair-card\"/,"reverse breeding results must render image-capable Pal pair cards");
assert.match(featureStyles,/\.pair-list>\.pair-card-grid\{display:grid;grid-template-columns:repeat\(auto-fit,minmax\(min\(100%,20rem\),1fr\)\)/,"reverse-breeding cards must override the legacy child grid with a readable responsive minimum width");
assert.match(featureStyles,/\.pair-card \.pal-visual small,\.pair-card \.pal-visual strong,\.pair-card>a>small\{white-space:nowrap;word-break:keep-all\}/,"reverse-breeding labels must not break into vertical text");
assert.match(main,/data-dynamic-link/,"dynamically rendered breeding results must support client-side detail navigation");
assert.match(main,/palVisual\(pal,"result"\)/,"forward breeding results must render a Pal image card");
assert.match(main,/\["\/map","\/database","\/calculators\/crafting"\]\.includes\(current\).*ensureItemData/,"item data must load only on routes that use it");
assert.match(main,/\["\/map","\/pals","\/calculators","\/calculators\/breeding"\]\.includes\(current\).*ensurePalData/,"Pal data must load only on routes that use it");
assert.match(main,/current==="\/map"\)ensureMapData/,"map marker data must load only on the map route");
assert.doesNotMatch(main,/href\(\"\/privacy\"\)/,"privacy policy must not be exposed in the public UI");

assert.match(main,/shellNavigation\.map\(item=>shellLink\(item\)\)/,"desktop navigation must use the shared shell route manifest");
assert.match(main,/shellNavigation\.map\(item=>shellLink\(item,true\)\)/,"compact navigation must use the shared shell route manifest");
assert.match(main,/aria-current="page"/,"the active shell destination must expose aria-current");
assert.match(main,/id="global-search-dialog"/,"the shell must provide a global search dialog");
assert.match(main,/ensureGlobalSearchData/,"global search must load Pal, item and skill data on demand");
assert.match(main,/data-theme-choice/,"theme selection must expose explicit system, light and dark choices");
assert.doesNotMatch(main,/trackEvent\([^\n]*(query|searchInput)/,"global search text must not be sent to analytics");
assert.match(main,/meta\[name="theme-color"\]/,"theme changes must update the browser theme color");

console.log("Passed 109 core safety, provenance, localization, shell, search, loading, data, map and calculator assertions.");
