import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import { findBreedingResult, findParentPairs } from "../src/breeding.ts";
import { messages, messageCatalogs, translationProvenance } from "../src/i18n.ts";
import { resolveLocale } from "../src/config.ts";
import { expandRecipe, parseServerIni } from "../src/data.ts";
import { createAnalyticsTracker, installGtagQueue } from "../src/analytics.ts";
import { itemCategories, itemCategoryFieldLabels, itemCategoryLabel, itemCategoryProvenance } from "../src/item-categories.ts";
import { groupItemDropSources } from "../src/drop-relations.ts";
import { databaseItemTabLabels, itemFilterAllLabels, itemFilterAllLabelsProvenance } from "../src/ui-i18n.ts";
import { entityRouteFamilies, routeFamilies, supportedLocales } from "../src/route-manifest.ts";
import { buildIndexableGroups, buildPrerenderEntries, productionOrigin, renderHtmlDocument, renderRouteModel } from "../scripts/seo-static.mjs";

const data = await readFile("src/data.ts", "utf8");
const main = await readFile("src/main.ts", "utf8");
const featureStyles = await readFile("src/features.css", "utf8");
const styles = await readFile("src/styles.css", "utf8");
const config = await readFile("src/config.ts", "utf8");
const routeManifest = await readFile("src/route-manifest.ts", "utf8");
const seoStatic = await readFile("scripts/seo-static.mjs", "utf8");
const staticGenerator = await readFile("scripts/generate-static.mjs", "utf8");
const builtChecker = await readFile("scripts/check-built.mjs", "utf8");
const dungeonImporter = await readFile("scripts/import-dungeon-data.mjs", "utf8");
const technologyImporter = await readFile("scripts/import-technology-data.mjs", "utf8");
const technologyStyles = await readFile("src/technology.css", "utf8");
const structureImporter = await readFile("scripts/import-structure-data.mjs", "utf8");
const structureStyles = await readFile("src/structures.css", "utf8");
const expeditionImporter = await readFile("scripts/import-expedition-data.mjs", "utf8");
const expeditionValidator = await readFile("scripts/validate-expedition-data.mjs", "utf8");
const expeditionStyles = await readFile("src/expeditions.css", "utf8");
const indexHtml = await readFile("index.html", "utf8");
const adsTxt = await readFile("public/ads.txt", "utf8");
const wranglerConfig = JSON.parse((await readFile("wrangler.jsonc", "utf8")).replace(/^\s*\/\/.*$/gm,""));
const palData = JSON.parse(await readFile("public/data/pals.json", "utf8"));
const itemData = JSON.parse(await readFile("public/data/items.json", "utf8"));
const imageManifest = JSON.parse(await readFile("public/assets/image-manifest.json", "utf8"));
const skillData = JSON.parse(await readFile("public/data/skills.json", "utf8"));
const npcData = JSON.parse(await readFile("public/data/npcs.json", "utf8"));
const dungeonData = JSON.parse(await readFile("public/data/dungeons.json", "utf8"));
const technologyData = JSON.parse(await readFile("public/data/technology.json", "utf8"));
const structureData = JSON.parse(await readFile("public/data/structures.json", "utf8"));
const healthData = JSON.parse(await readFile("public/data/health.json", "utf8"));
const elementData = JSON.parse(await readFile("public/data/elements.json", "utf8"));
const expeditionData = JSON.parse(await readFile("public/data/expeditions.json", "utf8"));
const elementImporter = await readFile("scripts/import-element-data.mjs", "utf8");
const elementStyles = await readFile("src/elements.css", "utf8");
const mapImage = await readFile("public/assets/world-map.webp");

assert.match(data, /Math\.min\(32,\s*Math\.max\(1/, "server generator must clamp the official supported player range");
assert.doesNotMatch(data, /WorkSpeedRate|bEnablePlayerToPlayerDamage|bEnableDefenseOtherGuildPlayer/, "server generator must not emit parameters absent from the current official parameter list");
assert.match(data, /bIsPvP/, "server generator must use the current official PvP parameter");
assert.match(data, /bIsUseBackupSaveData/, "server generator must use the current official backup parameter");
const importedServer=parseServerIni("[/Script/Pal.PalGameWorldSettings]\nOptionSettings=(ServerPlayerMaxNum=12,bIsPvP=True,bIsUseBackupSaveData=False,UnknownKey=1)");
assert.deepEqual(importedServer.value,{players:12,pvp:true,backup:false},"server INI importer must parse supported keys");
assert.equal(importedServer.warnings.length,1,"server INI importer must warn about unsupported keys");
assert.match(data, /Recipe cycle/, "crafting engine must detect cycles");
assert.match(data, /Math\.ceil\(needed\s*\/\s*recipe\.output\)/, "crafting engine must round process counts up");
assert.match(main, /localStorage\.getItem\("pw-consent"\)!=="granted"/, "analytics and ads must require explicit consent");
assert.match(main, /import\.meta\.env\.PROD&&site\.adsenseClient/, "AdSense must be production-only and site-configured");
assert.match(main, /pagead2\.googlesyndication\.com\/pagead\/js\/adsbygoogle\.js\?client=/, "AdSense must use the authorized Google loader URL");
assert.match(main, /script\.crossOrigin="anonymous"/, "AdSense loader must use anonymous cross-origin mode");
assert.match(config, /G-FF7N186M72/, "Palworld Analytics measurement ID must be configured");
assert.match(config, /https:\/\/palworld-helper\.woofy\.blog/, "production origin must be configured");
assert.doesNotMatch(config, /palworld-helper\.example/, "placeholder production origin must not remain configured");
assert.doesNotMatch(config, /G-GPSMFR1377/, "superseded Analytics measurement ID must not remain configured");
assert.match(config, /vcYPQJf0I03LumjZIODPdq47ZnYMCRvD2ABcBFyBImQ/, "Palworld Search Console verification must be configured");
assert.match(config, /ca-pub-1986785092914105/, "owner-approved shared AdSense publisher must be configured");
assert.match(routeManifest,/path:"database\/dungeons".*indexable:true/,"Dungeon collection must be an implemented indexable route");
assert.match(routeManifest,/prefix:"database\/dungeons".*dataset:"dungeons"/,"Dungeon details must share the typed entity route manifest");
assert.match(routeManifest,/path:"database\/technology".*indexable:true/,"Technology collection must be an implemented indexable route");
assert.match(routeManifest,/path:"database\/elements".*mode:"prerendered".*indexable:true.*element-matchup-guide/,"Element matchups must be an implemented, indexable prerendered route");
assert.match(routeManifest,/prefix:"database\/technology".*dataset:"technologies".*priorityLimit:20/,"Technology details must use a deterministic priority prerender policy");
assert.match(routeManifest,/path:"database\/structures".*indexable:true/,"Structure collection must be an implemented indexable route");
assert.match(routeManifest,/prefix:"database\/structures".*dataset:"structures".*priorityLimit:5/,"Structure details must use a deterministic priority prerender policy");
assert.match(routeManifest,/path:"database\/expeditions".*mode:"prerendered".*indexable:true/,"Pal Expedition collection must be an implemented indexable prerendered route");
assert.match(routeManifest,/prefix:"database\/expeditions".*dataset:"expeditions".*prerender:"all"/,"Every verified Pal Expedition detail must receive initial HTML");
assert.ok(routeFamilies.every(family=>family.indexable&&family.searchIntent),"every collection route must declare its indexability and search intent");
assert.ok(entityRouteFamilies.every(family=>family.sitemap&&family.searchIntent&&["all","priority"].includes(family.prerender)),"every entity family must declare one sitemap and deterministic prerender policy");
assert.match(routeManifest,/dataset:"items".*prerender:"priority".*priorityLimit:100/,"item prerendering must retain its documented priority cap");
assert.match(routeManifest,/dataset:"dungeons".*prerender:"all"/,"every verified Dungeon detail must receive initial HTML");
assert.match(main,/renderPalDropSection\(pal\).*renderPalDungeonSection\(pal\)/s,"Pal details must expose verified Dungeon backlinks");
assert.match(main,/layers=dungeon&dungeon=/,"Dungeon entrances must restore the verified Dungeon map layer and entity filter");
assert.match(featureStyles,/\.dungeon-grid.*\.dungeon-summary.*\.dungeon-entrance-grid.*\.dungeon-pool-grid/s,"Dungeon collection, detail, and pool layouts must retain responsive style contracts");
assert.match(dungeonImporter,/encounterGroupsForSpawners/,"Dungeon encounters must preserve source spawn groups");
assert.match(dungeonImporter,/memberRole=primary\?"primary"/,"Dungeon boss groups must distinguish the primary boss from companions");
assert.match(dungeonImporter,/ItemSlot\$\{slot\}_ProbabilityPercent/,"Dungeon item candidates must preserve the source slot boundary");
assert.doesNotMatch(dungeonImporter,/type==="Material"|materialItemCount/,"Item category must not be reinterpreted as a Dungeon resource");
assert.match(dungeonImporter,/rewardClassDefaultsRaw\.classes\[classPath\]/,"Dungeon rewards must follow the exact extracted class-default reference");
assert.match(dungeonImporter,/rewardKindByMapObjectId=new Map/,"Dungeon reward labels must use exact map-object IDs");
assert.doesNotMatch(dungeonImporter,/LotteryValueBlueprint(?:ClassName|SoftClass)[^\n]*(?:match|includes|startsWith)/,"Dungeon reward kinds must not be inferred from Blueprint path patterns");
assert.doesNotMatch(main,/materialItemCount|dungeon\.rewardKinds|dungeon\.rewardTypes|dungeon\.items|dungeon\.encounters|dungeon\.resourceStatus|dungeon\.rewardContentsStatus/,"Dungeon UI must not consume legacy flattened or inferred fields");
assert.match(main,/loaded\.meta\.schema!==3.*resourcesVerified!==false.*rewardSourcesVerified!==true.*rewardContentsVerified!==false/,"Dungeon runtime loader must enforce the schema 3 verification boundary");
assert.equal(dungeonData.meta.schema,3,"Dungeon public data must use schema 3");
assert.equal(dungeonData.meta.rewardSourceCount,79,"Dungeon reward source coverage must fail closed on extraction drift");
assert.equal(dungeonData.meta.rewardItemCandidateCount,819,"Dungeon reward candidate coverage must fail closed on extraction drift");
assert.ok(dungeonData.dungeons.filter(dungeon=>dungeon.kind==="rotating").every(dungeon=>dungeon.coverage.resources==="unverified"&&dungeon.resources.length===0),"Unlinked Dungeon resources must remain explicitly unpublished");
assert.ok(dungeonData.dungeons.filter(dungeon=>dungeon.kind==="rotating").every(dungeon=>dungeon.coverage.rewardSources==="verified"&&dungeon.rewardSources.length>0),"Every rotating Dungeon must expose its verified reward sources");
assert.deepEqual({schema:technologyData.meta.schema,gameBuild:technologyData.meta.gameBuild,verification:technologyData.meta.verification,localeCount:technologyData.meta.localeCount,count:technologyData.meta.technologyCount,regular:technologyData.meta.regularCount,ancient:technologyData.meta.ancientCount,prerequisites:technologyData.meta.prerequisiteCount,towers:technologyData.meta.towerBossCount,research:technologyData.meta.researchCount,min:technologyData.meta.levelMin,max:technologyData.meta.levelMax},{schema:1,gameBuild:"24181527",verification:"game-files",localeCount:17,count:588,regular:537,ancient:51,prerequisites:17,towers:17,research:10,min:1,max:80},"Technology public data must fail closed on the verified build baseline");
assert.deepEqual(technologyData.meta.imageProvenance,{direct:217,"shared-official":347,"atlas-official":0,"derived-official":24,missing:0},"Technology image provenance must distinguish direct, reused, atlas, derived, and missing coverage");
const technologySlugs=new Set(technologyData.technologies.map(technology=>technology.slug));
assert.equal(technologySlugs.size,588,"Technology public slugs must be unique");
assert.ok(technologyData.technologies.every(technology=>technology.image===true&&Object.keys(technology.names).length===17&&Object.values(technology.names).every(Boolean)&&Object.keys(technology.descriptions).length===17&&Object.values(technology.descriptions).every(description=>description.trim()&&!/<[^>]+>|\|/.test(description))),"Every Technology must have an icon and complete resolved official localization");
assert.ok(technologyData.technologies.every(technology=>technology.level>=1&&technology.level<=80&&technology.pointCost>=1&&technology.pointCost<=9&&technology.unlocks.length>0),"Technology level, point cost, and unlock targets must stay inside verified source bounds");
assert.ok(technologyData.technologies.every((technology,index,list)=>index===0||list[index-1].level<technology.level||list[index-1].level===technology.level&&list[index-1].order<=technology.order),"Technology entries must preserve level and authored table order");
assert.ok(technologyData.technologies.every(technology=>(!technology.prerequisite||technologySlugs.has(technology.prerequisite.slug))&&technology.dependents.every(relation=>technologySlugs.has(relation.slug))),"Technology prerequisite and dependent routes must remain referentially complete");
assert.doesNotMatch(JSON.stringify(technologyData),/EPal|NAME_RECIPE_|internalId|RequireTechnology|RequireDefeatTowerBoss|RequireResearchId/,"Technology public data must not expose raw game identifiers or source fields");
assert.deepEqual({schema:healthData.meta.schema,gameBuild:healthData.meta.gameBuild,verification:healthData.meta.verification,localeCount:healthData.meta.localeCount,conditions:healthData.meta.conditionCount,medicines:healthData.meta.medicineCount,numericEffectsVerified:healthData.meta.numericEffectsVerified},{schema:1,gameBuild:"24181527",verification:"game-files",localeCount:17,conditions:7,medicines:3,numericEffectsVerified:false},"Health data must fail closed on verified coverage and explicitly exclude unverified numeric effects");
assert.equal(new Set(healthData.conditions.map(condition=>condition.slug)).size,7,"Health condition slugs must be unique");
assert.ok(healthData.conditions.every(condition=>Object.keys(condition.names).length===17&&Object.keys(condition.descriptions).length===17&&condition.effects.numericModifiers===null&&healthData.medicines.some(medicine=>medicine.slug===condition.medicine&&medicine.cures.includes(condition.slug))),"Every condition needs complete official localization and a reciprocal verified treatment relation");
assert.ok(healthData.medicines.every(medicine=>medicine.healthRestoration===0&&medicine.recipe.workAmount>0&&medicine.recipe.ingredients.length>=2&&Object.keys(medicine.names).length===17&&Object.keys(medicine.descriptions).length===17),"Medicines must retain recipes, locale coverage, and the verified no-HP-healing boundary");
assert.doesNotMatch(JSON.stringify(healthData),/"(?:COMMON_[^"]*|ITEM_DESC_[^"]*|Cold|Bulimia|GastricUlcer|DepressionSprain|Herbs|LuxuryMedicines)"\s*:|[A-Z]:\\|file:\/\//,"Health public data must not expose raw condition/item identifiers or local provenance");
assert.deepEqual({schema:elementData.meta.schema,gameBuild:elementData.meta.gameBuild,verification:elementData.meta.verification,locales:elementData.meta.localeCount,elements:elementData.meta.elementCount,relations:elementData.meta.relationCount,pals:elementData.meta.palCount,numeric:elementData.meta.numericMultipliersVerified,dual:elementData.meta.dualElementRuleVerified,icons:elementData.meta.iconProvenance},{schema:1,gameBuild:"24181527",verification:"game-ui-chart-and-game-files",locales:17,elements:9,relations:9,pals:299,numeric:false,dual:false,icons:{direct:9,sharedOfficial:0,atlasOfficial:0,derivedOfficial:0,missing:0}},"Element data must fail closed on the verified game UI and extraction baseline");
const elementSlugs=new Set(elementData.elements.map(element=>element.slug));
assert.equal(elementSlugs.size,9,"Element slugs must be unique and safe");
assert.ok(elementData.elements.every(element=>Object.keys(element.names).length===17&&element.palCount>0&&element.activeSkillCount>0&&element.strongAgainst.every(slug=>elementSlugs.has(slug))&&element.weakTo.every(slug=>elementSlugs.has(slug))),"Every element needs official localized names and complete qualitative relationships");
assert.ok(elementData.relations.every(relation=>elementSlugs.has(relation.attacker)&&elementSlugs.has(relation.defender)&&relation.effect==="strong"&&relation.multiplier===null&&relation.verification==="game-ui-chart"),"Element relationships must remain qualitative until numeric multipliers are verified");
assert.deepEqual(elementData.rules,{numericMultipliers:null,dualElement:null},"Unverified numeric and dual-element rules must stay explicitly unavailable");
assert.ok(palData.pals.every(pal=>Array.isArray(pal.elementSlugs)&&pal.elementSlugs.length>=1&&pal.elementSlugs.length<=2&&pal.elementSlugs.every(slug=>elementSlugs.has(slug))),"Every published Pal must have one or two verified safe element slugs");
assert.doesNotMatch(JSON.stringify(elementData),/EPalElementType|COMMON_ELEMENT|[A-Z]:\\|file:\/\//,"Element public data must not expose raw source identifiers or private provenance");
assert.match(elementImporter,/sha256\(chartBytes\).*93BC7116E59463E93FA92968B825F566CBF9F0D55006E6906DC4DCB39658CA52/s,"Element import must pin the verified official matchup chart");
assert.match(elementImporter,/numericMultipliersVerified:false.*dualElementRuleVerified:false/s,"Element import must not invent numeric or dual-element rules");
assert.match(main,/function elementCollectionPage\(\).*element-matrix.*relatedPals.*relatedSkills/s,"Element page must include the chart, comparison matrix, Pals, and active skills");
assert.match(main,/fetch\("\/data\/elements\.json"\)/,"Element page and global search must load same-origin normalized data");
assert.match(main,/tool:"element_matchup",action:result/,"Element comparisons must use a stable privacy-safe analytics event");
assert.match(elementStyles,/\.element-matrix-scroll.*overflow-x:auto.*@media\(max-width:700px\)/s,"Element matrix and related content must retain a responsive overflow contract");
assert.match(technologyImporter,/extractionManifest\.extractedAt/,"Technology generation timestamp must remain deterministic for one extraction");
assert.match(technologyImporter,/mappingHash!=="C3107655159520375F7F75DF5812E9A9976458C56B4F619C7FD0AAF0D42C7851"/,"Technology import must enforce the build-compatible USMAP");
assert.match(main,/id="technology-kind".*id="technology-category".*id="technology-level".*id="technology-condition"/s,"Technology collection must expose type, unlock, level, and condition filters");
assert.match(main,/data-technology-level=.*technology-grid.*technologyCard/s,"Technology collection must render authored level groups");
assert.match(main,/technology\.prerequisite.*technology\.towerBossRequired.*technology\.labResearch/s,"Technology details must expose every verified prerequisite class");
assert.match(main,/fetch\("\/data\/technology\.json"\)/,"Technology collection, details, and global search must load same-origin normalized data");
assert.match(main,/renderTechnologyGlobalSearch/,'global search must include localized Technology names, descriptions, and unlock targets');
assert.match(technologyStyles,/\.technology-card\.ancient.*\.technology-point.*@media\(max-width:700px\)/s,"Technology cards must distinguish Ancient Technology and retain a responsive mobile layout");
assert.deepEqual({schema:structureData.meta.schema,gameBuild:structureData.meta.gameBuild,verification:structureData.meta.verification,locales:structureData.meta.localeCount,count:structureData.meta.structureCount,production:structureData.meta.productionCount,energy:structureData.meta.energyCount,materials:structureData.meta.materialRelationCount,technologies:structureData.meta.technologyRelationCount,images:structureData.meta.imageProvenance},{schema:1,gameBuild:"24181527",verification:"game-files",locales:17,count:472,production:12,energy:41,materials:992,technologies:473,images:{direct:472,"atlas-official":472,missing:0}},"Structure data must fail closed on the verified extraction baseline");
assert.deepEqual(structureData.meta.categoryCounts,{production:45,pal:23,infrastructure:23,food:16,storage:30,foundations:138,defenses:17,lighting:17,furniture:145,other:18},"Structure categories must retain the game-authored distribution");
const structureSlugs=new Set(structureData.structures.map(structure=>structure.slug)),legalItemIds=new Set(itemData.items.map(item=>item.id));
assert.equal(structureSlugs.size,472,"Structure public slugs must be unique");
assert.ok(structureData.structures.every(structure=>Object.keys(structure.names).length===17&&Object.keys(structure.descriptions).length===17&&Object.values(structure.descriptions).every(description=>description.trim()&&!/<[^>]+>|\|/.test(description))&&structure.materials.length>0&&structure.materials.every(material=>legalItemIds.has(material.itemId)&&material.count>0)&&structure.technologies.length>0&&structure.technologies.every(relation=>technologySlugs.has(relation.slug))&&structure.icon.index>=0&&structure.icon.index<472),"Every Structure needs complete localization, legal construction materials, Technology links, and an atlas cell");
assert.ok(structureData.structures.filter(structure=>structure.production).every(structure=>legalItemIds.has(structure.production.itemId)&&structure.production.workAmount>0),"Only directly linked verified production outputs may be published");
assert.doesNotMatch(JSON.stringify(structureData),/EPal|BUILDOBJECT|MAPOBJECT|OverrideDesc|RequiredEnergyType|Material[1-4]_Id|[A-Z]:\\|file:\/\//,"Structure public data must not expose raw object identifiers, source fields, or local provenance");
assert.match(structureImporter,/mappingHash!=="C3107655159520375F7F75DF5812E9A9976458C56B4F619C7FD0AAF0D42C7851"/,"Structure import must enforce the build-compatible USMAP");
assert.match(structureImporter,/farmCropRowsOmitted.*assignRowsOmitted.*storageCapacityOmitted/s,"Unverified farm, assignment, and storage-capacity relationships must remain behind the publication boundary");
assert.match(structureImporter,/Object\.entries\(productRows\)\.find.*toLocaleLowerCase/s,"Production output must follow an exact build-object row relation");
assert.match(main,/id="structure-category".*id="structure-subcategory".*id="structure-level".*id="structure-energy"/s,"Structure collection must expose category, subtype, unlock-level, and power filters");
assert.match(main,/function structureDetail.*structure\.restrictions.*structure\.materials.*structure\.production.*structure\.technologies/s,"Structure details must expose verified construction, unlock, production, and placement relations");
assert.match(main,/fetch\("\/data\/structures\.json"\)/,"Structure collection, details, and global search must load same-origin normalized data");
assert.match(main,/renderStructureGlobalSearch/,"Global search must include localized Structure names and categories");
assert.match(structureStyles,/\.structure-grid.*\.structure-summary.*\.structure-detail-grid.*@media\(max-width:760px\)/s,"Structure catalog and details must retain a responsive layout contract");
assert.deepEqual({schema:expeditionData.meta.schema,gameBuild:expeditionData.meta.gameBuild,verification:expeditionData.meta.verification,locales:expeditionData.meta.localeCount,count:expeditionData.meta.expeditionCount,standard:expeditionData.meta.standardCount,hard:expeditionData.meta.hardCount,slots:expeditionData.meta.rewardSlotCount,rewards:expeditionData.meta.rewardRowCount,items:expeditionData.meta.uniqueRewardItemCount,contents:expeditionData.meta.rewardContentsVerified,quantities:expeditionData.meta.rewardQuantitiesVerified,probabilities:expeditionData.meta.probabilitiesVerified,durationFormula:expeditionData.meta.durationFormulaVerified,images:expeditionData.meta.imageProvenance},{schema:1,gameBuild:"24181527",verification:"game-files",locales:17,count:18,standard:9,hard:9,slots:169,rewards:279,items:75,contents:true,quantities:true,probabilities:false,durationFormula:false,images:{direct:9,sharedAssignments:18,missing:0}},"Pal Expedition data must fail closed on the verified extraction baseline");
const expeditionSlugs=new Set(expeditionData.expeditions.map(expedition=>expedition.slug));
assert.equal(expeditionSlugs.size,18,"Pal Expedition public slugs must be unique");
assert.equal(expeditionData.expeditions.reduce((sum,expedition)=>sum+expedition.rewardSlots.length,0),169,"Pal Expedition reward slots must retain their source boundaries");
assert.equal(expeditionData.expeditions.reduce((sum,expedition)=>sum+expedition.rewardSlots.reduce((slotSum,slot)=>slotSum+slot.candidates.length,0),0),279,"Pal Expedition reward candidates must retain complete coverage");
assert.ok(expeditionData.expeditions.every(expedition=>Object.keys(expedition.names).length===17&&expedition.rewardSlots.every(slot=>slot.candidates.every(candidate=>candidate.slot===slot.slot&&legalItemIds.has(candidate.itemId)&&candidate.minCount>=0&&candidate.maxCount>=candidate.minCount&&candidate.selectionWeight>0&&!Object.hasOwn(candidate,"probability")))),"Every Pal Expedition needs complete localization, legal rewards, source quantities, and no invented probability");
const grassExpedition=expeditionData.expeditions.find(expedition=>expedition.slug==="verdant-hollow"),worldTreeHard=expeditionData.expeditions.find(expedition=>expedition.slug==="world-tree-forbidden-area");
assert.deepEqual({duration:grassExpedition.baseDurationSeconds,strength:grassExpedition.recommendedStrength,element:grassExpedition.requiredElementSlug,slots:grassExpedition.rewardSlots.length},{duration:1800,strength:25000,element:null,slots:9},"Verdant Hollow golden case must match the extracted mission table");
assert.deepEqual({duration:worldTreeHard.baseDurationSeconds,strength:worldTreeHard.recommendedStrength,variant:worldTreeHard.variant,difficulty:worldTreeHard.difficulty,slots:worldTreeHard.rewardSlots.length},{duration:7200,strength:2100000,variant:"hard",difficulty:"very-hard",slots:8},"World Tree hard golden case must match the extracted mission table");
assert.doesNotMatch(JSON.stringify(expeditionData),/CharacterTeamMission|FieldLottery|LotteryData|[A-Z]:\\|file:\/\//,"Pal Expedition public data must not expose raw table names or local provenance");
assert.match(expeditionImporter,/expectedMappingHash="C3107655159520375F7F75DF5812E9A9976458C56B4F619C7FD0AAF0D42C7851".*manifest\.mappingHash!==expectedMappingHash/s,"Pal Expedition import must enforce the build-compatible USMAP");
assert.match(expeditionImporter,/probabilitiesVerified:false.*durationFormulaVerified:false/s,"Pal Expedition import must explicitly preserve unverified probability and duration-formula boundaries");
assert.match(expeditionValidator,/verdant-hollow.*world-tree-forbidden-area/s,"Pal Expedition validation must include low- and high-progression golden cases");
assert.match(main,/id="expedition-variant".*id="expedition-difficulty".*id="expedition-element"/s,"Pal Expedition collection must expose variant, difficulty, and element filters");
assert.match(main,/function expeditionDetail.*visibilityCondition.*challengeCondition.*rewardSlots/s,"Pal Expedition details must expose verified requirements and slot-grouped rewards");
assert.match(main,/renderItemExpeditionSection\(item\)/,"Item details must expose Pal Expedition reward backlinks");
assert.match(main,/fetch\("\/data\/expeditions\.json"\)/,"Pal Expedition collection, details, backlinks, and search must load same-origin normalized data");
assert.match(main,/renderExpeditionGlobalSearch/,"Global search must include localized Pal Expedition names and reward items");
assert.match(expeditionStyles,/\.expedition-grid.*\.expedition-detail-grid.*\.expedition-reward-slots.*@media\(max-width:700px\)/s,"Pal Expedition catalog, details, and rewards must retain a responsive layout contract");
for(const image of new Set(expeditionData.expeditions.map(expedition=>expedition.image)))await access(`public${image}`);
assert.match(indexHtml, /name="google-site-verification" content="vcYPQJf0I03LumjZIODPdq47ZnYMCRvD2ABcBFyBImQ"/, "Search Console verification must exist in static HTML");
assert.match(indexHtml, /name="google-adsense-account" content="ca-pub-1986785092914105"/, "AdSense publisher metadata must exist in static HTML");
assert.equal(adsTxt.trim(),"google.com, pub-1986785092914105, DIRECT, f08c47fec0942fa0","ads.txt must use the exact owner-authorized account entry");
assert.equal(wranglerConfig.name,"palworld-helper","Wrangler project name must match the GitHub/project slug");
assert.equal(wranglerConfig.assets?.directory,"./dist","Wrangler must deploy only the verified static build output");
assert.equal(wranglerConfig.main,undefined,"static deployment must not introduce a Worker runtime");
assert.equal(wranglerConfig.assets?.not_found_handling,"single-page-application","collection and entity deep links must reuse the shared SPA document");
assert.equal(wranglerConfig.assets?.html_handling,"drop-trailing-slash","Cloudflare HTML routing must match the no-trailing-slash canonical contract");
const seoData={palData,itemData,skillData,npcData,dungeonData,technologyData,healthData,elementData,structureData,expeditionData},indexableGroups=buildIndexableGroups(seoData,productionOrigin),{entries:prerenderEntries,selected:prerenderSelection}=buildPrerenderEntries(seoData);
assert.equal(Object.values(indexableGroups).reduce((sum,urls)=>sum+urls.length,0),71689,"typed SEO groups must enumerate every implemented localized URL");
assert.deepEqual(Object.fromEntries(Object.entries(prerenderSelection).map(([key,value])=>[key,value.length])),{pals:299,items:100,activeSkills:40,passiveSkills:30,partnerSkills:30,npcs:164,dungeons:28,technologies:20,structures:5,conditions:7,expeditions:18},"hybrid prerender selection must retain its deterministic family limits");
assert.equal(prerenderEntries.length,12920,"collection and priority detail prerenders must remain inside the deployment budget");
const koreanElementEntry=prerenderEntries.find(entry=>entry.locale==="ko-KR"&&entry.kind==="collection"&&entry.route==="database/elements"),koreanElementHtml=renderHtmlDocument(indexHtml,koreanElementEntry,renderRouteModel(koreanElementEntry,seoData,prerenderSelection));
assert.match(koreanElementHtml,/속성 상성.*공식 상성도.*화염 속성.*풀 속성/s,"Element initial HTML must contain localized guide copy and official localized element names");
assert.match(koreanElementHtml,/assets\/elements\/matchup-chart\.webp/,"Element initial HTML must include the official extracted matchup chart");
assert.equal((koreanElementHtml.match(/<h1(?:\s[^>]*)?>/g)||[]).length,1,"Element initial HTML must contain exactly one h1");
const koreanDungeonEntry=prerenderEntries.find(entry=>entry.locale==="ko-KR"&&entry.dataset==="dungeons"),koreanDungeonModel=renderRouteModel(koreanDungeonEntry,seoData,prerenderSelection),koreanDungeonHtml=renderHtmlDocument(indexHtml,koreanDungeonEntry,koreanDungeonModel);
assert.match(koreanDungeonHtml,/<html lang="ko-KR"/,"Dungeon initial HTML must use the route locale");
assert.match(koreanDungeonHtml,/rel="canonical" href="https:\/\/palworld-helper\.woofy\.blog\/ko-KR\/database\/dungeons\//,"Dungeon initial HTML must use the production canonical");
assert.equal((koreanDungeonHtml.match(/<h1(?:\s[^>]*)?>/g)||[]).length,1,"Dungeon initial HTML must contain exactly one h1");
assert.match(koreanDungeonHtml,/"@type":"BreadcrumbList"/,"safe slug detail pages must include breadcrumb structured data");
const koreanTechnologyEntry=prerenderEntries.find(entry=>entry.locale==="ko-KR"&&entry.dataset==="technologies"),koreanTechnologyHtml=renderHtmlDocument(indexHtml,koreanTechnologyEntry,renderRouteModel(koreanTechnologyEntry,seoData,prerenderSelection));
assert.match(koreanTechnologyHtml,/rel="canonical" href="https:\/\/palworld-helper\.woofy\.blog\/ko-KR\/database\/technology\//,"Technology initial HTML must use a localized production canonical");
assert.match(koreanTechnologyHtml,/"@type":"WebPage".*"@type":"BreadcrumbList"/s,"Technology slug details must publish safe structured data and breadcrumbs");
assert.equal((koreanTechnologyHtml.match(/<h1(?:\s[^>]*)?>/g)||[]).length,1,"Technology initial HTML must contain exactly one h1");
const koreanStructureEntry=prerenderEntries.find(entry=>entry.locale==="ko-KR"&&entry.dataset==="structures"),koreanStructureHtml=renderHtmlDocument(indexHtml,koreanStructureEntry,renderRouteModel(koreanStructureEntry,seoData,prerenderSelection));
assert.match(koreanStructureHtml,/rel="canonical" href="https:\/\/palworld-helper\.woofy\.blog\/ko-KR\/database\/structures\//,"Structure initial HTML must use a localized production canonical");
assert.match(koreanStructureHtml,/"@type":"WebPage".*"@type":"BreadcrumbList"/s,"Structure slug details must publish safe structured data and breadcrumbs");
assert.equal((koreanStructureHtml.match(/<h1(?:\s[^>]*)?>/g)||[]).length,1,"Structure initial HTML must contain exactly one h1");
const koreanExpeditionEntry=prerenderEntries.find(entry=>entry.locale==="ko-KR"&&entry.dataset==="expeditions"&&entry.entity.slug==="world-tree-forbidden-area"),koreanExpeditionHtml=renderHtmlDocument(indexHtml,koreanExpeditionEntry,renderRouteModel(koreanExpeditionEntry,seoData,prerenderSelection));
assert.match(koreanExpeditionHtml,/rel="canonical" href="https:\/\/palworld-helper\.woofy\.blog\/ko-KR\/database\/expeditions\/world-tree-forbidden-area"/,"Pal Expedition initial HTML must use a localized production canonical");
assert.match(koreanExpeditionHtml,/획득 가능 보상.*보상 슬롯.*선택 가중치/s,"Pal Expedition initial HTML must include localized slot-grouped rewards");
assert.match(koreanExpeditionHtml,/"@type":"WebPage".*"@type":"BreadcrumbList"/s,"Pal Expedition slug details must publish safe structured data and breadcrumbs");
assert.equal((koreanExpeditionHtml.match(/<h1(?:\s[^>]*)?>/g)||[]).length,1,"Pal Expedition initial HTML must contain exactly one h1");
const englishPalEntry=prerenderEntries.find(entry=>entry.locale==="en-US"&&entry.dataset==="pals"),englishPalHtml=renderHtmlDocument(indexHtml,englishPalEntry,renderRouteModel(englishPalEntry,seoData,prerenderSelection));
assert.doesNotMatch(englishPalHtml,/data-route-structured-data/,"raw-ID entity routes must not publish unsupported structured data");
assert.match(englishPalHtml,/data-prerender-route=/,"prerendered detail HTML must expose a hydration marker");
assert.match(staticGenerator,/sitemapindex.*sitemaps\/\$\{name\}\.xml/s,"the build must publish a sitemap index with route-family child files");
assert.match(builtChecker,/hybrid-prerender-plus-spa/,"built-output verification must enforce the hybrid rendering architecture");
assert.match(seoStatic,/descriptionScore.*scoreMap.*localeCompare/s,"priority prerender selection must use stable content and relationship scoring with an ID tie-breaker");
assert.match(main,/preservingPrerender&&!routeDataReady\(\)/,"the app must preserve initial HTML until route data is ready");
assert.match(main,/app\.removeAttribute\("data-prerender-route"\)/,"hydration must explicitly retire the prerender marker");
assert.match(main,/property:"og:image".*name:"twitter:card".*name:"twitter:image"/s,"runtime navigation must refresh Open Graph and Twitter metadata");
assert.match(main,/BreadcrumbList.*position:1,name:m\.home.*position:2,name:parentLabel.*position:3,name:title/s,"runtime safe-detail breadcrumbs must preserve home, collection, and entity hierarchy");
assert.match(main,/history\.replaceState\(\{\},"",localizePath\(locale,location\.pathname\)\)/,"unprefixed entry routes must normalize to the selected locale without another HTML document");
assert.doesNotMatch(main, /gtag\([^\n]*(search|pin|server|ini)/i, "analytics must not receive search, pin, or server free-form data");
assert.match(main, /send_page_view:false/, "SPA analytics must disable automatic page views to prevent duplicates");
assert.match(main, /installGtagQueue\(win\)/, "Analytics must install the official command queue before loading gtag.js");
assert.doesNotMatch(main, /gtag=\(\.\.\.args\)=>/, "Analytics must not queue ordinary arrays in place of Arguments commands");
assert.match(main, /collection_search",\s*\{\s*collection:/, "collection search may emit only a stable collection identifier");
assert.doesNotMatch(main, /trackEvent\([^\n]*(\.value|FormData|coordinate|query)/, "analytics events must not include free-form control values");

let analyticsConsent=false;
let analyticsPath="/en-US";
let analyticsLocale="en-US";
const analyticsTarget={};
const analytics=createAnalyticsTracker({
  consentGranted:()=>analyticsConsent,
  currentPath:()=>analyticsPath,
  currentLocale:()=>analyticsLocale,
  sender:()=>analyticsTarget.gtag
});
assert.equal(analytics.trackPageView(),false,"Analytics must not track before consent");
analyticsConsent=true;
assert.equal(analytics.trackPageView(),false,"Analytics must not consume the page before the sender is initialized");
installGtagQueue(analyticsTarget);
analyticsTarget.gtag("js",new Date(0));
analyticsTarget.gtag("config","G-FF7N186M72",{send_page_view:false});
assert.equal(analytics.trackPageView(),true,"consent initialization must emit the current page once");
assert.equal(analytics.trackPageView(),false,"same-path rerenders must not emit another page view");
analyticsPath="/en-US/pals";
assert.equal(analytics.trackPageView(),true,"a pathname change must emit one new page view");
assert.deepEqual(analyticsTarget.dataLayer.map(command=>Object.prototype.toString.call(command)),[
  "[object Arguments]","[object Arguments]","[object Arguments]","[object Arguments]"
],"every Google tag command must use an Arguments object");
assert.deepEqual(Array.from(analyticsTarget.dataLayer[2]),["event","page_view",{page_path:"/en-US",locale:"en-US"}],"the first consented page view must be queued with sanitized fields");
assert.deepEqual(Array.from(analyticsTarget.dataLayer[3]),["event","page_view",{page_path:"/en-US/pals",locale:"en-US"}],"SPA navigation must queue exactly one new page view");
assert.match(main, /fetch\("\/data\/pals\.json"\)/, "verified static Pal data must load from the same origin");
assert.equal(palData.meta.palCount, 299, "verified Pal count must remain stable for this game build");
assert.equal(palData.meta.palPortraitCount, palData.meta.palCount, "every published Pal must have a verified portrait");
assert.equal(palData.meta.localIdMatchCount, palData.meta.palCount, "every published Pal ID must match the local game export");
assert.equal(palData.pairs.length, 44851, "breeding table must remain complete for this source revision");
assert.equal(new Set(palData.pals.map(p=>p.id)).size,palData.pals.length,"Pal internal IDs must be unique");
assert.ok(palData.pals.every(pal=>pal.image===true),"every published Pal must retain its portrait flag after a Pal-data refresh");
for(const pal of palData.pals)await access(`public/assets/pals/${pal.id}.png`);
assert.equal(palData.workSuitabilities.length,12,"all currently published Pal work suitability types must have metadata");
assert.ok(palData.workSuitabilities.every(work=>Object.keys(work.names).length===17&&Object.values(work.names).every(Boolean)),"every work suitability must use all 17 official localized labels");
for(const work of palData.workSuitabilities)await access(`public${work.icon}`);
assert.equal(palData.pals.filter(pal=>pal.descriptions["en-US"]).length,296,"official English Paldeck long-description coverage must remain stable");
assert.equal(palData.pals.filter(pal=>pal.descriptions["ko-KR"]).length,296,"official Korean Paldeck long-description coverage must remain stable");
for(const pal of palData.pals)for(const description of Object.values(pal.descriptions)){
  assert.doesNotMatch(description,/<[^>]+>|Error_Code:|\|/,`${pal.id} descriptions must not expose game-runtime markup`);
}
assert.ok(palData.pals.every(pal=>!/이\(가\)|은\(는\)|을\(를\)|과\(와\)/.test(pal.descriptions["ko-KR"])),"Korean Pal descriptions must resolve selectable particles");
assert.match(palData.pals.find(pal=>pal.id==="PinkCat").descriptions["ko-KR"],/까부냥이 핥아/,"PinkCat description must resolve its localized name and Korean subject particle");
assert.match(palData.pals.find(pal=>pal.id==="LilyQueen").descriptions["ko-KR"],/태양 폭발/,"active-skill markup must resolve to the official localized skill name");
assert.match(main,/category==="habitat"\?!!habitatSelect\?\.value/,"selected Pal habitats must remain enabled independently from point layers");
const byId=new Map(palData.pals.map(p=>[p.id,p.i]));
assert.equal(findBreedingResult(palData.pairs,byId.get("Anubis"),byId.get("Anubis"),"WILDCARD","WILDCARD"),byId.get("Anubis"),"Anubis self-pair golden case must pass");
assert.equal(findBreedingResult(palData.pairs,byId.get("CatMage"),byId.get("FoxMage"),"FEMALE","MALE"),byId.get("CatMage_Fire"),"gender-specific special combination must take precedence");
assert.equal(findBreedingResult(palData.pairs,byId.get("CatMage"),byId.get("FoxMage"),"MALE","FEMALE"),byId.get("FoxMage_Dark"),"reversed gender-specific special combination must remain distinct");
assert.ok(findParentPairs(palData.pairs,byId.get("Anubis")).length>0,"target reverse lookup must return verified parent pairs");
assert.equal(itemData.meta.gameBuild,"24181527","item data must match the verified local game build");
assert.equal(itemData.items.length,1891,"only legal in-game items from this build must be published");
assert.equal(itemData.recipes.length,1286,"every recipe with legal product and ingredient references must be published");
assert.equal(itemData.meta.localeCount,17,"official item names must cover all supported interface locales");
assert.equal(itemData.meta.dropCount,itemData.drops.length,"Pal drop metadata must match the normalized relationship count");
assert.equal(itemData.meta.dropPalCount,298,"current game files must provide drop rows for 298 published Pals");
assert.deepEqual(itemData.meta.excludedDrops.items,["poppy"],"unpublished drop items must remain explicit");
const palIdsForDrops=new Set(palData.pals.map(pal=>pal.id));
assert.ok(itemData.drops.every(drop=>palIdsForDrops.has(drop.palId)&&itemData.items.some(item=>item.id===drop.itemId)&&Number.isInteger(drop.level)&&drop.level>=0&&drop.rate>0&&drop.rate<=100&&Number.isInteger(drop.min)&&Number.isInteger(drop.max)&&drop.min>=0&&drop.max>=drop.min),"every published Pal drop must have valid references, level, rate and quantity");
assert.equal(new Set(itemData.drops.map(drop=>`${drop.palId}:${drop.level}:${drop.itemId}`)).size,itemData.drops.length,"Pal drop relationships must be unique");
assert.deepEqual(itemData.drops.filter(drop=>drop.palId==="Anubis"&&drop.level===0),[
  {palId:"Anubis",itemId:"Bone",level:0,rate:100,min:3,max:5},
  {palId:"Anubis",itemId:"PalUpgradeStone3",level:0,rate:100,min:1,max:1},
  {palId:"Anubis",itemId:"TechnologyBook_G2",level:0,rate:5,min:1,max:1}
],"Anubis base drop table must match the current extracted game row");
assert.match(main,/dropLabels:Record<Locale/,"drop relationship UI must provide labels for every supported locale");
assert.match(main,/itemData\.drops\.filter\(drop=>drop\.palId===pal\.id\)/,"Pal details must render normalized item drops");
assert.match(main,/renderItemDropSection\(item\)/,"item details must render reverse Pal drop relationships in the detail template");
assert.doesNotMatch(main,/function bindDropRelations/,"drop relationships must not depend on post-render DOM insertion");
const leatherSources=groupItemDropSources("Leather",palData.pals,itemData.drops);
assert.equal(leatherSources.length,77,"Leather detail must expose all 77 unique Pal sources");
assert.equal(leatherSources.flatMap(source=>source.drops).length,115,"Leather Pal cards must preserve all 115 level-specific drop rows");
assert.ok(leatherSources.every((source,index)=>index===0||leatherSources[index-1].pal.dex<=source.pal.dex),"item drop Pal sources must use deterministic Paldeck ordering");
assert.ok(groupItemDropSources("TechnologyBook_G2",palData.pals,itemData.drops).some(source=>source.pal.id==="Anubis"),"Technology Manual detail must link back to Anubis");
assert.deepEqual(groupItemDropSources("Accessory_AirDash1",palData.pals,itemData.drops),[],"items without Pal drops must produce an explicit empty result");
assert.equal(itemCategoryProvenance,"gpt","site-owned item category translations must record their provenance");
assert.deepEqual([...new Set(itemData.items.map(item=>item.type))].sort(),[...itemCategories].sort(),"every extracted item category must have a localized UI mapping");
for(const locale of Object.keys(messageCatalogs)){
  assert.ok(itemCategoryFieldLabels[locale],`${locale} must localize the item category field label`);
  assert.ok(itemCategories.every(category=>itemCategoryLabel(category,locale)),`${locale} must localize every item category`);
}
assert.equal(itemCategoryLabel("Armor","ko-KR"),"방어구","Korean armor category must be localized");
assert.equal(itemCategoryLabel("Blueprint","ko-KR"),"설계도","Korean schematic category must be localized");
assert.doesNotMatch(main,/item-card[^\n]*<code>\$\{esc\(item\.id\)\}/,"item cards must not expose internal item IDs");
assert.doesNotMatch(main,/<span>\$\{esc\(item\.subtype\)\}<\/span>/,"item cards and details must not expose raw subtype enums");
assert.match(styles,/\.item-card\{display:flex;flex-direction:column;/,"item cards must keep their header, category and stats in a stable vertical flow");
assert.match(main,/hero\(itemName\(item\)\)/,"item detail headers must omit the duplicated description");
assert.match(main,/function hero\(title:string,\.\.\._descriptions:string\[\]\).*<h1>\$\{title\}<\/h1><\/section>/,"all internal page headers must render only the verification badge and title");
assert.doesNotMatch(main,/function hero[^\n]*\$\{body\}/,"internal page headers must never render page descriptions");
assert.match(main,/usedIn\.length\.toLocaleString\(locale\).*\$\{m\.results\}/,"item detail result headings must include the localized actual count");
assert.doesNotMatch(main,/usedIn\.slice\(0,80\)/,"item detail result headings and rendered cards must not disagree because of a hidden cap");
assert.match(styles,/\.item-categories\{[^}]*margin:\.75rem 0 1rem/,"item categories must have visible separation from the item image and stats");
assert.match(styles,/\.item-stats\{[^}]*margin:auto 0 0/,"item stats must stay aligned at the bottom across one-line and wrapped item names");
assert.equal(itemData.meta.blueprintTargetCount,475,"every legal blueprint unlock relationship in the extracted recipe table must be retained");
assert.equal(itemData.meta.unavailableUnlockItem,1,"the one recipe referencing an unavailable blueprint must remain explicit");
assert.equal(itemData.items.find(item=>item.id==="Blueprint_Accessory_AT_1_2")?.unlocksItemId,"Accessory_AT_1","blueprint target links must come from the official UnlockItemID recipe field");
assert.match(main,/class="blueprint-product"/,"blueprint cards must show the verified unlocked-product image when available");
assert.equal(imageManifest.gameBuild,itemData.meta.gameBuild,"image manifest must match the item data build");
const imagedItems=itemData.items.filter(item=>item.image===true);
assert.equal(imageManifest.itemCount,imagedItems.length,"item image manifest must match verified image flags");
assert.equal(imagedItems.length,itemData.items.length,"every legal item must have a verified display image");
assert.equal(imageManifest.missingItemCount,0,"item image manifest must not permit missing display images");
assert.equal(imageManifest.derivedOfficialItemCount,76,"unresolvable cooked icons must use the reviewed official-derived image plan");
for(const item of imagedItems)await access(`public/assets/items/${item.id}.webp`);
for(const technology of technologyData.technologies)await access(`public/assets/technology/${technology.slug}.webp`);
await access("public/assets/structures/structures-atlas.webp");
assert.equal(new Set(itemData.items.map(item=>item.id.toLowerCase())).size,itemData.items.length,"item IDs must be unique without case ambiguity");
const itemIds=new Set(itemData.items.map(item=>item.id));
assert.ok(itemData.items.every(item=>Object.keys(item.names).length===17&&Object.values(item.names).every(Boolean)),"every item must have all 17 official localized names");
assert.ok(itemData.recipes.every(recipe=>itemIds.has(recipe.productId)&&recipe.ingredients.every(i=>itemIds.has(i.itemId)&&i.count>0)&&recipe.output>0&&recipe.workAmount>=0),"every published recipe reference and numeric value must be valid");
assert.deepEqual(itemData.meta.caseCorrections,["FIber->Fiber","cloth->Cloth","cloth2->Cloth2","stone->Stone","wood->Wood"],"known source case differences must be explicit and deterministic");
const mega=itemData.recipes.find(recipe=>recipe.id==="PalSphere_Mega");
assert.deepEqual(mega?.ingredients,[{itemId:"Pal_crystal_S",count:1},{itemId:"CopperIngot",count:1},{itemId:"Wood",count:3},{itemId:"Stone",count:3}],"Mega Sphere golden recipe must match the extracted game table");
assert.deepEqual(itemData.map,{minX:-1099400,minY:-724400,maxX:349400,maxY:724400,width:8192,height:8192},"official map bounds and texture dimensions must remain stable for this build");
assert.equal(mapImage.subarray(0,4).toString("ascii"),"RIFF","published map must be a WebP container");
assert.equal(mapImage.subarray(8,12).toString("ascii"),"WEBP","published map must have the WebP signature");
assert.match(main,/fetch\("\/data\/items\.json"\)/,"verified item data must load from the same origin");
assert.match(main,/bounds\.minX.*bounds\.maxX.*bounds\.minY.*bounds\.maxY/,"map pins must be constrained to extracted official bounds");
assert.equal(resolveLocale("/ja-JP/database"),"ja-JP","an explicit URL locale must take precedence");
globalThis.localStorage={getItem:key=>key==="pw-locale"?"ko-KR":null};
assert.equal(resolveLocale("/database"),"ko-KR","stored locale must be used when the URL has no locale");
globalThis.localStorage={getItem:()=>null};
assert.equal(resolveLocale("/database"),"en-US","English must be the final default without browser-language detection");
assert.equal(Object.keys(messageCatalogs["ja-JP"]).length,Object.keys(messageCatalogs["en-US"]).length,"Japanese UI catalog must be complete");
assert.equal(translationProvenance["ja-JP"],"gpt","provisional Japanese UI translation provenance must be explicit");
assert.notEqual(messages("ja-JP").itemDatabase,messages("en-US").itemDatabase,"Japanese item UI must not silently fall back to English");
assert.deepEqual(Object.keys(databaseItemTabLabels).sort(),Object.keys(messageCatalogs).sort(),"Item database tab labels must cover every supported locale");
assert.equal(databaseItemTabLabels["ko-KR"],"아이템","Korean item database tab must use the concise requested label");
assert.equal(messages("ko-KR").itemDatabase,"아이템","The Korean item collection title and metadata must use the requested concise label");
for(const locale of Object.keys(messageCatalogs).filter(locale=>locale!=="ko-KR")) assert.equal(databaseItemTabLabels[locale],messages(locale).itemDatabase,`${locale} item database label must remain unchanged`);
assert.deepEqual(Object.keys(itemFilterAllLabels).sort(),Object.keys(messageCatalogs).sort(),"Item filter all labels must cover every supported locale");
assert.equal(itemFilterAllLabelsProvenance,"gpt","Item filter all labels must record translation provenance");
assert.equal(itemFilterAllLabels["ko-KR"],"전체","Korean item filters must use an item-neutral all option");
assert.match(main,/id="item-type"><option value="">\$\{itemFilterAllLabels\[locale\]\}/,"Item category filter must not reuse the Pal selection prompt");
assert.match(main,/id="item-rarity"><option value="">\$\{itemFilterAllLabels\[locale\]\}/,"Item rarity filter must not reuse the Pal selection prompt");
assert.equal(itemData.items.find(item=>item.id==="PalSphere_Mega")?.names["ja-JP"],"メガスフィア","official Japanese game terminology must remain in extracted data");
assert.doesNotMatch(main,/const ui=/,"user-visible item and crafting copy must use the message catalog");
assert.equal(translationProvenance["zh-CN"],"gpt","Simplified Chinese UI provenance must be explicit");
assert.equal(translationProvenance["zh-TW"],"gpt","Traditional Chinese UI provenance must be explicit");
assert.notEqual(messages("zh-CN").privacy,messages("zh-TW").privacy,"Simplified and Traditional Chinese UI must remain independently localized");
assert.equal(itemData.items.find(item=>item.id==="PalSphere_Mega")?.names["zh-CN"],"高级帕鲁球","official Simplified Chinese item terminology must remain extracted game data");
assert.equal(itemData.items.find(item=>item.id==="PalSphere_Mega")?.names["zh-TW"],"高級帕魯球","official Traditional Chinese item terminology must remain extracted game data");
for(const locale of ["fr-FR","it-IT","de-DE"]) assert.equal(translationProvenance[locale],"gpt",`${locale} UI provenance must be explicit`);
const megaSphere=itemData.items.find(item=>item.id==="PalSphere_Mega");
assert.equal(megaSphere?.names["fr-FR"],"Méga Sphère","official French item terminology must remain extracted game data");
assert.equal(megaSphere?.names["it-IT"],"Sfera mega","official Italian item terminology must remain extracted game data");
assert.equal(megaSphere?.names["de-DE"],"Mega-Sphäre","official German item terminology must remain extracted game data");
assert.match(messages("fr-FR").verifiedBody,/44 851/,"French large-number prose must retain the verified row count");
assert.match(messages("it-IT").rarity,/à/,"Italian accented characters must remain valid UTF-8");
assert.match(messages("de-DE").ownedMaterials,/Vorhandene Materialien/,"long German control copy must remain localized");
const completedLocales=["es-ES","pt-BR","ru-RU","id-ID","es-419","th-TH","tr-TR","vi-VN","pl-PL"];
for(const locale of completedLocales){
  assert.equal(translationProvenance[locale],"gpt",`${locale} UI provenance must be explicit`);
  assert.equal(Object.keys(messageCatalogs[locale]).length,Object.keys(messageCatalogs["en-US"]).length,`${locale} UI catalog must be complete`);
}
const officialMegaNames={"es-ES":"Megaesfera","pt-BR":"Esfera Mega","ru-RU":"Мегасфера","id-ID":"Mega Sphere","es-419":"Megaesfera","th-TH":"เมกาสเฟียร์","tr-TR":"Mega Küre","vi-VN":"Quả Cầu Mega","pl-PL":"Mega Sfera"};
for(const [locale,name] of Object.entries(officialMegaNames)) assert.equal(megaSphere?.names[locale],name,`${locale} official item terminology must remain extracted game data`);
assert.equal(Object.values(translationProvenance).filter(value=>value==="fallback").length,0,"release catalog must have no fallback locales");
assert.match(messages("ru-RU").privacy,/Конфиденциальность/,"Cyrillic UI text must remain valid UTF-8");
assert.match(messages("th-TH").language,/ภาษา/,"Thai UI text must remain valid UTF-8");
assert.match(messages("vi-VN").quantity,/Số lượng/,"Vietnamese diacritics must remain valid UTF-8");
assert.doesNotMatch(main,/Loading…/,"home page must not show a loading state for data it intentionally loads lazily");
assert.match(main,/data-clear-search="pal"/,"Pal search must expose a one-action clear control");
assert.match(main,/data-clear-search="item"/,"item search must expose a one-action clear control");
assert.match(main,/id="pal-empty"[^>]*hidden/,"Pal search must have an explicit empty state");
assert.match(main,/id="item-empty"[^>]*hidden/,"item search must have an explicit empty state");
assert.match(main,/filterCollection\(kind\).*input\.focus\(\)/,"clearing search must restore results and keyboard focus");
assert.equal(skillData.meta.gameBuild,"24181527","skill data must match the verified local game build");
assert.equal(skillData.elements.length,9,"all nine game elements must be published");
assert.equal(skillData.activeSkills.length,317,"only active skills with an official player-facing name must be published");
assert.ok(skillData.activeSkills.every(skill=>Object.values(skill.names).every(name=>name.trim().length>0)),"every published active skill must have all 17 official localized names");
assert.equal(skillData.activeSkills.filter(skill=>Object.values(skill.descriptions).every(description=>description.trim().length>0)).length,314,"official active-skill description coverage must remain stable");
assert.equal(skillData.passiveSkills.length,115,"only displayable standard passive skills with descriptions must be published");
assert.equal(skillData.partnerSkills.length,299,"every Pal must retain its partner-skill route");
assert.ok(skillData.passiveSkills.every(skill=>Object.keys(skill.descriptions).length===17&&Object.values(skill.descriptions).every(description=>description.trim().length>0)),"every passive skill must publish all 17 official localized descriptions");
assert.ok(skillData.passiveSkills.every(skill=>[-3,-2,-1,1,2,3,4,5].includes(skill.rank)),"every passive skill must map to an extracted rank icon");
assert.ok(skillData.elements.every(element=>Object.keys(element.names).length===17),"every element must have all supported localized names");
assert.ok(skillData.activeSkills.every(skill=>skillData.elements.some(element=>element.id===skill.elementId)),"every active skill must reference a published element");
assert.ok(palData.pals.every(pal=>Array.isArray(pal.guaranteedPassiveIds)),"every Pal must expose a deterministic guaranteed-passive list");
const passiveIds=new Set(skillData.passiveSkills.map(skill=>skill.id));
assert.ok(palData.pals.every(pal=>pal.guaranteedPassiveIds.every(id=>passiveIds.has(id))),"every guaranteed Pal passive must reference a published passive skill");
assert.match(main,/fetch\("\/data\/skills\.json"\)/,"versioned skill data must load from the same origin");
assert.match(main,/id="skill-element"/,"skill collection must support element filtering");
assert.match(main,/role="status"/,"collection result counts must be announced as status updates");
assert.match(main,/rankOrder=\[5,4,3,2,1,-1,-2,-3\]/,"passive skill groups must be ordered from highest to lowest extracted rank");
assert.match(main,/data-passive-group=/,"passive skills must render in semantic rank groups");
assert.match(main,/id="skill-rank"/,"passive skill collections must provide a rank filter");
assert.match(main,/partnerSkillName\(skill,pal\)/,"partner skill names must safely fall back through linked Pal names");
assert.match(featureStyles,/\.skill-name-link,\.pal-passives strong a\{[^}]*text-decoration:none/,"skill name links must remove the default underline");
assert.match(featureStyles,/\.passive-rank-group\[data-passive-group="5"\]/,"highest passive ranks must have a game-inspired rank accent");
assert.match(featureStyles,/\.passive-rank-group\[data-passive-group="1"\],\.passive-rank-group\[data-passive-group="2"\],\.passive-rank-group\[data-passive-group="3"\]\{--rank-accent:#ffdd00\}/,"positive passive ranks 1 through 3 must use the extracted game-yellow accent");
assert.match(featureStyles,/\.passive-rank-group:is\(\[data-passive-group="1"\],\[data-passive-group="2"\],\[data-passive-group="3"\]\) \.passive-rank-heading img/,"game-yellow rank accents must tint the extracted rank icon masks");
assert.match(featureStyles,/\.passive-rank-group \.passive-game-card\{[^}]*background:linear-gradient\([^}]*var\(--rank-accent\)/,"passive skill card backgrounds must inherit their rank accent");
assert.match(featureStyles,/\.passive-rank-group\[data-passive-group="1"\]\{--rank-surface-strength:6%\}\.passive-rank-group\[data-passive-group="2"\]\{--rank-surface-strength:9%\}\.passive-rank-group\[data-passive-group="3"\]\{--rank-surface-strength:12%\}/,"yellow passive ranks must remain distinguishable through graduated surface strength");
assert.match(featureStyles,/\.passive-rank-group \.passive-game-card:hover,\.passive-rank-group \.passive-game-card:focus-within/,"rank-colored passive cards must preserve hover and keyboard focus feedback");
assert.doesNotMatch(main,/<code>\$\{esc\(skill\.id\)\}<\/code>/,"skill cards and details must not expose internal identifiers");
assert.match(main,/const description=localized\(skill\.descriptions\);setMeta\(localized\(skill\.names\),description\|\|labels\.active\)/,"active skill details must use the official localized description in metadata");
assert.match(main,/<p class="entity-description">\$\{esc\(description\)\}<\/p>/,"skill details must render the official localized description in the detail content");
const convergingRecipes={A:{id:"A",output:1,ingredients:{B:1,C:1}},B:{id:"B",output:1,ingredients:{D:1}},C:{id:"C",output:1,ingredients:{D:1}},D:{id:"D",output:2,ingredients:{E:1}}};
assert.deepEqual(expandRecipe("A",1,convergingRecipes),{E:1},"converging demands must aggregate before process rounding");
assert.deepEqual(expandRecipe("A",1,convergingRecipes,{D:1}),{E:1},"owned intermediate stock must be consumed once after demands converge");
assert.deepEqual(expandRecipe("A",1,convergingRecipes,{E:1}),{},"owned raw material must reduce the final net requirement");
assert.deepEqual(expandRecipe("A",1,convergingRecipes,{A:1}),{},"owned target products must avoid all crafting requirements");
assert.throws(()=>expandRecipe("A",1,{A:{id:"A",output:1,ingredients:{B:1}},B:{id:"B",output:1,ingredients:{A:1}}}),/Recipe cycle/,"recipe cycles must fail closed");
assert.throws(()=>expandRecipe("A",0,convergingRecipes),/Invalid recipe target or quantity/,"zero target quantity must be rejected");
assert.throws(()=>expandRecipe("A",1,{A:{id:"A",output:0,ingredients:{E:1}}}),/Invalid recipe output/,"non-positive recipe output must be rejected");
assert.match(main,/totals\.get\(recipe\.productId\).*number.*totals\.get\(recipe\.productId\)/,"recipe selector must distinguish multiple recipe rows without exposing recipe IDs");
const productRecipeCounts=new Map();
for(const recipe of itemData.recipes)productRecipeCounts.set(recipe.productId,(productRecipeCounts.get(recipe.productId)||0)+1);
const selectedMega=itemData.recipes.find(recipe=>recipe.id==="PalSphere_Mega");
const unambiguousRecipes=Object.fromEntries(itemData.recipes.filter(recipe=>productRecipeCounts.get(recipe.productId)===1).map(recipe=>[recipe.productId,{id:recipe.id,output:recipe.output,ingredients:Object.fromEntries(recipe.ingredients.map(i=>[i.itemId,i.count]))}]));
unambiguousRecipes[selectedMega.productId]={id:selectedMega.id,output:selectedMega.output,ingredients:Object.fromEntries(selectedMega.ingredients.map(i=>[i.itemId,i.count]))};
assert.deepEqual(expandRecipe("PalSphere_Mega",1,unambiguousRecipes),{CopperOre:2,Pal_crystal_S:1,Stone:3,Wood:3},"Mega Sphere expanded BOM must match verified recipes while stopping at ambiguous recipe boundaries");
assert.deepEqual(expandRecipe("PalSphere_Mega",10,unambiguousRecipes,{Wood:10,Stone:10,CopperIngot:2}),{CopperOre:16,Pal_crystal_S:10,Stone:20,Wood:20},"Mega Sphere owned-material golden case must consume stock once and expand the remainder");
assert.match(main,/recipeCounts\.get\(recipe\.productId\)===1/,"recursive crafting must not guess among ambiguous intermediate recipes");
assert.match(main,/function enhancePalSelect/,"breeding Pal selectors must use an image-capable searchable combobox");
assert.match(main,/class=\"pair-card\"/,"reverse breeding results must render image-capable Pal pair cards");
assert.match(featureStyles,/\.pair-list>\.pair-card-grid\{display:grid;grid-template-columns:repeat\(auto-fit,minmax\(min\(100%,20rem\),1fr\)\)/,"reverse-breeding cards must override the legacy child grid with a readable responsive minimum width");
assert.match(featureStyles,/\.pair-card \.pal-visual small,\.pair-card \.pal-visual strong,\.pair-card>a>small\{white-space:nowrap;word-break:keep-all\}/,"reverse-breeding labels must not break into vertical text");
assert.match(main,/data-dynamic-link/,"dynamically rendered breeding results must support client-side detail navigation");
assert.match(main,/palVisual\(pal,"result"\)/,"forward breeding results must render a Pal image card");
assert.match(main,/\["\/map","\/database","\/calculators\/crafting"\]\.includes\(current\).*ensureItemData/,"item data must load only on routes that use it");
assert.match(main,/\["\/map","\/pals","\/calculators","\/calculators\/breeding"\]\.includes\(current\).*current\.startsWith\("\/skills\/partner"\).*ensurePalData/,"Pal data must load on partner-skill routes");
assert.match(main,/current==="\/map"\)ensureMapData/,"map marker data must load only on the map route");
assert.doesNotMatch(main,/href\(\"\/privacy\"\)/,"privacy policy must not be exposed in the public UI");

assert.match(main,/shellNavigation\.map\(item=>shellLink\(item\)\)/,"desktop navigation must use the shared shell route manifest");
assert.match(main,/shellNavigation\.map\(item=>shellLink\(item,true\)\)/,"compact navigation must use the shared shell route manifest");
assert.match(main,/aria-current="page"/,"the active shell destination must expose aria-current");
assert.match(main,/id="global-search-dialog"/,"the shell must provide a global search dialog");
assert.match(main,/ensureGlobalSearchData/,"global search must load Pal, item and skill data on demand");
assert.match(main,/data-theme-choice/,"theme selection must expose explicit system, light and dark choices");
assert.doesNotMatch(main,/trackEvent\([^\n]*(query|searchInput)/,"global search text must not be sent to analytics");
assert.match(main,/meta\[name="theme-color"\]/,"theme changes must update the browser theme color");

console.log("Passed core SEO, safety, provenance, localization, shell, search, loading, data, map and calculator assertions.");
