import type {Locale} from "../config.ts";
import type {Messages} from "../i18n.ts";
import {itemCategoryFieldLabels,itemCategoryLabel} from "../item-categories.ts";
import {groupItemDropSources} from "../drop-relations.ts";
import {dungeonCopy} from "../dungeon-i18n.ts";
import {expeditionCopy} from "../expedition-i18n.ts";
import {itemFilterAllLabels} from "../ui-i18n.ts";
import {shellCopy} from "../shell-i18n.ts";
import {technologyCopy} from "../technology-i18n.ts";
import {structureCopy} from "../structure-i18n.ts";
import {itemPublicSlug} from "../public-slugs.ts";

const itemPageSize=96;

type Pal={id:string;dex:number;variant:boolean;names:Record<Locale,string>;image?:boolean};
type PalDrop={palId:string;itemId:string;level:number;rate:number;min:number;max:number};
type PalData={pals:Pal[]};
type Item={id:string;names:Record<Locale,string>;descriptions:Record<Locale,string>;type:string;subtype:string;rank:number;rarity:number;maxStack:number;weight:number;price:number;image?:boolean;unlocksItemId?:string};
type ItemRecipe={id:string;productId:string;output:number;workAmount:number;ingredients:{itemId:string;count:number}[]};
type ItemData={items:Item[];recipes:ItemRecipe[];drops:PalDrop[]};
type DungeonItemPool={kind:"normal"|"special"|"reward";slots:{candidates:{itemId:string}[]}[]};
type Dungeon={slug:string;names:Record<Locale,string>;itemPools:DungeonItemPool[];rewardSources:{itemPools:DungeonItemPool[]}[]};
type DungeonData={dungeons:Dungeon[]};
type ExpeditionRewardCandidate={itemId:string;minCount:number;maxCount:number};
type Expedition={slug:string;names:Record<Locale,string>;image:string;rewardSlots:{slot:number;candidates:ExpeditionRewardCandidate[]}[]};
type ExpeditionData={expeditions:Expedition[]};
type ItemRelationTechnology={slug:string;names:Record<Locale,string>;level:number;kind:"regular"|"ancient"};
type ItemRelationStructure={slug:string;names:Record<Locale,string>;icon:{index:number}};
type ItemRelations={craftedBy:string[];ingredientOf:{recipeId:string;count:number}[];unlockedBy:string[];constructionMaterialFor:{slug:string;count:number}[];producedBy:string[]};
type ItemRelationData={meta:{structureAtlas:{path:string;columns:number;rows:number}};technologies:ItemRelationTechnology[];structures:ItemRelationStructure[];byItem:Record<string,ItemRelations>};
type DatabaseTab="items"|"npcs"|"dungeons"|"technology"|"health"|"elements"|"structures"|"expeditions"|"quests";
type DropLabels={items:string;pals:string;level:string;chance:string;quantity:string};
const dropEmptyLabels:Record<Locale,string>={
  "en-US":"No Pal drops this item.","ko-KR":"이 아이템을 드랍하는 팰이 없습니다.","ja-JP":"このアイテムをドロップするパルはいません。","zh-CN":"没有帕鲁掉落此物品。","zh-TW":"沒有帕魯掉落此物品。","fr-FR":"Aucun Pal ne laisse tomber cet objet.","it-IT":"Nessun Pal rilascia questo oggetto.","de-DE":"Kein Pal lässt diesen Gegenstand fallen.","es-ES":"Ningún Pal suelta este objeto.","es-419":"Ningún Pal suelta este objeto.","pt-BR":"Nenhum Pal deixa este item.","ru-RU":"Ни один Пал не оставляет этот предмет.","id-ID":"Tidak ada Pal yang menjatuhkan item ini.","th-TH":"ไม่มีพาลตัวใดดรอปไอเทมนี้","tr-TR":"Bu eşyayı düşüren Pal yok.","vi-VN":"Không có Pal nào làm rơi vật phẩm này.","pl-PL":"Żaden Pal nie upuszcza tego przedmiotu."
};

type RenderContext={
  locale:Locale;
  defaultLocale:Locale;
  messages:Messages;
  data:PalData|null;
  itemData:ItemData|null;
  itemRelationData:ItemRelationData|null;
  dungeonData:DungeonData|null;
  expeditionData:ExpeditionData|null;
  dropLabels:DropLabels;
  href:(path:string)=>string;
  escape:(value:string)=>string;
  resolveItemSegment:(segment:string)=>Item|null;
  setMeta:(title:string,description?:string)=>void;
  hero:(title:string,...descriptions:string[])=>string;
  databaseTabs:(active:DatabaseTab)=>string;
  placeholder:(title:string)=>string;
};

type BindContext={document:Document;locale:Locale;messages:Messages;trackOnce:(key:string,name:string,params:Record<string,string|number|boolean>)=>boolean};

export function renderItemsPage(segment:string|null,context:RenderContext){
  const {locale,defaultLocale,messages:m,data,itemData,itemRelationData,dungeonData,expeditionData,dropLabels,href,escape:esc,resolveItemSegment,setMeta,hero,databaseTabs,placeholder}=context;
  const localized=(names:Record<Locale,string>)=>names[locale]||names[defaultLocale]||"",itemName=(item:Item)=>localized(item.names),palName=(pal:Pal)=>localized(pal.names),dungeonName=(dungeon:Dungeon)=>localized(dungeon.names),expeditionName=(expedition:Expedition)=>localized(expedition.names);
  const dropFacts=(drop:PalDrop)=>{const quantity=drop.min===drop.max?drop.min.toLocaleString(locale):`${drop.min.toLocaleString(locale)}–${drop.max.toLocaleString(locale)}`;return `<small>${dropLabels.level} ${drop.level.toLocaleString(locale)} · ${dropLabels.chance} ${drop.rate.toLocaleString(locale)}% · ${dropLabels.quantity} ${quantity}</small>`};
  const itemVisual=(item:Item,{detail=false}={})=>{const target=item.unlocksItemId?itemData?.items.find(candidate=>candidate.id===item.unlocksItemId):undefined,base=item.image?`<img class="${detail?"detail-image":"entity-image item-image"}" src="/assets/items/${encodeURIComponent(item.id)}.webp" alt="${esc(itemName(item))}" ${detail?"":'loading="lazy" width="96" height="96"'}>`:`<span class="${detail?"detail-image ":""}item-image item-fallback" aria-hidden="true">◇</span>`;return target?.image?`<span class="blueprint-visual${detail?" detail":""}">${base}<img class="blueprint-product" src="/assets/items/${encodeURIComponent(target.id)}.webp" alt="" loading="lazy"></span>`:base};
  const itemCard=(item:Item,deferred=false)=>{const category=itemCategoryLabel(item.type,locale),search=[...Object.values(item.names),item.id,item.type,item.subtype,category].join(" ").toLocaleLowerCase(locale);return `<article class="item-card" data-item="${esc(search)}" data-type="${esc(item.type)}" data-rarity="${item.rarity}"${deferred?" hidden":""}><div class="item-card-head">${itemVisual(item)}<div class="item-card-copy"><h2><a href="${href(`/items/${encodeURIComponent(item.id)}`)}" data-link>${esc(itemName(item))}</a></h2></div></div><p class="work-tags item-categories"><span>${esc(category)}</span></p><dl class="item-stats"><div><dt>${m.rank}</dt><dd>${item.rank}</dd></div><div><dt>${m.rarity}</dt><dd>${item.rarity}</dd></div><div><dt>${m.stack}</dt><dd>${item.maxStack.toLocaleString(locale)}</dd></div><div><dt>${m.weight}</dt><dd>${item.weight.toLocaleString(locale)}</dd></div><div><dt>${m.price}</dt><dd>${item.price.toLocaleString(locale)}</dd></div></dl></article>`};
  const renderItemDropSection=(item:Item)=>{const entries=groupItemDropSources(item.id,data?.pals||[],itemData?.drops||[]);return `<section class="detail-section item-drop-section"><h2>${dropLabels.pals}${entries.length?` · ${entries.length.toLocaleString(locale)}`:""}</h2>${entries.length?`<div class="relation-list entity-relation-list">${entries.map(({pal,drops})=>`<a href="${href(`/pals/${encodeURIComponent(pal.id)}`)}" data-link>${pal.image?`<img src="/assets/pals/${encodeURIComponent(pal.id)}.png" alt="" loading="lazy">`:""}<span><strong>#${pal.dex}${pal.variant?"B":""} ${esc(palName(pal))}</strong>${drops.map(drop=>dropFacts(drop)).join("")}</span></a>`).join("")}</div>`:`<p class="empty-compact">${esc(dropEmptyLabels[locale])}</p>`}</section>`};
  const rewardItemPools=(dungeon:Dungeon)=>dungeon.rewardSources.flatMap(source=>source.itemPools);
  const renderItemDungeonSection=(item:Item)=>{if(!dungeonData)return "";const copy=dungeonCopy[locale],matches=dungeonData.dungeons.map(dungeon=>({dungeon,pools:[...dungeon.itemPools,...rewardItemPools(dungeon)].filter(pool=>pool.slots.some(slot=>slot.candidates.some(candidate=>candidate.itemId===item.id)))})).filter(entry=>entry.pools.length);if(!matches.length)return "";return `<section class="detail-section dungeon-backlinks"><h2>${copy.title}</h2><p class="notice">${esc(copy.itemNotice)}</p><div class="dungeon-backlink-grid">${matches.map(({dungeon,pools})=>`<a href="${href(`/database/dungeons/${dungeon.slug}`)}" data-link><img src="/assets/map-icons/dungeon.webp" alt="" width="40" height="40"><span><strong>${esc(dungeonName(dungeon))}</strong><small>${esc([...new Set(pools.map(pool=>pool.kind==="normal"?copy.floor:pool.kind==="special"?copy.special:copy.rewardItemPool))].join(" · "))}</small></span></a>`).join("")}</div></section>`};
  const expeditionQuantity=(candidate:ExpeditionRewardCandidate)=>candidate.minCount===candidate.maxCount?candidate.minCount.toLocaleString(locale):`${candidate.minCount.toLocaleString(locale)}–${candidate.maxCount.toLocaleString(locale)}`;
  const renderItemExpeditionSection=(item:Item)=>{const copy=expeditionCopy[locale],relations=(expeditionData?.expeditions||[]).flatMap(expedition=>expedition.rewardSlots.flatMap(slot=>slot.candidates.filter(candidate=>candidate.itemId===item.id).map(candidate=>({expedition,slot:slot.slot,candidate}))));if(!relations.length)return "";return `<section class="detail-section item-expedition-section"><h2>${esc(copy.obtainedFrom)}</h2><div class="item-expedition-list">${relations.map(({expedition,slot,candidate})=>`<a href="${href(`/database/expeditions/${expedition.slug}`)}" data-link><img src="${expedition.image}" alt="" width="216" height="20" loading="lazy"><span><strong>${esc(expeditionName(expedition))}</strong><small>${esc(copy.rewardSlot)} ${slot.toLocaleString(locale)} · ${dropLabels.quantity} ${expeditionQuantity(candidate)}</small></span></a>`).join("")}</div><p class="notice">${esc(copy.rewardNotice)}</p></section>`};
  const renderItemTechnologySection=(item:Item)=>{const slugs=itemRelationData?.byItem[item.id]?.unlockedBy||[],bySlug=new Map((itemRelationData?.technologies||[]).map(entry=>[entry.slug,entry])),copy=technologyCopy[locale],relations=slugs.map(slug=>bySlug.get(slug)).filter((entry):entry is ItemRelationTechnology=>Boolean(entry)).sort((left,right)=>left.level-right.level||new Intl.Collator(locale).compare(localized(left.names),localized(right.names))||left.slug.localeCompare(right.slug));if(!relations.length)return "";return `<section class="detail-section item-technology-relations"><h2>${esc(copy.title)}</h2><div class="relation-list entity-relation-list">${relations.map(entry=>`<a href="${href(`/database/technology/${entry.slug}`)}" data-link><img src="/assets/technology/${encodeURIComponent(entry.slug)}.webp" alt="" width="48" height="48" loading="lazy"><span><strong>${esc(localized(entry.names))}</strong><small>${esc(entry.kind==="ancient"?copy.ancient:copy.regular)} · ${esc(copy.level)} ${entry.level.toLocaleString(locale)}</small></span></a>`).join("")}</div></section>`};
  const structureIcon=(structure:ItemRelationStructure)=>{const atlas=itemRelationData?.meta.structureAtlas;if(!atlas)return "";const column=structure.icon.index%atlas.columns,row=Math.floor(structure.icon.index/atlas.columns),x=atlas.columns>1?column/(atlas.columns-1)*100:0,y=atlas.rows>1?row/(atlas.rows-1)*100:0;return `<span class="structure-icon search" aria-hidden="true" style="--structure-atlas:url('${atlas.path}');--structure-atlas-width:${atlas.columns*100}%;--structure-atlas-height:${atlas.rows*100}%;--structure-atlas-x:${x}%;--structure-atlas-y:${y}%"></span>`};
  const renderItemStructureSection=(item:Item)=>{const relations=itemRelationData?.byItem[item.id],bySlug=new Map((itemRelationData?.structures||[]).map(entry=>[entry.slug,entry])),copy=structureCopy[locale],sort=(left:ItemRelationStructure,right:ItemRelationStructure)=>new Intl.Collator(locale).compare(localized(left.names),localized(right.names))||left.slug.localeCompare(right.slug),produced=(relations?.producedBy||[]).map(slug=>bySlug.get(slug)).filter((entry):entry is ItemRelationStructure=>Boolean(entry)).sort(sort),materials=(relations?.constructionMaterialFor||[]).map(relation=>({relation,structure:bySlug.get(relation.slug)})).filter((entry):entry is {relation:{slug:string;count:number};structure:ItemRelationStructure}=>Boolean(entry.structure)).sort((left,right)=>sort(left.structure,right.structure));if(!produced.length&&!materials.length)return "";const cards=(entries:{structure:ItemRelationStructure;detail:string}[])=>`<div class="relation-list item-structure-relation-list">${entries.map(({structure,detail})=>`<a href="${href(`/database/structures/${structure.slug}`)}" data-link>${structureIcon(structure)}<span><strong>${esc(localized(structure.names))}</strong><small>${esc(detail)}</small></span></a>`).join("")}</div>`;return `<section class="detail-section item-structure-relations"><h2>${esc(copy.title)}</h2>${produced.length?`<h3>${esc(copy.production)}</h3>${cards(produced.map(structure=>({structure,detail:copy.production})))}`:""}${materials.length?`<h3>${esc(copy.materials)}</h3>${cards(materials.map(({structure,relation})=>({structure,detail:`${copy.materials} ×${relation.count.toLocaleString(locale)}`})))}`:""}</section>`};
  const collection=()=>{setMeta(m.itemDatabase,m.itemDatabaseBody);const items=[...(itemData?.items||[])],sorted=items.sort((a,b)=>new Intl.Collator(locale,{numeric:true}).compare(itemName(a),itemName(b))||a.id.localeCompare(b.id)),types=[...new Set(items.map(item=>item.type))].sort((a,b)=>new Intl.Collator(locale).compare(itemCategoryLabel(a,locale),itemCategoryLabel(b,locale))),rarities=[...new Set(items.map(item=>item.rarity))].sort((a,b)=>a-b);return `${hero(m.itemDatabase,m.itemDatabaseBody)}<section class="section">${databaseTabs("items")}<p><a class="button primary" href="${href("/calculators/crafting")}" data-link>${m.openCrafting}</a></p><div class="collection-filters"><label class="collection-search">${m.searchItems}<input id="item-search" type="search" autocomplete="off"></label><label>${itemCategoryFieldLabels[locale]}<select id="item-type"><option value="">${itemFilterAllLabels[locale]}</option>${types.map(value=>`<option value="${esc(value)}">${esc(itemCategoryLabel(value,locale))}</option>`).join("")}</select></label><label>${m.rarity}<select id="item-rarity"><option value="">${itemFilterAllLabels[locale]}</option>${rarities.map(value=>`<option value="${value}">${value}</option>`).join("")}</select></label><button class="button search-clear" data-clear-search="item" aria-label="${m.remove}">×</button></div><p id="item-count" role="status">${sorted.length.toLocaleString(locale)} ${m.results}</p><p id="item-empty" class="empty-compact" hidden>${m.noResult}</p><div class="item-grid" id="item-grid">${sorted.map((item,index)=>itemCard(item,index>=itemPageSize)).join("")}</div><p class="collection-more"><button class="button" id="item-more" type="button" aria-controls="item-grid"${sorted.length<=itemPageSize?" hidden":""}>${shellCopy[locale].more}</button></p></section>`};
  const detail=(detailSegment:string)=>{
    const item=resolveItemSegment(detailSegment);if(!item)return itemData?placeholder("404"):"";setMeta(itemName(item),item.descriptions?.[locale]||m.itemDatabaseBody);
    const byId=new Map(itemData?.items.map(candidate=>[candidate.id,candidate])||[]),recipeById=new Map(itemData?.recipes.map(recipe=>[recipe.id,recipe])||[]),relations=itemRelationData?.byItem[item.id],recipes=(relations?.craftedBy||[]).map(id=>recipeById.get(id)).filter((recipe):recipe is ItemRecipe=>Boolean(recipe)),usedIn=(relations?.ingredientOf||[]).map(relation=>recipeById.get(relation.recipeId)).filter((recipe):recipe is ItemRecipe=>Boolean(recipe)),unlocked=item.unlocksItemId?byId.get(item.unlocksItemId):undefined;
    const calculatorHref=(recipeIndex?:number)=>href(`/calculators/crafting?target=${encodeURIComponent(itemPublicSlug(item))}${recipeIndex?`&recipe=${recipeIndex}`:""}`),primaryCalculatorHref=recipes.length===1?calculatorHref(1):href("/calculators/crafting");
    const recipeCards=recipes.map((recipe,index)=>`<article class="relation-card item-recipe-card"><dl><div><dt>${esc(m.quantity)}</dt><dd>${recipe.output.toLocaleString(locale)}</dd></div><div><dt>${esc(m.workAmount)}</dt><dd>${recipe.workAmount.toLocaleString(locale)}</dd></div></dl><h3>${esc(m.directMaterials)}</h3><ul>${recipe.ingredients.map(ingredient=>{const related=byId.get(ingredient.itemId);return related?`<li><a href="${href(`/items/${encodeURIComponent(related.id)}`)}" data-link>${esc(itemName(related))}</a> × ${ingredient.count.toLocaleString(locale)}</li>`:""}).join("")}</ul><a class="button" href="${calculatorHref(index+1)}" data-link>${esc(m.openCrafting)}</a></article>`).join("");
    return `${hero(itemName(item))}<article class="entity-detail item-detail panel">${itemVisual(item,{detail:true})}<div class="entity-detail-content"><p class="entity-description">${esc(item.descriptions?.[locale]||m.itemDatabaseBody)}</p>${unlocked?`<p><a class="button" href="${href(`/items/${encodeURIComponent(unlocked.id)}`)}" data-link>${unlocked.image?`<img src="/assets/items/${encodeURIComponent(unlocked.id)}.webp" alt="" width="32" height="32">`:""}${esc(itemName(unlocked))}</a></p>`:""}<p class="work-tags item-categories"><span>${esc(itemCategoryLabel(item.type,locale))}</span></p><dl class="detail-stats"><div><dt>${m.rank}</dt><dd>${item.rank}</dd></div><div><dt>${m.rarity}</dt><dd>${item.rarity}</dd></div><div><dt>${m.stack}</dt><dd>${item.maxStack.toLocaleString(locale)}</dd></div><div><dt>${m.weight}</dt><dd>${item.weight.toLocaleString(locale)}</dd></div><div><dt>${m.price}</dt><dd>${item.price.toLocaleString(locale)}</dd></div></dl>${renderItemDropSection(item)}${renderItemDungeonSection(item)}${renderItemExpeditionSection(item)}${recipes.length?`<section class="detail-section item-crafting-relations"><h2>${m.crafting}</h2>${recipeCards}</section>`:""}${usedIn.length?`<section class="detail-section item-ingredient-relations"><h2>${usedIn.length.toLocaleString(locale)} ${m.results}</h2><div class="relation-list">${usedIn.map(recipe=>{const product=byId.get(recipe.productId);return product?`<a href="${href(`/items/${encodeURIComponent(product.id)}`)}" data-link>${product.image?`<img src="/assets/items/${encodeURIComponent(product.id)}.webp" alt="" loading="lazy">`:""}<span>${esc(itemName(product))}</span></a>`:""}).join("")}</div></section>`:""}<div class="detail-actions item-detail-actions"><a class="button primary" href="${primaryCalculatorHref}" data-link>${m.openCrafting}</a></div></div></article>`
  };
  if(segment===null)return collection();
  const item=resolveItemSegment(segment),markup=detail(segment);
  if(!item)return markup;
  return markup.replace('<section class="detail-section item-drop-section">',`${renderItemTechnologySection(item)}${renderItemStructureSection(item)}<section class="detail-section item-drop-section">`);
}

export function bindItemsPage(context:BindContext){
  const {document,locale,messages:m,trackOnce}=context;
  let visibleLimit=itemPageSize;
  const filterItems=(resetLimit=false)=>{if(resetLimit)visibleLimit=itemPageSize;const input=document.querySelector<HTMLInputElement>("#item-search");if(!input)return;const query=input.value.trim().toLocaleLowerCase(locale),rarity=document.querySelector<HTMLSelectElement>("#item-rarity")?.value||"",type=document.querySelector<HTMLSelectElement>("#item-type")?.value||"";let count=0;document.querySelectorAll<HTMLElement>(".item-card").forEach(card=>{const matches=(!query||card.dataset.item?.includes(query))&&(!rarity||card.dataset.rarity===rarity)&&(!type||card.dataset.type===type);if(matches)count++;card.hidden=!matches||count>visibleLimit});const status=document.querySelector<HTMLElement>("#item-count"),empty=document.querySelector<HTMLElement>("#item-empty"),more=document.querySelector<HTMLButtonElement>("#item-more");if(status)status.textContent=`${count.toLocaleString(locale)} ${m.results}`;if(empty)empty.hidden=count!==0;if(more)more.hidden=count<=visibleLimit};
  const search=document.querySelector<HTMLInputElement>("#item-search");search?.addEventListener("input",()=>{filterItems(true);if(search.value.trim())trackOnce("search:item","collection_search",{collection:"item"})});
  ["#item-type","#item-rarity"].forEach(selector=>document.querySelector(selector)?.addEventListener("change",()=>filterItems(true)));
  document.querySelector<HTMLButtonElement>("#item-more")?.addEventListener("click",()=>{visibleLimit+=itemPageSize;filterItems()});
  document.querySelector<HTMLButtonElement>('[data-clear-search="item"]')?.addEventListener("click",()=>{if(!search)return;search.value="";document.querySelectorAll<HTMLSelectElement>("#item-type,#item-rarity").forEach(select=>select.value="");filterItems(true);search.focus()});
}
