import type {Locale} from "../config.ts";
import type {Messages} from "../i18n.ts";
import {itemCategoryFieldLabels,itemCategoryLabel} from "../item-categories.ts";
import {groupItemDropSources} from "../drop-relations.ts";
import {dungeonCopy} from "../dungeon-i18n.ts";
import {expeditionCopy} from "../expedition-i18n.ts";
import {itemFilterAllLabels} from "../ui-i18n.ts";

type Pal={id:string;dex:number;variant:boolean;names:Record<Locale,string>;image?:boolean};
type PalDrop={palId:string;itemId:string;level:number;rate:number;min:number;max:number};
type PalData={pals:Pal[]};
type Item={id:string;names:Record<Locale,string>;descriptions:Record<Locale,string>;type:string;subtype:string;rank:number;rarity:number;maxStack:number;weight:number;price:number;image?:boolean;unlocksItemId?:string};
type ItemRecipe={id:string;productId:string;output:number;workAmount:number;ingredients:{itemId:string;count:number}[]};
type ItemData={items:Item[];recipes:ItemRecipe[];drops:PalDrop[]};
type DungeonItemPool={kind:"normal"|"special"|"reward";slots:{candidates:{itemId:string}[]}[]};
type Dungeon={slug:string;names:Record<Locale,string>;itemPools:DungeonItemPool[];rewardSources:{itemPools:DungeonItemPool[]}[]};
type DungeonData={dungeons:Dungeon[]};
type ExpeditionRewardCandidate={itemId:string;minCount:number;maxCount:number};
type Expedition={slug:string;names:Record<Locale,string>;image:string;rewardSlots:{slot:number;candidates:ExpeditionRewardCandidate[]}[]};
type ExpeditionData={expeditions:Expedition[]};
type DatabaseTab="items"|"npcs"|"dungeons"|"technology"|"health"|"elements"|"structures"|"expeditions"|"quests";
type DropLabels={items:string;pals:string;level:string;chance:string;quantity:string};
const dropEmptyLabels:Record<Locale,string>={
  "en-US":"No Pal drops this item.","ko-KR":"이 아이템을 드랍하는 팰이 없습니다.","ja-JP":"このアイテムをドロップするパルはいません。","zh-CN":"没有帕鲁掉落此物品。","zh-TW":"沒有帕魯掉落此物品。","fr-FR":"Aucun Pal ne laisse tomber cet objet.","it-IT":"Nessun Pal rilascia questo oggetto.","de-DE":"Kein Pal lässt diesen Gegenstand fallen.","es-ES":"Ningún Pal suelta este objeto.","es-419":"Ningún Pal suelta este objeto.","pt-BR":"Nenhum Pal deixa este item.","ru-RU":"Ни один Пал не оставляет этот предмет.","id-ID":"Tidak ada Pal yang menjatuhkan item ini.","th-TH":"ไม่มีพาลตัวใดดรอปไอเทมนี้","tr-TR":"Bu eşyayı düşüren Pal yok.","vi-VN":"Không có Pal nào làm rơi vật phẩm này.","pl-PL":"Żaden Pal nie upuszcza tego przedmiotu."
};

type RenderContext={
  locale:Locale;
  defaultLocale:Locale;
  messages:Messages;
  data:PalData|null;
  itemData:ItemData|null;
  dungeonData:DungeonData|null;
  expeditionData:ExpeditionData|null;
  dropLabels:DropLabels;
  href:(path:string)=>string;
  escape:(value:string)=>string;
  resolveItemSegment:(segment:string)=>Item|null;
  setMeta:(title:string,description?:string)=>void;
  hero:(title:string,...descriptions:string[])=>string;
  databaseTabs:(active:DatabaseTab)=>string;
  placeholder:(title:string)=>string;
};

type BindContext={document:Document;locale:Locale;messages:Messages;trackOnce:(key:string,name:string,params:Record<string,string|number|boolean>)=>boolean};

export function renderItemsPage(segment:string|null,context:RenderContext){
  const {locale,defaultLocale,messages:m,data,itemData,dungeonData,expeditionData,dropLabels,href,escape:esc,resolveItemSegment,setMeta,hero,databaseTabs,placeholder}=context;
  const localized=(names:Record<Locale,string>)=>names[locale]||names[defaultLocale]||"",itemName=(item:Item)=>localized(item.names),palName=(pal:Pal)=>localized(pal.names),dungeonName=(dungeon:Dungeon)=>localized(dungeon.names),expeditionName=(expedition:Expedition)=>localized(expedition.names);
  const dropFacts=(drop:PalDrop)=>{const quantity=drop.min===drop.max?drop.min.toLocaleString(locale):`${drop.min.toLocaleString(locale)}–${drop.max.toLocaleString(locale)}`;return `<small>${dropLabels.level} ${drop.level.toLocaleString(locale)} · ${dropLabels.chance} ${drop.rate.toLocaleString(locale)}% · ${dropLabels.quantity} ${quantity}</small>`};
  const itemVisual=(item:Item,{detail=false}={})=>{const target=item.unlocksItemId?itemData?.items.find(candidate=>candidate.id===item.unlocksItemId):undefined,base=item.image?`<img class="${detail?"detail-image":"entity-image item-image"}" src="/assets/items/${encodeURIComponent(item.id)}.webp" alt="${esc(itemName(item))}" ${detail?"":'loading="lazy" width="96" height="96"'}>`:`<span class="${detail?"detail-image ":""}item-image item-fallback" aria-hidden="true">◇</span>`;return target?.image?`<span class="blueprint-visual${detail?" detail":""}">${base}<img class="blueprint-product" src="/assets/items/${encodeURIComponent(target.id)}.webp" alt="" loading="lazy"></span>`:base};
  const itemCard=(item:Item)=>{const category=itemCategoryLabel(item.type,locale),search=[...Object.values(item.names),item.id,item.type,item.subtype,category].join(" ").toLocaleLowerCase(locale);return `<article class="item-card" data-item="${esc(search)}" data-type="${esc(item.type)}" data-rarity="${item.rarity}"><div class="item-card-head">${itemVisual(item)}<div class="item-card-copy"><h2><a href="${href(`/items/${encodeURIComponent(item.id)}`)}" data-link>${esc(itemName(item))}</a></h2></div></div><p class="work-tags item-categories"><span>${esc(category)}</span></p><dl class="item-stats"><div><dt>${m.rank}</dt><dd>${item.rank}</dd></div><div><dt>${m.rarity}</dt><dd>${item.rarity}</dd></div><div><dt>${m.stack}</dt><dd>${item.maxStack.toLocaleString(locale)}</dd></div><div><dt>${m.weight}</dt><dd>${item.weight.toLocaleString(locale)}</dd></div><div><dt>${m.price}</dt><dd>${item.price.toLocaleString(locale)}</dd></div></dl></article>`};
  const renderItemDropSection=(item:Item)=>{const entries=groupItemDropSources(item.id,data?.pals||[],itemData?.drops||[]);return `<section class="detail-section item-drop-section"><h2>${dropLabels.pals}${entries.length?` · ${entries.length.toLocaleString(locale)}`:""}</h2>${entries.length?`<div class="relation-list entity-relation-list">${entries.map(({pal,drops})=>`<a href="${href(`/pals/${encodeURIComponent(pal.id)}`)}" data-link>${pal.image?`<img src="/assets/pals/${encodeURIComponent(pal.id)}.png" alt="" loading="lazy">`:""}<span><strong>#${pal.dex}${pal.variant?"B":""} ${esc(palName(pal))}</strong>${drops.map(drop=>dropFacts(drop)).join("")}</span></a>`).join("")}</div>`:`<p class="empty-compact">${esc(dropEmptyLabels[locale])}</p>`}</section>`};
  const rewardItemPools=(dungeon:Dungeon)=>dungeon.rewardSources.flatMap(source=>source.itemPools);
  const renderItemDungeonSection=(item:Item)=>{if(!dungeonData)return "";const copy=dungeonCopy[locale],matches=dungeonData.dungeons.map(dungeon=>({dungeon,pools:[...dungeon.itemPools,...rewardItemPools(dungeon)].filter(pool=>pool.slots.some(slot=>slot.candidates.some(candidate=>candidate.itemId===item.id)))})).filter(entry=>entry.pools.length);if(!matches.length)return "";return `<section class="detail-section dungeon-backlinks"><h2>${copy.title}</h2><p class="notice">${esc(copy.itemNotice)}</p><div class="dungeon-backlink-grid">${matches.map(({dungeon,pools})=>`<a href="${href(`/database/dungeons/${dungeon.slug}`)}" data-link><img src="/assets/map-icons/dungeon.webp" alt="" width="40" height="40"><span><strong>${esc(dungeonName(dungeon))}</strong><small>${esc([...new Set(pools.map(pool=>pool.kind==="normal"?copy.floor:pool.kind==="special"?copy.special:copy.rewardItemPool))].join(" · "))}</small></span></a>`).join("")}</div></section>`};
  const expeditionQuantity=(candidate:ExpeditionRewardCandidate)=>candidate.minCount===candidate.maxCount?candidate.minCount.toLocaleString(locale):`${candidate.minCount.toLocaleString(locale)}–${candidate.maxCount.toLocaleString(locale)}`;
  const renderItemExpeditionSection=(item:Item)=>{const copy=expeditionCopy[locale],relations=(expeditionData?.expeditions||[]).flatMap(expedition=>expedition.rewardSlots.flatMap(slot=>slot.candidates.filter(candidate=>candidate.itemId===item.id).map(candidate=>({expedition,slot:slot.slot,candidate}))));if(!relations.length)return "";return `<section class="detail-section item-expedition-section"><h2>${esc(copy.obtainedFrom)}</h2><div class="item-expedition-list">${relations.map(({expedition,slot,candidate})=>`<a href="${href(`/database/expeditions/${expedition.slug}`)}" data-link><img src="${expedition.image}" alt="" width="216" height="20" loading="lazy"><span><strong>${esc(expeditionName(expedition))}</strong><small>${esc(copy.rewardSlot)} ${slot.toLocaleString(locale)} · ${dropLabels.quantity} ${expeditionQuantity(candidate)}</small></span></a>`).join("")}</div><p class="notice">${esc(copy.rewardNotice)}</p></section>`};
  const collection=()=>{setMeta(m.itemDatabase,m.itemDatabaseBody);const items=[...(itemData?.items||[])],sorted=items.sort((a,b)=>new Intl.Collator(locale,{numeric:true}).compare(itemName(a),itemName(b))||a.id.localeCompare(b.id)),types=[...new Set(items.map(item=>item.type))].sort((a,b)=>new Intl.Collator(locale).compare(itemCategoryLabel(a,locale),itemCategoryLabel(b,locale))),rarities=[...new Set(items.map(item=>item.rarity))].sort((a,b)=>a-b);return `${hero(m.itemDatabase,m.itemDatabaseBody)}<section class="section">${databaseTabs("items")}<p><a class="button primary" href="${href("/calculators/crafting")}" data-link>${m.openCrafting}</a></p><div class="collection-filters"><label class="collection-search">${m.searchItems}<input id="item-search" type="search" autocomplete="off"></label><label>${itemCategoryFieldLabels[locale]}<select id="item-type"><option value="">${itemFilterAllLabels[locale]}</option>${types.map(value=>`<option value="${esc(value)}">${esc(itemCategoryLabel(value,locale))}</option>`).join("")}</select></label><label>${m.rarity}<select id="item-rarity"><option value="">${itemFilterAllLabels[locale]}</option>${rarities.map(value=>`<option value="${value}">${value}</option>`).join("")}</select></label><button class="button search-clear" data-clear-search="item" aria-label="${m.remove}">×</button></div><p id="item-count" role="status">${sorted.length.toLocaleString(locale)} ${m.results}</p><p id="item-empty" class="empty-compact" hidden>${m.noResult}</p><div class="item-grid">${sorted.map(itemCard).join("")}</div></section>`};
  const detail=(detailSegment:string)=>{const item=resolveItemSegment(detailSegment);if(!item)return itemData?placeholder("404"):"";setMeta(itemName(item),item.descriptions?.[locale]||m.itemDatabaseBody);const recipes=itemData?.recipes.filter(recipe=>recipe.productId===item.id)||[],usedIn=itemData?.recipes.filter(recipe=>recipe.ingredients.some(ingredient=>ingredient.itemId===item.id))||[],byId=new Map(itemData?.items.map(candidate=>[candidate.id,candidate])||[]),unlocked=item.unlocksItemId?byId.get(item.unlocksItemId):undefined;return `${hero(itemName(item))}<article class="entity-detail item-detail panel">${itemVisual(item,{detail:true})}<div class="entity-detail-content"><p class="entity-description">${esc(item.descriptions?.[locale]||m.itemDatabaseBody)}</p>${unlocked?`<p><a class="button" href="${href(`/items/${encodeURIComponent(unlocked.id)}`)}" data-link>${unlocked.image?`<img src="/assets/items/${encodeURIComponent(unlocked.id)}.webp" alt="" width="32" height="32">`:""}${esc(itemName(unlocked))}</a></p>`:""}<p class="work-tags item-categories"><span>${esc(itemCategoryLabel(item.type,locale))}</span></p><dl class="detail-stats"><div><dt>${m.rank}</dt><dd>${item.rank}</dd></div><div><dt>${m.rarity}</dt><dd>${item.rarity}</dd></div><div><dt>${m.stack}</dt><dd>${item.maxStack.toLocaleString(locale)}</dd></div><div><dt>${m.weight}</dt><dd>${item.weight.toLocaleString(locale)}</dd></div><div><dt>${m.price}</dt><dd>${item.price.toLocaleString(locale)}</dd></div></dl>${renderItemDropSection(item)}${renderItemDungeonSection(item)}${renderItemExpeditionSection(item)}${recipes.length?`<section class="detail-section"><h2>${m.crafting}</h2>${recipes.map(recipe=>`<article class="relation-card"><ul>${recipe.ingredients.map(ingredient=>{const related=byId.get(ingredient.itemId);return related?`<li><a href="${href(`/items/${encodeURIComponent(related.id)}`)}" data-link>${esc(itemName(related))}</a> × ${ingredient.count.toLocaleString(locale)}</li>`:""}).join("")}</ul></article>`).join("")}</section>`:""}${usedIn.length?`<section class="detail-section"><h2>${usedIn.length.toLocaleString(locale)} ${m.results}</h2><div class="relation-list">${usedIn.map(recipe=>{const product=byId.get(recipe.productId);return product?`<a href="${href(`/items/${encodeURIComponent(product.id)}`)}" data-link>${product.image?`<img src="/assets/items/${encodeURIComponent(product.id)}.webp" alt="" loading="lazy">`:""}<span>${esc(itemName(product))}</span></a>`:""}).join("")}</div></section>`:""}<div class="detail-actions item-detail-actions"><a class="button primary" href="${href("/calculators/crafting")}" data-link>${m.openCrafting}</a></div></div></article>`};
  return segment===null?collection():detail(segment);
}

export function bindItemsPage(context:BindContext){
  const {document,locale,messages:m,trackOnce}=context;
  const filterItems=()=>{const input=document.querySelector<HTMLInputElement>("#item-search");if(!input)return;const query=input.value.trim().toLocaleLowerCase(locale),rarity=document.querySelector<HTMLSelectElement>("#item-rarity")?.value||"",type=document.querySelector<HTMLSelectElement>("#item-type")?.value||"";let count=0;document.querySelectorAll<HTMLElement>(".item-card").forEach(card=>{const show=(!query||card.dataset.item?.includes(query))&&(!rarity||card.dataset.rarity===rarity)&&(!type||card.dataset.type===type);card.hidden=!show;if(show)count++});const status=document.querySelector<HTMLElement>("#item-count"),empty=document.querySelector<HTMLElement>("#item-empty");if(status)status.textContent=`${count.toLocaleString(locale)} ${m.results}`;if(empty)empty.hidden=count!==0};
  const search=document.querySelector<HTMLInputElement>("#item-search");search?.addEventListener("input",()=>{filterItems();if(search.value.trim())trackOnce("search:item","collection_search",{collection:"item"})});
  ["#item-type","#item-rarity"].forEach(selector=>document.querySelector(selector)?.addEventListener("change",filterItems));
  document.querySelector<HTMLButtonElement>('[data-clear-search="item"]')?.addEventListener("click",()=>{if(!search)return;search.value="";document.querySelectorAll<HTMLSelectElement>("#item-type,#item-rarity").forEach(select=>select.value="");filterItems();search.focus()});
}
