import type {Locale} from "../config.ts";
import type {Messages} from "../i18n.ts";
import {dungeonCopy} from "../dungeon-i18n.ts";
import {uiCopy} from "../ui-i18n.ts";
import {skillLabels} from "../skill-i18n.ts";

type Work=Record<string,number>;
type Pal={id:string;dex:number;variant:boolean;names:Record<Locale,string>;descriptions:Record<Locale,string>;shortDescriptions:Record<Locale,string>;power:number;rarity:number;size:string;nocturnal:boolean;hp:number;attack:number;defense:number;work:Work;elementSlugs:string[];guaranteedPassiveIds:string[];image?:boolean};
type WorkSuitability={id:string;names:Record<Locale,string>;icon:string};
type PalData={workSuitabilities:WorkSuitability[];pals:Pal[]};
type Item={id:string;names:Record<Locale,string>;image?:boolean};
type PalDrop={palId:string;itemId:string;level:number;rate:number;min:number;max:number};
type ItemData={items:Item[];drops:PalDrop[]};
type PassiveSkill={id:string;names:Record<Locale,string>;descriptions:Record<Locale,string>};
type SkillData={passiveSkills:PassiveSkill[]};
type PublicElement={slug:string;names:Record<Locale,string>;icon:string};
type ElementData={elements:PublicElement[]};
type DungeonRoomRole="normal"|"boss"|"midboss"|"monster"|"aquatic";
type DungeonMemberRole="primary"|"companion"|"member";
type Dungeon={slug:string;names:Record<Locale,string>;encounterGroups:{roomRole:DungeonRoomRole;members:{palId:string;memberRole:DungeonMemberRole}[]}[]};
type DungeonData={dungeons:Dungeon[]};
type DropLabels={items:string;level:string;chance:string;quantity:string};
type DungeonLabels={title:string;roleNormal:string;roleBoss:string;roleMidboss:string;roleMonster:string;roleAquatic:string;primaryBoss:string;companion:string;groupMember:string};
type Context={locale:Locale;defaultLocale:Locale;messages:Messages;data:PalData|null;itemData:ItemData|null;skillData:SkillData|null;elementData:ElementData|null;dungeonData:DungeonData|null;dropLabels:DropLabels;href:(path:string)=>string;escape:(value:string)=>string;resolvePalSegment:(segment:string)=>Pal|null;setMeta:(title:string,description?:string)=>void;hero:(title:string,...descriptions:string[])=>string;placeholder:(title:string)=>string};
type BindContext={document:Document;locale:Locale;messages:Messages;trackOnce:(key:string,event:string,params:Record<string,string>)=>void};

export function renderPalsPage(segment:string|null,context:Context){
  const {locale,defaultLocale,messages:m,data,itemData,skillData,elementData,dungeonData,dropLabels,href,escape:esc,resolvePalSegment,setMeta,hero,placeholder}=context,dungeonLabels:DungeonLabels=dungeonCopy[locale],detailLabels={passive:skillLabels[locale].passive,size:uiCopy[locale].size,breedingPower:uiCopy[locale].breedingPower};
  const palName=(pal:Pal)=>pal.names[locale]||pal.names[defaultLocale];
  const palDescription=(pal:Pal)=>pal.descriptions?.[locale]||pal.descriptions?.[defaultLocale]||pal.shortDescriptions?.[locale]||pal.shortDescriptions?.[defaultLocale]||"";
  const localized=(names:Record<Locale,string>)=>names[locale]||names[defaultLocale];
  const itemName=(item:Item)=>localized(item.names);
  const elementBadges=(pal:Pal)=>`<span class="element-badges">${pal.elementSlugs.map(slug=>{const element=elementData?.elements.find(entry=>entry.slug===slug);return element?`<a href="${href("/database/elements")}?attack=${slug}" data-link class="element-badge"><img src="${element.icon}" alt="" width="28" height="28"><span>${esc(localized(element.names))}</span></a>`:""}).join("")}</span>`;
  const workSuitabilityBadges=(work:Work,compact=false)=>{const metadata=new Map((data?.workSuitabilities||[]).map(entry=>[entry.id,entry]));return Object.entries(work).filter(([,level])=>level>0).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([id,level])=>{const entry=metadata.get(id),label=entry?.names[locale]||entry?.names[defaultLocale]||id,accessible=`${label} ${level}`;return `<span class="work-suitability${compact?" compact":""}" title="${esc(accessible)}" aria-label="${esc(accessible)}"><img src="${esc(entry?.icon||`/assets/work-suitability/${id}.webp`)}" alt="" width="24" height="24"><span class="work-suitability-label">${esc(label)}</span><b>${level}</b></span>`}).join("")};
  const dropFacts=(drop:PalDrop)=>{const quantity=drop.min===drop.max?drop.min.toLocaleString(locale):`${drop.min.toLocaleString(locale)}–${drop.max.toLocaleString(locale)}`;return `<small>${dropLabels.level} ${drop.level.toLocaleString(locale)} · ${dropLabels.chance} ${drop.rate.toLocaleString(locale)}% · ${dropLabels.quantity} ${quantity}</small>`};
  const renderDropSection=(pal:Pal)=>{if(!itemData)return "";const byId=new Map(itemData.items.map(item=>[item.id,item])),drops=itemData.drops.filter(drop=>drop.palId===pal.id);if(!drops.length)return "";return `<section class="detail-section pal-drop-section"><h2>${dropLabels.items}</h2><div class="relation-list entity-relation-list">${drops.map(drop=>{const item=byId.get(drop.itemId);return item?`<a href="${href(`/items/${encodeURIComponent(item.id)}`)}" data-link>${item.image?`<img src="/assets/items/${encodeURIComponent(item.id)}.webp" alt="" loading="lazy">`:""}<span><strong>${esc(itemName(item))}</strong>${dropFacts(drop)}</span></a>`:""}).join("")}</div></section>`};
  const dungeonRoleLabel=(role:DungeonRoomRole)=>({normal:dungeonLabels.roleNormal,boss:dungeonLabels.roleBoss,midboss:dungeonLabels.roleMidboss,monster:dungeonLabels.roleMonster,aquatic:dungeonLabels.roleAquatic})[role];
  const dungeonMemberRoleLabel=(role:DungeonMemberRole)=>({primary:dungeonLabels.primaryBoss,companion:dungeonLabels.companion,member:dungeonLabels.groupMember})[role];
  const renderDungeonSection=(pal:Pal)=>{if(!dungeonData)return "";const matches=dungeonData.dungeons.map(dungeon=>({dungeon,groups:dungeon.encounterGroups.map(group=>({group,members:group.members.filter(member=>member.palId===pal.id)})).filter(entry=>entry.members.length)})).filter(entry=>entry.groups.length);if(!matches.length)return "";return `<section class="detail-section dungeon-backlinks"><h2>${dungeonLabels.title}</h2><div class="dungeon-backlink-grid">${matches.map(({dungeon,groups})=>{const labels=groups.flatMap(({group,members})=>members.map(member=>`${dungeonRoleLabel(group.roomRole)} · ${dungeonMemberRoleLabel(member.memberRole)}`));return `<a href="${href(`/database/dungeons/${dungeon.slug}`)}" data-link><img src="/assets/map-icons/dungeon.webp" alt="" width="40" height="40"><span><strong>${esc(localized(dungeon.names))}</strong><small>${esc([...new Set(labels)].join(" · "))}</small></span></a>`}).join("")}</div></section>`};
  const card=(pal:Pal)=>{const search=[...Object.values(pal.names),pal.id,pal.dex,...pal.elementSlugs,...Object.keys(pal.work).filter(key=>pal.work[key]>0)].join(" ").toLocaleLowerCase(locale);return `<article class="pal-card" data-pal="${esc(search)}" data-rarity="${pal.rarity}" data-work="${esc(Object.keys(pal.work).filter(key=>pal.work[key]>0).join(" "))}">${pal.image?`<img class="entity-image pal-image" src="/assets/pals/${encodeURIComponent(pal.id)}.png" alt="${esc(palName(pal))}" loading="lazy" width="160" height="160">`:`<div class="pal-image item-fallback" aria-hidden="true">◇</div>`}<div class="pal-card-body"><div class="pal-number">#${pal.dex}${pal.variant?"B":""}</div><h2><a href="${href(`/pals/${encodeURIComponent(pal.id)}`)}" data-link>${esc(palName(pal))}</a></h2>${elementBadges(pal)}<dl class="pal-stats"><div><dt>${m.hp}</dt><dd>${pal.hp}</dd></div><div><dt>${m.attack}</dt><dd>${pal.attack}</dd></div><div><dt>${m.defense}</dt><dd>${pal.defense}</dd></div><div><dt>${m.rarity}</dt><dd>${pal.rarity}</dd></div></dl><div class="work-suitability-list compact-list">${workSuitabilityBadges(pal.work,true)}</div></div></article>`};
  const collection=()=>{const description=`${m.palDex}. ${m.tagline}`;setMeta(m.palDex,description);const pals=[...(data?.pals||[])],sorted=pals.sort((a,b)=>a.dex-b.dex||Number(a.variant)-Number(b.variant)||a.id.localeCompare(b.id)),rarities=[...new Set(pals.map(pal=>pal.rarity))].sort((a,b)=>a-b),works=[...new Set(pals.flatMap(pal=>Object.keys(pal.work).filter(key=>pal.work[key]>0)))].sort(),workById=new Map((data?.workSuitabilities||[]).map(entry=>[entry.id,entry]));return `${hero(m.palDex,m.palDexBody)}<section class="section"><div class="collection-filters"><label class="collection-search">${m.search}<input id="pal-search" type="search" autocomplete="off"></label><label>${m.rarity}<select id="pal-rarity"><option value="">${m.choose}</option>${rarities.map(value=>`<option value="${value}">${value}</option>`).join("")}</select></label><label>${m.work}<select id="pal-work"><option value="">${m.choose}</option>${works.map(id=>{const work=workById.get(id),label=work?.names[locale]||work?.names[defaultLocale]||id;return `<option value="${esc(id)}">${esc(label)}</option>`}).join("")}</select></label><button class="button search-clear" data-clear-search="pal" aria-label="${m.remove}">×</button></div><p id="pal-count" role="status">${sorted.length.toLocaleString(locale)} ${m.results}</p><p id="pal-empty" class="empty-compact" hidden>${m.noResult}</p><div class="pal-grid">${sorted.map(card).join("")}</div></section>`};
  const detail=(detailSegment:string)=>{const pal=resolvePalSegment(detailSegment);if(!pal){setMeta("404");return placeholder("404")}const description=palDescription(pal),metaDescription=description||m.palDexBody;setMeta(palName(pal),metaDescription);const passiveById=new Map(skillData?.passiveSkills.map(skill=>[skill.id,skill])||[]);return `${hero(palName(pal),metaDescription)}<article class="entity-detail pal-detail panel">${pal.image?`<img class="detail-image" src="/assets/pals/${encodeURIComponent(pal.id)}.png" alt="${esc(palName(pal))}">`:`<div class="detail-image item-fallback" aria-hidden="true">◇</div>`}<div><p class="pal-number">#${pal.dex}${pal.variant?"B":""}</p>${elementBadges(pal)}${description?`<p class="entity-description pal-lore">${esc(description)}</p>`:""}<dl class="detail-stats"><div><dt>${m.hp}</dt><dd>${pal.hp}</dd></div><div><dt>${m.attack}</dt><dd>${pal.attack}</dd></div><div><dt>${m.defense}</dt><dd>${pal.defense}</dd></div><div><dt>${m.rarity}</dt><dd>${pal.rarity}</dd></div><div><dt>${detailLabels.size}</dt><dd>${esc(pal.size)}</dd></div><div><dt>${detailLabels.breedingPower}</dt><dd>${pal.power.toLocaleString(locale)}</dd></div><div><dt>${m.nocturnal}</dt><dd>${pal.nocturnal?m.yes:m.no}</dd></div></dl><h2>${m.work}</h2><div class="work-suitability-list detail-work-list">${workSuitabilityBadges(pal.work)}</div>${pal.guaranteedPassiveIds.length?`<section class="pal-passives"><h2>${detailLabels.passive}</h2>${pal.guaranteedPassiveIds.map(passiveId=>{const passive=passiveById.get(passiveId);return passive?`<article><strong><a href="${href(`/skills/passive/${encodeURIComponent(passive.id)}`)}" data-link>${esc(localized(passive.names))}</a></strong><p>${esc(localized(passive.descriptions))}</p></article>`:""}).join("")}</section>`:""}${renderDropSection(pal)}${renderDungeonSection(pal)}<div class="detail-actions"><a class="button primary" href="${href("/calculators/breeding")}" data-link>${m.openBreed}</a><a class="button" href="${href(`/map?pal=${encodeURIComponent(pal.id)}`)}" data-link>${m.map}</a></div></div></article>`};
  return segment===null?collection():detail(segment);
}

export function bindPalsPage(context:BindContext){
  const {document,locale,messages:m,trackOnce}=context;
  const filterPals=()=>{const input=document.querySelector<HTMLInputElement>("#pal-search");if(!input)return;const query=input.value.trim().toLocaleLowerCase(locale),rarity=document.querySelector<HTMLSelectElement>("#pal-rarity")?.value||"",work=document.querySelector<HTMLSelectElement>("#pal-work")?.value||"";let count=0;document.querySelectorAll<HTMLElement>(".pal-card").forEach(card=>{const show=(!query||card.dataset.pal?.includes(query))&&(!rarity||card.dataset.rarity===rarity)&&(!work||card.dataset.work?.split(" ").includes(work));card.hidden=!show;if(show)count++});const status=document.querySelector<HTMLElement>("#pal-count"),empty=document.querySelector<HTMLElement>("#pal-empty");if(status)status.textContent=`${count.toLocaleString(locale)} ${m.results}`;if(empty)empty.hidden=count!==0};
  const search=document.querySelector<HTMLInputElement>("#pal-search");search?.addEventListener("input",()=>{filterPals();if(search.value.trim())trackOnce("search:pal","collection_search",{collection:"pal"})});
  ["#pal-rarity","#pal-work"].forEach(selector=>document.querySelector(selector)?.addEventListener("change",filterPals));
  document.querySelector<HTMLButtonElement>('[data-clear-search="pal"]')?.addEventListener("click",()=>{if(!search)return;search.value="";document.querySelectorAll<HTMLSelectElement>("#pal-rarity,#pal-work").forEach(select=>select.value="");filterPals();search.focus()});
}
