import {access,readFile,readdir} from "node:fs/promises";
import path from "node:path";
import {collectionRoutes as routes,deploymentFileBudget,supportedLocales as locales} from "../src/route-manifest.ts";

const root=process.cwd(),dist=path.join(root,"dist");
const [palData,itemData,skillData,index,sitemap,report,wrangler]=await Promise.all(["pals","items","skills"].map(name=>readFile(`public/data/${name}.json`,"utf8").then(JSON.parse)).concat([readFile(path.join(dist,"index.html"),"utf8"),readFile(path.join(dist,"sitemap.xml"),"utf8"),readFile(path.join(dist,"prerender-report.json"),"utf8").then(JSON.parse),readFile("wrangler.jsonc","utf8").then(value=>JSON.parse(value.replace(/^\s*\/\/.*$/gm,"")))]));
for(const declaration of ['name="google-site-verification" content="vcYPQJf0I03LumjZIODPdq47ZnYMCRvD2ABcBFyBImQ"','name="google-adsense-account" content="ca-pub-1986785092914105"'])if(!index.includes(declaration))throw new Error(`Root document is missing ${declaration}`);
if(/palworld-helper\.example|24181527|Data version|Game build/.test(index))throw new Error("Root document exposes a placeholder domain or public build information");
if(wrangler.assets?.directory!=="./dist"||wrangler.assets?.not_found_handling!=="single-page-application")throw new Error("Cloudflare Assets must preserve the SPA fallback for hybrid routes");
if(wrangler.workers_dev!==false||wrangler.preview_urls!==false||"main" in wrangler)throw new Error("Cloudflare public development hostnames must be disabled and no Worker runtime may be configured");
const allFiles=[],htmlFiles=[];async function collect(directory){for(const entry of await readdir(directory,{withFileTypes:true})){const target=path.join(directory,entry.name);if(entry.isDirectory())await collect(target);else{allFiles.push(target);if(entry.name.endsWith(".html"))htmlFiles.push(target)}}}await collect(dist);
const expectedPerLocale=routes.length+palData.pals.length+itemData.items.length+skillData.activeSkills.length+skillData.passiveSkills.length+skillData.partnerSkills.length,expectedUrls=locales.length*expectedPerLocale;
if((sitemap.match(/<url>/g)||[]).length!==expectedUrls)throw new Error(`Sitemap must contain ${expectedUrls} URLs`);
if(report.schema!==2||report.architecture!=="shared-spa-document"||report.indexableUrlCount!==expectedUrls||report.physicalHtmlDocuments!==1)throw new Error("Shared-document report does not match the route manifest");
if(htmlFiles.length!==1||path.relative(dist,htmlFiles[0])!=="index.html")throw new Error(`Expected exactly one shared index.html, found ${htmlFiles.length} HTML documents`);
if(allFiles.length>deploymentFileBudget.hardLimit-deploymentFileBudget.reservedHeadroom)throw new Error(`Deployment contains ${allFiles.length} files and violates the ${deploymentFileBudget.reservedHeadroom}-file growth reserve`);
for(const locale of locales){for(const [family,entity] of [["pals",palData.pals[0]],["items",itemData.items[0]],["skills/active",skillData.activeSkills[0]],["skills/passive",skillData.passiveSkills[0]],["skills/partner",skillData.partnerSkills[0]]])if(!sitemap.includes(`<loc>https://palworld-helper.woofy.blog/${locale}/${family}/${encodeURIComponent(entity.id)}</loc>`))throw new Error(`${locale}: ${family} detail URL missing from sitemap`)}
if(/\/guides|\/privacy|\/calculators\/(capture|iv)/.test(sitemap))throw new Error("Placeholder routes must not appear in sitemap");
for(const asset of ["data/pals.json","data/items.json","data/skills.json","assets/image-manifest.json","assets/world-map.webp","assets/elements/Fire.png","assets/passive-ranks/3.png","favicon.svg","favicon-32.png","apple-touch-icon.png","icon-192.png","icon-512.png","og-image.png","site.webmanifest","sitemap.xml","prerender-report.json","robots.txt","ads.txt","_headers"])await access(path.join(dist,asset));for(let y=0;y<4;y++)for(let x=0;x<4;x++)await access(path.join(dist,"assets","map-tiles",`${x}-${y}.webp`));
const builtItems=JSON.parse(await readFile(path.join(dist,"data","items.json"),"utf8"));
const builtImageManifest=JSON.parse(await readFile(path.join(dist,"assets","image-manifest.json"),"utf8"));
const imagedItems=builtItems.items.filter(item=>item.image===true),missingItemImages=builtItems.items.length-imagedItems.length;
if(builtImageManifest.gameBuild!==builtItems.meta.gameBuild||builtImageManifest.itemCount!==imagedItems.length)throw new Error(`Built item image manifest mismatch: manifest=${builtImageManifest.itemCount}, flags=${imagedItems.length}`);
const builtItemImages=(await readdir(path.join(dist,"assets","items"))).filter(name=>name.endsWith(".webp"));
if(builtItemImages.length!==imagedItems.length)throw new Error(`Built item image file mismatch: files=${builtItemImages.length}, flags=${imagedItems.length}`);
for(const item of imagedItems)await access(path.join(dist,"assets","items",`${item.id}.webp`));
if(missingItemImages)console.warn(`Item image extraction remains incomplete: ${imagedItems.length}/${builtItems.items.length}. Run npm run check:item-images before accepting a complete data refresh.`);
for(const work of palData.workSuitabilities)await access(path.join(dist,work.icon.replace(/^\//,"")));
if(palData.meta.palPortraitCount!==palData.pals.length||palData.pals.some(pal=>pal.image!==true))throw new Error("Every published Pal must retain its portrait manifest state");
for(const pal of palData.pals)await access(path.join(dist,"assets","pals",`${pal.id}.png`));
for(const pal of palData.pals)for(const description of Object.values(pal.descriptions))if(/<[^>]+>|Error_Code:|\||이\(가\)|은\(는\)|을\(를\)|과\(와\)/.test(description))throw new Error(`${pal.id} exposes unresolved game-runtime description markup`);
const adsTxt=await readFile(path.join(dist,"ads.txt"),"utf8");if(adsTxt.trim()!=="google.com, pub-1986785092914105, DIRECT, f08c47fec0942fa0")throw new Error("ads.txt must contain the exact authorized account entry");
console.log(`Validated ${expectedUrls} indexable URLs, one shared index.html and ${allFiles.length} deployed files.`);
