import {copyFile,mkdir,readFile,writeFile} from "node:fs/promises";
import path from "node:path";
import {defaultLocale} from "../src/config.ts";
import {messages} from "../src/i18n.ts";
import {collectionRoutes as routes,itemPrerenderLimit,supportedLocales as locales} from "../src/route-manifest.ts";

const origin=process.env.VITE_SITE_ORIGIN||"https://palworld-helper.woofy.blog",siteName="Palworld Helper";
const [palData,itemData,skillData,template]=await Promise.all(["pals","items","skills"].map(name=>readFile(`public/data/${name}.json`,"utf8").then(JSON.parse)).concat(readFile("dist/index.html","utf8")));
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const text=value=>String(value??"").replace(/<[^>]+>/g,"").replace(/\s+/g," ").trim();
const local=(values,locale)=>text(values?.[locale]||values?.[defaultLocale]||"");
const url=(locale,route)=>`${origin}/${locale}${route?`/${route}`:""}`;
const link=(locale,route,label)=>`<a href="/${locale}/${route}">${esc(label)}</a>`;
const alternates=(route)=>locales.map(locale=>`<link rel="alternate" hreflang="${locale}" href="${url(locale,route)}">`).join("")+`<link rel="alternate" hreflang="x-default" href="${url(defaultLocale,route)}">`;
const initialStyle=`<style data-prerender-style>:root{--pre-bg:#edf7f5;--pre-surface:#fffdf7;--pre-soft:#e3f0ec;--pre-text:#10263a;--pre-muted:#526b76;--pre-line:#b7d4d2}html[data-theme="dark"]{--pre-bg:#071627;--pre-surface:#0d2537;--pre-soft:#143449;--pre-text:#edf9f7;--pre-muted:#a9c5ca;--pre-line:#285166}@media(prefers-color-scheme:dark){html[data-theme="system"]{--pre-bg:#071627;--pre-surface:#0d2537;--pre-soft:#143449;--pre-text:#edf9f7;--pre-muted:#a9c5ca;--pre-line:#285166}}body{margin:0;font-family:Inter,"Noto Sans",system-ui,sans-serif;background:var(--pre-bg);color:var(--pre-text)}.prerender{max-width:1180px;margin:auto;padding:3rem 1.25rem 5rem}.prerender nav{display:flex;gap:1rem;flex-wrap:wrap;margin-bottom:3rem}.prerender h1{font-size:clamp(2.5rem,7vw,5rem);line-height:1;margin:.4rem 0 1rem}.prerender .lead{max-width:780px;font-size:1.1rem;line-height:1.7;color:var(--pre-muted)}.prerender-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem;margin-top:2rem}.prerender-card{background:var(--pre-surface);border:1px solid var(--pre-line);border-radius:16px;padding:1.2rem}.prerender-detail{display:grid;grid-template-columns:minmax(180px,320px) 1fr;gap:2rem;margin-top:2rem}.prerender-detail img{width:100%;height:auto;object-fit:contain;background:var(--pre-soft);border-radius:16px}.prerender dl{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:.6rem}.prerender dl div{background:var(--pre-surface);padding:.8rem;border-radius:12px}.prerender dt{color:var(--pre-muted);font-size:.8rem}.prerender dd{margin:.25rem 0 0;font-weight:700}@media(max-width:650px){.prerender-detail{grid-template-columns:1fr}.prerender{padding-top:2rem}}</style>`;
function shell(locale,route,title,description,body,structured){const canonical=url(locale,route),fullTitle=`${title} · ${siteName}`,meta=`<meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}">${alternates(route)}<meta property="og:type" content="website"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin}/og-image.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:type" content="image/png"><meta property="og:image:alt" content="${esc(fullTitle)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${origin}/og-image.png"><meta name="twitter:image:alt" content="${esc(fullTitle)}">${structured?`<script type="application/ld+json">${JSON.stringify(structured).replace(/</g,"\\u003c")}</script>`:""}${initialStyle}`;return template.replace(/<html lang="[^"]+"/,`<html lang="${locale}"`).replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(fullTitle)}</title>${meta}`).replace('<div id="app"></div>',`<div id="app">${body}</div>`)}
const nav=locale=>{const m=messages(locale);return `<nav aria-label="${esc(m.home)}">${link(locale,"",m.home)}${link(locale,"pals",m.pals)}${link(locale,"database",m.database)}${link(locale,"skills",m.stats)}${link(locale,"map",m.map)}${link(locale,"calculators/breeding",m.calculators)}</nav>`};
const page=(locale,title,description,content)=>`<main class="prerender">${nav(locale)}<p>${esc(messages(locale).verified)}</p><h1>${esc(title)}</h1><p class="lead">${esc(description)}</p>${content}</main>`;
const collectionCopy=(locale,route)=>{const m=messages(locale),map={"": [m.hero,m.tagline],map:[m.mapTitle,m.mapBody],pals:[m.palDex,m.palDexBody],skills:[m.stats,`${m.stats}: Active, Passive, Partner`],"skills/active":["Active skills",m.stats],"skills/passive":["Passive skills",m.stats],"skills/partner":["Partner skills",m.stats],calculators:[m.calculators,m.breedingBody],"calculators/breeding":[m.breeding,m.breedingBody],"calculators/crafting":[m.crafting,m.craftingBody],database:[m.itemDatabase,m.itemDatabaseBody],"server-tools/settings-generator":[m.serverTitle,m.footer]};return map[route]||[siteName,m.tagline]};
const collectionLinks=(locale,route)=>{if(route==="pals")return palData.pals.slice(0,36).map(pal=>`<article class="prerender-card">${link(locale,`pals/${encodeURIComponent(pal.id)}`,`#${pal.dex}${pal.variant?"B":""} ${local(pal.names,locale)}`)}</article>`).join("");if(route==="database")return itemData.items.filter(item=>item.image).slice(0,36).map(item=>`<article class="prerender-card">${link(locale,`items/${encodeURIComponent(item.id)}`,local(item.names,locale))}</article>`).join("");if(route.startsWith("skills"))return skillData.activeSkills.slice(0,18).map(skill=>`<article class="prerender-card">${link(locale,`skills/active/${encodeURIComponent(skill.id)}`,local(skill.names,locale))}</article>`).join("");return [link(locale,"pals",messages(locale).pals),link(locale,"database",messages(locale).database),link(locale,"skills",messages(locale).stats)].map(value=>`<article class="prerender-card">${value}</article>`).join("")};
const recipesByProduct=new Map();for(const recipe of itemData.recipes){const list=recipesByProduct.get(recipe.productId)||[];list.push(recipe);recipesByProduct.set(recipe.productId,list)}
const usedBy=new Map();for(const recipe of itemData.recipes)for(const ingredient of recipe.ingredients){const list=usedBy.get(ingredient.itemId)||[];list.push(recipe);usedBy.set(ingredient.itemId,list)}
const priorityItems=[...itemData.items].sort((a,b)=>{const score=item=>(item.image?8:0)+(local(item.descriptions,"en-US")?6:0)+(recipesByProduct.get(item.id)?.length||0)*4+Math.min(8,(usedBy.get(item.id)?.length||0)*2)+(item.type==="Weapon"||item.type==="Armor"?4:0);return score(b)-score(a)||a.id.localeCompare(b.id)}).slice(0,itemPrerenderLimit);
const prerenderRoutes=[];
for(const locale of locales){
  for(const route of routes){const [title,description]=collectionCopy(locale,route),body=page(locale,title,description,`<section class="prerender-grid">${collectionLinks(locale,route)}</section>`);await emit(locale,route,shell(locale,route,title,description,body,{"@context":"https://schema.org","@type":"WebPage",name:title,url:url(locale,route)}));prerenderRoutes.push(`${locale}/${route}`)}
  for(const pal of palData.pals){const title=local(pal.names,locale),description=`#${pal.dex}${pal.variant?"B":""} ${title}. ${messages(locale).palDexBody}`,stats=[[messages(locale).hp,pal.hp],[messages(locale).attack,pal.attack],[messages(locale).defense,pal.defense],[messages(locale).rarity,pal.rarity]],content=`<article class="prerender-detail">${pal.image?`<img src="/assets/pals/${encodeURIComponent(pal.id)}.png" alt="${esc(title)}" width="320" height="320">`:"<div></div>"}<div><p>${esc(description)}</p><dl>${stats.map(([key,value])=>`<div><dt>${esc(key)}</dt><dd>${esc(value)}</dd></div>`).join("")}</dl><h2>${esc(messages(locale).work)}</h2><p>${Object.entries(pal.work).filter(([,value])=>value>0).map(([key,value])=>`${esc(key)} ${value}`).join(" · ")}</p><p>${link(locale,"calculators/breeding",messages(locale).breeding)} · ${link(locale,`map?pal=${encodeURIComponent(pal.id)}`,messages(locale).map)}</p></div></article>`;const route=`pals/${encodeURIComponent(pal.id)}`;await emit(locale,route,shell(locale,route,title,description,page(locale,title,description,content),breadcrumb(locale,route,title)));prerenderRoutes.push(`${locale}/${route}`)}
  for(const [kind,skills] of [["active",skillData.activeSkills],["passive",skillData.passiveSkills]])for(const skill of skills){const title=local(skill.names,locale),description=local(skill.descriptions,locale)||`${title} · ${kind} skill`,element=kind==="active"?skillData.elements.find(entry=>entry.id===skill.elementId):null,content=`<article class="prerender-detail">${element?`<img src="${esc(element.icon)}" alt="${esc(local(element.names,locale))}" width="240" height="240">`:`<div class="prerender-card"><strong>${esc(skill.rank>=0?`+${skill.rank}`:skill.rank)}</strong></div>`}<div><p>${esc(description)}</p><dl>${kind==="active"?`<div><dt>Power</dt><dd>${skill.power}</dd></div><div><dt>Cooldown</dt><dd>${skill.cooldown}</dd></div>`:`<div><dt>Rank</dt><dd>${skill.rank}</dd></div>`}</dl>${link(locale,"skills",messages(locale).stats)}</div></article>`,route=`skills/${kind}/${encodeURIComponent(skill.id)}`;await emit(locale,route,shell(locale,route,title,description,page(locale,title,description,content),breadcrumb(locale,route,title)));prerenderRoutes.push(`${locale}/${route}`)}
  for(const item of priorityItems){const title=local(item.names,locale),description=local(item.descriptions,locale)||messages(locale).itemDatabaseBody,relations=(usedBy.get(item.id)||[]).slice(0,12).map(recipe=>{const product=itemData.items.find(entry=>entry.id===recipe.productId);return product?`<li>${link(locale,`items/${encodeURIComponent(product.id)}`,local(product.names,locale))}</li>`:""}).join(""),content=`<article class="prerender-detail">${item.image?`<img src="/assets/items/${encodeURIComponent(item.id)}.webp" alt="${esc(title)}" width="320" height="320">`:"<div></div>"}<div><p>${esc(description)}</p><dl><div><dt>${esc(messages(locale).rarity)}</dt><dd>${item.rarity}</dd></div><div><dt>${esc(messages(locale).weight)}</dt><dd>${item.weight}</dd></div><div><dt>${esc(messages(locale).price)}</dt><dd>${item.price}</dd></div></dl>${relations?`<h2>${esc(messages(locale).results)}</h2><ul>${relations}</ul>`:""}${link(locale,"calculators/crafting",messages(locale).crafting)}</div></article>`,route=`items/${encodeURIComponent(item.id)}`;await emit(locale,route,shell(locale,route,title,description,page(locale,title,description,content),breadcrumb(locale,route,title)));prerenderRoutes.push(`${locale}/${route}`)}
}
function breadcrumb(locale,route,title){return {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:siteName,item:url(locale,"")},{"@type":"ListItem",position:2,name:title,item:url(locale,route)}]}}
async function emit(locale,route,html){const directory=path.join("dist",locale,...route.split("/").filter(Boolean));await mkdir(directory,{recursive:true});await writeFile(path.join(directory,"index.html"),html)}
const entityRoutes=[...palData.pals.map(pal=>`pals/${encodeURIComponent(pal.id)}`),...itemData.items.map(item=>`items/${encodeURIComponent(item.id)}`),...skillData.activeSkills.map(skill=>`skills/active/${encodeURIComponent(skill.id)}`),...skillData.passiveSkills.map(skill=>`skills/passive/${encodeURIComponent(skill.id)}`),...skillData.partnerSkills.map(skill=>`skills/partner/${encodeURIComponent(skill.id)}`)],indexableRoutes=[...routes,...entityRoutes],urls=locales.flatMap(locale=>indexableRoutes.map(route=>url(locale,route)));
await writeFile("dist/sitemap.xml",`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(value=>`<url><loc>${value}</loc></url>`).join("")}</urlset>`);
await writeFile("dist/prerender-report.json",JSON.stringify({schema:1,indexableUrlCount:urls.length,initialHtmlCoverage:prerenderRoutes.length,itemPrerenderLimit,routeFamilies:{static:routes.length*locales.length,pals:palData.pals.length*locales.length,activeSkills:skillData.activeSkills.length*locales.length,passiveSkills:skillData.passiveSkills.length*locales.length,priorityItems:priorityItems.length*locales.length}},null,2));
await writeFile("dist/robots.txt",`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);await writeFile("dist/_headers",`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n\n/assets/*\n  Cache-Control: public, max-age=31536000, immutable\n`);await copyFile("public/site.webmanifest","dist/site.webmanifest");
console.log(`Generated ${urls.length} indexable URLs; ${prerenderRoutes.length} have meaningful initial HTML.`);
