import {copyFile,readFile,writeFile} from "node:fs/promises";
import {collectionRoutes as routes,supportedLocales as locales} from "../src/route-manifest.ts";

const origin=process.env.VITE_SITE_ORIGIN||"https://palworld-helper.woofy.blog";
const [palData,itemData,skillData,npcData]=await Promise.all(["pals","items","skills","npcs"].map(name=>readFile(`public/data/${name}.json`,"utf8").then(JSON.parse)));
const url=(locale,route)=>`${origin}/${locale}${route?`/${route}`:""}`;
const entityRoutes=[...palData.pals.map(pal=>`pals/${encodeURIComponent(pal.id)}`),...itemData.items.map(item=>`items/${encodeURIComponent(item.id)}`),...skillData.activeSkills.map(skill=>`skills/active/${encodeURIComponent(skill.id)}`),...skillData.passiveSkills.map(skill=>`skills/passive/${encodeURIComponent(skill.id)}`),...skillData.partnerSkills.map(skill=>`skills/partner/${encodeURIComponent(skill.id)}`),...npcData.npcs.map(npc=>`database/npcs/${encodeURIComponent(npc.slug)}`)],indexableRoutes=[...routes,...entityRoutes],urls=locales.flatMap(locale=>indexableRoutes.map(route=>url(locale,route)));
await writeFile("dist/sitemap.xml",`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(value=>`<url><loc>${value}</loc></url>`).join("")}</urlset>`);
await writeFile("dist/prerender-report.json",JSON.stringify({schema:2,architecture:"shared-spa-document",indexableUrlCount:urls.length,physicalHtmlDocuments:1,routeFamilies:{static:routes.length*locales.length,pals:palData.pals.length*locales.length,items:itemData.items.length*locales.length,activeSkills:skillData.activeSkills.length*locales.length,passiveSkills:skillData.passiveSkills.length*locales.length,partnerSkills:skillData.partnerSkills.length*locales.length,npcs:npcData.npcs.length*locales.length}},null,2));
await writeFile("dist/robots.txt",`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);await writeFile("dist/_headers",`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n\n/assets/*\n  Cache-Control: public, max-age=31536000, immutable\n`);await copyFile("public/site.webmanifest","dist/site.webmanifest");
console.log(`Generated ${urls.length} indexable URLs backed by one shared SPA document.`);
