import {messages} from "../src/i18n.ts";
import {itemCategoryFieldLabels,itemCategoryLabel} from "../src/item-categories.ts";
import {npcCopy} from "../src/npc-i18n.ts";
import {dungeonCopy} from "../src/dungeon-i18n.ts";
import {technologyCopy} from "../src/technology-i18n.ts";
import {healthCopy} from "../src/health-i18n.ts";
import {elementCopy} from "../src/element-i18n.ts";
import {elementMatchupCopy} from "../src/element-matchup-i18n.ts";
import {renderElementMatchupGraph} from "../src/element-graph.ts";
import {structureCopy} from "../src/structure-i18n.ts";
import {expeditionCopy} from "../src/expedition-i18n.ts";
import {questCopy} from "../src/quest-i18n.ts";
import {partnerLabel,passiveUiLabels,skillLabels} from "../src/skill-i18n.ts";
import {plannerCopy} from "../src/planner-i18n.ts";
import {collectionRoutes,entityRouteFamilies,routeFamilies,seoHreflang,shellNavigation,supportedLocales} from "../src/route-manifest.ts";
import {activeSkillOwner,assertPublicSlugRegistry,createPublicSlugRegistry,publicSlug} from "../src/public-slugs.ts";
import {databaseItemTabLabels} from "../src/ui-i18n.ts";
import {shellCopy} from "../src/shell-i18n.ts";
import {homeCopy} from "../src/home-i18n.ts";
import {renderHomeMarkup} from "../src/home-render.ts";
import {homeCatalogGroups,homeQuickActions,validateHomeManifest} from "../src/home-manifest.ts";
import {icon} from "../src/icons.ts";
import {renderFooter} from "../src/footer.ts";
import {guideNavLabel} from "../src/guide-nav-i18n.ts";
import {guidePageModel} from "../src/pages/guides.ts";
import {palToolsCopy} from "../src/pal-tools-i18n.ts";
import {breedingPathCopy} from "../src/breeding-path-i18n.ts";
import {palProfileCopy} from "../src/pal-profile-i18n.ts";
import {ivCopy} from "../src/iv-i18n.ts";

export const productionOrigin="https://palworld-helper.woofy.blog";
export const defaultLocale="en-US";
const siteName="Palworld Helper";
validateHomeManifest(collectionRoutes);

export const mapSeoCopy={
  "en-US":{title:"Palpagos interactive map",body:"Explore verified bosses, fast travel points and Pal habitats on the game map."},"ko-KR":{title:"팔파고스 탐험 지도",body:"게임 지도에서 검증된 보스 팰, 빠른 이동 지점과 팰 서식지를 찾아보세요."},"ja-JP":{title:"パルパゴス探索マップ",body:"検証済みのボス、ファストトラベル、パルの生息地をゲームマップで探索できます。"},"zh-CN":{title:"帕洛斯群岛探索地图",body:"在游戏地图上查找经过验证的首领帕鲁、快速移动点和帕鲁栖息地。"},"zh-TW":{title:"帕洛斯群島探索地圖",body:"在遊戲地圖上尋找經過驗證的頭目帕魯、快速移動點與帕魯棲息地。"},"fr-FR":{title:"Carte interactive de Palpagos",body:"Explorez les boss, points de voyage rapide et habitats de Pals vérifiés."},"it-IT":{title:"Mappa interattiva di Palpagos",body:"Esplora boss, punti di viaggio rapido e habitat dei Pal verificati."},"de-DE":{title:"Interaktive Palpagos-Karte",body:"Erkunde verifizierte Bosse, Schnellreisepunkte und Pal-Lebensräume."},"es-ES":{title:"Mapa interactivo de Palpagos",body:"Explora jefes, puntos de viaje rápido y hábitats de Pals verificados."},"es-419":{title:"Mapa interactivo de Palpagos",body:"Explora jefes, puntos de viaje rápido y hábitats de Pals verificados."},"pt-BR":{title:"Mapa interativo de Palpagos",body:"Explore chefes, pontos de viagem rápida e habitats de Pals verificados."},"ru-RU":{title:"Интерактивная карта Палпагоса",body:"Исследуйте проверенные места боссов, быстрого перемещения и обитания Палов."},"id-ID":{title:"Peta interaktif Palpagos",body:"Jelajahi bos, titik perjalanan cepat, dan habitat Pal yang terverifikasi."},"th-TH":{title:"แผนที่สำรวจพัลพากอส",body:"สำรวจบอส จุดเดินทางด่วน และถิ่นอาศัยของพัลที่ผ่านการตรวจสอบ"},"tr-TR":{title:"Palpagos etkileşimli haritası",body:"Doğrulanmış bossları, hızlı seyahat noktalarını ve Pal yaşam alanlarını keşfet."},"vi-VN":{title:"Bản đồ tương tác Palpagos",body:"Khám phá boss, điểm dịch chuyển nhanh và môi trường sống của Pal đã xác minh."},"pl-PL":{title:"Interaktywna mapa Palpagos",body:"Odkrywaj zweryfikowane bossy, punkty szybkiej podróży i siedliska Pali."}
};
export const mapSeoTranslationProvenance=Object.fromEntries(supportedLocales.map(locale=>[locale,"gpt"]));

const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const clean=value=>String(value??"").replace(/\s+/g," ").trim();
const useful=value=>{const text=clean(value);return text&&!/Error_Code:|\||\(\s*\)/.test(text)?text:""};
const seoDescription=(lead,facts=[])=>clean([clean(lead).slice(0,180),...facts.filter(Boolean)].join(" · ")).slice(0,300);
const localized=(entity,locale,field="names")=>clean(entity?.[field]?.[locale]||entity?.[field]?.[defaultLocale]||"");
const localizedDescription=(entity,locale,field="descriptions")=>useful(entity?.[field]?.[locale]||entity?.[field]?.[defaultLocale]||"");
let activeSlugRegistry=null;
const publicRoute=(route="")=>{
  if(!activeSlugRegistry)return route;
  const [pathname,query=""]=route.replace(/^\//,"").split("?"),patterns=[["pals/","pals"],["items/","items"],["skills/active/","activeSkills"],["skills/passive/","passiveSkills"],["skills/partner/","partnerSkills"]];
  let normalized=pathname;
  for(const [prefix,family] of patterns)if(pathname.startsWith(prefix)){const segment=decodeURIComponent(pathname.slice(prefix.length)),slug=activeSlugRegistry.byId[family].get(segment);if(slug)normalized=`${prefix}${slug}`;break}
  if(!query)return normalized;
  const params=new URLSearchParams(query),pal=params.get("pal"),palSlug=pal&&activeSlugRegistry.byId.pals.get(pal);if(palSlug)params.set("pal",palSlug);
  return `${normalized}?${params}`;
};
const publicAssetHtml=markup=>activeSlugRegistry?markup.replace(/\/assets\/(pals|items)\/([^"'?/]+)\.(png|webp)/g,(match,kind,encodedId,extension)=>{const family=kind==="pals"?"pals":"items",slug=activeSlugRegistry.byId[family].get(decodeURIComponent(encodedId));return slug?`/assets/${kind}/${slug}.${extension}`:match}):markup;
const href=(locale,route="")=>{const normalized=publicRoute(route);return `/${locale}${normalized?`/${normalized}`:""}`};
const absolute=(origin,locale,route="")=>`${origin}${href(locale,route)}`;
const internalEntityId=entity=>entity.slug??entity.id;
const addCount=(map,key,value=1)=>map.set(key,(map.get(key)||0)+value);

export function createSeoSlugRegistry({palData,itemData,skillData}){
  return assertPublicSlugRegistry({pals:palData.pals,items:itemData.items,activeSkills:skillData.activeSkills,passiveSkills:skillData.passiveSkills,partnerSkills:skillData.partnerSkills});
}

const publicEntitySlug=(dataset,entity,registry)=>registry.byId[dataset]?publicSlug(registry,dataset,entity.id):entity.slug;

export function createEntityDatasets({palData,itemData,skillData,npcData,dungeonData,technologyData,healthData,structureData,expeditionData,questData}){
  return {pals:palData.pals,items:itemData.items,activeSkills:skillData.activeSkills,passiveSkills:skillData.passiveSkills,partnerSkills:skillData.partnerSkills,npcs:npcData.npcs,dungeons:dungeonData.dungeons,technologies:technologyData.technologies,structures:structureData.structures,conditions:healthData.conditions,expeditions:expeditionData.expeditions,quests:questData.quests};
}

function relationScores({palData,itemData,skillData,npcData,dungeonData,technologyData,structureData,expeditionData,questData}){
  const item=new Map(),active=new Map(),passive=new Map(),partner=new Map(),npcScore=new Map(),technology=new Map(),structure=new Map(),quest=new Map();
  for(const recipe of itemData.recipes){addCount(item,recipe.productId,14);for(const ingredient of recipe.ingredients)addCount(item,ingredient.itemId,4)}
  for(const drop of itemData.drops)addCount(item,drop.itemId,8);
  for(const dungeon of dungeonData.dungeons){
    const pools=[...dungeon.itemPools,...dungeon.rewardSources.flatMap(source=>source.itemPools||[])];
    for(const candidate of pools.flatMap(pool=>pool.slots.flatMap(slot=>slot.candidates)))addCount(item,candidate.itemId,10);
  }
  for(const expedition of expeditionData.expeditions)for(const candidate of expedition.rewardSlots.flatMap(slot=>slot.candidates))addCount(item,candidate.itemId,10);
  for(const entry of questData.quests){for(const reward of entry.rewards.items)addCount(item,reward.itemId,10);addCount(quest,entry.slug,(entry.kind==="main"?40:0)+entry.objectiveGroups.reduce((sum,group)=>sum+group.steps.length,0)*8+entry.rewards.items.length*4+(entry.previousSlugs.length+entry.nextSlugs.length)*2)}
  for(const npc of npcData.npcs){
    const offers=npc.merchant?.type==="items"?(npc.merchant.offers||[]):npc.merchant?.type==="item-profiles"?npc.merchant.profiles.flatMap(profile=>profile.offers||[]):[];
    const palOffers=npc.merchant?.type==="pals"?npc.merchant.profiles.flatMap(profile=>profile.palIds||[]):[];
    const eventSteps=npc.events?.steps||[];
    addCount(npcScore,npc.slug,(npc.kind==="merchant"?40:0)+(npc.kind==="quest"?32:0)+(npc.kind==="combat"?24:0)+offers.length*5+palOffers.length*4+eventSteps.length*8+npc.encounters.length*3+npc.roles.length*2);
    for(const offer of offers)addCount(item,offer.itemId,6);
    for(const step of eventSteps){if(step.requestItemId)addCount(item,step.requestItemId,5);for(const reward of step.rewards||[])addCount(item,reward.itemId,6)}
  }
  for(const pal of palData.pals)for(const id of pal.guaranteedPassiveIds||[])addCount(passive,id,18);
  for(const skill of skillData.activeSkills){addCount(active,skill.id,(skill.power>0?4:0)+(skill.canInherit?3:0)+(skill.hasSkillFruit?5:0))}
  for(const skill of skillData.passiveSkills)addCount(passive,skill.id,Math.abs(skill.rank||0)+(skill.surgeryCost>0?3:0));
  for(const skill of skillData.partnerSkills)addCount(partner,skill.id,12);
  for(const entry of technologyData.technologies){addCount(technology,entry.slug,entry.unlocks.length*3+entry.dependents.length*8+(entry.prerequisite?10:0)+(entry.towerBossRequired?8:0)+(entry.labResearch?12:0));if(entry.prerequisite)addCount(technology,entry.prerequisite.slug,12)}
  for(const entry of structureData.structures)addCount(structure,entry.slug,entry.materials.length*3+entry.technologies.length*10+(entry.production?20:0)+(entry.energy?5:0));
  return {items:item,activeSkills:active,passiveSkills:passive,partnerSkills:partner,npcs:npcScore,technologies:technology,structures:structure,quests:quest};
}

export function selectPrerenderEntities(data){
  const datasets=createEntityDatasets(data),scores=relationScores(data),selection={};
  for(const family of entityRouteFamilies){
    const entities=datasets[family.dataset];
    if(family.prerender==="all"){selection[family.dataset]=entities;continue}
    const scoreMap=scores[family.dataset]||new Map();
    selection[family.dataset]=[...entities].sort((a,b)=>{
      const descriptionScore=entity=>Object.values(entity.descriptions||entity.palDescriptions||{}).filter(useful).length*2;
      const score=entity=>descriptionScore(entity)+(scoreMap.get(internalEntityId(entity))||0);
      return score(b)-score(a)||String(internalEntityId(a)).localeCompare(String(internalEntityId(b)));
    }).slice(0,family.priorityLimit);
  }
  return selection;
}

export function buildIndexableGroups(data,origin=productionOrigin){
  const datasets=createEntityDatasets(data),registry=createSeoSlugRegistry(data);
  const collections=supportedLocales.flatMap(locale=>collectionRoutes.map(route=>absolute(origin,locale,route)));
  const groups={collections};
  for(const family of entityRouteFamilies)groups[family.sitemap]=supportedLocales.flatMap(locale=>datasets[family.dataset].map(entity=>absolute(origin,locale,`${family.prefix}/${publicEntitySlug(family.dataset,entity,registry)}`)));
  return groups;
}

export function buildPrerenderEntries(data){
  const selected=selectPrerenderEntities(data),registry=createSeoSlugRegistry(data),entries=[];
  for(const locale of supportedLocales){
    for(const route of collectionRoutes)entries.push({locale,route,kind:"collection"});
    for(const family of entityRouteFamilies)for(const entity of selected[family.dataset])entries.push({locale,route:`${family.prefix}/${publicEntitySlug(family.dataset,entity,registry)}`,kind:"entity",dataset:family.dataset,entity});
  }
  return {entries,selected,registry};
}

function shellLabel(item,locale,m){const id=item.id,skills=skillLabels[locale],tools=palToolsCopy[locale];return id==="map"?m.map:id==="pals"?m.pals:id==="skills"?skills.title:id==="skills-active"?skills.active:id==="skills-passive"?skills.passive:id==="skills-partner"?partnerLabel[locale]:id==="calculators"?m.calculators:id==="calculators-breeding"?m.breeding:id==="calculators-crafting"?m.crafting:id==="calculators-base"?plannerCopy[locale].baseTitle:id==="calculators-iv"?ivCopy[locale].title:id==="calculators-pal-compare"?tools.compareTitle:id==="calculators-team-builder"?tools.teamTitle:id==="calculators-condensing"?tools.condensingTitle:id==="database"?m.database:id==="database-items"?databaseItemTabLabels[locale]:id==="database-quests"?questCopy[locale].title:id==="database-structures"?structureCopy[locale].title:id==="database-expeditions"?expeditionCopy[locale].title:id==="database-elements"?elementCopy[locale].title:id==="database-technology"?technologyCopy[locale].title:id==="database-health"?healthCopy[locale].title:id==="database-npcs"?npcCopy[locale].catalogTitle:id==="database-dungeons"?dungeonCopy[locale].title:id==="guides"?guideNavLabel[locale]:m.server}
function shellRouteActive(item,route){return item.active.some(({path,exact=false})=>route===path||!exact&&route.startsWith(`${path}/`))}
function shellLink(item,locale,route,m){return `<a href="${href(locale,item.path)}"${shellRouteActive(item,route)?' aria-current="page"':""}>${esc(shellLabel(item,locale,m))}</a>`}
function shell(locale,route,title,content){
  const m=messages(locale),links=shellNavigation.map(item=>item.children?`<details class="nav-group nav-group-${item.id}${shellRouteActive(item,route)?" active":""}"><summary><span>${esc(shellLabel(item,locale,m))}</span>${icon("chevronDown","nav-chevron")}</summary><div class="nav-panel">${item.children.map(child=>shellLink(child,locale,route,m)).join("")}</div></details>`:shellLink(item,locale,route,m)).join("");
  return `<a class="skip-link" href="#main">${esc(m.skip)}</a><header class="site-header prerender-header"><a class="brand" href="${href(locale)}"><span class="brand-mark"><img src="/favicon.svg" alt="" width="34" height="34"></span><span>${siteName}</span></a><nav class="primary-nav" aria-label="${esc(shellCopy[locale].primaryNavigation)}">${links}</nav></header><main id="main" data-prerender-content>${content}</main>${renderFooter(locale,m.footer)}`;
}
const hero=(m,title)=>`<section class="page-hero"><p class="eyebrow">${esc(m.verified)}</p><h1>${esc(title)}</h1></section>`;
const relationLinks=links=>links.length?`<div class="relation-list entity-relation-list seo-link-list">${links.map(link=>`<a href="${esc(link.href)}">${link.image?`<img src="${esc(link.image)}" alt="" width="48" height="48" loading="lazy">`:""}<span><strong>${esc(link.label)}</strong>${link.detail?`<small>${esc(link.detail)}</small>`:""}</span></a>`).join("")}</div>`:"";
const uniqueLinks=links=>[...new Map(links.filter(link=>link?.label).map(link=>[link.href,link])).values()];
const breadcrumb=(locale,parentRoute,parentLabel,title)=>`<nav class="breadcrumbs" aria-label="${esc(messages(locale).home)}"><a href="${href(locale)}">${esc(messages(locale).home)}</a><a href="${href(locale,parentRoute)}">${esc(parentLabel)}</a><span aria-current="page">${esc(title)}</span></nav>`;
const details=facts=>`<dl class="detail-stats">${facts.filter(([,value])=>value!==undefined&&value!==null&&value!=="").map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join("")}</dl>`;

function pageStructuredData({origin,locale,route,title,description,type,parent}){
  if(!type)return null;
  const url=absolute(origin,locale,route),page={"@type":type,name:title,url,description,inLanguage:locale};
  if(type==="WebApplication"){page.applicationCategory="GameApplication";page.operatingSystem="Any"}
  if(type==="WebSite")return {"@context":"https://schema.org",...page};
  const graph=[page];
  if(parent)graph.push({"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:messages(locale).home,item:absolute(origin,locale)},{"@type":"ListItem",position:2,name:parent.label,item:absolute(origin,locale,parent.route)},{"@type":"ListItem",position:3,name:title,item:url}]});
  return {"@context":"https://schema.org","@graph":graph};
}

function collectionModel(route,locale,data,selection,registry){
  if(route==="guides"||route.startsWith("guides/"))return guidePageModel(locale,route,target=>href(locale,target),data.guideSnapshotData);
  const {palData,itemData,skillData,npcData,dungeonData,technologyData,healthData,elementData,structureData,expeditionData,questData}=data,m=messages(locale),skills=skillLabels[locale],planner=plannerCopy[locale],tools=palToolsCopy[locale],iv=ivCopy[locale],pathCopy=breedingPathCopy[locale],dungeons=dungeonCopy[locale],npcs=npcCopy[locale],technology=technologyCopy[locale],structures=structureCopy[locale],health=healthCopy[locale],elementsCopy=elementCopy[locale],elementMatchups=elementMatchupCopy[locale],expeditions=expeditionCopy[locale],quests=questCopy[locale];
  let title,description,links=[],type="CollectionPage";
  if(route===""){({metaTitle:title,metaDescription:description}=homeCopy[locale]);type="WebSite"}
  else if(route==="map"){({title,body:description}=mapSeoCopy[locale]);type="WebApplication";links=[{href:href(locale,"pals"),label:m.palDex},{href:href(locale,"database/dungeons"),label:dungeons.title},{href:href(locale,"database/npcs"),label:npcs.catalogTitle}]}
  else if(route==="pals"){title=m.palDex;description=`${m.palDex}. ${m.tagline}`;links=[...palData.pals].sort((a,b)=>a.dex-b.dex||Number(a.variant)-Number(b.variant)||a.id.localeCompare(b.id)).map(pal=>({href:href(locale,`pals/${encodeURIComponent(pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${encodeURIComponent(pal.id)}.png`}))}
  else if(route==="skills"||route.startsWith("skills/")){const group=route.split("/")[1];title=group==="active"?skills.active:group==="passive"?skills.passive:group==="partner"?partnerLabel[locale]:skills.title;description=[skills.active,skills.passive,partnerLabel[locale]].join(" · ");const datasets=group==="active"?["activeSkills"]:group==="passive"?["passiveSkills"]:group==="partner"?["partnerSkills"]:["activeSkills","passiveSkills","partnerSkills"];links=datasets.flatMap(dataset=>selection[dataset].map(entity=>({href:href(locale,`${dataset==="activeSkills"?"skills/active":dataset==="passiveSkills"?"skills/passive":"skills/partner"}/${encodeURIComponent(entity.id)}`),label:localized(entity,locale)||localized(palData.pals.find(pal=>pal.id===entity.palId),locale)})))}
  else if(route==="calculators"||route==="calculators/breeding"){title=route==="calculators"?m.calculators:m.breeding;description=m.breedingBody;type="WebApplication";links=[{href:href(locale,"pals"),label:m.palDex},{href:href(locale,"calculators/crafting"),label:m.crafting},{href:href(locale,"calculators/base"),label:planner.baseTitle}]}
  else if(route==="calculators/breeding-path"){title=pathCopy.title;description=pathCopy.intro;type="WebApplication";links=[{href:href(locale,"calculators/breeding"),label:m.breeding},...selection.pals.slice(0,24).map(pal=>({href:href(locale,`pals/${publicSlug(registry,"pals",pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${publicSlug(registry,"pals",pal.id)}.png`}))]}
  else if(route==="calculators/crafting"){title=m.crafting;description=planner.craftingIntro;type="WebApplication";links=[{href:href(locale,"calculators/base"),label:planner.baseTitle},...selection.items.map(item=>({href:href(locale,`items/${encodeURIComponent(item.id)}`),label:localized(item,locale),image:`/assets/items/${encodeURIComponent(item.id)}.webp`}))]}
  else if(route==="calculators/base"){title=planner.baseTitle;description=planner.baseIntro;type="WebApplication";links=[{href:href(locale,"calculators/crafting"),label:m.crafting},...selection.pals.slice(0,24).map(pal=>({href:href(locale,`pals/${encodeURIComponent(pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${encodeURIComponent(pal.id)}.png`}))]}
  else if(route==="calculators/iv"){title=iv.title;description=iv.intro;type="WebApplication";links=selection.pals.slice(0,24).map(pal=>({href:href(locale,`pals/${publicSlug(registry,"pals",pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${publicSlug(registry,"pals",pal.id)}.png`}))}
  else if(route==="calculators/pal-compare"){title=tools.compareTitle;description=tools.compareIntro;type="WebApplication";links=selection.pals.slice(0,24).map(pal=>({href:href(locale,`pals/${encodeURIComponent(pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${encodeURIComponent(pal.id)}.png`}))}
  else if(route==="calculators/team-builder"){title=tools.teamTitle;description=tools.teamIntro;type="WebApplication";links=[{href:href(locale,"calculators/pal-compare"),label:tools.compareTitle},{href:href(locale,"pals"),label:m.palDex}]}
  else if(route==="calculators/condensing"){title=tools.condensingTitle;description=tools.condensingIntro;type="WebApplication";links=[{href:href(locale,"calculators/pal-compare"),label:tools.compareTitle},{href:href(locale,"calculators/team-builder"),label:tools.teamTitle}]}
  else if(route==="database"){title=m.itemDatabase;description=m.itemDatabaseBody;links=selection.items.map(item=>({href:href(locale,`items/${encodeURIComponent(item.id)}`),label:localized(item,locale),image:`/assets/items/${encodeURIComponent(item.id)}.webp`,detail:itemCategoryLabel(item.type,locale)}))}
  else if(route==="database/quests"){title=quests.title;description=quests.intro;links=[...questData.quests].sort((a,b)=>a.kind.localeCompare(b.kind)||a.order-b.order||a.slug.localeCompare(b.slug)).map(entry=>({href:href(locale,`database/quests/${entry.slug}`),label:localized(entry,locale),detail:`${entry.kind==="main"?quests.main:quests.side} · ${quests.sequence} ${(entry.order+1).toLocaleString(locale)} · ${quests.experience} ${entry.rewards.experience.toLocaleString(locale)}`}))}
  else if(route==="database/structures"){title=structures.title;description=structures.intro;links=selection.structures.map(entry=>({href:href(locale,`database/structures/${entry.slug}`),label:localized(entry,locale),detail:`${localized(entry.category,locale)} · ${structures.level} ${[...entry.technologies].sort((a,b)=>a.level-b.level)[0].level.toLocaleString(locale)}`}))}
  else if(route==="database/expeditions"){title=expeditions.title;description=expeditions.intro;links=[...expeditionData.expeditions].sort((a,b)=>a.order-b.order||a.slug.localeCompare(b.slug)).map(entry=>({href:href(locale,`database/expeditions/${entry.slug}`),label:localized(entry,locale),image:entry.image,detail:`${entry.variant==="hard"?expeditions.hardVariant:expeditions.standard} · ${expeditions.recommendedStrength} ${entry.recommendedStrength.toLocaleString(locale)} · ${expeditions.possibleRewards} ${entry.summary.uniqueRewardItemCount.toLocaleString(locale)}`}))}
  else if(route==="database/elements"){title=elementsCopy.title;description=elementsCopy.intro;const bySlug=new Map(elementData.elements.map(element=>[element.slug,element]));links=elementData.relations.map(relation=>{const attacker=bySlug.get(relation.attacker),defender=bySlug.get(relation.defender);return {href:`${href(locale,"database/elements")}?attack=${relation.attacker}&defend=${relation.defender}`,label:`${localized(attacker,locale)} → ${localized(defender,locale)}`,image:attacker?.icon,detail:elementsCopy.strong}})}
  else if(route==="database/technology"){title=technology.title;description=technology.intro;links=[...selection.technologies].sort((a,b)=>a.level-b.level||a.order-b.order||a.slug.localeCompare(b.slug)).map(entry=>({href:href(locale,`database/technology/${entry.slug}`),label:localized(entry,locale),image:`/assets/technology/${encodeURIComponent(entry.slug)}.webp`,detail:`${technology.level} ${entry.level.toLocaleString(locale)} · ${entry.kind==="ancient"?technology.ancient:technology.regular}`}))}
  else if(route==="database/health"){title=health.title;description=health.intro;links=healthData.conditions.map(entry=>({href:href(locale,`database/health/conditions/${entry.slug}`),label:localized(entry,locale),detail:health[entry.category]}))}
  else if(route==="database/npcs"){title=npcs.catalogTitle;description=npcs.catalogIntro;links=[...npcData.npcs].sort((a,b)=>new Intl.Collator(locale,{numeric:true}).compare(localized(a,locale),localized(b,locale))||a.slug.localeCompare(b.slug)).map(npc=>({href:href(locale,`database/npcs/${npc.slug}`),label:localized(npc,locale)}))}
  else if(route==="database/dungeons"){title=dungeons.title;description=dungeons.intro;links=[...dungeonData.dungeons].sort((a,b)=>(a.encounterLevel?.min??999)-(b.encounterLevel?.min??999)||new Intl.Collator(locale).compare(localized(a,locale),localized(b,locale))).map(dungeon=>({href:href(locale,`database/dungeons/${dungeon.slug}`),label:localized(dungeon,locale),image:"/assets/map-icons/dungeon.webp"}))}
  else {title=m.serverTitle;description=m.footer;type="WebApplication";links=[]}
  const itemsById=new Map(itemData.items.map(item=>[item.id,item]));
  const elementBody=route==="database/elements"?`${hero(m,title)}<section class="section element-page"><p class="collection-intro">${esc(description)}</p>${renderElementMatchupGraph({nodes:elementData.elements.map(element=>({slug:element.slug,name:localized(element,locale),icon:element.icon})),relations:elementData.relations,title:elementsCopy.chartTitle,description:elementsCopy.chartDescription,strongLabel:elementsCopy.strong,baseHref:href(locale,"database/elements")})}<article class="panel element-formula"><header><h2>${esc(elementMatchups.combinationRule)}</h2><span>${esc(elementMatchups.runtimeVerified)}</span></header><div class="element-rule-guide"><div><strong>+1</strong><span>${esc(elementsCopy.strong)} · 1.5×</span></div><div><strong>0</strong><span>${esc(elementsCopy.neutral)} · 1×</span></div><div><strong>−1</strong><span>${esc(elementsCopy.weak)} · 0.66×</span></div><p>${esc(elementMatchups.sameElementRule)}</p><p>${esc(elementMatchups.neutralRule)}</p></div><p class="element-damage-context">${esc(elementMatchups.damageContext)}</p></article></section>`:null;
  const healthBody=route==="database/health"?`${hero(m,title)}<section class="section health-catalog"><p class="health-intro">${esc(description)}</p><article class="panel health-san"><h2>${esc(localized(healthData.san,locale))}</h2><div><p>${esc(localizedDescription(healthData.san,locale))}</p><p class="notice warning">${esc(health.runtimeUnavailable)}</p></div></article><section class="health-section"><h2>${esc(health.sanEvents)}</h2><p class="section-note">${esc(health.sanSourceNote)}</p><div class="health-event-grid">${healthData.san.behaviors.map(event=>`<article class="panel health-event-card"><div><span class="health-tag">${esc(event.category==="rest"?health.rest:event.category==="disruptive"?health.disruptive:health.illness)}</span><strong>${esc(health.sanValue)} ${event.sanValue.toLocaleString(locale)}</strong></div><h3>${esc(localized(event,locale))}</h3><p>${esc(localizedDescription(event,locale))}</p></article>`).join("")}</div></section><section class="health-section"><h2>${esc(health.conditions)}</h2><p class="section-note">${esc(health.effectSourceNote)}</p>${relationLinks(healthData.conditions.map(condition=>({href:href(locale,`database/health/conditions/${condition.slug}`),label:localized(condition,locale),detail:[[health.workSpeed,condition.effects.workSpeed],[health.moveSpeed,condition.effects.moveSpeed],[health.satietyDecrease,condition.effects.satietyDecrease]].filter(([,value])=>value!==0).map(([label,value])=>`${label} ${value}`).join(" · ")})))}</section><section class="health-section"><h2>${esc(health.medicines)}</h2>${relationLinks(healthData.medicines.map(medicine=>({href:href(locale,`items/${medicine.itemId}`),label:localized(medicine,locale),image:medicine.image,detail:localizedDescription(medicine,locale)})))}</section></section>`:null;
  const station=structureData.structures.find(entry=>entry.slug==="pal-expedition-station"),stationTechnology=technologyData.technologies.find(entry=>entry.slug==="pal-expedition-station");
  const expeditionBody=route==="database/expeditions"&&station&&stationTechnology?`${hero(m,title)}<section class="section expedition-catalog"><p class="collection-intro">${esc(description)}</p><article class="panel expedition-station"><div class="expedition-station-copy"><p class="eyebrow">${esc(expeditions.stationOverview)}</p><h2>${esc(localized(station,locale))}</h2><p>${esc(localizedDescription(station,locale))}</p>${details([[structures.unlockLevel,stationTechnology.level.toLocaleString(locale)],[technology.pointCost,stationTechnology.pointCost.toLocaleString(locale)]])}<p><a href="${href(locale,`database/structures/${station.slug}`)}">${esc(`${structures.title} · ${structures.details}`)}</a> · <a href="${href(locale,`database/technology/${stationTechnology.slug}`)}">${esc(`${technology.title} · ${technology.details}`)}</a></p></div>${relationLinks(station.materials.map(material=>{const item=itemsById.get(material.itemId);return item?{href:href(locale,`items/${encodeURIComponent(item.id)}`),label:localized(item,locale),image:`/assets/items/${encodeURIComponent(item.id)}.webp`,detail:`× ${material.count.toLocaleString(locale)}`}:null}))}</article>${relationLinks(links)}</section>`:null;
  const body=elementBody||healthBody||expeditionBody||(route===""?renderHomeMarkup({copy:homeCopy[locale],href:target=>href(locale,target),renderIcon:icon,quickActions:homeQuickActions,catalogGroups:homeCatalogGroups,guideLabel:guideNavLabel[locale]}):`${hero(m,title)}<section class="section"><p class="collection-intro">${esc(description)}</p>${relationLinks(links)}</section>`);
  return {title,description,body,type};
}

function palModel(locale,pal,data){
  const {palData,itemData,skillData,dungeonData}=data,m=messages(locale),profile=palProfileCopy[locale],title=localized(pal,locale),description=localizedDescription(pal,locale)||m.tagline,documentTitle=`#${pal.dex}${pal.variant?"B":""} ${title}`,metaDescription=seoDescription(description,[`${m.hp} ${pal.hp}`,`${m.attack} ${pal.attack}`,`${m.defense} ${pal.defense}`,`${m.rarity} ${pal.rarity}`]),itemsById=new Map(itemData.items.map(item=>[item.id,item])),passives=new Map(skillData.passiveSkills.map(skill=>[skill.id,skill]));
  const workById=new Map(palData.workSuitabilities.map(work=>[work.id,work])),work=Object.entries(pal.work).filter(([,level])=>level>0).sort((a,b)=>b[1]-a[1]).map(([id,level])=>`${localized(workById.get(id),locale)} ${level}`).join(" · ");
  const itemLinks=itemData.drops.filter(drop=>drop.palId===pal.id).map(drop=>{const item=itemsById.get(drop.itemId);return item?{href:href(locale,`items/${encodeURIComponent(item.id)}`),label:localized(item,locale),image:`/assets/items/${encodeURIComponent(item.id)}.webp`}:null});
  const dungeonLinks=dungeonData.dungeons.filter(dungeon=>dungeon.encounterGroups.some(group=>group.members.some(member=>member.palId===pal.id))).map(dungeon=>({href:href(locale,`database/dungeons/${dungeon.slug}`),label:localized(dungeon,locale),image:"/assets/map-icons/dungeon.webp"}));
  const passiveLinks=(pal.guaranteedPassiveIds||[]).map(id=>passives.get(id)).filter(Boolean).map(skill=>({href:href(locale,`skills/passive/${encodeURIComponent(skill.id)}`),label:localized(skill,locale)}));
  const facts=details([[m.hp,pal.hp],[m.attack,pal.attack],[m.defense,pal.defense],[m.rarity,pal.rarity],[m.work,work],[m.nocturnal,pal.nocturnal?m.yes:m.no]]);
  const profileFacts=details([[profile.support,pal.support],[profile.food,pal.food],[profile.maleProbability,`${pal.maleProbability.toLocaleString(locale)}%`],[profile.femaleProbability,`${(100-pal.maleProbability).toLocaleString(locale)}%`],[profile.slowWalk,pal.movement.slowWalk],[profile.walk,pal.movement.walk],[profile.run,pal.movement.run],[profile.rideSprint,pal.movement.rideSprint],[profile.transport,pal.movement.transport],[profile.swim,pal.movement.swim],[profile.swimDash,pal.movement.swimDash],[profile.stamina,pal.movement.stamina]].filter(([,value])=>value!==null));
  const body=`${hero(m,title)}<article class="entity-detail pal-detail panel"><img class="detail-image" src="/assets/pals/${encodeURIComponent(pal.id)}.png" alt="${esc(title)}" width="240" height="240"><div class="entity-detail-content">${breadcrumb(locale,"pals",m.palDex,title)}<p class="pal-number">#${pal.dex}${pal.variant?"B":""}</p><p class="entity-description">${esc(description)}</p>${facts}<section class="detail-section pal-profile"><h2>${esc(profile.profile)}</h2>${profileFacts}<p class="section-note">${esc(profile.sourceValueNote)}</p></section>${passiveLinks.length?`<section class="detail-section"><h2>${esc(skillLabels[locale].passive)}</h2>${relationLinks(passiveLinks)}</section>`:""}${itemLinks.length?`<section class="detail-section"><h2>${esc(m.itemDatabase)}</h2>${relationLinks(uniqueLinks(itemLinks))}</section>`:""}${dungeonLinks.length?`<section class="detail-section"><h2>${esc(dungeonCopy[locale].title)}</h2>${relationLinks(dungeonLinks)}</section>`:""}<div class="detail-actions"><a class="button primary" href="${href(locale,"calculators/breeding")}">${esc(m.openBreed)}</a><a class="button" href="${href(locale,"map")}?pal=${encodeURIComponent(pal.id)}">${esc(m.map)}</a></div></div></article>`;
  return {title,documentTitle,description:metaDescription,body,type:"WebPage",parent:{route:"pals",label:m.palDex}};
}

function itemModel(locale,item,data){
  const {palData,itemData}=data,m=messages(locale),title=localized(item,locale),category=itemCategoryLabel(item.type,locale),documentTitle=`${title} · ${category} · ${m.rank} ${item.rank} · ${m.rarity} ${item.rarity}`,description=localizedDescription(item,locale)||m.itemDatabaseBody,metaDescription=seoDescription(description,[category,`${m.rank} ${item.rank}`,`${m.rarity} ${item.rarity}`,`${m.stack} ${item.maxStack.toLocaleString(locale)}`]),itemsById=new Map(itemData.items.map(entry=>[entry.id,entry])),palsById=new Map(palData.pals.map(pal=>[pal.id,pal]));
  const recipes=itemData.recipes.filter(recipe=>recipe.productId===item.id),usedIn=itemData.recipes.filter(recipe=>recipe.ingredients.some(ingredient=>ingredient.itemId===item.id));
  const ingredients=recipes.flatMap(recipe=>recipe.ingredients).map(ingredient=>{const related=itemsById.get(ingredient.itemId);return related?{href:href(locale,`items/${encodeURIComponent(related.id)}`),label:localized(related,locale),image:`/assets/items/${encodeURIComponent(related.id)}.webp`,detail:`× ${ingredient.count.toLocaleString(locale)}`}:null});
  const products=usedIn.map(recipe=>itemsById.get(recipe.productId)).filter(Boolean).map(product=>({href:href(locale,`items/${encodeURIComponent(product.id)}`),label:localized(product,locale),image:`/assets/items/${encodeURIComponent(product.id)}.webp`}));
  const drops=itemData.drops.filter(drop=>drop.itemId===item.id).map(drop=>palsById.get(drop.palId)).filter(Boolean).map(pal=>({href:href(locale,`pals/${encodeURIComponent(pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${encodeURIComponent(pal.id)}.png`}));
  const itemRelations=data.itemRelationData?.byItem[item.id],relationTechnologies=new Map((data.itemRelationData?.technologies||[]).map(entry=>[entry.slug,entry])),relationStructures=new Map((data.itemRelationData?.structures||[]).map(entry=>[entry.slug,entry])),relationNpcs=new Map((data.itemRelationData?.npcs||[]).map(entry=>[entry.slug,entry])),relationDungeons=new Map((data.itemRelationData?.dungeons||[]).map(entry=>[entry.slug,entry])),relationExpeditions=new Map((data.itemRelationData?.expeditions||[]).map(entry=>[entry.slug,entry])),relationQuests=new Map((data.itemRelationData?.quests||[]).map(entry=>[entry.slug,entry]));
  const unlocks=(itemRelations?.unlockedBy||[]).map(slug=>relationTechnologies.get(slug)).filter(Boolean).map(entry=>({href:href(locale,`database/technology/${entry.slug}`),label:localized(entry,locale),image:`/assets/technology/${entry.slug}.webp`,detail:`${technologyCopy[locale].level} ${entry.level.toLocaleString(locale)} · ${entry.kind==="ancient"?technologyCopy[locale].ancient:technologyCopy[locale].regular}`}));
  const construction=(itemRelations?.constructionMaterialFor||[]).map(relation=>{const structure=relationStructures.get(relation.slug);return structure?{href:href(locale,`database/structures/${structure.slug}`),label:localized(structure,locale),detail:`${structureCopy[locale].materials} ×${relation.count.toLocaleString(locale)}`}:null});
  const production=(itemRelations?.producedBy||[]).map(slug=>relationStructures.get(slug)).filter(Boolean).map(structure=>({href:href(locale,`database/structures/${structure.slug}`),label:localized(structure,locale),detail:structureCopy[locale].production}));
  const npcSlugs=[...(itemRelations?.soldBy||[]),...(itemRelations?.requestedBy||[]),...(itemRelations?.rewardedByNpc||[])].map(relation=>relation.slug),npcs=[...new Set(npcSlugs)].map(slug=>relationNpcs.get(slug)).filter(Boolean).map(npc=>({href:href(locale,`database/npcs/${npc.slug}`),label:localized(npc,locale),image:`/assets/map-icons/${npc.kind==="merchant"?"merchant":npc.kind==="combat"?"wanted":"npc"}.webp`}));
  const dungeons=(itemRelations?.foundInDungeons||[]).map(relation=>relationDungeons.get(relation.slug)).filter(Boolean).map(dungeon=>({href:href(locale,`database/dungeons/${dungeon.slug}`),label:localized(dungeon,locale),image:"/assets/map-icons/dungeon.webp"}));
  const expeditionRewards=(itemRelations?.rewardedByExpeditions||[]).map(relation=>{const expedition=relationExpeditions.get(relation.slug);return expedition?{href:href(locale,`database/expeditions/${expedition.slug}`),label:localized(expedition,locale),image:expedition.image,detail:relation.rewards.map(reward=>`${expeditionCopy[locale].rewardSlot} ${reward.slot.toLocaleString(locale)} · ${reward.minCount.toLocaleString(locale)}${reward.minCount===reward.maxCount?"":`–${reward.maxCount.toLocaleString(locale)}`}`).join(" · ")}:null}).filter(Boolean);
  const questRewards=(itemRelations?.rewardedByQuests||[]).map(relation=>{const quest=relationQuests.get(relation.slug);return quest?{href:href(locale,`database/quests/${quest.slug}`),label:localized(quest,locale),detail:`${quest.kind==="main"?questCopy[locale].main:questCopy[locale].side} · ${relation.quantity.toLocaleString(locale)}`}:null}).filter(Boolean);
  const facts=details([[itemCategoryFieldLabels[locale],itemCategoryLabel(item.type,locale)],[m.rank,item.rank],[m.rarity,item.rarity],[m.stack,item.maxStack.toLocaleString(locale)],[m.weight,item.weight.toLocaleString(locale)],[m.price,item.price.toLocaleString(locale)]]);
  const body=`${hero(m,title)}<article class="entity-detail item-detail panel"><img class="detail-image" src="/assets/items/${encodeURIComponent(item.id)}.webp" alt="${esc(title)}" width="192" height="192"><div class="entity-detail-content">${breadcrumb(locale,"database",m.itemDatabase,title)}<p class="entity-description">${esc(description)}</p>${facts}${unlocks.length?`<section class="detail-section"><h2>${esc(technologyCopy[locale].title)}</h2>${relationLinks(unlocks)}</section>`:""}${production.length||construction.length?`<section class="detail-section"><h2>${esc(structureCopy[locale].title)}</h2>${production.length?`<h3>${esc(structureCopy[locale].production)}</h3>${relationLinks(production)}`:""}${construction.length?`<h3>${esc(structureCopy[locale].materials)}</h3>${relationLinks(construction)}`:""}</section>`:""}${npcs.length?`<section class="detail-section"><h2>${esc(npcCopy[locale].title)}</h2>${relationLinks(npcs)}</section>`:""}${questRewards.length?`<section class="detail-section"><h2>${esc(questCopy[locale].rewards)} · ${esc(questCopy[locale].title)}</h2>${relationLinks(questRewards)}</section>`:""}${ingredients.length?`<section class="detail-section"><h2>${esc(m.crafting)}</h2>${relationLinks(uniqueLinks(ingredients))}</section>`:""}${products.length?`<section class="detail-section"><h2>${esc(m.results)}</h2>${relationLinks(uniqueLinks(products))}</section>`:""}${drops.length?`<section class="detail-section"><h2>${esc(m.pals)}</h2>${relationLinks(uniqueLinks(drops))}</section>`:""}${dungeons.length?`<section class="detail-section"><h2>${esc(dungeonCopy[locale].title)}</h2>${relationLinks(dungeons)}</section>`:""}${expeditionRewards.length?`<section class="detail-section"><h2>${esc(expeditionCopy[locale].obtainedFrom)}</h2>${relationLinks(expeditionRewards)}<p class="notice">${esc(expeditionCopy[locale].rewardNotice)}</p></section>`:""}</div></article>`;
  return {title,documentTitle,description:metaDescription,body,type:"WebPage",parent:{route:"database",label:m.itemDatabase}};
}

function skillModel(locale,skill,dataset,data){
  const {palData,skillData}=data,m=messages(locale),labels=skillLabels[locale],palById=new Map(palData.pals.map(pal=>[pal.id,pal])),title=localized(skill,locale)||localized(palById.get(skill.palId),locale),kindLabel=dataset==="activeSkills"?labels.active:dataset==="passiveSkills"?labels.passive:partnerLabel[locale],description=localizedDescription(skill,locale,dataset==="partnerSkills"?"palDescriptions":"descriptions")||kindLabel;
  let facts=[],links=[],image="";
  if(dataset==="activeSkills"){const element=skillData.elements.find(entry=>entry.id===skill.elementId);facts=[[labels.elements,localized(element,locale)],[labels.power,skill.power],[labels.cooldown,skill.cooldown],[labels.inherit,skill.canInherit?m.yes:m.no]];image=element?.icon||""}
  else if(dataset==="passiveSkills")facts=[[passiveUiLabels[locale].rank,`${skill.rank>=0?"+":""}${skill.rank}`],[labels.inherit,skill.randomInheritanceAllowed?m.yes:m.no],[passiveUiLabels[locale].surgery,skill.surgeryCost.toLocaleString(locale)]];
  else {const pal=palById.get(skill.palId);if(pal){links=[{href:href(locale,`pals/${encodeURIComponent(pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${encodeURIComponent(pal.id)}.png`}];image=`/assets/pals/${encodeURIComponent(pal.id)}.png`}}
  const parent=dataset==="activeSkills"?"skills/active":dataset==="passiveSkills"?"skills/passive":"skills/partner",parentLabel=dataset==="activeSkills"?labels.active:dataset==="passiveSkills"?labels.passive:partnerLabel[locale];
  const owner=dataset==="activeSkills"?activeSkillOwner(skill,palData.pals):dataset==="partnerSkills"?palById.get(skill.palId):null,ownerLabel=owner?`#${owner.dex}${owner.variant?"B":""} ${localized(owner,locale)}`:"",detailLabel=dataset==="passiveSkills"?`${passiveUiLabels[locale].rank} ${skill.rank>=0?"+":""}${skill.rank}`:ownerLabel,documentTitle=[title,kindLabel,detailLabel].filter(Boolean).join(" · "),metaDescription=seoDescription(description,[kindLabel,detailLabel,...facts.map(([label,value])=>`${label} ${value}`)]);
  const body=`${hero(m,title)}<article class="entity-detail panel">${image?`<img class="detail-image" src="${esc(image)}" alt="${esc(title)}" width="192" height="192">`:""}<div class="entity-detail-content">${breadcrumb(locale,parent,parentLabel,title)}<p class="entity-description">${esc(description)}</p>${details(facts)}${relationLinks(links)}</div></article>`;
  return {title,documentTitle,description:metaDescription,body,type:"WebPage",parent:{route:parent,label:parentLabel}};
}

function technologyModel(locale,technology){
  const m=messages(locale),copy=technologyCopy[locale],title=localized(technology,locale),description=clean(technology.descriptions?.[locale]||technology.descriptions?.[defaultLocale]||copy.intro).replace(/\|/g,""),kind=technology.kind==="ancient"?copy.ancient:copy.regular,category=technology.category==="building"?copy.building:copy.item,pointLabel=technology.kind==="ancient"?copy.ancientPoints:copy.regularPoints;
  const conditions=[];
  if(technology.prerequisite)conditions.push({href:href(locale,`database/technology/${technology.prerequisite.slug}`),label:localized(technology.prerequisite,locale),detail:copy.prerequisite});
  const tower=technology.towerBossRequired?`<p class="notice"><strong>${esc(copy.towerBoss)}</strong> — ${esc(copy.towerBossNote)}</p>`:"";
  const research=technology.labResearch?`<section class="detail-section"><h2>${esc(copy.research)}</h2><p><strong>${esc(localized(technology.labResearch,locale))}</strong></p>${details([[copy.researchWork,technology.labResearch.workAmount.toLocaleString(locale)],[copy.researchPrerequisite,localized(technology.labResearch.prerequisiteNames?{names:technology.labResearch.prerequisiteNames}:null,locale)]])}${technology.labResearch.materials.length?`<h3>${esc(copy.researchMaterials)}</h3><ul>${technology.labResearch.materials.map(material=>`<li>${esc(localized(material,locale))} × ${material.count.toLocaleString(locale)}</li>`).join("")}</ul>`:""}</section>`:"";
  const unlocks=`<ul class="technology-unlocks">${technology.unlocks.map(unlock=>`<li><span>${esc(unlock.kind==="building"?copy.building:copy.item)}</span><strong>${esc(localized(unlock,locale))}</strong></li>`).join("")}</ul>`;
  const dependents=technology.dependents.map(relation=>({href:href(locale,`database/technology/${relation.slug}`),label:localized(relation,locale)}));
  const body=`${hero(m,title)}<article class="entity-detail technology-summary panel ${technology.kind}"><img class="detail-image" src="/assets/technology/${encodeURIComponent(technology.slug)}.webp" alt="${esc(title)}" width="220" height="220"><div class="entity-detail-content">${breadcrumb(locale,"database/technology",copy.title,title)}<p class="entity-description">${esc(description)}</p>${details([[copy.requiredLevel,technology.level.toLocaleString(locale)],[copy.pointCost,`${technology.pointCost.toLocaleString(locale)} ${pointLabel}`],[copy.kind,kind],[copy.category,category]])}${conditions.length?`<section class="detail-section"><h2>${esc(copy.conditions)}</h2>${relationLinks(conditions)}</section>`:""}${tower}${research}<section class="detail-section"><h2>${esc(copy.unlocks)}</h2>${unlocks}</section>${dependents.length?`<section class="detail-section"><h2>${esc(copy.dependents)}</h2>${relationLinks(dependents)}</section>`:""}<p class="technology-scope-note">${esc(copy.scopeNote)}</p></div></article>`;
  return {title,description,body,type:"WebPage",parent:{route:"database/technology",label:copy.title}};
}

function structureModel(locale,structure,data){
  const m=messages(locale),copy=structureCopy[locale],title=localized(structure,locale),description=localizedDescription(structure,locale)||copy.intro,items=new Map(data.itemData.items.map(item=>[item.id,item])),technology=[...structure.technologies].sort((a,b)=>a.level-b.level||a.slug.localeCompare(b.slug))[0],atlas=data.structureData.meta.atlas,column=structure.icon.index%atlas.columns,row=Math.floor(structure.icon.index/atlas.columns),x=atlas.columns>1?column/(atlas.columns-1)*100:0,y=atlas.rows>1?row/(atlas.rows-1)*100:0;
  const iconStyle=`--structure-atlas:url('${atlas.path}');--structure-atlas-width:${atlas.columns*100}%;--structure-atlas-height:${atlas.rows*100}%;--structure-atlas-x:${x}%;--structure-atlas-y:${y}%`;
  const materials=structure.materials.map(material=>{const item=items.get(material.itemId);return item?{href:href(locale,`items/${encodeURIComponent(item.id)}`),label:localized(item,locale),image:`/assets/items/${encodeURIComponent(item.id)}.webp`,detail:`× ${material.count.toLocaleString(locale)}`}:null});
  const technologies=structure.technologies.map(entry=>({href:href(locale,`database/technology/${entry.slug}`),label:localized(entry,locale),detail:`${copy.level} ${entry.level.toLocaleString(locale)} · ${entry.pointCost.toLocaleString(locale)} ${copy.points}`}));
  const output=structure.production?items.get(structure.production.itemId):null,outputLinks=output?[{href:href(locale,`items/${encodeURIComponent(output.id)}`),label:localized(output,locale),image:`/assets/items/${encodeURIComponent(output.id)}.webp`,detail:`${copy.productionWork} ${structure.production.workAmount.toLocaleString(locale)}`}]:[];
  const facts=details([[copy.category,localized(structure.category,locale)],[copy.subcategory,localized(structure.subcategory,locale)],[copy.unlockLevel,technology.level.toLocaleString(locale)],[copy.rank,structure.rank.toLocaleString(locale)],[copy.workAmount,structure.workAmount.toLocaleString(locale)],[copy.power,structure.energy?`${copy.powered} · ${structure.energy.consumption.toLocaleString(locale)}`:copy.unpowered],[copy.hp,structure.stats.hp?.toLocaleString(locale)],[copy.defense,structure.stats.defense?.toLocaleString(locale)]]);
  const body=`${hero(m,title)}<article class="entity-detail structure-summary panel"><span class="structure-icon detail" aria-hidden="true" style="${iconStyle}"></span><div class="entity-detail-content">${breadcrumb(locale,"database/structures",copy.title,title)}<p class="entity-description">${esc(description)}</p>${facts}<section class="detail-section"><h2>${esc(copy.materials)}</h2>${relationLinks(materials)}</section><section class="detail-section"><h2>${esc(copy.technology)}</h2>${relationLinks(technologies)}</section>${outputLinks.length?`<section class="detail-section"><h2>${esc(copy.production)}</h2>${relationLinks(outputLinks)}</section>`:""}<p class="structure-scope-note">${esc(copy.scopeNote)}</p></div></article>`;
  return {title,description,body,type:"WebPage",parent:{route:"database/structures",label:copy.title}};
}

function npcDescription(npc,locale){const copy=npcCopy[locale];return npc.merchant?.type==="items"||npc.merchant?.type==="item-profiles"?copy.itemMerchantDescription:npc.merchant?.type==="pals"?copy.palMerchantDescription:npc.events?.type==="achievement"?copy.achievementDescription:npc.events?.type==="item-request"?copy.foodDescription:npc.events?.type==="pal-request"?copy.palCriticDescription:npc.kind==="merchant"?copy.stockUnavailable:npc.kind==="quest"?copy.questDescription:npc.kind==="guide"?copy.guideDescription:npc.kind==="combat"?copy.combatDescription:npc.kind==="reward"?copy.rewardDescription:copy.characterDescription}
function npcModel(locale,npc,data){
  const {palData,itemData,npcData}=data,m=messages(locale),copy=npcCopy[locale],title=localized(npc,locale),sameName=npcData.npcs.filter(entry=>localized(entry,locale)===title).sort((a,b)=>a.slug.localeCompare(b.slug)),variantIndex=sameName.findIndex(entry=>entry.slug===npc.slug),documentTitle=sameName.length>1?`${title} (${variantIndex+1}/${sameName.length})`:title,baseDescription=npcDescription(npc,locale),description=seoDescription(baseDescription,[documentTitle,`${copy.roles} ${npc.roles.length.toLocaleString(locale)}`,`${copy.fixedLocations} ${npc.encounters.length.toLocaleString(locale)}`]),items=new Map(itemData.items.map(item=>[item.id,item])),pals=new Map(palData.pals.map(pal=>[pal.id,pal]));
  const offers=npc.merchant?.type==="items"?(npc.merchant.offers||[]):npc.merchant?.type==="item-profiles"?npc.merchant.profiles.flatMap(profile=>profile.offers||[]):[];
  const itemLinks=[...offers.map(offer=>items.get(offer.itemId)),...(npc.events?.steps||[]).flatMap(step=>(step.rewards||[]).map(reward=>items.get(reward.itemId)))].filter(Boolean).map(item=>({href:href(locale,`items/${encodeURIComponent(item.id)}`),label:localized(item,locale),image:`/assets/items/${encodeURIComponent(item.id)}.webp`}));
  const palLinks=npc.merchant?.type==="pals"?npc.merchant.profiles.flatMap(profile=>profile.palIds.map(id=>pals.get(id))).filter(Boolean).map(pal=>({href:href(locale,`pals/${encodeURIComponent(pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${encodeURIComponent(pal.id)}.png`})):[];
  const body=`${hero(m,title)}<article class="entity-detail panel"><img class="detail-image" src="/assets/map-icons/${npc.kind==="merchant"?"merchant":npc.kind==="combat"?"wanted":"npc"}.webp" alt="" width="128" height="128"><div class="entity-detail-content">${breadcrumb(locale,"database/npcs",copy.catalogTitle,title)}<p class="entity-description">${esc(baseDescription)}</p>${details([[copy.roles,npc.roles.length.toLocaleString(locale)],[copy.fixedLocations,npc.encounters.length.toLocaleString(locale)],[copy.level,npc.level?`${npc.level.min.toLocaleString(locale)}${npc.level.min===npc.level.max?"":`–${npc.level.max.toLocaleString(locale)}`}`:copy.noFixedLocation]])}${itemLinks.length?`<section class="detail-section"><h2>${esc(copy.soldItems)}</h2>${relationLinks(uniqueLinks(itemLinks).slice(0,40))}</section>`:""}${palLinks.length?`<section class="detail-section"><h2>${esc(m.pals)}</h2>${relationLinks(uniqueLinks(palLinks).slice(0,40))}</section>`:""}</div></article>`;
  return {title,documentTitle,description,body,type:"WebPage",parent:{route:"database/npcs",label:copy.catalogTitle}};
}

function dungeonModel(locale,dungeon,data){
  const {palData,itemData}=data,m=messages(locale),copy=dungeonCopy[locale],title=localized(dungeon,locale),description=`${title} — ${copy.intro}`,pals=new Map(palData.pals.map(pal=>[pal.id,pal])),items=new Map(itemData.items.map(item=>[item.id,item]));
  const palLinks=dungeon.encounterGroups.flatMap(group=>group.members).map(member=>pals.get(member.palId)).filter(Boolean).map(pal=>({href:href(locale,`pals/${encodeURIComponent(pal.id)}`),label:`#${pal.dex}${pal.variant?"B":""} ${localized(pal,locale)}`,image:`/assets/pals/${encodeURIComponent(pal.id)}.png`}));
  const pools=[...dungeon.itemPools,...dungeon.rewardSources.flatMap(source=>source.itemPools||[])],itemLinks=pools.flatMap(pool=>pool.slots.flatMap(slot=>slot.candidates)).map(candidate=>items.get(candidate.itemId)).filter(Boolean).map(item=>({href:href(locale,`items/${encodeURIComponent(item.id)}`),label:localized(item,locale),image:`/assets/items/${encodeURIComponent(item.id)}.webp`}));
  const level=dungeon.encounterLevel?`${dungeon.encounterLevel.min.toLocaleString(locale)}${dungeon.encounterLevel.min===dungeon.encounterLevel.max?"":`–${dungeon.encounterLevel.max.toLocaleString(locale)}`}`:copy.noData;
  const body=`${hero(m,title)}<article class="dungeon-detail section"><section class="dungeon-summary panel"><img src="/assets/map-icons/dungeon.webp" alt="" width="96" height="96"><div>${breadcrumb(locale,"database/dungeons",copy.title,title)}<p class="entity-description">${esc(description)}</p>${details([[copy.encounterLevel,level],[copy.entrances,dungeon.summary.entranceCount.toLocaleString(locale)],[copy.possiblePals,dungeon.summary.palCount.toLocaleString(locale)],[copy.encounterGroups,dungeon.summary.encounterGroupCount.toLocaleString(locale)],[copy.itemCandidates,dungeon.summary.itemCandidateCount.toLocaleString(locale)]])}</div></section>${palLinks.length?`<section class="detail-section"><h2>${esc(copy.possiblePals)}</h2>${relationLinks(uniqueLinks(palLinks))}</section>`:""}${itemLinks.length?`<section class="detail-section"><h2>${esc(copy.possibleItems)}</h2><p class="notice">${esc(copy.itemNotice)}</p>${relationLinks(uniqueLinks(itemLinks).slice(0,80))}</section>`:""}</article>`;
  return {title,description,body,type:"WebPage",parent:{route:"database/dungeons",label:copy.title}};
}

function expeditionDifficulty(locale,difficulty){const copy=expeditionCopy[locale];return difficulty==="very-hard"?copy.veryHard:copy[difficulty]}
function expeditionDuration(locale,seconds){const unit=seconds%3600===0?"hour":"minute",value=unit==="hour"?seconds/3600:seconds/60;return new Intl.NumberFormat(locale,{style:"unit",unit,unitDisplay:"long",maximumFractionDigits:1}).format(value)}
function expeditionCondition(locale,condition,data){const copy=expeditionCopy[locale];if(!condition)return copy.alwaysAvailable;const region=data.expeditionData.expeditions.find(entry=>entry.variant==="standard"&&entry.imageRegionSlug===condition.regionSlug),difficulty=condition.difficulty==="hard"?copy.hardVariant:copy.normal,count=condition.hardBossCount>0?` ×${condition.hardBossCount.toLocaleString(locale)}`:"";return `${copy.completeBoss}: ${localized(region,locale)} (${difficulty}${count})`}
function expeditionModel(locale,expedition,data){
  const m=messages(locale),copy=expeditionCopy[locale],title=localized(expedition,locale),description=`${copy.intro} ${copy.possibleRewards}: ${expedition.summary.uniqueRewardItemCount.toLocaleString(locale)}.`,items=new Map(data.itemData.items.map(item=>[item.id,item])),element=data.elementData.elements.find(entry=>entry.slug===expedition.requiredElementSlug);
  const rewards=expedition.rewardSlots.map(slot=>`<article class="panel expedition-reward-slot"><header><h3>${esc(copy.rewardSlot)} ${slot.slot.toLocaleString(locale)}</h3><span>${slot.candidates.length.toLocaleString(locale)} ${esc(copy.candidates)}</span></header><ul>${slot.candidates.map(candidate=>{const item=items.get(candidate.itemId),quantity=candidate.minCount===candidate.maxCount?candidate.minCount.toLocaleString(locale):`${candidate.minCount.toLocaleString(locale)}–${candidate.maxCount.toLocaleString(locale)}`;return item?`<li><a href="${href(locale,`items/${encodeURIComponent(item.id)}`)}"><img src="/assets/items/${encodeURIComponent(item.id)}.webp" alt="" width="52" height="52"><span><strong>${esc(localized(item,locale))}</strong><small>${esc(quantity)}</small></span></a><span class="expedition-weight">${esc(copy.relativeWeight)} ${candidate.selectionWeight.toLocaleString(locale)}</span></li>`:""}).join("")}</ul></article>`).join("");
  const facts=details([[copy.variant,expedition.variant==="hard"?copy.hardVariant:copy.standard],[copy.difficulty,expeditionDifficulty(locale,expedition.difficulty)],[copy.recommendedStrength,expedition.recommendedStrength.toLocaleString(locale)],[copy.baseDuration,expeditionDuration(locale,expedition.baseDurationSeconds)],[copy.maxPalCount,expedition.maxPalCount.toLocaleString(locale)],[copy.requiredElement,element?`${localized(element,locale)} ×${expedition.requiredElementCount.toLocaleString(locale)}`:copy.noElementRequirement],[copy.unlockCondition,expeditionCondition(locale,expedition.visibilityCondition,data)],[copy.challengeCondition,expeditionCondition(locale,expedition.challengeCondition,data)]]);
  const body=`${hero(m,title)}<article class="expedition-detail section"><img class="expedition-banner" src="${esc(expedition.image)}" alt="" width="1080" height="100"><div class="panel">${breadcrumb(locale,"database/expeditions",copy.title,title)}${facts}<p class="notice">${esc(copy.durationNotice)}</p></div><section class="expedition-rewards"><h2>${esc(copy.possibleRewards)}</h2><p class="notice warning">${esc(copy.rewardNotice)}</p><div class="expedition-reward-slots">${rewards}</div></section></article>`;
  return {title,description,body,type:"WebPage",parent:{route:"database/expeditions",label:copy.title}};
}

function questModel(locale,quest,data){
  const m=messages(locale),copy=questCopy[locale],title=localized(quest,locale),description=localizedDescription(quest,locale)||copy.intro,items=new Map(data.itemData.items.map(item=>[item.id,item])),quests=new Map(data.questData.quests.map(entry=>[entry.slug,entry]));
  const objectives=quest.objectiveGroups.length?quest.objectiveGroups.map((group,index)=>`<section class="quest-objective-group"><h3>${esc(`${copy.objectives} ${(index+1).toLocaleString(locale)}`)}</h3><ol>${group.steps.map(step=>`<li>${esc(step.texts[locale]||step.texts[defaultLocale])}</li>`).join("")}</ol></section>`).join(""):`<p class="notice">${esc(copy.noObjectives)}</p>`;
  const rewardLinks=quest.rewards.items.map(reward=>{const item=items.get(reward.itemId);return item?{href:href(locale,`items/${encodeURIComponent(item.id)}`),label:localized(item,locale),image:`/assets/items/${encodeURIComponent(item.id)}.webp`,detail:`× ${reward.quantity.toLocaleString(locale)}`}:null});
  const relation=(slugs,label)=>slugs.map(slug=>quests.get(slug)).filter(Boolean).map(entry=>({href:href(locale,`database/quests/${entry.slug}`),label:localized(entry,locale),detail:label}));
  const previous=relation(quest.previousSlugs,copy.previous),next=relation(quest.nextSlugs,copy.next),facts=details([[quest.kind==="main"?copy.main:copy.side,`${copy.sequence} ${(quest.order+1).toLocaleString(locale)}`],[copy.experience,quest.rewards.experience.toLocaleString(locale)],[copy.items,quest.rewards.items.length.toLocaleString(locale)]]);
  const body=`${hero(m,title)}<article class="quest-detail section"><div class="panel quest-detail-content">${breadcrumb(locale,"database/quests",copy.title,title)}<p class="entity-description">${esc(description)}</p>${facts}<section class="detail-section"><h2>${esc(copy.objectives)}</h2>${objectives}<p class="notice">${esc(copy.objectiveNotice)}</p></section><section class="detail-section"><h2>${esc(copy.rewards)}</h2>${relationLinks(rewardLinks)}${quest.rewards.additionalRewardStatus==="unavailable"?`<p class="notice warning">${esc(copy.additionalUnavailable)}</p>`:""}</section>${previous.length||next.length?`<section class="detail-section"><h2>${esc(copy.sequence)}</h2>${relationLinks([...previous,...next])}</section>`:""}<p><a class="button" href="${href(locale,"database/quests")}">${esc(copy.back)}</a></p></div></article>`;
  return {title,description,body,type:"WebPage",parent:{route:"database/quests",label:copy.title}};
}

function healthConditionModel(locale,condition,data){
  const copy=healthCopy[locale],title=localized(condition,locale),description=localizedDescription(condition,locale),medicine=data.healthData.medicines.find(entry=>entry.slug===condition.medicine),medicineName=localized(medicine,locale);
  const ingredients=medicine.recipe.ingredients.map(ingredient=>`<li><a href="${href(locale,`items/${ingredient.itemId}`)}">${esc(localized(ingredient,locale))}</a> × ${ingredient.count.toLocaleString(locale)}</li>`).join("");
  const effects=details([[copy.workSpeed,condition.effects.workSpeed],[copy.moveSpeed,condition.effects.moveSpeed],[copy.satietyDecrease,condition.effects.satietyDecrease],[copy.palBoxRecovery,condition.effects.palBoxRecovery]]);
  const body=`${hero(messages(locale),title)}<article class="entity-detail panel"><div class="entity-detail-content">${breadcrumb(locale,"database/health",copy.title,title)}<p class="entity-description">${esc(description)}</p><section class="detail-section"><h2>${esc(copy.sourceEffects)}</h2>${effects}<p class="notice warning">${esc(copy.runtimeUnavailable)}</p></section><section class="detail-section"><h2>${esc(copy.treatment)}</h2><p><a href="${href(locale,`items/${medicine.itemId}`)}"><strong>${esc(medicineName)}</strong></a></p><p class="medicine-description">${esc(localizedDescription(medicine,locale))}</p><h3>${esc(copy.recipe)}</h3><ul>${ingredients}</ul><p>${esc(copy.work)}: ${medicine.recipe.workAmount.toLocaleString(locale)}</p></section></div></article>`;
  return {title,description,body,type:"WebPage",parent:{route:"database/health",label:copy.title}};
}

export function renderRouteModel(entry,data,selection,registry=createSeoSlugRegistry(data)){
  activeSlugRegistry=registry;
  if(entry.kind==="collection")return collectionModel(entry.route,entry.locale,data,selection,registry);
  if(entry.dataset==="pals")return palModel(entry.locale,entry.entity,data);
  if(entry.dataset==="items")return itemModel(entry.locale,entry.entity,data);
  if(entry.dataset==="activeSkills"||entry.dataset==="passiveSkills"||entry.dataset==="partnerSkills")return skillModel(entry.locale,entry.entity,entry.dataset,data);
  if(entry.dataset==="npcs")return npcModel(entry.locale,entry.entity,data);
  if(entry.dataset==="technologies")return technologyModel(entry.locale,entry.entity);
  if(entry.dataset==="structures")return structureModel(entry.locale,entry.entity,data);
  if(entry.dataset==="expeditions")return expeditionModel(entry.locale,entry.entity,data);
  if(entry.dataset==="quests")return questModel(entry.locale,entry.entity,data);
  if(entry.dataset==="conditions")return healthConditionModel(entry.locale,entry.entity,data);
  return dungeonModel(entry.locale,entry.entity,data);
}

export function renderHtmlDocument(template,entry,model,origin=productionOrigin){
  const canonical=absolute(origin,entry.locale,entry.route),documentTitle=model.documentTitle||model.title,title=`${documentTitle} · ${siteName}`,description=seoDescription(model.description,[documentTitle]),alternates=supportedLocales.map(locale=>`<link rel="alternate" hreflang="${seoHreflang(locale)}" href="${absolute(origin,locale,entry.route)}" data-dynamic-meta="true">`).join(""),structured=pageStructuredData({origin,locale:entry.locale,route:entry.route,title:model.title,description,type:model.type,parent:model.parent});
  const metadata=`<meta name="description" content="${esc(description)}" data-dynamic-meta="true"><link rel="canonical" href="${canonical}" data-dynamic-meta="true">${alternates}<link rel="alternate" hreflang="x-default" href="${absolute(origin,defaultLocale,entry.route)}" data-dynamic-meta="true"><meta property="og:type" content="website" data-dynamic-meta="true"><meta property="og:title" content="${esc(title)}" data-dynamic-meta="true"><meta property="og:description" content="${esc(description)}" data-dynamic-meta="true"><meta property="og:url" content="${canonical}" data-dynamic-meta="true"><meta property="og:image" content="${origin}/og-image.png" data-dynamic-meta="true"><meta name="twitter:card" content="summary_large_image" data-dynamic-meta="true"><meta name="twitter:title" content="${esc(title)}" data-dynamic-meta="true"><meta name="twitter:description" content="${esc(description)}" data-dynamic-meta="true"><meta name="twitter:image" content="${origin}/og-image.png" data-dynamic-meta="true">${structured?`<script type="application/ld+json" data-route-structured-data>${JSON.stringify(structured).replace(/</g,"\\u003c")}</script>`:""}`;
  return publicAssetHtml(template.replace('<html lang="en-US"',`<html lang="${entry.locale}"`).replace(/<title>[^<]*<\/title>/,`<title>${esc(title)}</title>${metadata}`).replace('<div id="app"></div>',`<div id="app" data-prerender-route="/${entry.locale}/${esc(entry.route)}">${shell(entry.locale,entry.route,model.title,model.body)}</div>`));
}

export function routeRenderingReport(data,selection){
  const datasets=createEntityDatasets(data),collections=routeFamilies.map(route=>({path:route.path,mode:route.mode,indexable:route.indexable,searchIntent:route.searchIntent,indexableUrls:supportedLocales.length,prerenderedUrls:supportedLocales.length})),entities=entityRouteFamilies.map(family=>({prefix:family.prefix,dataset:family.dataset,mode:family.mode,searchIntent:family.searchIntent,indexableUrls:datasets[family.dataset].length*supportedLocales.length,prerenderedUrls:selection[family.dataset].length*supportedLocales.length,selection:family.prerender}));
  return {collections,entities};
}
