import type {Locale} from "./config";
import type {BasePresetGroup,BasePresetId} from "./base-presets";

export type BasePresetUiCopy={
  custom:string;
  selectedRoles:string;
  noRoles:string;
  groups:Record<BasePresetGroup,string>;
  presets:Record<BasePresetId,string>;
};

export const basePresetCopyProvenance="gpt" as const;

export const basePresetCopy:Record<Locale,BasePresetUiCopy>={
  "en-US":{custom:"Custom roles",selectedRoles:"Selected work roles",noRoles:"Select at least one work role.",groups:{general:"General",food:"Food and farming",resources:"Resources",production:"Production and support"},presets:{all:"Self-sufficient",food:"Food and cooking",crops:"Crop farming",ranch:"Ranch production","cake-breeding":"Cake and breeding support",production:"Manufacturing",resources:"Resource gathering",mining:"Mining",logging:"Logging","cold-storage":"Cold storage and transport",medicine:"Medicine supply"}},
  "ko-KR":{custom:"직접 설정",selectedRoles:"선택한 작업 역할",noRoles:"작업 역할을 하나 이상 선택하세요.",groups:{general:"일반",food:"식량·농업",resources:"자원",production:"생산·지원"},presets:{all:"자급자족",food:"식량 조리",crops:"농작물 재배",ranch:"목장 생산","cake-breeding":"케이크·교배 지원",production:"제조",resources:"자원 채집",mining:"채광 전용",logging:"벌목 전용","cold-storage":"냉장·운반",medicine:"의약품 공급"}},
  "ja-JP":{custom:"カスタム",selectedRoles:"選択中の作業",noRoles:"作業を1つ以上選択してください。",groups:{general:"一般",food:"食料・農業",resources:"資源",production:"生産・支援"},presets:{all:"自給自足",food:"食料・調理",crops:"農作物栽培",ranch:"牧場生産","cake-breeding":"ケーキ・配合支援",production:"製造",resources:"資源採取",mining:"採掘特化",logging:"伐採特化","cold-storage":"冷蔵・運搬",medicine:"医薬品供給"}},
  "zh-CN":{custom:"自定义",selectedRoles:"已选工作",noRoles:"请至少选择一种工作。",groups:{general:"通用",food:"食物与农业",resources:"资源",production:"生产与辅助"},presets:{all:"自给自足",food:"食物与烹饪",crops:"农作物种植",ranch:"牧场生产","cake-breeding":"蛋糕与配种辅助",production:"制造",resources:"资源采集",mining:"专门采矿",logging:"专门伐木","cold-storage":"冷藏与搬运",medicine:"药品供应"}},
  "zh-TW":{custom:"自訂",selectedRoles:"已選工作",noRoles:"請至少選擇一種工作。",groups:{general:"通用",food:"食物與農業",resources:"資源",production:"生產與支援"},presets:{all:"自給自足",food:"食物與烹飪",crops:"農作物栽培",ranch:"牧場生產","cake-breeding":"蛋糕與配種支援",production:"製造",resources:"資源採集",mining:"專門採礦",logging:"專門伐木","cold-storage":"冷藏與搬運",medicine:"藥品供應"}},
  "fr-FR":{custom:"Rôles personnalisés",selectedRoles:"Travaux sélectionnés",noRoles:"Sélectionnez au moins un travail.",groups:{general:"Général",food:"Alimentation et agriculture",resources:"Ressources",production:"Production et soutien"},presets:{all:"Autonomie",food:"Alimentation et cuisine",crops:"Cultures",ranch:"Production d’élevage","cake-breeding":"Gâteaux et soutien à l’élevage",production:"Fabrication",resources:"Collecte de ressources",mining:"Extraction minière",logging:"Exploitation forestière","cold-storage":"Réfrigération et transport",medicine:"Approvisionnement médical"}},
  "it-IT":{custom:"Ruoli personalizzati",selectedRoles:"Lavori selezionati",noRoles:"Seleziona almeno un lavoro.",groups:{general:"Generale",food:"Cibo e agricoltura",resources:"Risorse",production:"Produzione e supporto"},presets:{all:"Autosufficienza",food:"Cibo e cucina",crops:"Coltivazione",ranch:"Produzione da pascolo","cake-breeding":"Torte e supporto alla riproduzione",production:"Produzione",resources:"Raccolta risorse",mining:"Estrazione mineraria",logging:"Taglio del legname","cold-storage":"Refrigerazione e trasporto",medicine:"Fornitura di medicinali"}},
  "de-DE":{custom:"Eigene Rollen",selectedRoles:"Ausgewählte Arbeiten",noRoles:"Wähle mindestens eine Arbeit aus.",groups:{general:"Allgemein",food:"Nahrung und Landwirtschaft",resources:"Ressourcen",production:"Produktion und Unterstützung"},presets:{all:"Selbstversorgung",food:"Nahrung und Kochen",crops:"Feldbau",ranch:"Farmproduktion","cake-breeding":"Kuchen- und Zuchtunterstützung",production:"Fertigung",resources:"Ressourcengewinnung",mining:"Bergbau",logging:"Holzgewinnung","cold-storage":"Kühlung und Transport",medicine:"Medizinversorgung"}},
  "es-ES":{custom:"Trabajos personalizados",selectedRoles:"Trabajos seleccionados",noRoles:"Selecciona al menos un trabajo.",groups:{general:"General",food:"Alimentos y agricultura",resources:"Recursos",production:"Producción y apoyo"},presets:{all:"Autosuficiencia",food:"Alimentos y cocina",crops:"Cultivo",ranch:"Producción de rancho","cake-breeding":"Tartas y apoyo a la cría",production:"Fabricación",resources:"Obtención de recursos",mining:"Minería",logging:"Tala","cold-storage":"Refrigeración y transporte",medicine:"Suministro médico"}},
  "es-419":{custom:"Trabajos personalizados",selectedRoles:"Trabajos seleccionados",noRoles:"Selecciona al menos un trabajo.",groups:{general:"General",food:"Alimentos y agricultura",resources:"Recursos",production:"Producción y apoyo"},presets:{all:"Autosuficiencia",food:"Alimentos y cocina",crops:"Cultivo",ranch:"Producción de rancho","cake-breeding":"Pasteles y apoyo a la cría",production:"Fabricación",resources:"Obtención de recursos",mining:"Minería",logging:"Tala","cold-storage":"Refrigeración y transporte",medicine:"Suministro médico"}},
  "pt-BR":{custom:"Trabalhos personalizados",selectedRoles:"Trabalhos selecionados",noRoles:"Selecione pelo menos um trabalho.",groups:{general:"Geral",food:"Alimentos e agricultura",resources:"Recursos",production:"Produção e apoio"},presets:{all:"Autossuficiência",food:"Alimentos e cozinha",crops:"Cultivo",ranch:"Produção de rancho","cake-breeding":"Bolos e apoio à reprodução",production:"Fabricação",resources:"Coleta de recursos",mining:"Mineração",logging:"Extração de madeira","cold-storage":"Refrigeração e transporte",medicine:"Suprimento médico"}},
  "ru-RU":{custom:"Свои работы",selectedRoles:"Выбранные работы",noRoles:"Выберите хотя бы одну работу.",groups:{general:"Общее",food:"Еда и сельское хозяйство",resources:"Ресурсы",production:"Производство и поддержка"},presets:{all:"Самообеспечение",food:"Еда и готовка",crops:"Выращивание культур",ranch:"Производство на пастбище","cake-breeding":"Торты и поддержка разведения",production:"Производство",resources:"Добыча ресурсов",mining:"Горное дело",logging:"Лесозаготовка","cold-storage":"Охлаждение и транспортировка",medicine:"Снабжение лекарствами"}},
  "id-ID":{custom:"Pekerjaan khusus",selectedRoles:"Pekerjaan terpilih",noRoles:"Pilih setidaknya satu pekerjaan.",groups:{general:"Umum",food:"Makanan dan pertanian",resources:"Sumber daya",production:"Produksi dan dukungan"},presets:{all:"Swasembada",food:"Makanan dan memasak",crops:"Budidaya tanaman",ranch:"Produksi peternakan","cake-breeding":"Kue dan dukungan pembiakan",production:"Manufaktur",resources:"Pengumpulan sumber daya",mining:"Penambangan",logging:"Penebangan","cold-storage":"Pendinginan dan pengangkutan",medicine:"Pasokan obat"}},
  "th-TH":{custom:"งานที่กำหนดเอง",selectedRoles:"งานที่เลือก",noRoles:"เลือกงานอย่างน้อยหนึ่งประเภท",groups:{general:"ทั่วไป",food:"อาหารและเกษตรกรรม",resources:"ทรัพยากร",production:"การผลิตและสนับสนุน"},presets:{all:"พึ่งพาตนเอง",food:"อาหารและการปรุง",crops:"เพาะปลูก",ranch:"ผลผลิตจากฟาร์มปศุสัตว์","cake-breeding":"เค้กและสนับสนุนการผสมพันธุ์",production:"การผลิต",resources:"รวบรวมทรัพยากร",mining:"ทำเหมือง",logging:"ตัดไม้","cold-storage":"ทำความเย็นและขนส่ง",medicine:"จัดหายา"}},
  "tr-TR":{custom:"Özel işler",selectedRoles:"Seçili işler",noRoles:"En az bir iş seçin.",groups:{general:"Genel",food:"Yiyecek ve tarım",resources:"Kaynaklar",production:"Üretim ve destek"},presets:{all:"Kendi kendine yeterli",food:"Yiyecek ve pişirme",crops:"Ekin yetiştirme",ranch:"Çiftlik üretimi","cake-breeding":"Pasta ve çiftleştirme desteği",production:"Üretim",resources:"Kaynak toplama",mining:"Madencilik",logging:"Odunculuk","cold-storage":"Soğutma ve taşıma",medicine:"İlaç tedariki"}},
  "vi-VN":{custom:"Công việc tùy chỉnh",selectedRoles:"Công việc đã chọn",noRoles:"Chọn ít nhất một công việc.",groups:{general:"Chung",food:"Thực phẩm và nông nghiệp",resources:"Tài nguyên",production:"Sản xuất và hỗ trợ"},presets:{all:"Tự cung tự cấp",food:"Thực phẩm và nấu ăn",crops:"Trồng trọt",ranch:"Sản xuất tại nông trại","cake-breeding":"Bánh và hỗ trợ phối giống",production:"Chế tạo",resources:"Thu thập tài nguyên",mining:"Khai khoáng",logging:"Khai thác gỗ","cold-storage":"Làm lạnh và vận chuyển",medicine:"Cung cấp thuốc"}},
  "pl-PL":{custom:"Własne prace",selectedRoles:"Wybrane prace",noRoles:"Wybierz co najmniej jedną pracę.",groups:{general:"Ogólne",food:"Żywność i rolnictwo",resources:"Zasoby",production:"Produkcja i wsparcie"},presets:{all:"Samowystarczalność",food:"Żywność i gotowanie",crops:"Uprawa roślin",ranch:"Produkcja rancza","cake-breeding":"Ciasta i wsparcie hodowli",production:"Wytwarzanie",resources:"Pozyskiwanie zasobów",mining:"Górnictwo",logging:"Wyrąb drewna","cold-storage":"Chłodzenie i transport",medicine:"Zaopatrzenie medyczne"}},
};
