import type {Locale} from "./config.ts";

const en={title:"Practical breeding path",intro:"Start with Pals you have and compare the fewest-generation route with a practical weighted route.",owned:"Owned starting Pals",addOwned:"Add owned Pal",selectedOwned:"Selected starting Pals",target:"Target Pal",maxDepth:"Maximum generations",find:"Find paths",shortest:"Fewest generations",practical:"Recommended practical route",sameRoute:"Both rankings selected the same route.",noPath:"No verified path was found within these limits.",chooseOwned:"Add at least two starting Pals.",step:"Breeding step",generation:"Generation",score:"Practical score",assumptions:"Scoring boundary",assumptionBody:"Only verified breeding rows are used. Capture difficulty, passive inheritance chance, IVs, egg counts, cakes, and time are not estimated.",weights:"Practical weights",generations:"Generations",uniqueOwned:"Unique starting Pals",genderConstraints:"Gender constraints",specialSteps:"Conditional combinations",repeatedOwnedUses:"Repeated starting-Pal use",evaluated:"Candidate paths checked",truncated:"The candidate limit was reached. Reduce generations or starting Pals.",remove:"Remove",reset:"Reset",directOwned:"Already owned",parent:"Parents",child:"Result",shareNote:"Selections stay in this browser and shared URLs use public Pal slugs only."};
export type BreedingPathCopy=typeof en;

export const breedingPathCopy:Record<Locale,BreedingPathCopy>={
  "en-US":en,
  "ko-KR":{title:"실용 교배 경로",intro:"보유한 팰에서 시작해 최소 세대 경로와 가중치를 적용한 실용 경로를 비교합니다.",owned:"보유 시작 팰",addOwned:"보유 팰 추가",selectedOwned:"선택한 시작 팰",target:"목표 팰",maxDepth:"최대 세대",find:"경로 찾기",shortest:"최소 세대 경로",practical:"추천 실용 경로",sameRoute:"두 기준이 같은 경로를 선택했습니다.",noPath:"이 제한 안에서 검증된 경로를 찾지 못했습니다.",chooseOwned:"시작 팰을 두 종 이상 추가하세요.",step:"교배 단계",generation:"세대",score:"실용 점수",assumptions:"점수 적용 범위",assumptionBody:"검증된 교배 행만 사용합니다. 포획 난도, 패시브 유전 확률, IV, 알 수, 케이크와 시간은 추정하지 않습니다.",weights:"실용 가중치",generations:"세대 수",uniqueOwned:"고유 시작 팰",genderConstraints:"성별 제약",specialSteps:"조건부 조합",repeatedOwnedUses:"시작 팰 재사용",evaluated:"검사한 후보 경로",truncated:"후보 제한에 도달했습니다. 최대 세대나 시작 팰 수를 줄이세요.",remove:"제거",reset:"초기화",directOwned:"이미 보유",parent:"부모",child:"결과",shareNote:"선택 내용은 브라우저에서만 처리되며 공유 URL에는 공개 팰 슬러그만 사용합니다."},
  "ja-JP":{title:"実用的な配合ルート",intro:"所持パルから始め、最少世代ルートと重み付きの実用ルートを比較します。",owned:"所持している開始パル",addOwned:"所持パルを追加",selectedOwned:"選択した開始パル",target:"目標パル",maxDepth:"最大世代",find:"ルートを検索",shortest:"最少世代ルート",practical:"おすすめ実用ルート",sameRoute:"両方の基準で同じルートが選ばれました。",noPath:"この条件内では検証済みルートが見つかりませんでした。",chooseOwned:"開始パルを2種類以上追加してください。",step:"配合手順",generation:"世代",score:"実用スコア",assumptions:"スコアの範囲",assumptionBody:"検証済みの配合データのみ使用します。捕獲難度、パッシブ継承率、IV、卵数、ケーキ、時間は推定しません。",weights:"実用ウェイト",generations:"世代数",uniqueOwned:"固有の開始パル",genderConstraints:"性別条件",specialSteps:"条件付き配合",repeatedOwnedUses:"開始パルの再利用",evaluated:"確認した候補ルート",truncated:"候補上限に達しました。最大世代または開始パル数を減らしてください。",remove:"削除",reset:"リセット",directOwned:"所持済み",parent:"親",child:"結果",shareNote:"選択内容はブラウザ内で処理され、共有URLには公開パルスラッグのみ使用します。"},
  "zh-CN":{title:"实用配种路径",intro:"从已有帕鲁出发，对比最少世代路径与加权实用路径。",owned:"已有起始帕鲁",addOwned:"添加已有帕鲁",selectedOwned:"已选起始帕鲁",target:"目标帕鲁",maxDepth:"最大世代",find:"查找路径",shortest:"最少世代路径",practical:"推荐实用路径",sameRoute:"两种排序选择了同一路径。",noPath:"在当前限制内未找到已验证路径。",chooseOwned:"请至少添加两种起始帕鲁。",step:"配种步骤",generation:"世代",score:"实用分数",assumptions:"评分范围",assumptionBody:"仅使用已验证配种记录。不估算捕获难度、被动遗传概率、IV、蛋数、蛋糕或时间。",weights:"实用权重",generations:"世代数",uniqueOwned:"不同起始帕鲁",genderConstraints:"性别限制",specialSteps:"条件组合",repeatedOwnedUses:"重复使用起始帕鲁",evaluated:"已检查候选路径",truncated:"已达到候选上限。请减少最大世代或起始帕鲁。",remove:"移除",reset:"重置",directOwned:"已经拥有",parent:"亲代",child:"结果",shareNote:"选择仅在浏览器中处理，共享URL只使用公开帕鲁别名。"},
  "zh-TW":{title:"實用配種路徑",intro:"從已有帕魯出發，比較最少世代路徑與加權實用路徑。",owned:"已有起始帕魯",addOwned:"新增已有帕魯",selectedOwned:"已選起始帕魯",target:"目標帕魯",maxDepth:"最大世代",find:"尋找路徑",shortest:"最少世代路徑",practical:"推薦實用路徑",sameRoute:"兩種排序選擇了相同路徑。",noPath:"在目前限制內找不到已驗證路徑。",chooseOwned:"請至少新增兩種起始帕魯。",step:"配種步驟",generation:"世代",score:"實用分數",assumptions:"評分範圍",assumptionBody:"只使用已驗證配種紀錄。不估算捕獲難度、被動遺傳機率、IV、蛋數、蛋糕或時間。",weights:"實用權重",generations:"世代數",uniqueOwned:"不同起始帕魯",genderConstraints:"性別限制",specialSteps:"條件組合",repeatedOwnedUses:"重複使用起始帕魯",evaluated:"已檢查候選路徑",truncated:"已達候選上限。請減少最大世代或起始帕魯。",remove:"移除",reset:"重設",directOwned:"已經擁有",parent:"親代",child:"結果",shareNote:"選擇只在瀏覽器中處理，共用網址只使用公開帕魯別名。"},
  "de-DE":{title:"Praktischer Zuchtweg",intro:"Beginne mit deinen Pals und vergleiche den Weg mit den wenigsten Generationen mit einem gewichteten praktischen Weg.",owned:"Vorhandene Start-Pals",addOwned:"Vorhandenen Pal hinzufügen",selectedOwned:"Gewählte Start-Pals",target:"Ziel-Pal",maxDepth:"Maximale Generationen",find:"Wege suchen",shortest:"Wenigste Generationen",practical:"Empfohlener praktischer Weg",sameRoute:"Beide Wertungen haben denselben Weg gewählt.",noPath:"Innerhalb dieser Grenzen wurde kein geprüfter Weg gefunden.",chooseOwned:"Füge mindestens zwei Start-Pals hinzu.",step:"Zuchtschritt",generation:"Generation",score:"Praxiswert",assumptions:"Wertungsgrenze",assumptionBody:"Es werden nur geprüfte Zuchtzeilen verwendet. Fangschwierigkeit, Passivvererbung, IVs, Eier, Kuchen und Zeit werden nicht geschätzt.",weights:"Praxisgewichte",generations:"Generationen",uniqueOwned:"Einzigartige Start-Pals",genderConstraints:"Geschlechtsbedingungen",specialSteps:"Bedingte Kombinationen",repeatedOwnedUses:"Wiederverwendung von Start-Pals",evaluated:"Geprüfte Kandidatenwege",truncated:"Das Kandidatenlimit wurde erreicht. Verringere Generationen oder Start-Pals.",remove:"Entfernen",reset:"Zurücksetzen",directOwned:"Bereits vorhanden",parent:"Eltern",child:"Ergebnis",shareNote:"Auswahlen werden nur im Browser verarbeitet; geteilte URLs verwenden nur öffentliche Pal-Slugs."},
  "fr-FR":{title:"Parcours d’élevage pratique",intro:"Partez de vos Pals et comparez le parcours avec le moins de générations au parcours pratique pondéré.",owned:"Pals de départ possédés",addOwned:"Ajouter un Pal possédé",selectedOwned:"Pals de départ choisis",target:"Pal cible",maxDepth:"Générations maximales",find:"Chercher les parcours",shortest:"Moins de générations",practical:"Parcours pratique recommandé",sameRoute:"Les deux classements ont choisi le même parcours.",noPath:"Aucun parcours vérifié n’a été trouvé dans ces limites.",chooseOwned:"Ajoutez au moins deux Pals de départ.",step:"Étape d’élevage",generation:"Génération",score:"Score pratique",assumptions:"Limites du score",assumptionBody:"Seules les combinaisons vérifiées sont utilisées. Difficulté de capture, héritage des passifs, IV, œufs, gâteaux et durée ne sont pas estimés.",weights:"Poids pratiques",generations:"Générations",uniqueOwned:"Pals de départ distincts",genderConstraints:"Contraintes de sexe",specialSteps:"Combinaisons conditionnelles",repeatedOwnedUses:"Réutilisation des Pals de départ",evaluated:"Parcours candidats vérifiés",truncated:"La limite de candidats est atteinte. Réduisez les générations ou les Pals de départ.",remove:"Retirer",reset:"Réinitialiser",directOwned:"Déjà possédé",parent:"Parents",child:"Résultat",shareNote:"Les choix restent dans ce navigateur et les URL partagées utilisent uniquement les identifiants publics des Pals."},
  "it-IT":{title:"Percorso di riproduzione pratico",intro:"Parti dai Pal che possiedi e confronta il percorso con meno generazioni con quello pratico ponderato.",owned:"Pal iniziali posseduti",addOwned:"Aggiungi Pal posseduto",selectedOwned:"Pal iniziali selezionati",target:"Pal obiettivo",maxDepth:"Generazioni massime",find:"Trova percorsi",shortest:"Meno generazioni",practical:"Percorso pratico consigliato",sameRoute:"Entrambe le classifiche hanno scelto lo stesso percorso.",noPath:"Nessun percorso verificato trovato entro questi limiti.",chooseOwned:"Aggiungi almeno due Pal iniziali.",step:"Passaggio di riproduzione",generation:"Generazione",score:"Punteggio pratico",assumptions:"Limiti del punteggio",assumptionBody:"Si usano solo combinazioni verificate. Difficoltà di cattura, eredità passive, IV, uova, torte e tempo non vengono stimati.",weights:"Pesi pratici",generations:"Generazioni",uniqueOwned:"Pal iniziali unici",genderConstraints:"Vincoli di sesso",specialSteps:"Combinazioni condizionali",repeatedOwnedUses:"Riutilizzo dei Pal iniziali",evaluated:"Percorsi candidati controllati",truncated:"Raggiunto il limite dei candidati. Riduci generazioni o Pal iniziali.",remove:"Rimuovi",reset:"Reimposta",directOwned:"Già posseduto",parent:"Genitori",child:"Risultato",shareNote:"Le selezioni restano nel browser e gli URL condivisi usano solo slug pubblici dei Pal."},
  "es-ES":{title:"Ruta de cría práctica",intro:"Parte de los Pals que tienes y compara la ruta de menos generaciones con una ruta práctica ponderada.",owned:"Pals iniciales disponibles",addOwned:"Añadir Pal disponible",selectedOwned:"Pals iniciales seleccionados",target:"Pal objetivo",maxDepth:"Generaciones máximas",find:"Buscar rutas",shortest:"Menos generaciones",practical:"Ruta práctica recomendada",sameRoute:"Ambas clasificaciones eligieron la misma ruta.",noPath:"No se encontró una ruta verificada dentro de estos límites.",chooseOwned:"Añade al menos dos Pals iniciales.",step:"Paso de cría",generation:"Generación",score:"Puntuación práctica",assumptions:"Límite de la puntuación",assumptionBody:"Solo se usan combinaciones verificadas. No se estiman dificultad de captura, herencia pasiva, IV, huevos, tartas ni tiempo.",weights:"Pesos prácticos",generations:"Generaciones",uniqueOwned:"Pals iniciales distintos",genderConstraints:"Restricciones de sexo",specialSteps:"Combinaciones condicionales",repeatedOwnedUses:"Reutilización de Pals iniciales",evaluated:"Rutas candidatas comprobadas",truncated:"Se alcanzó el límite de candidatos. Reduce generaciones o Pals iniciales.",remove:"Quitar",reset:"Restablecer",directOwned:"Ya disponible",parent:"Progenitores",child:"Resultado",shareNote:"Las selecciones se procesan en este navegador y las URL compartidas solo usan identificadores públicos."},
  "es-419":{title:"Ruta de crianza práctica",intro:"Parte de los Pals que tienes y compara la ruta de menos generaciones con una ruta práctica ponderada.",owned:"Pals iniciales disponibles",addOwned:"Agregar Pal disponible",selectedOwned:"Pals iniciales seleccionados",target:"Pal objetivo",maxDepth:"Generaciones máximas",find:"Buscar rutas",shortest:"Menos generaciones",practical:"Ruta práctica recomendada",sameRoute:"Ambas clasificaciones eligieron la misma ruta.",noPath:"No se encontró una ruta verificada dentro de estos límites.",chooseOwned:"Agrega al menos dos Pals iniciales.",step:"Paso de crianza",generation:"Generación",score:"Puntuación práctica",assumptions:"Límite de la puntuación",assumptionBody:"Solo se usan combinaciones verificadas. No se estiman dificultad de captura, herencia pasiva, IV, huevos, pasteles ni tiempo.",weights:"Pesos prácticos",generations:"Generaciones",uniqueOwned:"Pals iniciales distintos",genderConstraints:"Restricciones de sexo",specialSteps:"Combinaciones condicionales",repeatedOwnedUses:"Reutilización de Pals iniciales",evaluated:"Rutas candidatas comprobadas",truncated:"Se alcanzó el límite de candidatos. Reduce generaciones o Pals iniciales.",remove:"Quitar",reset:"Restablecer",directOwned:"Ya disponible",parent:"Progenitores",child:"Resultado",shareNote:"Las selecciones se procesan en este navegador y las URL compartidas solo usan identificadores públicos."},
  "pt-BR":{title:"Rota prática de cruzamento",intro:"Comece pelos Pals que você tem e compare a rota de menos gerações com uma rota prática ponderada.",owned:"Pals iniciais disponíveis",addOwned:"Adicionar Pal disponível",selectedOwned:"Pals iniciais selecionados",target:"Pal alvo",maxDepth:"Máximo de gerações",find:"Buscar rotas",shortest:"Menos gerações",practical:"Rota prática recomendada",sameRoute:"As duas classificações escolheram a mesma rota.",noPath:"Nenhuma rota verificada foi encontrada nesses limites.",chooseOwned:"Adicione pelo menos dois Pals iniciais.",step:"Etapa de cruzamento",generation:"Geração",score:"Pontuação prática",assumptions:"Limite da pontuação",assumptionBody:"Só são usadas combinações verificadas. Dificuldade de captura, herança de passivas, IV, ovos, bolos e tempo não são estimados.",weights:"Pesos práticos",generations:"Gerações",uniqueOwned:"Pals iniciais distintos",genderConstraints:"Restrições de sexo",specialSteps:"Combinações condicionais",repeatedOwnedUses:"Reutilização de Pals iniciais",evaluated:"Rotas candidatas verificadas",truncated:"O limite de candidatos foi atingido. Reduza gerações ou Pals iniciais.",remove:"Remover",reset:"Redefinir",directOwned:"Já disponível",parent:"Pais",child:"Resultado",shareNote:"As seleções ficam neste navegador e URLs compartilhadas usam apenas slugs públicos dos Pals."},
  "ru-RU":{title:"Практический путь разведения",intro:"Начните с имеющихся Палов и сравните путь с минимумом поколений с взвешенным практическим путём.",owned:"Имеющиеся стартовые Палы",addOwned:"Добавить имеющегося Пала",selectedOwned:"Выбранные стартовые Палы",target:"Целевой Пал",maxDepth:"Максимум поколений",find:"Найти пути",shortest:"Минимум поколений",practical:"Рекомендуемый практический путь",sameRoute:"Оба рейтинга выбрали один путь.",noPath:"В этих пределах проверенный путь не найден.",chooseOwned:"Добавьте хотя бы двух стартовых Палов.",step:"Шаг разведения",generation:"Поколение",score:"Практический балл",assumptions:"Границы оценки",assumptionBody:"Используются только проверенные комбинации. Сложность поимки, наследование пассивов, IV, яйца, торты и время не оцениваются.",weights:"Практические веса",generations:"Поколения",uniqueOwned:"Уникальные стартовые Палы",genderConstraints:"Ограничения пола",specialSteps:"Условные комбинации",repeatedOwnedUses:"Повторное использование стартовых Палов",evaluated:"Проверено путей-кандидатов",truncated:"Достигнут лимит кандидатов. Уменьшите поколения или число стартовых Палов.",remove:"Убрать",reset:"Сбросить",directOwned:"Уже имеется",parent:"Родители",child:"Результат",shareNote:"Выбор обрабатывается только в браузере, а общие URL используют лишь публичные идентификаторы Палов."},
  "id-ID":{title:"Jalur pembiakan praktis",intro:"Mulai dari Pal yang dimiliki dan bandingkan jalur generasi tersedikit dengan jalur praktis berbobot.",owned:"Pal awal yang dimiliki",addOwned:"Tambah Pal yang dimiliki",selectedOwned:"Pal awal terpilih",target:"Pal target",maxDepth:"Generasi maksimum",find:"Cari jalur",shortest:"Generasi tersedikit",practical:"Jalur praktis yang disarankan",sameRoute:"Kedua peringkat memilih jalur yang sama.",noPath:"Tidak ada jalur terverifikasi dalam batas ini.",chooseOwned:"Tambahkan setidaknya dua Pal awal.",step:"Tahap pembiakan",generation:"Generasi",score:"Skor praktis",assumptions:"Batas penilaian",assumptionBody:"Hanya kombinasi terverifikasi yang digunakan. Kesulitan menangkap, pewarisan pasif, IV, telur, kue, dan waktu tidak diperkirakan.",weights:"Bobot praktis",generations:"Generasi",uniqueOwned:"Pal awal unik",genderConstraints:"Batasan gender",specialSteps:"Kombinasi bersyarat",repeatedOwnedUses:"Penggunaan ulang Pal awal",evaluated:"Jalur kandidat diperiksa",truncated:"Batas kandidat tercapai. Kurangi generasi atau Pal awal.",remove:"Hapus",reset:"Atur ulang",directOwned:"Sudah dimiliki",parent:"Induk",child:"Hasil",shareNote:"Pilihan diproses hanya di browser dan URL bersama hanya memakai slug Pal publik."},
  "th-TH":{title:"เส้นทางผสมพันธุ์แบบใช้งานจริง",intro:"เริ่มจากพาลที่มี แล้วเปรียบเทียบเส้นทางที่ใช้รุ่นน้อยที่สุดกับเส้นทางใช้งานจริงแบบถ่วงน้ำหนัก",owned:"พาลเริ่มต้นที่มี",addOwned:"เพิ่มพาลที่มี",selectedOwned:"พาลเริ่มต้นที่เลือก",target:"พาลเป้าหมาย",maxDepth:"จำนวนรุ่นสูงสุด",find:"ค้นหาเส้นทาง",shortest:"รุ่นน้อยที่สุด",practical:"เส้นทางใช้งานจริงที่แนะนำ",sameRoute:"การจัดอันดับทั้งสองเลือกเส้นทางเดียวกัน",noPath:"ไม่พบเส้นทางที่ตรวจสอบแล้วภายในข้อจำกัดนี้",chooseOwned:"เพิ่มพาลเริ่มต้นอย่างน้อยสองชนิด",step:"ขั้นตอนผสมพันธุ์",generation:"รุ่น",score:"คะแนนใช้งานจริง",assumptions:"ขอบเขตการให้คะแนน",assumptionBody:"ใช้เฉพาะชุดผสมที่ตรวจสอบแล้ว ไม่ประมาณความยากในการจับ การสืบทอดพาสซีฟ IV จำนวนไข่ เค้ก หรือเวลา",weights:"น้ำหนักใช้งานจริง",generations:"จำนวนรุ่น",uniqueOwned:"พาลเริ่มต้นไม่ซ้ำ",genderConstraints:"ข้อจำกัดเพศ",specialSteps:"ชุดผสมมีเงื่อนไข",repeatedOwnedUses:"การใช้พาลเริ่มต้นซ้ำ",evaluated:"เส้นทางตัวเลือกที่ตรวจสอบ",truncated:"ถึงขีดจำกัดตัวเลือกแล้ว โปรดลดจำนวนรุ่นหรือพาลเริ่มต้น",remove:"นำออก",reset:"รีเซ็ต",directOwned:"มีอยู่แล้ว",parent:"พ่อแม่",child:"ผลลัพธ์",shareNote:"ตัวเลือกจะประมวลผลในเบราว์เซอร์นี้เท่านั้น และ URL ที่แชร์ใช้เฉพาะ slug พาลสาธารณะ"},
  "tr-TR":{title:"Pratik çiftleştirme yolu",intro:"Sahip olduğun Pallarla başla; en az nesilli yolu ağırlıklı pratik yolla karşılaştır.",owned:"Sahip olunan başlangıç Palları",addOwned:"Sahip olunan Pal ekle",selectedOwned:"Seçili başlangıç Palları",target:"Hedef Pal",maxDepth:"Azami nesil",find:"Yolları bul",shortest:"En az nesil",practical:"Önerilen pratik yol",sameRoute:"İki sıralama da aynı yolu seçti.",noPath:"Bu sınırlar içinde doğrulanmış yol bulunamadı.",chooseOwned:"En az iki başlangıç Palı ekle.",step:"Çiftleştirme adımı",generation:"Nesil",score:"Pratik puan",assumptions:"Puanlama sınırı",assumptionBody:"Yalnızca doğrulanmış kombinasyonlar kullanılır. Yakalama zorluğu, pasif aktarımı, IV, yumurta, pasta ve süre tahmin edilmez.",weights:"Pratik ağırlıklar",generations:"Nesiller",uniqueOwned:"Benzersiz başlangıç Palları",genderConstraints:"Cinsiyet kısıtları",specialSteps:"Koşullu kombinasyonlar",repeatedOwnedUses:"Başlangıç Palını yeniden kullanma",evaluated:"Kontrol edilen aday yollar",truncated:"Aday sınırına ulaşıldı. Nesli veya başlangıç Palı sayısını azalt.",remove:"Kaldır",reset:"Sıfırla",directOwned:"Zaten sahip",parent:"Ebeveynler",child:"Sonuç",shareNote:"Seçimler yalnızca tarayıcıda işlenir ve paylaşılan URL’lerde sadece herkese açık Pal slugları kullanılır."},
  "vi-VN":{title:"Lộ trình phối giống thực tế",intro:"Bắt đầu từ Pal đang có và so sánh lộ trình ít thế hệ nhất với lộ trình thực tế có trọng số.",owned:"Pal khởi đầu đang có",addOwned:"Thêm Pal đang có",selectedOwned:"Pal khởi đầu đã chọn",target:"Pal mục tiêu",maxDepth:"Số thế hệ tối đa",find:"Tìm lộ trình",shortest:"Ít thế hệ nhất",practical:"Lộ trình thực tế đề xuất",sameRoute:"Cả hai cách xếp hạng chọn cùng một lộ trình.",noPath:"Không tìm thấy lộ trình đã xác minh trong giới hạn này.",chooseOwned:"Hãy thêm ít nhất hai Pal khởi đầu.",step:"Bước phối giống",generation:"Thế hệ",score:"Điểm thực tế",assumptions:"Phạm vi chấm điểm",assumptionBody:"Chỉ dùng tổ hợp đã xác minh. Không ước tính độ khó bắt, xác suất truyền nội tại, IV, số trứng, bánh hay thời gian.",weights:"Trọng số thực tế",generations:"Số thế hệ",uniqueOwned:"Pal khởi đầu khác nhau",genderConstraints:"Ràng buộc giới tính",specialSteps:"Tổ hợp có điều kiện",repeatedOwnedUses:"Dùng lại Pal khởi đầu",evaluated:"Lộ trình ứng viên đã kiểm tra",truncated:"Đã đạt giới hạn ứng viên. Hãy giảm số thế hệ hoặc Pal khởi đầu.",remove:"Xóa",reset:"Đặt lại",directOwned:"Đã sở hữu",parent:"Bố mẹ",child:"Kết quả",shareNote:"Lựa chọn chỉ được xử lý trong trình duyệt và URL chia sẻ chỉ dùng slug Pal công khai."},
  "pl-PL":{title:"Praktyczna ścieżka hodowli",intro:"Zacznij od posiadanych Pali i porównaj ścieżkę z najmniejszą liczbą pokoleń ze ścieżką praktyczną z wagami.",owned:"Posiadane Pale startowe",addOwned:"Dodaj posiadanego Pala",selectedOwned:"Wybrane Pale startowe",target:"Pal docelowy",maxDepth:"Maksymalna liczba pokoleń",find:"Znajdź ścieżki",shortest:"Najmniej pokoleń",practical:"Zalecana ścieżka praktyczna",sameRoute:"Oba rankingi wybrały tę samą ścieżkę.",noPath:"W tych granicach nie znaleziono zweryfikowanej ścieżki.",chooseOwned:"Dodaj co najmniej dwa Pale startowe.",step:"Etap hodowli",generation:"Pokolenie",score:"Wynik praktyczny",assumptions:"Zakres oceny",assumptionBody:"Używane są tylko zweryfikowane kombinacje. Trudność schwytania, dziedziczenie pasywów, IV, jaja, ciasta i czas nie są szacowane.",weights:"Wagi praktyczne",generations:"Pokolenia",uniqueOwned:"Unikalne Pale startowe",genderConstraints:"Ograniczenia płci",specialSteps:"Kombinacje warunkowe",repeatedOwnedUses:"Ponowne użycie Pali startowych",evaluated:"Sprawdzone ścieżki kandydujące",truncated:"Osiągnięto limit kandydatów. Zmniejsz liczbę pokoleń lub Pali startowych.",remove:"Usuń",reset:"Resetuj",directOwned:"Już posiadany",parent:"Rodzice",child:"Wynik",shareNote:"Wybory są przetwarzane tylko w przeglądarce, a udostępniane URL używają wyłącznie publicznych slugów Pali."}
};

export const breedingPathCopyProvenance=Object.fromEntries(Object.keys(en).map(key=>[key,"gpt"])) as Record<keyof BreedingPathCopy,"gpt">;

export type BreedingPathRuntimeCopy={searching:string;cancel:string;cancelled:string};
export const breedingPathRuntimeCopy:Record<Locale,BreedingPathRuntimeCopy>={
  "en-US":{searching:"Searching verified paths…",cancel:"Cancel search",cancelled:"Search cancelled."},
  "ko-KR":{searching:"검증된 경로 검색 중…",cancel:"검색 취소",cancelled:"검색을 취소했습니다."},
  "ja-JP":{searching:"検証済み経路を検索中…",cancel:"検索をキャンセル",cancelled:"検索をキャンセルしました。"},
  "zh-CN":{searching:"正在搜索已验证路线…",cancel:"取消搜索",cancelled:"搜索已取消。"},
  "zh-TW":{searching:"正在搜尋已驗證路線…",cancel:"取消搜尋",cancelled:"搜尋已取消。"},
  "fr-FR":{searching:"Recherche des parcours vérifiés…",cancel:"Annuler la recherche",cancelled:"Recherche annulée."},
  "it-IT":{searching:"Ricerca dei percorsi verificati…",cancel:"Annulla ricerca",cancelled:"Ricerca annullata."},
  "de-DE":{searching:"Geprüfte Wege werden gesucht…",cancel:"Suche abbrechen",cancelled:"Suche abgebrochen."},
  "es-ES":{searching:"Buscando rutas verificadas…",cancel:"Cancelar búsqueda",cancelled:"Búsqueda cancelada."},
  "pt-BR":{searching:"Buscando rotas verificadas…",cancel:"Cancelar busca",cancelled:"Busca cancelada."},
  "ru-RU":{searching:"Поиск проверенных путей…",cancel:"Отменить поиск",cancelled:"Поиск отменён."},
  "id-ID":{searching:"Mencari jalur terverifikasi…",cancel:"Batalkan pencarian",cancelled:"Pencarian dibatalkan."},
  "es-419":{searching:"Buscando rutas verificadas…",cancel:"Cancelar búsqueda",cancelled:"Búsqueda cancelada."},
  "th-TH":{searching:"กำลังค้นหาเส้นทางที่ตรวจสอบแล้ว…",cancel:"ยกเลิกการค้นหา",cancelled:"ยกเลิกการค้นหาแล้ว"},
  "tr-TR":{searching:"Doğrulanmış yollar aranıyor…",cancel:"Aramayı iptal et",cancelled:"Arama iptal edildi."},
  "vi-VN":{searching:"Đang tìm lộ trình đã xác minh…",cancel:"Hủy tìm kiếm",cancelled:"Đã hủy tìm kiếm."},
  "pl-PL":{searching:"Wyszukiwanie zweryfikowanych ścieżek…",cancel:"Anuluj wyszukiwanie",cancelled:"Wyszukiwanie anulowane."},
};
export const breedingPathRuntimeCopyProvenance:Record<keyof BreedingPathRuntimeCopy,"gpt">={searching:"gpt",cancel:"gpt",cancelled:"gpt"};
