import type { Locale } from "./config";

export type DungeonCopy={title:string;intro:string;kind:string;fixed:string;rotating:string;entrances:string;possiblePals:string;possibleItems:string;resources:string;rewardSources:string;levelRange:string;quantity:string;openMap:string;details:string;noEntrance:string;noData:string;probabilityNotice:string;rotationNotice:string;cooldown:string;minutes:string;floor:string;special:string;roleNormal:string;roleBoss:string;roleMidboss:string;roleMonster:string;roleAquatic:string;rewardPalCage:string;rewardPal:string;rewardChest:string;rewardEgg:string;rewardLotus:string;rewardSkillFruit:string;rewardCaveMushroom:string;rewardMushroom:string;rewardElixir:string;rewardSalvage:string;loadError:string};

export const dungeonCopy:Record<Locale,DungeonCopy>={
  "en-US":{title:"Dungeons",intro:"Browse verified dungeon entrances, possible Pals, resources, items, and reward sources extracted from the game files.",kind:"Dungeon type",fixed:"Fixed dungeon",rotating:"Rotating dungeon",entrances:"Entrances",possiblePals:"Possible Pals",possibleItems:"Possible items",resources:"Resources",rewardSources:"Reward sources",levelRange:"Level range",quantity:"Quantity",openMap:"Open on map",details:"View details",noEntrance:"No verified entrance is available for this dungeon.",noData:"No verified data is available for this section.",probabilityNotice:"These are possible pool contents. Exact final probabilities are not shown until the multi-stage lottery is verified.",rotationNotice:"Rotation candidates are not a live availability indicator.",cooldown:"Boss respawn cooldown",minutes:"minutes",floor:"Floor pickups",special:"Special pickups",roleNormal:"Normal encounters",roleBoss:"Bosses",roleMidboss:"Mid-bosses",roleMonster:"Special monsters",roleAquatic:"Aquatic Pals",rewardPalCage:"Pal cage",rewardPal:"Pal encounter",rewardChest:"Treasure chest",rewardEgg:"Pal Egg",rewardLotus:"Lotus",rewardSkillFruit:"Skill Fruit",rewardCaveMushroom:"Cave Mushroom",rewardMushroom:"Mushroom",rewardElixir:"Elixir",rewardSalvage:"Salvage",loadError:"Dungeon data could not be loaded."},
  "ko-KR":{title:"던전",intro:"게임 파일에서 확인된 던전 입구와 등장 가능한 팰, 자원, 아이템, 보상 정보를 살펴보세요.",kind:"던전 유형",fixed:"고정 던전",rotating:"로테이션 던전",entrances:"입구",possiblePals:"등장 가능한 팰",possibleItems:"획득 가능한 아이템",resources:"자원",rewardSources:"보상 종류",levelRange:"레벨 범위",quantity:"수량",openMap:"지도에서 보기",details:"상세 보기",noEntrance:"이 던전과 연결된 입구가 아직 확인되지 않았습니다.",noData:"이 항목에는 확인된 데이터가 없습니다.",probabilityNotice:"표시된 내용은 추첨 풀에서 나올 수 있는 후보입니다. 다단계 추첨 방식이 검증되기 전에는 최종 확률을 표시하지 않습니다.",rotationNotice:"로테이션 입구 후보는 현재 활성 상태를 뜻하지 않습니다.",cooldown:"보스 재등장 대기 시간",minutes:"분",floor:"바닥 아이템",special:"특수 아이템",roleNormal:"일반 등장",roleBoss:"보스",roleMidboss:"중간 보스",roleMonster:"특수 몬스터",roleAquatic:"수중 팰",rewardPalCage:"팰 우리",rewardPal:"팰 등장",rewardChest:"보물 상자",rewardEgg:"팰 알",rewardLotus:"연꽃",rewardSkillFruit:"스킬 열매",rewardCaveMushroom:"동굴 버섯",rewardMushroom:"버섯",rewardElixir:"비약",rewardSalvage:"잔해",loadError:"던전 데이터를 불러오지 못했습니다."},
  "ja-JP":{title:"ダンジョン",intro:"ゲームファイルで確認された入口、出現する可能性のあるパル、資源、アイテム、報酬を確認できます。",kind:"ダンジョンの種類",fixed:"固定ダンジョン",rotating:"ローテーションダンジョン",entrances:"入口",possiblePals:"出現する可能性のあるパル",possibleItems:"入手可能なアイテム",resources:"資源",rewardSources:"報酬の種類",levelRange:"レベル範囲",quantity:"数量",openMap:"マップで開く",details:"詳細を見る",noEntrance:"このダンジョンに結び付く確認済みの入口はありません。",noData:"この項目には確認済みデータがありません。",probabilityNotice:"表示内容は抽選候補です。多段階抽選が検証されるまで最終確率は表示しません。",rotationNotice:"ローテーション候補は現在の開放状態を示すものではありません。",cooldown:"ボス再出現までの時間",minutes:"分",floor:"床のアイテム",special:"特殊アイテム",roleNormal:"通常出現",roleBoss:"ボス",roleMidboss:"中ボス",roleMonster:"特殊モンスター",roleAquatic:"水生パル",rewardPalCage:"パルの檻",rewardPal:"パル出現",rewardChest:"宝箱",rewardEgg:"パルのタマゴ",rewardLotus:"ハス",rewardSkillFruit:"スキルフルーツ",rewardCaveMushroom:"洞窟キノコ",rewardMushroom:"キノコ",rewardElixir:"秘薬",rewardSalvage:"残骸",loadError:"ダンジョンデータを読み込めませんでした。"},
  "zh-CN":{title:"地下城",intro:"查看从游戏文件验证的地下城入口、可能出现的帕鲁、资源、物品和奖励。",kind:"地下城类型",fixed:"固定地下城",rotating:"轮换地下城",entrances:"入口",possiblePals:"可能出现的帕鲁",possibleItems:"可能获得的物品",resources:"资源",rewardSources:"奖励类型",levelRange:"等级范围",quantity:"数量",openMap:"在地图中打开",details:"查看详情",noEntrance:"尚无与此地下城关联的已验证入口。",noData:"此部分暂无已验证数据。",probabilityNotice:"这些是奖池中的可能内容。在多阶段抽取机制验证前不显示最终概率。",rotationNotice:"轮换入口候选不代表当前开放状态。",cooldown:"首领重生等待时间",minutes:"分钟",floor:"地面物品",special:"特殊物品",roleNormal:"普通遭遇",roleBoss:"首领",roleMidboss:"中型首领",roleMonster:"特殊怪物",roleAquatic:"水生帕鲁",rewardPalCage:"帕鲁笼",rewardPal:"帕鲁遭遇",rewardChest:"宝箱",rewardEgg:"帕鲁蛋",rewardLotus:"莲花",rewardSkillFruit:"技能果实",rewardCaveMushroom:"洞穴蘑菇",rewardMushroom:"蘑菇",rewardElixir:"秘药",rewardSalvage:"废料",loadError:"无法加载地下城数据。"},
  "zh-TW":{title:"地下城",intro:"查看從遊戲檔案驗證的地下城入口、可能出現的帕魯、資源、物品與獎勵。",kind:"地下城類型",fixed:"固定地下城",rotating:"輪替地下城",entrances:"入口",possiblePals:"可能出現的帕魯",possibleItems:"可能取得的物品",resources:"資源",rewardSources:"獎勵類型",levelRange:"等級範圍",quantity:"數量",openMap:"在地圖中開啟",details:"查看詳情",noEntrance:"尚無與此地下城連結的已驗證入口。",noData:"此部分暫無已驗證資料。",probabilityNotice:"這些是獎池中的可能內容。在多階段抽取機制驗證前不顯示最終機率。",rotationNotice:"輪替入口候選不代表目前開放狀態。",cooldown:"首領重生等待時間",minutes:"分鐘",floor:"地面物品",special:"特殊物品",roleNormal:"一般遭遇",roleBoss:"首領",roleMidboss:"中型首領",roleMonster:"特殊怪物",roleAquatic:"水生帕魯",rewardPalCage:"帕魯籠",rewardPal:"帕魯遭遇",rewardChest:"寶箱",rewardEgg:"帕魯蛋",rewardLotus:"蓮花",rewardSkillFruit:"技能果實",rewardCaveMushroom:"洞穴蘑菇",rewardMushroom:"蘑菇",rewardElixir:"秘藥",rewardSalvage:"廢料",loadError:"無法載入地下城資料。"},
  "fr-FR":{title:"Donjons",intro:"Consultez les entrées, Pals possibles, ressources, objets et récompenses vérifiés dans les fichiers du jeu.",kind:"Type de donjon",fixed:"Donjon fixe",rotating:"Donjon en rotation",entrances:"Entrées",possiblePals:"Pals possibles",possibleItems:"Objets possibles",resources:"Ressources",rewardSources:"Sources de récompense",levelRange:"Plage de niveaux",quantity:"Quantité",openMap:"Ouvrir sur la carte",details:"Voir les détails",noEntrance:"Aucune entrée vérifiée n’est associée à ce donjon.",noData:"Aucune donnée vérifiée n’est disponible pour cette section.",probabilityNotice:"Ces éléments sont des résultats possibles. Les probabilités finales restent masquées tant que le tirage à plusieurs étapes n’est pas vérifié.",rotationNotice:"Les entrées candidates à la rotation n’indiquent pas leur disponibilité actuelle.",cooldown:"Délai de réapparition du boss",minutes:"minutes",floor:"Objets au sol",special:"Objets spéciaux",roleNormal:"Rencontres normales",roleBoss:"Boss",roleMidboss:"Mini-boss",roleMonster:"Monstres spéciaux",roleAquatic:"Pals aquatiques",rewardPalCage:"Cage de Pal",rewardPal:"Rencontre de Pal",rewardChest:"Coffre au trésor",rewardEgg:"Œuf de Pal",rewardLotus:"Lotus",rewardSkillFruit:"Fruit de compétence",rewardCaveMushroom:"Champignon des cavernes",rewardMushroom:"Champignon",rewardElixir:"Élixir",rewardSalvage:"Débris",loadError:"Impossible de charger les données des donjons."},
  "it-IT":{title:"Dungeon",intro:"Consulta ingressi, Pal possibili, risorse, oggetti e ricompense verificati nei file di gioco.",kind:"Tipo di dungeon",fixed:"Dungeon fisso",rotating:"Dungeon a rotazione",entrances:"Ingressi",possiblePals:"Pal possibili",possibleItems:"Oggetti possibili",resources:"Risorse",rewardSources:"Fonti ricompensa",levelRange:"Intervallo livelli",quantity:"Quantità",openMap:"Apri sulla mappa",details:"Vedi dettagli",noEntrance:"Nessun ingresso verificato è associato a questo dungeon.",noData:"Non sono disponibili dati verificati per questa sezione.",probabilityNotice:"Questi sono contenuti possibili del pool. Le probabilità finali non vengono mostrate finché l’estrazione a più fasi non è verificata.",rotationNotice:"Gli ingressi candidati alla rotazione non indicano la disponibilità attuale.",cooldown:"Attesa ricomparsa boss",minutes:"minuti",floor:"Oggetti a terra",special:"Oggetti speciali",roleNormal:"Incontri normali",roleBoss:"Boss",roleMidboss:"Mini boss",roleMonster:"Mostri speciali",roleAquatic:"Pal acquatici",rewardPalCage:"Gabbia Pal",rewardPal:"Incontro Pal",rewardChest:"Forziere",rewardEgg:"Uovo di Pal",rewardLotus:"Loto",rewardSkillFruit:"Frutto abilità",rewardCaveMushroom:"Fungo delle caverne",rewardMushroom:"Fungo",rewardElixir:"Elisir",rewardSalvage:"Rottami",loadError:"Impossibile caricare i dati dei dungeon."},
  "de-DE":{title:"Dungeons",intro:"Durchsuche verifizierte Eingänge, mögliche Pals, Ressourcen, Gegenstände und Belohnungen aus den Spieldateien.",kind:"Dungeon-Typ",fixed:"Fester Dungeon",rotating:"Rotierender Dungeon",entrances:"Eingänge",possiblePals:"Mögliche Pals",possibleItems:"Mögliche Gegenstände",resources:"Ressourcen",rewardSources:"Belohnungsquellen",levelRange:"Stufenbereich",quantity:"Menge",openMap:"Auf Karte öffnen",details:"Details ansehen",noEntrance:"Für diesen Dungeon ist kein verifizierter Eingang verfügbar.",noData:"Für diesen Abschnitt sind keine verifizierten Daten verfügbar.",probabilityNotice:"Dies sind mögliche Pool-Inhalte. Endgültige Wahrscheinlichkeiten werden erst nach Prüfung der mehrstufigen Auswahl angezeigt.",rotationNotice:"Rotationskandidaten zeigen nicht an, ob ein Eingang aktuell geöffnet ist.",cooldown:"Wartezeit bis zur Boss-Rückkehr",minutes:"Minuten",floor:"Bodenfunde",special:"Spezialfunde",roleNormal:"Normale Begegnungen",roleBoss:"Bosse",roleMidboss:"Zwischenbosse",roleMonster:"Spezialmonster",roleAquatic:"Wasser-Pals",rewardPalCage:"Pal-Käfig",rewardPal:"Pal-Begegnung",rewardChest:"Schatztruhe",rewardEgg:"Pal-Ei",rewardLotus:"Lotus",rewardSkillFruit:"Fähigkeitsfrucht",rewardCaveMushroom:"Höhlenpilz",rewardMushroom:"Pilz",rewardElixir:"Elixier",rewardSalvage:"Schrott",loadError:"Dungeon-Daten konnten nicht geladen werden."},
  "es-ES":{title:"Mazmorras",intro:"Consulta entradas, Pals posibles, recursos, objetos y recompensas verificados en los archivos del juego.",kind:"Tipo de mazmorra",fixed:"Mazmorra fija",rotating:"Mazmorra rotatoria",entrances:"Entradas",possiblePals:"Pals posibles",possibleItems:"Objetos posibles",resources:"Recursos",rewardSources:"Fuentes de recompensa",levelRange:"Rango de nivel",quantity:"Cantidad",openMap:"Abrir en el mapa",details:"Ver detalles",noEntrance:"No hay ninguna entrada verificada asociada a esta mazmorra.",noData:"No hay datos verificados para esta sección.",probabilityNotice:"Estos son posibles contenidos del lote. No se muestran probabilidades finales hasta verificar el sorteo por etapas.",rotationNotice:"Las entradas candidatas a rotación no indican disponibilidad actual.",cooldown:"Espera de reaparición del jefe",minutes:"minutos",floor:"Objetos del suelo",special:"Objetos especiales",roleNormal:"Encuentros normales",roleBoss:"Jefes",roleMidboss:"Minijefes",roleMonster:"Monstruos especiales",roleAquatic:"Pals acuáticos",rewardPalCage:"Jaula de Pal",rewardPal:"Encuentro de Pal",rewardChest:"Cofre del tesoro",rewardEgg:"Huevo de Pal",rewardLotus:"Loto",rewardSkillFruit:"Fruto de habilidad",rewardCaveMushroom:"Seta de cueva",rewardMushroom:"Seta",rewardElixir:"Elixir",rewardSalvage:"Restos",loadError:"No se pudieron cargar los datos de las mazmorras."},
  "pt-BR":{title:"Masmorras",intro:"Consulte entradas, Pals possíveis, recursos, itens e recompensas verificados nos arquivos do jogo.",kind:"Tipo de masmorra",fixed:"Masmorra fixa",rotating:"Masmorra rotativa",entrances:"Entradas",possiblePals:"Pals possíveis",possibleItems:"Itens possíveis",resources:"Recursos",rewardSources:"Fontes de recompensa",levelRange:"Faixa de nível",quantity:"Quantidade",openMap:"Abrir no mapa",details:"Ver detalhes",noEntrance:"Nenhuma entrada verificada está associada a esta masmorra.",noData:"Não há dados verificados para esta seção.",probabilityNotice:"Estes são conteúdos possíveis do conjunto. As probabilidades finais só serão exibidas após a verificação do sorteio em várias etapas.",rotationNotice:"Entradas candidatas à rotação não indicam disponibilidade atual.",cooldown:"Espera para reaparecimento do chefe",minutes:"minutos",floor:"Itens no chão",special:"Itens especiais",roleNormal:"Encontros normais",roleBoss:"Chefes",roleMidboss:"Minichefes",roleMonster:"Monstros especiais",roleAquatic:"Pals aquáticos",rewardPalCage:"Jaula de Pal",rewardPal:"Encontro de Pal",rewardChest:"Baú do tesouro",rewardEgg:"Ovo de Pal",rewardLotus:"Lótus",rewardSkillFruit:"Fruta de habilidade",rewardCaveMushroom:"Cogumelo da caverna",rewardMushroom:"Cogumelo",rewardElixir:"Elixir",rewardSalvage:"Sucata",loadError:"Não foi possível carregar os dados das masmorras."},
  "ru-RU":{title:"Подземелья",intro:"Просматривайте проверенные по файлам игры входы, возможных Палов, ресурсы, предметы и награды.",kind:"Тип подземелья",fixed:"Постоянное подземелье",rotating:"Ротирующееся подземелье",entrances:"Входы",possiblePals:"Возможные Палы",possibleItems:"Возможные предметы",resources:"Ресурсы",rewardSources:"Источники наград",levelRange:"Диапазон уровней",quantity:"Количество",openMap:"Открыть на карте",details:"Подробнее",noEntrance:"Для этого подземелья нет подтверждённого входа.",noData:"Для этого раздела нет подтверждённых данных.",probabilityNotice:"Это возможное содержимое пула. Итоговые вероятности не показываются до проверки многоэтапного выбора.",rotationNotice:"Кандидаты ротации не показывают, открыт ли вход сейчас.",cooldown:"Ожидание возрождения босса",minutes:"минут",floor:"Предметы на полу",special:"Особые предметы",roleNormal:"Обычные встречи",roleBoss:"Боссы",roleMidboss:"Мини-боссы",roleMonster:"Особые монстры",roleAquatic:"Водные Палы",rewardPalCage:"Клетка с Палом",rewardPal:"Встреча с Палом",rewardChest:"Сундук с сокровищами",rewardEgg:"Яйцо Пала",rewardLotus:"Лотос",rewardSkillFruit:"Плод навыка",rewardCaveMushroom:"Пещерный гриб",rewardMushroom:"Гриб",rewardElixir:"Эликсир",rewardSalvage:"Обломки",loadError:"Не удалось загрузить данные подземелий."},
  "id-ID":{title:"Dungeon",intro:"Lihat pintu masuk, kemungkinan Pal, sumber daya, item, dan hadiah yang terverifikasi dari file game.",kind:"Jenis dungeon",fixed:"Dungeon tetap",rotating:"Dungeon rotasi",entrances:"Pintu masuk",possiblePals:"Pal yang mungkin muncul",possibleItems:"Item yang mungkin diperoleh",resources:"Sumber daya",rewardSources:"Sumber hadiah",levelRange:"Rentang level",quantity:"Jumlah",openMap:"Buka di peta",details:"Lihat detail",noEntrance:"Belum ada pintu masuk terverifikasi yang terkait dengan dungeon ini.",noData:"Belum ada data terverifikasi untuk bagian ini.",probabilityNotice:"Ini adalah kemungkinan isi pool. Probabilitas akhir tidak ditampilkan sampai undian bertahap terverifikasi.",rotationNotice:"Kandidat pintu masuk rotasi bukan penanda ketersediaan saat ini.",cooldown:"Waktu tunggu kemunculan bos",minutes:"menit",floor:"Item di lantai",special:"Item khusus",roleNormal:"Pertemuan normal",roleBoss:"Bos",roleMidboss:"Bos menengah",roleMonster:"Monster khusus",roleAquatic:"Pal air",rewardPalCage:"Kandang Pal",rewardPal:"Pertemuan Pal",rewardChest:"Peti harta",rewardEgg:"Telur Pal",rewardLotus:"Lotus",rewardSkillFruit:"Buah Skill",rewardCaveMushroom:"Jamur Gua",rewardMushroom:"Jamur",rewardElixir:"Eliksir",rewardSalvage:"Rongsokan",loadError:"Data dungeon tidak dapat dimuat."},
  "es-419":{title:"Mazmorras",intro:"Consulta entradas, Pals posibles, recursos, objetos y recompensas verificados en los archivos del juego.",kind:"Tipo de mazmorra",fixed:"Mazmorra fija",rotating:"Mazmorra rotativa",entrances:"Entradas",possiblePals:"Pals posibles",possibleItems:"Objetos posibles",resources:"Recursos",rewardSources:"Fuentes de recompensa",levelRange:"Rango de nivel",quantity:"Cantidad",openMap:"Abrir en el mapa",details:"Ver detalles",noEntrance:"No hay una entrada verificada asociada a esta mazmorra.",noData:"No hay datos verificados para esta sección.",probabilityNotice:"Estos son posibles contenidos del lote. No se muestran probabilidades finales hasta verificar el sorteo por etapas.",rotationNotice:"Las entradas candidatas a rotación no indican disponibilidad actual.",cooldown:"Espera de reaparición del jefe",minutes:"minutos",floor:"Objetos del suelo",special:"Objetos especiales",roleNormal:"Encuentros normales",roleBoss:"Jefes",roleMidboss:"Minijefes",roleMonster:"Monstruos especiales",roleAquatic:"Pals acuáticos",rewardPalCage:"Jaula de Pal",rewardPal:"Encuentro de Pal",rewardChest:"Cofre del tesoro",rewardEgg:"Huevo de Pal",rewardLotus:"Loto",rewardSkillFruit:"Fruta de habilidad",rewardCaveMushroom:"Hongo de cueva",rewardMushroom:"Hongo",rewardElixir:"Elixir",rewardSalvage:"Restos",loadError:"No se pudieron cargar los datos de las mazmorras."},
  "th-TH":{title:"ดันเจียน",intro:"ดูทางเข้า พาล ทรัพยากร ไอเทม และรางวัลที่เป็นไปได้ซึ่งตรวจสอบจากไฟล์เกม",kind:"ประเภทดันเจียน",fixed:"ดันเจียนคงที่",rotating:"ดันเจียนหมุนเวียน",entrances:"ทางเข้า",possiblePals:"พาลที่อาจพบ",possibleItems:"ไอเทมที่อาจได้รับ",resources:"ทรัพยากร",rewardSources:"ประเภทรางวัล",levelRange:"ช่วงเลเวล",quantity:"จำนวน",openMap:"เปิดในแผนที่",details:"ดูรายละเอียด",noEntrance:"ยังไม่มีทางเข้าที่ตรวจสอบแล้วสำหรับดันเจียนนี้",noData:"ยังไม่มีข้อมูลที่ตรวจสอบแล้วสำหรับส่วนนี้",probabilityNotice:"รายการเหล่านี้เป็นผลลัพธ์ที่เป็นไปได้ ระบบจะไม่แสดงโอกาสสุดท้ายจนกว่าจะตรวจสอบการสุ่มหลายขั้นตอนแล้ว",rotationNotice:"ทางเข้าที่อยู่ในกลุ่มหมุนเวียนไม่ได้แสดงสถานะเปิดในขณะนี้",cooldown:"เวลารอบอสเกิดใหม่",minutes:"นาที",floor:"ไอเทมบนพื้น",special:"ไอเทมพิเศษ",roleNormal:"การเผชิญหน้าทั่วไป",roleBoss:"บอส",roleMidboss:"มินิบอส",roleMonster:"มอนสเตอร์พิเศษ",roleAquatic:"พาลน้ำ",rewardPalCage:"กรงพาล",rewardPal:"พบพาล",rewardChest:"หีบสมบัติ",rewardEgg:"ไข่พาล",rewardLotus:"ดอกบัว",rewardSkillFruit:"ผลสกิล",rewardCaveMushroom:"เห็ดถ้ำ",rewardMushroom:"เห็ด",rewardElixir:"ยาอายุวัฒนะ",rewardSalvage:"ซากวัสดุ",loadError:"ไม่สามารถโหลดข้อมูลดันเจียนได้"},
  "tr-TR":{title:"Zindanlar",intro:"Oyun dosyalarından doğrulanan girişleri, olası Palları, kaynakları, eşyaları ve ödülleri incele.",kind:"Zindan türü",fixed:"Sabit zindan",rotating:"Dönüşümlü zindan",entrances:"Girişler",possiblePals:"Olası Pallar",possibleItems:"Olası eşyalar",resources:"Kaynaklar",rewardSources:"Ödül kaynakları",levelRange:"Seviye aralığı",quantity:"Miktar",openMap:"Haritada aç",details:"Ayrıntıları gör",noEntrance:"Bu zindanla ilişkili doğrulanmış bir giriş yok.",noData:"Bu bölüm için doğrulanmış veri yok.",probabilityNotice:"Bunlar havuzdaki olası içeriklerdir. Çok aşamalı çekiliş doğrulanana kadar nihai olasılıklar gösterilmez.",rotationNotice:"Dönüşüm adayları girişin şu anda açık olduğunu göstermez.",cooldown:"Boss yeniden doğma süresi",minutes:"dakika",floor:"Yerdeki eşyalar",special:"Özel eşyalar",roleNormal:"Normal karşılaşmalar",roleBoss:"Bosslar",roleMidboss:"Ara bosslar",roleMonster:"Özel canavarlar",roleAquatic:"Su Pallar",rewardPalCage:"Pal kafesi",rewardPal:"Pal karşılaşması",rewardChest:"Hazine sandığı",rewardEgg:"Pal Yumurtası",rewardLotus:"Lotus",rewardSkillFruit:"Beceri Meyvesi",rewardCaveMushroom:"Mağara Mantarı",rewardMushroom:"Mantar",rewardElixir:"İksir",rewardSalvage:"Hurda",loadError:"Zindan verileri yüklenemedi."},
  "vi-VN":{title:"Hầm ngục",intro:"Xem lối vào, Pal, tài nguyên, vật phẩm và phần thưởng có thể xuất hiện đã được xác minh từ tệp trò chơi.",kind:"Loại hầm ngục",fixed:"Hầm ngục cố định",rotating:"Hầm ngục luân phiên",entrances:"Lối vào",possiblePals:"Pal có thể xuất hiện",possibleItems:"Vật phẩm có thể nhận",resources:"Tài nguyên",rewardSources:"Nguồn phần thưởng",levelRange:"Khoảng cấp",quantity:"Số lượng",openMap:"Mở trên bản đồ",details:"Xem chi tiết",noEntrance:"Chưa có lối vào đã xác minh liên kết với hầm ngục này.",noData:"Chưa có dữ liệu đã xác minh cho phần này.",probabilityNotice:"Đây là các nội dung có thể xuất hiện trong nhóm. Chưa hiển thị xác suất cuối cùng cho đến khi cơ chế quay nhiều bước được xác minh.",rotationNotice:"Lối vào thuộc nhóm luân phiên không cho biết trạng thái đang mở.",cooldown:"Thời gian boss xuất hiện lại",minutes:"phút",floor:"Vật phẩm trên sàn",special:"Vật phẩm đặc biệt",roleNormal:"Chạm trán thường",roleBoss:"Boss",roleMidboss:"Boss trung gian",roleMonster:"Quái vật đặc biệt",roleAquatic:"Pal thủy sinh",rewardPalCage:"Lồng Pal",rewardPal:"Chạm trán Pal",rewardChest:"Rương kho báu",rewardEgg:"Trứng Pal",rewardLotus:"Hoa sen",rewardSkillFruit:"Trái Kỹ Năng",rewardCaveMushroom:"Nấm Hang",rewardMushroom:"Nấm",rewardElixir:"Thuốc tiên",rewardSalvage:"Phế liệu",loadError:"Không thể tải dữ liệu hầm ngục."},
  "pl-PL":{title:"Lochy",intro:"Przeglądaj zweryfikowane w plikach gry wejścia, możliwe Pale, zasoby, przedmioty i nagrody.",kind:"Typ lochu",fixed:"Stały loch",rotating:"Rotacyjny loch",entrances:"Wejścia",possiblePals:"Możliwe Pale",possibleItems:"Możliwe przedmioty",resources:"Zasoby",rewardSources:"Źródła nagród",levelRange:"Zakres poziomów",quantity:"Ilość",openMap:"Otwórz na mapie",details:"Zobacz szczegóły",noEntrance:"Brak zweryfikowanego wejścia powiązanego z tym lochem.",noData:"Brak zweryfikowanych danych dla tej sekcji.",probabilityNotice:"To możliwa zawartość puli. Końcowe prawdopodobieństwa nie są pokazywane do czasu weryfikacji wieloetapowego losowania.",rotationNotice:"Kandydaci rotacji nie wskazują, czy wejście jest obecnie otwarte.",cooldown:"Czas odrodzenia bossa",minutes:"minut",floor:"Przedmioty na podłodze",special:"Przedmioty specjalne",roleNormal:"Zwykłe spotkania",roleBoss:"Bossowie",roleMidboss:"Minibossowie",roleMonster:"Specjalne potwory",roleAquatic:"Wodne Pale",rewardPalCage:"Klatka z Palem",rewardPal:"Spotkanie Pala",rewardChest:"Skrzynia skarbów",rewardEgg:"Jajo Pala",rewardLotus:"Lotos",rewardSkillFruit:"Owoc Umiejętności",rewardCaveMushroom:"Jaskiniowy grzyb",rewardMushroom:"Grzyb",rewardElixir:"Eliksir",rewardSalvage:"Złom",loadError:"Nie udało się wczytać danych lochów."}
};

export const dungeonSearchCopy:Record<Locale,string>={
  "en-US":"Search dungeons",
  "zh-CN":"搜索地下城",
  "zh-TW":"搜尋地下城",
  "ja-JP":"ダンジョンを検索",
  "fr-FR":"Rechercher des donjons",
  "it-IT":"Cerca dungeon",
  "de-DE":"Dungeons suchen",
  "es-ES":"Buscar mazmorras",
  "pt-BR":"Buscar masmorras",
  "ru-RU":"Поиск подземелий",
  "ko-KR":"던전 검색",
  "id-ID":"Cari dungeon",
  "es-419":"Buscar mazmorras",
  "th-TH":"ค้นหาดันเจียน",
  "tr-TR":"Zindan ara",
  "vi-VN":"Tìm hầm ngục",
  "pl-PL":"Szukaj lochów"
};

export const dungeonTranslationProvenance:Record<Locale,"gpt"|"reviewed">=Object.fromEntries(Object.keys(dungeonCopy).map(locale=>[locale,locale==="en-US"?"reviewed":"gpt"])) as Record<Locale,"gpt"|"reviewed">;
