import type {Locale} from "./config";

export type ElementCopy={title:string;intro:string;chartTitle:string;chartDescription:string;compareTitle:string;attacker:string;defender:string;strong:string;weak:string;neutral:string;strongAgainst:string;weakTo:string;matrixTitle:string;matrixDescription:string;relatedPals:string;relatedSkills:string;palsCount:string;skillsCount:string;numericUnavailable:string;dualUnavailable:string};
export const elementCopy:Record<Locale,ElementCopy>={
  "en-US":{title:"Element Matchups",intro:"Compare all nine Pal elements, see verified strengths and weaknesses, and find Pals and active skills for each element.",chartTitle:"Official matchup chart",chartDescription:"An arrow points from the attacking element to the element it is strong against.",compareTitle:"Compare elements",attacker:"Attacking element",defender:"Defending element",strong:"Strong",weak:"Weak",neutral:"No verified advantage",strongAgainst:"Strong against",weakTo:"Weak to",matrixTitle:"Complete matchup table",matrixDescription:"Rows are attacking elements and columns are defending elements.",relatedPals:"Related Pals",relatedSkills:"Related active skills",palsCount:"Pals",skillsCount:"active skills",numericUnavailable:"Exact damage multipliers are not shown because the numeric values have not been verified.",dualUnavailable:"For dual-element Pals, the exact rule for combining matchups is not shown because it has not been verified."},
  "ko-KR":{title:"속성 상성",intro:"9가지 팰 속성의 강점과 약점을 비교하고, 속성별 팰과 액티브 스킬을 확인하세요.",chartTitle:"공식 상성도",chartDescription:"화살표는 공격 속성에서 그 공격이 유리한 방어 속성을 향합니다.",compareTitle:"속성 비교",attacker:"공격 속성",defender:"방어 속성",strong:"유리",weak:"불리",neutral:"확인된 상성 없음",strongAgainst:"유리한 속성",weakTo:"불리한 속성",matrixTitle:"전체 상성표",matrixDescription:"행은 공격 속성, 열은 방어 속성입니다.",relatedPals:"관련 팰",relatedSkills:"관련 액티브 스킬",palsCount:"팰",skillsCount:"액티브 스킬",numericUnavailable:"수치가 검증되지 않아 정확한 피해 배율은 표시하지 않습니다.",dualUnavailable:"복합 속성 팰의 상성 결합 규칙은 검증되지 않아 표시하지 않습니다."},
  "ja-JP":{title:"属性相性",intro:"9種類の属性の強みと弱みを比較し、属性ごとのパルとアクティブスキルを確認できます。",chartTitle:"公式相性図",chartDescription:"矢印は攻撃属性から、その攻撃が有利な防御属性へ向かいます。",compareTitle:"属性を比較",attacker:"攻撃属性",defender:"防御属性",strong:"有利",weak:"不利",neutral:"確認済みの有利不利なし",strongAgainst:"有利な属性",weakTo:"不利な属性",matrixTitle:"属性相性一覧",matrixDescription:"行が攻撃属性、列が防御属性です。",relatedPals:"関連するパル",relatedSkills:"関連するアクティブスキル",palsCount:"パル",skillsCount:"アクティブスキル",numericUnavailable:"数値が検証されていないため、正確なダメージ倍率は表示していません。",dualUnavailable:"複合属性パルの相性を組み合わせる正確なルールは未検証のため表示していません。"},
  "zh-CN":{title:"属性克制",intro:"比较九种帕鲁属性的优势与弱点，并查看各属性的帕鲁和主动技能。",chartTitle:"官方克制图",chartDescription:"箭头从攻击属性指向其克制的防御属性。",compareTitle:"属性比较",attacker:"攻击属性",defender:"防御属性",strong:"克制",weak:"被克制",neutral:"无已验证优势",strongAgainst:"克制属性",weakTo:"被以下属性克制",matrixTitle:"完整克制表",matrixDescription:"行表示攻击属性，列表示防御属性。",relatedPals:"相关帕鲁",relatedSkills:"相关主动技能",palsCount:"帕鲁",skillsCount:"主动技能",numericUnavailable:"具体数值尚未验证，因此不显示精确伤害倍率。",dualUnavailable:"双属性帕鲁的克制合并规则尚未验证，因此不显示。"},
  "zh-TW":{title:"屬性相剋",intro:"比較九種帕魯屬性的優勢與弱點，並查看各屬性的帕魯與主動技能。",chartTitle:"官方相剋圖",chartDescription:"箭頭由攻擊屬性指向其剋制的防禦屬性。",compareTitle:"屬性比較",attacker:"攻擊屬性",defender:"防禦屬性",strong:"剋制",weak:"被剋制",neutral:"無已驗證優勢",strongAgainst:"剋制屬性",weakTo:"被以下屬性剋制",matrixTitle:"完整相剋表",matrixDescription:"列為攻擊屬性，欄為防禦屬性。",relatedPals:"相關帕魯",relatedSkills:"相關主動技能",palsCount:"帕魯",skillsCount:"主動技能",numericUnavailable:"具體數值尚未驗證，因此不顯示精確傷害倍率。",dualUnavailable:"雙屬性帕魯的相剋合併規則尚未驗證，因此不顯示。"},
  "de-DE":{title:"Elementverhältnisse",intro:"Vergleiche die Stärken und Schwächen aller neun Elemente und finde passende Pals und aktive Fähigkeiten.",chartTitle:"Offizielle Elementgrafik",chartDescription:"Ein Pfeil zeigt vom angreifenden Element auf das Element, gegen das es stark ist.",compareTitle:"Elemente vergleichen",attacker:"Angriffselement",defender:"Verteidigungselement",strong:"Stark",weak:"Schwach",neutral:"Kein bestätigter Vorteil",strongAgainst:"Stark gegen",weakTo:"Schwach gegen",matrixTitle:"Vollständige Elementtabelle",matrixDescription:"Zeilen sind Angriffs-, Spalten Verteidigungselemente.",relatedPals:"Zugehörige Pals",relatedSkills:"Zugehörige aktive Fähigkeiten",palsCount:"Pals",skillsCount:"aktive Fähigkeiten",numericUnavailable:"Exakte Schadensmultiplikatoren werden nicht angezeigt, da die Zahlenwerte nicht bestätigt sind.",dualUnavailable:"Die genaue Kombination der Verhältnisse bei Pals mit zwei Elementen ist nicht bestätigt."},
  "fr-FR":{title:"Affinités élémentaires",intro:"Comparez les forces et faiblesses des neuf éléments et trouvez les Pals et compétences actives associés.",chartTitle:"Schéma officiel des affinités",chartDescription:"Une flèche va de l’élément attaquant vers l’élément contre lequel il est fort.",compareTitle:"Comparer les éléments",attacker:"Élément attaquant",defender:"Élément défenseur",strong:"Fort",weak:"Faible",neutral:"Aucun avantage vérifié",strongAgainst:"Fort contre",weakTo:"Faible contre",matrixTitle:"Tableau complet des affinités",matrixDescription:"Les lignes sont les éléments attaquants et les colonnes les éléments défenseurs.",relatedPals:"Pals associés",relatedSkills:"Compétences actives associées",palsCount:"Pals",skillsCount:"compétences actives",numericUnavailable:"Les multiplicateurs de dégâts exacts ne sont pas affichés, car les valeurs numériques ne sont pas vérifiées.",dualUnavailable:"La règle exacte de combinaison pour les Pals à deux éléments n’a pas été vérifiée."},
  "it-IT":{title:"Affinità elementali",intro:"Confronta punti di forza e debolezze dei nove elementi e trova i Pal e le abilità attive correlate.",chartTitle:"Schema ufficiale delle affinità",chartDescription:"La freccia va dall’elemento d’attacco a quello contro cui è forte.",compareTitle:"Confronta elementi",attacker:"Elemento d’attacco",defender:"Elemento di difesa",strong:"Forte",weak:"Debole",neutral:"Nessun vantaggio verificato",strongAgainst:"Forte contro",weakTo:"Debole contro",matrixTitle:"Tabella completa delle affinità",matrixDescription:"Le righe sono elementi d’attacco e le colonne elementi di difesa.",relatedPals:"Pal correlati",relatedSkills:"Abilità attive correlate",palsCount:"Pal",skillsCount:"abilità attive",numericUnavailable:"I moltiplicatori esatti non sono mostrati perché i valori numerici non sono verificati.",dualUnavailable:"La regola esatta per combinare le affinità dei Pal con due elementi non è stata verificata."},
  "es-ES":{title:"Afinidades elementales",intro:"Compara las fortalezas y debilidades de los nueve elementos y encuentra Pals y habilidades activas relacionados.",chartTitle:"Diagrama oficial de afinidades",chartDescription:"La flecha va del elemento atacante al elemento contra el que es fuerte.",compareTitle:"Comparar elementos",attacker:"Elemento atacante",defender:"Elemento defensor",strong:"Fuerte",weak:"Débil",neutral:"Sin ventaja verificada",strongAgainst:"Fuerte contra",weakTo:"Débil contra",matrixTitle:"Tabla completa de afinidades",matrixDescription:"Las filas son elementos atacantes y las columnas, elementos defensores.",relatedPals:"Pals relacionados",relatedSkills:"Habilidades activas relacionadas",palsCount:"Pals",skillsCount:"habilidades activas",numericUnavailable:"No se muestran multiplicadores exactos porque los valores numéricos no están verificados.",dualUnavailable:"No se ha verificado la regla exacta para combinar afinidades en Pals de dos elementos."},
  "es-419":{title:"Afinidades elementales",intro:"Compara las fortalezas y debilidades de los nueve elementos y encuentra Pals y habilidades activas relacionados.",chartTitle:"Diagrama oficial de afinidades",chartDescription:"La flecha va del elemento atacante al elemento contra el que es fuerte.",compareTitle:"Comparar elementos",attacker:"Elemento atacante",defender:"Elemento defensor",strong:"Fuerte",weak:"Débil",neutral:"Sin ventaja verificada",strongAgainst:"Fuerte contra",weakTo:"Débil contra",matrixTitle:"Tabla completa de afinidades",matrixDescription:"Las filas son elementos atacantes y las columnas son elementos defensores.",relatedPals:"Pals relacionados",relatedSkills:"Habilidades activas relacionadas",palsCount:"Pals",skillsCount:"habilidades activas",numericUnavailable:"No se muestran multiplicadores exactos porque los valores numéricos no están verificados.",dualUnavailable:"No se ha verificado la regla exacta para combinar afinidades en Pals de dos elementos."},
  "pt-BR":{title:"Vantagens elementais",intro:"Compare forças e fraquezas dos nove elementos e encontre Pals e habilidades ativas relacionados.",chartTitle:"Diagrama oficial de vantagens",chartDescription:"A seta vai do elemento atacante ao elemento contra o qual ele é forte.",compareTitle:"Comparar elementos",attacker:"Elemento atacante",defender:"Elemento defensor",strong:"Forte",weak:"Fraco",neutral:"Sem vantagem verificada",strongAgainst:"Forte contra",weakTo:"Fraco contra",matrixTitle:"Tabela completa de vantagens",matrixDescription:"As linhas são elementos atacantes e as colunas são elementos defensores.",relatedPals:"Pals relacionados",relatedSkills:"Habilidades ativas relacionadas",palsCount:"Pals",skillsCount:"habilidades ativas",numericUnavailable:"Multiplicadores exatos não são exibidos porque os valores numéricos não foram verificados.",dualUnavailable:"A regra exata de combinação para Pals de dois elementos não foi verificada."},
  "ru-RU":{title:"Стихийные преимущества",intro:"Сравнивайте сильные и слабые стороны девяти стихий и находите связанных Палов и активные навыки.",chartTitle:"Официальная схема стихий",chartDescription:"Стрелка направлена от атакующей стихии к стихии, против которой она сильна.",compareTitle:"Сравнить стихии",attacker:"Стихия атаки",defender:"Стихия защиты",strong:"Сильна",weak:"Слаба",neutral:"Нет подтверждённого преимущества",strongAgainst:"Сильна против",weakTo:"Слаба против",matrixTitle:"Полная таблица стихий",matrixDescription:"Строки — атакующие стихии, столбцы — защищающиеся.",relatedPals:"Связанные Палы",relatedSkills:"Связанные активные навыки",palsCount:"Палы",skillsCount:"активные навыки",numericUnavailable:"Точные множители урона не показаны, поскольку числовые значения не подтверждены.",dualUnavailable:"Точное правило сочетания преимуществ у Палов с двумя стихиями не подтверждено."},
  "id-ID":{title:"Kecocokan Elemen",intro:"Bandingkan kekuatan dan kelemahan sembilan elemen serta temukan Pal dan skill aktif terkait.",chartTitle:"Bagan kecocokan resmi",chartDescription:"Panah menunjuk dari elemen penyerang ke elemen yang dilawannya dengan kuat.",compareTitle:"Bandingkan elemen",attacker:"Elemen penyerang",defender:"Elemen bertahan",strong:"Kuat",weak:"Lemah",neutral:"Tidak ada keunggulan terverifikasi",strongAgainst:"Kuat terhadap",weakTo:"Lemah terhadap",matrixTitle:"Tabel kecocokan lengkap",matrixDescription:"Baris adalah elemen penyerang dan kolom adalah elemen bertahan.",relatedPals:"Pal terkait",relatedSkills:"Skill aktif terkait",palsCount:"Pal",skillsCount:"skill aktif",numericUnavailable:"Pengali kerusakan tepat tidak ditampilkan karena nilai angkanya belum terverifikasi.",dualUnavailable:"Aturan tepat untuk menggabungkan kecocokan Pal berelemen ganda belum terverifikasi."},
  "th-TH":{title:"ความได้เปรียบของธาตุ",intro:"เปรียบเทียบจุดแข็งและจุดอ่อนของทั้งเก้าธาตุ พร้อมดูพาลและสกิลแอคทีฟที่เกี่ยวข้อง",chartTitle:"แผนผังธาตุอย่างเป็นทางการ",chartDescription:"ลูกศรชี้จากธาตุโจมตีไปยังธาตุที่ได้เปรียบ",compareTitle:"เปรียบเทียบธาตุ",attacker:"ธาตุโจมตี",defender:"ธาตุป้องกัน",strong:"ได้เปรียบ",weak:"เสียเปรียบ",neutral:"ไม่มีความได้เปรียบที่ยืนยันแล้ว",strongAgainst:"ได้เปรียบต่อ",weakTo:"เสียเปรียบต่อ",matrixTitle:"ตารางธาตุทั้งหมด",matrixDescription:"แถวคือธาตุโจมตีและคอลัมน์คือธาตุป้องกัน",relatedPals:"พาลที่เกี่ยวข้อง",relatedSkills:"สกิลแอคทีฟที่เกี่ยวข้อง",palsCount:"พาล",skillsCount:"สกิลแอคทีฟ",numericUnavailable:"ไม่แสดงตัวคูณความเสียหายที่แน่นอน เพราะค่าตัวเลขยังไม่ได้รับการยืนยัน",dualUnavailable:"กฎการรวมความได้เปรียบของพาลสองธาตุยังไม่ได้รับการยืนยัน"},
  "tr-TR":{title:"Element Eşleşmeleri",intro:"Dokuz elementin güçlü ve zayıf yönlerini karşılaştır, ilgili Pal ve aktif becerileri bul.",chartTitle:"Resmî eşleşme şeması",chartDescription:"Ok, saldırı elementinden güçlü olduğu savunma elementine gider.",compareTitle:"Elementleri karşılaştır",attacker:"Saldırı elementi",defender:"Savunma elementi",strong:"Güçlü",weak:"Zayıf",neutral:"Doğrulanmış avantaj yok",strongAgainst:"Şuna karşı güçlü",weakTo:"Şuna karşı zayıf",matrixTitle:"Tam eşleşme tablosu",matrixDescription:"Satırlar saldırı, sütunlar savunma elementleridir.",relatedPals:"İlgili Pallar",relatedSkills:"İlgili aktif beceriler",palsCount:"Pal",skillsCount:"aktif beceri",numericUnavailable:"Sayısal değerler doğrulanmadığı için kesin hasar çarpanları gösterilmez.",dualUnavailable:"Çift elementli Pallar için eşleşmeleri birleştirme kuralı doğrulanmamıştır."},
  "vi-VN":{title:"Tương Khắc Hệ",intro:"So sánh điểm mạnh và điểm yếu của chín hệ, đồng thời tìm Pal và kỹ năng chủ động liên quan.",chartTitle:"Sơ đồ tương khắc chính thức",chartDescription:"Mũi tên đi từ hệ tấn công đến hệ mà nó khắc chế.",compareTitle:"So sánh hệ",attacker:"Hệ tấn công",defender:"Hệ phòng thủ",strong:"Khắc chế",weak:"Bị khắc chế",neutral:"Không có lợi thế đã xác minh",strongAgainst:"Khắc chế",weakTo:"Bị khắc chế bởi",matrixTitle:"Bảng tương khắc đầy đủ",matrixDescription:"Hàng là hệ tấn công và cột là hệ phòng thủ.",relatedPals:"Pal liên quan",relatedSkills:"Kỹ năng chủ động liên quan",palsCount:"Pal",skillsCount:"kỹ năng chủ động",numericUnavailable:"Không hiển thị hệ số sát thương chính xác vì giá trị số chưa được xác minh.",dualUnavailable:"Quy tắc kết hợp tương khắc cho Pal hai hệ chưa được xác minh."},
  "pl-PL":{title:"Relacje żywiołów",intro:"Porównaj mocne i słabe strony dziewięciu żywiołów oraz znajdź powiązane Pale i umiejętności aktywne.",chartTitle:"Oficjalny schemat żywiołów",chartDescription:"Strzałka prowadzi od żywiołu ataku do żywiołu, przeciw któremu jest silny.",compareTitle:"Porównaj żywioły",attacker:"Żywioł ataku",defender:"Żywioł obrony",strong:"Silny",weak:"Słaby",neutral:"Brak potwierdzonej przewagi",strongAgainst:"Silny przeciw",weakTo:"Słaby przeciw",matrixTitle:"Pełna tabela żywiołów",matrixDescription:"Wiersze to żywioły ataku, a kolumny — żywioły obrony.",relatedPals:"Powiązane Pale",relatedSkills:"Powiązane umiejętności aktywne",palsCount:"Pale",skillsCount:"umiejętności aktywne",numericUnavailable:"Dokładne mnożniki obrażeń nie są wyświetlane, ponieważ wartości liczbowe nie zostały potwierdzone.",dualUnavailable:"Dokładna reguła łączenia relacji u Pali z dwoma żywiołami nie została potwierdzona."}
};

const elementOverviewCopy:Record<Locale,Pick<ElementCopy,"chartTitle"|"chartDescription">>={
  "en-US":{chartTitle:"Element matchup flow",chartDescription:"Each arrow runs from an attacking element to an element it has a verified advantage against."},
  "ko-KR":{chartTitle:"속성 상성 흐름도",chartDescription:"화살표는 공격 속성에서 그 공격이 유리한 방어 속성으로 이어집니다."},
  "ja-JP":{chartTitle:"属性相性フロー",chartDescription:"矢印は攻撃属性から、その攻撃が有利な防御属性へ向かいます。"},
  "zh-CN":{chartTitle:"属性克制流程图",chartDescription:"箭头从攻击属性指向已确认对其有利的防御属性。"},
  "zh-TW":{chartTitle:"屬性相剋流程圖",chartDescription:"箭頭由攻擊屬性指向已確認對其有利的防禦屬性。"},
  "de-DE":{chartTitle:"Fluss der Elementvorteile",chartDescription:"Jeder Pfeil führt vom Angriffselement zu einem Element, gegen das sein Vorteil bestätigt ist."},
  "fr-FR":{chartTitle:"Flux des affinités élémentaires",chartDescription:"Chaque flèche relie un élément attaquant à un élément contre lequel son avantage est confirmé."},
  "it-IT":{chartTitle:"Flusso delle affinità elementali",chartDescription:"Ogni freccia va dall’elemento d’attacco a un elemento contro cui ha un vantaggio verificato."},
  "es-ES":{chartTitle:"Flujo de afinidades elementales",chartDescription:"Cada flecha va del elemento atacante a un elemento contra el que tiene una ventaja verificada."},
  "es-419":{chartTitle:"Flujo de afinidades elementales",chartDescription:"Cada flecha va del elemento atacante a un elemento contra el que tiene una ventaja verificada."},
  "pt-BR":{chartTitle:"Fluxo de vantagens elementais",chartDescription:"Cada seta vai do elemento atacante a um elemento contra o qual ele tem vantagem verificada."},
  "ru-RU":{chartTitle:"Схема преимуществ стихий",chartDescription:"Каждая стрелка ведёт от стихии атаки к стихии, против которой подтверждено преимущество."},
  "id-ID":{chartTitle:"Alur keunggulan elemen",chartDescription:"Setiap panah mengarah dari elemen penyerang ke elemen yang memiliki keunggulan terverifikasi terhadapnya."},
  "th-TH":{chartTitle:"ผังลำดับการได้เปรียบของธาตุ",chartDescription:"ลูกศรชี้จากธาตุโจมตีไปยังธาตุป้องกันที่ยืนยันแล้วว่าได้เปรียบ"},
  "tr-TR":{chartTitle:"Element avantaj akışı",chartDescription:"Her ok, saldırı elementinden doğrulanmış avantaja sahip olduğu savunma elementine gider."},
  "vi-VN":{chartTitle:"Sơ đồ tương khắc hệ",chartDescription:"Mỗi mũi tên đi từ hệ tấn công đến hệ phòng thủ mà nó có lợi thế đã được xác minh."},
  "pl-PL":{chartTitle:"Przepływ przewag żywiołów",chartDescription:"Każda strzałka prowadzi od żywiołu ataku do żywiołu, przeciw któremu potwierdzono przewagę."}
};
for(const locale of Object.keys(elementOverviewCopy) as Locale[])Object.assign(elementCopy[locale],elementOverviewCopy[locale]);

export const elementCopyProvenance=Object.fromEntries(Object.keys(elementCopy).map(locale=>[locale,{title:"gpt",remaining:"gpt"}])) as unknown as Record<Locale,Record<string,"gpt">>;
