import type {Locale} from "./config";

export type ElementMatchupCopy={primaryDefender:string;secondaryDefender:string;noSecondElement:string;dualPal:string;manualSelection:string;componentEffects:string;qualitativeResult:string;damageMultiplier:string;combinationRule:string;finalMultiplier:string;verified:string;unavailable:string};

export const elementMatchupCopy:Record<Locale,ElementMatchupCopy>={
  "en-US":{primaryDefender:"Defending element 1",secondaryDefender:"Defending element 2",noSecondElement:"No second element",dualPal:"Choose a dual-element Pal",manualSelection:"Choose elements manually",componentEffects:"Effects by defending element",qualitativeResult:"Matchup",damageMultiplier:"Damage multiplier",combinationRule:"Dual-element combination",finalMultiplier:"Final damage multiplier",verified:"Verified",unavailable:"Unavailable"},
  "ko-KR":{primaryDefender:"방어 속성 1",secondaryDefender:"방어 속성 2",noSecondElement:"두 번째 속성 없음",dualPal:"복합 속성 팰 선택",manualSelection:"속성 직접 선택",componentEffects:"방어 속성별 판정",qualitativeResult:"상성 판정",damageMultiplier:"피해 배율",combinationRule:"복합 속성 결합",finalMultiplier:"최종 피해 배율",verified:"확인됨",unavailable:"미확인"},
  "ja-JP":{primaryDefender:"防御属性1",secondaryDefender:"防御属性2",noSecondElement:"2つ目の属性なし",dualPal:"複合属性パルを選択",manualSelection:"属性を手動で選択",componentEffects:"防御属性ごとの判定",qualitativeResult:"相性判定",damageMultiplier:"ダメージ倍率",combinationRule:"複合属性の組み合わせ",finalMultiplier:"最終ダメージ倍率",verified:"確認済み",unavailable:"未確認"},
  "zh-CN":{primaryDefender:"防御属性 1",secondaryDefender:"防御属性 2",noSecondElement:"无第二属性",dualPal:"选择双属性帕鲁",manualSelection:"手动选择属性",componentEffects:"各防御属性的判定",qualitativeResult:"属性判定",damageMultiplier:"伤害倍率",combinationRule:"双属性组合规则",finalMultiplier:"最终伤害倍率",verified:"已验证",unavailable:"未验证"},
  "zh-TW":{primaryDefender:"防禦屬性 1",secondaryDefender:"防禦屬性 2",noSecondElement:"無第二屬性",dualPal:"選擇雙屬性帕魯",manualSelection:"手動選擇屬性",componentEffects:"各防禦屬性的判定",qualitativeResult:"屬性判定",damageMultiplier:"傷害倍率",combinationRule:"雙屬性組合規則",finalMultiplier:"最終傷害倍率",verified:"已驗證",unavailable:"未驗證"},
  "de-DE":{primaryDefender:"Verteidigungselement 1",secondaryDefender:"Verteidigungselement 2",noSecondElement:"Kein zweites Element",dualPal:"Pal mit zwei Elementen wählen",manualSelection:"Elemente manuell wählen",componentEffects:"Wirkung je Verteidigungselement",qualitativeResult:"Elementverhältnis",damageMultiplier:"Schadensmultiplikator",combinationRule:"Kombination zweier Elemente",finalMultiplier:"Endgültiger Schadensmultiplikator",verified:"Bestätigt",unavailable:"Nicht verfügbar"},
  "fr-FR":{primaryDefender:"Élément défenseur 1",secondaryDefender:"Élément défenseur 2",noSecondElement:"Aucun second élément",dualPal:"Choisir un Pal à deux éléments",manualSelection:"Choisir les éléments manuellement",componentEffects:"Effet par élément défenseur",qualitativeResult:"Affinité",damageMultiplier:"Multiplicateur de dégâts",combinationRule:"Combinaison de deux éléments",finalMultiplier:"Multiplicateur de dégâts final",verified:"Vérifié",unavailable:"Indisponible"},
  "it-IT":{primaryDefender:"Elemento difensore 1",secondaryDefender:"Elemento difensore 2",noSecondElement:"Nessun secondo elemento",dualPal:"Scegli un Pal con due elementi",manualSelection:"Scegli gli elementi manualmente",componentEffects:"Effetto per elemento difensore",qualitativeResult:"Affinità",damageMultiplier:"Moltiplicatore danni",combinationRule:"Combinazione di due elementi",finalMultiplier:"Moltiplicatore danni finale",verified:"Verificato",unavailable:"Non disponibile"},
  "es-ES":{primaryDefender:"Elemento defensor 1",secondaryDefender:"Elemento defensor 2",noSecondElement:"Sin segundo elemento",dualPal:"Elegir un Pal de dos elementos",manualSelection:"Elegir elementos manualmente",componentEffects:"Efecto por elemento defensor",qualitativeResult:"Afinidad",damageMultiplier:"Multiplicador de daño",combinationRule:"Combinación de dos elementos",finalMultiplier:"Multiplicador de daño final",verified:"Verificado",unavailable:"No disponible"},
  "es-419":{primaryDefender:"Elemento defensor 1",secondaryDefender:"Elemento defensor 2",noSecondElement:"Sin segundo elemento",dualPal:"Elegir un Pal de dos elementos",manualSelection:"Elegir elementos manualmente",componentEffects:"Efecto por elemento defensor",qualitativeResult:"Afinidad",damageMultiplier:"Multiplicador de daño",combinationRule:"Combinación de dos elementos",finalMultiplier:"Multiplicador de daño final",verified:"Verificado",unavailable:"No disponible"},
  "pt-BR":{primaryDefender:"Elemento defensor 1",secondaryDefender:"Elemento defensor 2",noSecondElement:"Sem segundo elemento",dualPal:"Escolher um Pal de dois elementos",manualSelection:"Escolher elementos manualmente",componentEffects:"Efeito por elemento defensor",qualitativeResult:"Vantagem elemental",damageMultiplier:"Multiplicador de dano",combinationRule:"Combinação de dois elementos",finalMultiplier:"Multiplicador de dano final",verified:"Verificado",unavailable:"Indisponível"},
  "ru-RU":{primaryDefender:"Стихия защиты 1",secondaryDefender:"Стихия защиты 2",noSecondElement:"Без второй стихии",dualPal:"Выбрать Пала с двумя стихиями",manualSelection:"Выбрать стихии вручную",componentEffects:"Эффект для каждой стихии защиты",qualitativeResult:"Соотношение стихий",damageMultiplier:"Множитель урона",combinationRule:"Сочетание двух стихий",finalMultiplier:"Итоговый множитель урона",verified:"Подтверждено",unavailable:"Недоступно"},
  "id-ID":{primaryDefender:"Elemen bertahan 1",secondaryDefender:"Elemen bertahan 2",noSecondElement:"Tanpa elemen kedua",dualPal:"Pilih Pal berelemen ganda",manualSelection:"Pilih elemen secara manual",componentEffects:"Efek per elemen bertahan",qualitativeResult:"Kecocokan",damageMultiplier:"Pengali kerusakan",combinationRule:"Kombinasi elemen ganda",finalMultiplier:"Pengali kerusakan akhir",verified:"Terverifikasi",unavailable:"Tidak tersedia"},
  "th-TH":{primaryDefender:"ธาตุป้องกัน 1",secondaryDefender:"ธาตุป้องกัน 2",noSecondElement:"ไม่มีธาตุที่สอง",dualPal:"เลือกพาลสองธาตุ",manualSelection:"เลือกธาตุด้วยตนเอง",componentEffects:"ผลต่อธาตุป้องกันแต่ละธาตุ",qualitativeResult:"ความได้เปรียบของธาตุ",damageMultiplier:"ตัวคูณความเสียหาย",combinationRule:"การรวมสองธาตุ",finalMultiplier:"ตัวคูณความเสียหายสุดท้าย",verified:"ตรวจสอบแล้ว",unavailable:"ยังไม่มีข้อมูล"},
  "tr-TR":{primaryDefender:"Savunma elementi 1",secondaryDefender:"Savunma elementi 2",noSecondElement:"İkinci element yok",dualPal:"Çift elementli bir Pal seç",manualSelection:"Elementleri elle seç",componentEffects:"Savunma elementine göre etkiler",qualitativeResult:"Element eşleşmesi",damageMultiplier:"Hasar çarpanı",combinationRule:"Çift element birleşimi",finalMultiplier:"Nihai hasar çarpanı",verified:"Doğrulandı",unavailable:"Kullanılamıyor"},
  "vi-VN":{primaryDefender:"Hệ phòng thủ 1",secondaryDefender:"Hệ phòng thủ 2",noSecondElement:"Không có hệ thứ hai",dualPal:"Chọn Pal song hệ",manualSelection:"Chọn hệ thủ công",componentEffects:"Hiệu quả theo từng hệ phòng thủ",qualitativeResult:"Tương khắc",damageMultiplier:"Hệ số sát thương",combinationRule:"Kết hợp song hệ",finalMultiplier:"Hệ số sát thương cuối",verified:"Đã xác minh",unavailable:"Chưa có"},
  "pl-PL":{primaryDefender:"Żywioł obrony 1",secondaryDefender:"Żywioł obrony 2",noSecondElement:"Bez drugiego żywiołu",dualPal:"Wybierz Pala z dwoma żywiołami",manualSelection:"Wybierz żywioły ręcznie",componentEffects:"Efekt dla każdego żywiołu obrony",qualitativeResult:"Relacja żywiołów",damageMultiplier:"Mnożnik obrażeń",combinationRule:"Łączenie dwóch żywiołów",finalMultiplier:"Końcowy mnożnik obrażeń",verified:"Potwierdzono",unavailable:"Niedostępne"}
};

export const elementMatchupCopyProvenance=Object.fromEntries(Object.keys(elementMatchupCopy).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;
