import type {Locale} from "./config";

export type GuideId="getting-started"|"returning-player"|"breeding"|"base"|"server"|"combat";
export type GuideMetricKind="locations"|"pals"|"entries"|"recipes"|"combinations"|"skills"|"work-roles"|"settings"|"conditions";
export type GuideStepKind="discover"|"compare"|"verify"|"plan";
export type GuideDefinition={id:GuideId;slug:GuideId;related:readonly string[];stepKinds:readonly GuideStepKind[];reviewTrigger:string};
export type GuideSnapshotData={meta:{schema:2;gameBuild:string;verification:"verified";localeCount:number;guideCount:number;metricCount:number};guides:Record<GuideId,{reviewTrigger:string;metrics:{route:string;kind:GuideMetricKind;count:number}[]}>};

export const guideDefinitions=[
  {id:"getting-started",slug:"getting-started",related:["map","pals","database/technology","calculators/base","calculators/crafting"],stepKinds:["discover","compare","verify","plan","plan"],reviewTrigger:"major progression or map change"},
  {id:"returning-player",slug:"returning-player",related:["database/quests","database/technology","database/expeditions","map"],stepKinds:["verify","verify","compare","discover"],reviewTrigger:"major content update"},
  {id:"breeding",slug:"breeding",related:["pals","calculators/breeding","calculators/breeding-path","skills/passive","calculators/team-builder"],stepKinds:["compare","verify","plan","compare","verify"],reviewTrigger:"breeding rule or Pal roster change"},
  {id:"base",slug:"base",related:["calculators/base","pals","database/structures","calculators/crafting","database"],stepKinds:["plan","compare","verify","plan","verify"],reviewTrigger:"work suitability, recipe, or structure change"},
  {id:"server",slug:"server",related:["server-tools/settings-generator","calculators/base","database/structures","calculators/crafting"],stepKinds:["verify","plan","verify","plan"],reviewTrigger:"official server guide change"},
  {id:"combat",slug:"combat",related:["database/elements","skills/active","calculators/iv","database/health","calculators/team-builder"],stepKinds:["compare","compare","verify","verify","plan"],reviewTrigger:"element, condition, or active-skill change"},
] as const satisfies readonly GuideDefinition[];

export const guideStepKindLabels:Record<Locale,Record<GuideStepKind,string>>={
  "en-US":{discover:"Find the relevant options and narrow the next stop.",compare:"Compare the current choices before selecting one.",verify:"Check the current constraints and confirm the checkpoint.",plan:"Record the requirements before committing resources."},
  "ko-KR":{discover:"관련 선택지를 찾아 다음 목적지를 좁히세요.",compare:"현재 선택지를 비교한 뒤 하나를 고르세요.",verify:"현재 조건을 점검하고 이 확인 지점을 완료하세요.",plan:"자원을 투입하기 전에 필요한 조건을 계획하세요."},
  "ja-JP":{discover:"関連する選択肢を探し、次の目的地を絞ります。",compare:"現在の選択肢を比較してから一つを選びます。",verify:"現在の条件を確認し、このチェックポイントを完了します。",plan:"資源を使う前に必要条件を計画します。"},
  "zh-CN":{discover:"查找相关选项并缩小下一站范围。",compare:"比较当前选项后再作选择。",verify:"检查当前限制并完成此检查点。",plan:"投入资源前先规划所需条件。"},
  "zh-TW":{discover:"查找相關選項並縮小下一站範圍。",compare:"比較目前選項後再作選擇。",verify:"檢查目前限制並完成此檢查點。",plan:"投入資源前先規劃所需條件。"},
  "fr-FR":{discover:"Repérez les options utiles et réduisez le choix de la prochaine étape.",compare:"Comparez les choix actuels avant d’en sélectionner un.",verify:"Vérifiez les contraintes actuelles et validez ce point de contrôle.",plan:"Notez les besoins avant d’engager des ressources."},
  "it-IT":{discover:"Trova le opzioni pertinenti e restringi la prossima tappa.",compare:"Confronta le scelte attuali prima di selezionarne una.",verify:"Controlla i vincoli attuali e completa questo punto di verifica.",plan:"Annota i requisiti prima di impegnare risorse."},
  "de-DE":{discover:"Finde passende Optionen und grenze das nächste Ziel ein.",compare:"Vergleiche die aktuellen Optionen, bevor du eine auswählst.",verify:"Prüfe die aktuellen Bedingungen und bestätige diesen Kontrollpunkt.",plan:"Halte die Anforderungen fest, bevor du Ressourcen einsetzt."},
  "es-ES":{discover:"Busca las opciones relevantes y concreta el siguiente destino.",compare:"Compara las opciones actuales antes de elegir una.",verify:"Revisa las condiciones actuales y confirma este punto de control.",plan:"Anota los requisitos antes de comprometer recursos."},
  "es-419":{discover:"Busca las opciones relevantes y define el siguiente destino.",compare:"Compara las opciones actuales antes de elegir una.",verify:"Revisa las condiciones actuales y confirma este punto de control.",plan:"Anota los requisitos antes de comprometer recursos."},
  "pt-BR":{discover:"Encontre as opções relevantes e restrinja o próximo destino.",compare:"Compare as opções atuais antes de escolher uma.",verify:"Confira as condições atuais e conclua este ponto de verificação.",plan:"Registre os requisitos antes de comprometer recursos."},
  "ru-RU":{discover:"Найдите подходящие варианты и сузьте выбор следующей цели.",compare:"Сравните текущие варианты, прежде чем выбрать один.",verify:"Проверьте текущие условия и завершите этот контрольный пункт.",plan:"Запишите требования до расходования ресурсов."},
  "id-ID":{discover:"Temukan opsi yang relevan dan persempit tujuan berikutnya.",compare:"Bandingkan pilihan saat ini sebelum memilih satu.",verify:"Periksa ketentuan saat ini dan selesaikan titik pemeriksaan ini.",plan:"Catat kebutuhan sebelum memakai sumber daya."},
  "th-TH":{discover:"ค้นหาตัวเลือกที่เกี่ยวข้องและจำกัดจุดหมายถัดไป",compare:"เปรียบเทียบตัวเลือกปัจจุบันก่อนเลือก",verify:"ตรวจสอบเงื่อนไขปัจจุบันและยืนยันจุดตรวจนี้",plan:"บันทึกข้อกำหนดก่อนใช้ทรัพยากร"},
  "tr-TR":{discover:"İlgili seçenekleri bulun ve sonraki hedefi daraltın.",compare:"Birini seçmeden önce güncel seçenekleri karşılaştırın.",verify:"Güncel koşulları kontrol edin ve bu kontrol noktasını tamamlayın.",plan:"Kaynak ayırmadan önce gereksinimleri kaydedin."},
  "vi-VN":{discover:"Tìm các lựa chọn liên quan và thu hẹp điểm đến tiếp theo.",compare:"So sánh các lựa chọn hiện tại trước khi chọn.",verify:"Kiểm tra điều kiện hiện tại và hoàn tất điểm kiểm tra này.",plan:"Ghi lại yêu cầu trước khi dùng tài nguyên."},
  "pl-PL":{discover:"Znajdź odpowiednie opcje i zawęź następny cel.",compare:"Porównaj aktualne opcje przed wybraniem jednej.",verify:"Sprawdź bieżące warunki i zakończ ten punkt kontrolny.",plan:"Zapisz wymagania przed przeznaczeniem zasobów."},
};

export const guidePreparationKindLabels:Record<Locale,Record<GuideStepKind,string>>={
  "en-US":{discover:"Set the area or target you want to explore.",compare:"List the options and the constraint that matters most.",verify:"Have the current input or state ready to check.",plan:"Write down the goal, available resources, and limits."},
  "ko-KR":{discover:"탐색할 지역이나 목표를 정해 두세요.",compare:"선택지와 가장 중요한 조건을 목록으로 만드세요.",verify:"확인할 현재 입력값이나 상태를 준비하세요.",plan:"목표, 사용 가능한 자원과 제한을 적어 두세요."},
  "ja-JP":{discover:"探索する地域や対象を決めておきます。",compare:"選択肢と最も重要な条件を一覧にします。",verify:"確認する現在の入力や状態を用意します。",plan:"目標、利用できる資源、制限を書き出します。"},
  "zh-CN":{discover:"先确定要探索的区域或目标。",compare:"列出选项和最重要的限制条件。",verify:"准备好要检查的当前输入或状态。",plan:"记下目标、可用资源和限制。"},
  "zh-TW":{discover:"先確定要探索的區域或目標。",compare:"列出選項和最重要的限制條件。",verify:"準備好要檢查的目前輸入或狀態。",plan:"記下目標、可用資源和限制。"},
  "fr-FR":{discover:"Définissez la zone ou la cible à explorer.",compare:"Listez les options et la contrainte la plus importante.",verify:"Préparez l’entrée ou l’état actuel à vérifier.",plan:"Notez l’objectif, les ressources disponibles et les limites."},
  "it-IT":{discover:"Definisci l’area o l’obiettivo da esplorare.",compare:"Elenca le opzioni e il vincolo più importante.",verify:"Prepara il dato o lo stato attuale da controllare.",plan:"Annota l’obiettivo, le risorse disponibili e i limiti."},
  "de-DE":{discover:"Lege das Gebiet oder Ziel für die Erkundung fest.",compare:"Liste die Optionen und die wichtigste Bedingung auf.",verify:"Halte die aktuelle Eingabe oder den Zustand zur Prüfung bereit.",plan:"Notiere Ziel, verfügbare Ressourcen und Grenzen."},
  "es-ES":{discover:"Define la zona o el objetivo que quieres explorar.",compare:"Enumera las opciones y la condición más importante.",verify:"Prepara la entrada o el estado actual que vas a comprobar.",plan:"Anota el objetivo, los recursos disponibles y los límites."},
  "es-419":{discover:"Define la zona o el objetivo que quieres explorar.",compare:"Enumera las opciones y la condición más importante.",verify:"Prepara la entrada o el estado actual que vas a revisar.",plan:"Anota el objetivo, los recursos disponibles y los límites."},
  "pt-BR":{discover:"Defina a área ou o objetivo que deseja explorar.",compare:"Liste as opções e a condição mais importante.",verify:"Prepare a entrada ou o estado atual que será verificado.",plan:"Anote o objetivo, os recursos disponíveis e os limites."},
  "ru-RU":{discover:"Определите область или цель для исследования.",compare:"Перечислите варианты и самое важное ограничение.",verify:"Подготовьте текущие данные или состояние для проверки.",plan:"Запишите цель, доступные ресурсы и ограничения."},
  "id-ID":{discover:"Tentukan area atau target yang ingin dijelajahi.",compare:"Daftarkan pilihan dan batasan yang paling penting.",verify:"Siapkan input atau status saat ini untuk diperiksa.",plan:"Catat tujuan, sumber daya yang tersedia, dan batasan."},
  "th-TH":{discover:"กำหนดพื้นที่หรือเป้าหมายที่ต้องการสำรวจ",compare:"จดตัวเลือกและเงื่อนไขที่สำคัญที่สุด",verify:"เตรียมข้อมูลหรือสถานะปัจจุบันที่จะตรวจสอบ",plan:"จดเป้าหมาย ทรัพยากรที่มี และข้อจำกัด"},
  "tr-TR":{discover:"Keşfetmek istediğiniz alanı veya hedefi belirleyin.",compare:"Seçenekleri ve en önemli koşulu listeleyin.",verify:"Kontrol edilecek güncel girdiyi veya durumu hazırlayın.",plan:"Hedefi, kullanılabilir kaynakları ve sınırları yazın."},
  "vi-VN":{discover:"Xác định khu vực hoặc mục tiêu muốn khám phá.",compare:"Liệt kê các lựa chọn và điều kiện quan trọng nhất.",verify:"Chuẩn bị dữ liệu hoặc trạng thái hiện tại cần kiểm tra.",plan:"Ghi lại mục tiêu, tài nguyên hiện có và giới hạn."},
  "pl-PL":{discover:"Określ obszar lub cel, który chcesz zbadać.",compare:"Wypisz opcje i najważniejszy warunek.",verify:"Przygotuj bieżące dane lub stan do sprawdzenia.",plan:"Zapisz cel, dostępne zasoby i ograniczenia."},
};

export const guideResultKindLabels:Record<Locale,Record<GuideStepKind,string>>={
  "en-US":{discover:"A next destination or shortlist is selected.",compare:"The selected option and its reason are recorded.",verify:"Constraints, warnings, and unavailable values have been checked.",plan:"Requirements and the next action are clear before resources are spent."},
  "ko-KR":{discover:"다음 목적지나 후보 목록을 선택했습니다.",compare:"선택한 항목과 선택 이유를 기록했습니다.",verify:"제약 조건, 경고와 제공 불가 값을 확인했습니다.",plan:"자원을 쓰기 전에 요구 사항과 다음 행동을 확정했습니다."},
  "ja-JP":{discover:"次の目的地または候補一覧を選びました。",compare:"選んだ項目とその理由を記録しました。",verify:"制約、警告、利用できない値を確認しました。",plan:"資源を使う前に要件と次の行動を確定しました。"},
  "zh-CN":{discover:"已选定下一目的地或候选清单。",compare:"已记录所选项目及其理由。",verify:"已检查限制、警告和不可用数值。",plan:"已在投入资源前明确要求和下一步行动。"},
  "zh-TW":{discover:"已選定下一目的地或候選清單。",compare:"已記錄所選項目及其理由。",verify:"已檢查限制、警告和不可用數值。",plan:"已在投入資源前明確要求和下一步行動。"},
  "fr-FR":{discover:"Une prochaine destination ou une liste restreinte est choisie.",compare:"L’option choisie et sa raison sont consignées.",verify:"Les contraintes, avertissements et valeurs indisponibles ont été vérifiés.",plan:"Les besoins et l’action suivante sont clairs avant toute dépense de ressources."},
  "it-IT":{discover:"È stata scelta la prossima destinazione o una lista ristretta.",compare:"L’opzione scelta e il motivo sono stati registrati.",verify:"Vincoli, avvisi e valori non disponibili sono stati controllati.",plan:"Requisiti e azione successiva sono chiari prima di spendere risorse."},
  "de-DE":{discover:"Ein nächstes Ziel oder eine engere Auswahl steht fest.",compare:"Die gewählte Option und der Grund sind festgehalten.",verify:"Bedingungen, Warnungen und nicht verfügbare Werte sind geprüft.",plan:"Anforderungen und nächster Schritt stehen vor dem Ressourceneinsatz fest."},
  "es-ES":{discover:"Se ha elegido el siguiente destino o una lista reducida.",compare:"Se han anotado la opción elegida y su motivo.",verify:"Se han revisado las condiciones, los avisos y los valores no disponibles.",plan:"Los requisitos y la siguiente acción están claros antes de gastar recursos."},
  "es-419":{discover:"Se eligió el siguiente destino o una lista reducida.",compare:"Se registraron la opción elegida y su motivo.",verify:"Se revisaron las condiciones, las advertencias y los valores no disponibles.",plan:"Los requisitos y la siguiente acción están claros antes de gastar recursos."},
  "pt-BR":{discover:"O próximo destino ou uma lista reduzida foi escolhido.",compare:"A opção escolhida e o motivo foram registrados.",verify:"Condições, avisos e valores indisponíveis foram verificados.",plan:"Os requisitos e a próxima ação estão claros antes de gastar recursos."},
  "ru-RU":{discover:"Выбрана следующая цель или сокращённый список.",compare:"Выбранный вариант и причина записаны.",verify:"Ограничения, предупреждения и недоступные значения проверены.",plan:"Требования и следующий шаг определены до расходования ресурсов."},
  "id-ID":{discover:"Tujuan berikutnya atau daftar pendek telah dipilih.",compare:"Pilihan dan alasannya telah dicatat.",verify:"Batasan, peringatan, dan nilai yang tidak tersedia telah diperiksa.",plan:"Kebutuhan dan tindakan berikutnya sudah jelas sebelum sumber daya dipakai."},
  "th-TH":{discover:"เลือกจุดหมายถัดไปหรือรายการตัวเลือกแล้ว",compare:"บันทึกตัวเลือกและเหตุผลที่เลือกแล้ว",verify:"ตรวจสอบข้อจำกัด คำเตือน และค่าที่ไม่พร้อมใช้งานแล้ว",plan:"กำหนดข้อกำหนดและการดำเนินการถัดไปก่อนใช้ทรัพยากรแล้ว"},
  "tr-TR":{discover:"Sonraki hedef veya kısa liste seçildi.",compare:"Seçilen seçenek ve nedeni kaydedildi.",verify:"Koşullar, uyarılar ve kullanılamayan değerler kontrol edildi.",plan:"Kaynak harcamadan önce gereksinimler ve sonraki işlem netleştirildi."},
  "vi-VN":{discover:"Đã chọn điểm đến tiếp theo hoặc danh sách rút gọn.",compare:"Đã ghi lại lựa chọn và lý do.",verify:"Đã kiểm tra điều kiện, cảnh báo và các giá trị không khả dụng.",plan:"Đã xác định yêu cầu và hành động tiếp theo trước khi dùng tài nguyên."},
  "pl-PL":{discover:"Wybrano następny cel lub krótką listę.",compare:"Zapisano wybraną opcję i jej uzasadnienie.",verify:"Sprawdzono warunki, ostrzeżenia i niedostępne wartości.",plan:"Wymagania i następne działanie są jasne przed wydaniem zasobów."},
};

const serverSteps=(values:string)=>{const steps=values.split("|");if(steps.length!==4)throw new Error("Server guide needs four specific steps");return {server:steps} as const};
export const guideSpecificStepLabels:Record<Locale,Partial<Record<GuideId,readonly string[]>>>={
  "en-US":serverSteps("Import the current INI or start from the official defaults, then resolve validation, security, and performance warnings.|Define the player load and operating goals before choosing capacity or rate settings.|Review the structures and progression that the server rules must support before changing related settings.|Confirm resource demand, back up the save, then apply the reviewed file during a planned restart."),
  "ko-KR":serverSteps("현재 INI를 가져오거나 공식 기본값에서 시작한 뒤 유효성·보안·성능 경고를 해결하세요.|수용 인원이나 배율 설정을 고르기 전에 플레이어 부하와 운영 목표를 정하세요.|관련 설정을 바꾸기 전에 서버 규칙이 지원해야 할 건축물과 진행 단계를 검토하세요.|자원 수요를 확인하고 저장 데이터를 백업한 뒤 계획된 재시작 때 검토한 파일을 적용하세요."),
  "ja-JP":serverSteps("現在のINIを読み込むか公式初期値から始め、検証・セキュリティ・性能の警告を解消します。|収容人数や倍率を決める前に、プレイヤー負荷と運用目標を定めます。|関連設定を変える前に、サーバールールが支える建築物と進行を確認します。|資源需要を確認し、セーブをバックアップしてから、計画した再起動時に確認済みファイルを適用します。"),
  "zh-CN":serverSteps("导入当前INI或从官方默认值开始，然后处理验证、安全和性能警告。|选择容量或倍率设置前，先确定玩家负载和运营目标。|更改相关设置前，检查服务器规则需要支持的建筑和进度。|确认资源需求并备份存档，然后在计划重启时应用已审核的文件。"),
  "zh-TW":serverSteps("匯入目前INI或從官方預設值開始，然後處理驗證、安全與效能警告。|選擇容量或倍率設定前，先確定玩家負載和營運目標。|變更相關設定前，檢查伺服器規則需要支援的建築與進度。|確認資源需求並備份存檔，然後在計畫重新啟動時套用已檢查的檔案。"),
  "fr-FR":serverSteps("Importez l’INI actuel ou partez des valeurs officielles, puis corrigez les alertes de validation, de sécurité et de performances.|Définissez la charge des joueurs et les objectifs d’exploitation avant de choisir les réglages de capacité ou de taux.|Examinez les structures et la progression que les règles du serveur doivent prendre en charge avant de modifier les réglages associés.|Confirmez les besoins en ressources, sauvegardez la partie, puis appliquez le fichier vérifié lors d’un redémarrage planifié."),
  "it-IT":serverSteps("Importa l’INI attuale o parti dai valori ufficiali, quindi risolvi gli avvisi di convalida, sicurezza e prestazioni.|Definisci il carico dei giocatori e gli obiettivi operativi prima di scegliere capacità o valori dei tassi.|Controlla le strutture e la progressione che le regole del server devono supportare prima di modificare le impostazioni correlate.|Conferma la richiesta di risorse, esegui il backup del salvataggio e applica il file verificato durante un riavvio pianificato."),
  "de-DE":serverSteps("Importiere die aktuelle INI oder beginne mit den offiziellen Standardwerten und behebe Prüf-, Sicherheits- und Leistungswarnungen.|Lege Spielerlast und Betriebsziele fest, bevor du Kapazitäts- oder Rateneinstellungen wählst.|Prüfe Gebäude und Fortschritt, die von den Serverregeln unterstützt werden müssen, bevor du zugehörige Einstellungen änderst.|Bestätige den Ressourcenbedarf, sichere den Spielstand und wende die geprüfte Datei bei einem geplanten Neustart an."),
  "es-ES":serverSteps("Importa el INI actual o parte de los valores oficiales y resuelve los avisos de validación, seguridad y rendimiento.|Define la carga de jugadores y los objetivos de funcionamiento antes de elegir ajustes de capacidad o tasas.|Revisa las estructuras y la progresión que deben admitir las reglas del servidor antes de cambiar los ajustes relacionados.|Confirma la demanda de recursos, haz una copia de la partida y aplica el archivo revisado durante un reinicio planificado."),
  "es-419":serverSteps("Importa el INI actual o parte de los valores oficiales y resuelve las advertencias de validación, seguridad y rendimiento.|Define la carga de jugadores y los objetivos de operación antes de elegir ajustes de capacidad o tasas.|Revisa las estructuras y el progreso que deben admitir las reglas del servidor antes de cambiar los ajustes relacionados.|Confirma la demanda de recursos, respalda la partida y aplica el archivo revisado durante un reinicio planificado."),
  "pt-BR":serverSteps("Importe o INI atual ou comece pelos valores oficiais e resolva os avisos de validação, segurança e desempenho.|Defina a carga de jogadores e os objetivos de operação antes de escolher configurações de capacidade ou taxas.|Revise as estruturas e a progressão que as regras do servidor devem comportar antes de alterar configurações relacionadas.|Confirme a demanda de recursos, faça backup do save e aplique o arquivo revisado durante uma reinicialização planejada."),
  "ru-RU":serverSteps("Импортируйте текущий INI или начните с официальных значений, затем устраните предупреждения проверки, безопасности и производительности.|Определите нагрузку игроков и цели работы до выбора настроек вместимости или коэффициентов.|Проверьте постройки и прогресс, которые должны поддерживать правила сервера, прежде чем менять связанные настройки.|Подтвердите потребность в ресурсах, создайте резервную копию сохранения и примените проверенный файл во время запланированного перезапуска."),
  "id-ID":serverSteps("Impor INI saat ini atau mulai dari nilai resmi, lalu selesaikan peringatan validasi, keamanan, dan performa.|Tentukan beban pemain dan tujuan operasi sebelum memilih pengaturan kapasitas atau rate.|Tinjau struktur dan progres yang harus didukung aturan server sebelum mengubah pengaturan terkait.|Pastikan kebutuhan sumber daya, cadangkan save, lalu terapkan file yang telah diperiksa saat restart terjadwal."),
  "th-TH":serverSteps("นำเข้า INI ปัจจุบันหรือเริ่มจากค่าเริ่มต้นทางการ แล้วแก้คำเตือนด้านการตรวจสอบ ความปลอดภัย และประสิทธิภาพ|กำหนดภาระผู้เล่นและเป้าหมายการดำเนินงานก่อนเลือกค่าความจุหรืออัตรา|ตรวจสอบสิ่งปลูกสร้างและความคืบหน้าที่กฎเซิร์ฟเวอร์ต้องรองรับก่อนเปลี่ยนการตั้งค่าที่เกี่ยวข้อง|ยืนยันความต้องการทรัพยากร สำรองเซฟ แล้วใช้ไฟล์ที่ตรวจสอบแล้วระหว่างการรีสตาร์ตตามแผน"),
  "tr-TR":serverSteps("Güncel INI dosyasını içe aktarın veya resmî varsayılanlardan başlayıp doğrulama, güvenlik ve performans uyarılarını giderin.|Kapasite veya oran ayarlarını seçmeden önce oyuncu yükünü ve işletim hedeflerini belirleyin.|İlgili ayarları değiştirmeden önce sunucu kurallarının desteklemesi gereken yapıları ve ilerlemeyi inceleyin.|Kaynak ihtiyacını doğrulayın, kaydı yedekleyin ve incelenen dosyayı planlı yeniden başlatma sırasında uygulayın."),
  "vi-VN":serverSteps("Nhập INI hiện tại hoặc bắt đầu từ giá trị chính thức, rồi xử lý cảnh báo xác thực, bảo mật và hiệu năng.|Xác định tải người chơi và mục tiêu vận hành trước khi chọn thiết lập sức chứa hoặc tỷ lệ.|Xem lại công trình và tiến trình mà quy tắc máy chủ phải hỗ trợ trước khi đổi thiết lập liên quan.|Xác nhận nhu cầu tài nguyên, sao lưu bản lưu rồi áp dụng tệp đã kiểm tra trong lần khởi động lại theo kế hoạch."),
  "pl-PL":serverSteps("Zaimportuj bieżący plik INI lub zacznij od wartości oficjalnych, a następnie usuń ostrzeżenia walidacji, bezpieczeństwa i wydajności.|Określ obciążenie graczy i cele działania przed wyborem ustawień pojemności lub mnożników.|Sprawdź budowle i postęp, które muszą obsługiwać reguły serwera, zanim zmienisz powiązane ustawienia.|Potwierdź zapotrzebowanie na zasoby, wykonaj kopię zapisu i zastosuj sprawdzony plik podczas planowanego restartu."),
};
export const guideSpecificStepLabelsProvenance=Object.fromEntries(Object.keys(guideSpecificStepLabels).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;

const breedingSteps=(values:string)=>{const steps=values.split("|");if(steps.length!==5)throw new Error("Breeding guide needs five specific steps");return steps};
export const guideBreedingStepLabels:Record<Locale,readonly string[]>={
  "en-US":breedingSteps("Choose the target child in the Pal catalog and note the parents or children you want to test.|Use the breeding calculator in forward or reverse mode to confirm the current parent-to-child relationship.|Compare candidate paths by length and the visible practical-score factors; do not treat the shortest path as automatically best.|Choose desired passive skills and check which candidate parents already carry them; inheritance chances remain outside this guide.|Place the planned result in the team builder and confirm its intended role and coverage before committing to the chain."),
  "ko-KR":breedingSteps("팰 도감에서 목표 자식을 고르고 확인할 부모나 자식을 정하세요.|교배 계산기의 정방향 또는 역방향 모드로 현재 부모-자식 관계를 확인하세요.|후보 경로의 길이와 표시된 실용 점수 요소를 비교하되 최단 경로를 자동으로 최선이라 판단하지 마세요.|원하는 패시브 스킬을 고르고 후보 부모가 이미 보유했는지 확인하세요. 상속 확률은 이 가이드 범위 밖입니다.|계획한 결과를 팀 빌더에 넣고 의도한 역할과 커버리지를 확인한 뒤 교배 경로를 진행하세요."),
  "ja-JP":breedingSteps("パル図鑑で目標の子を選び、確認したい親または子を決めます。|配合計算機の順方向または逆方向で、現在の親子関係を確認します。|候補経路の長さと表示される実用スコア要素を比較し、最短経路を自動的に最良とみなしません。|希望するパッシブスキルを選び、候補の親が既に持つか確認します。継承確率はこのガイドの対象外です。|計画した結果をチームビルダーに入れ、目的の役割と範囲を確認してから配合経路を進めます。"),
  "zh-CN":breedingSteps("在帕鲁图鉴中选择目标子代，并记下要测试的亲代或子代。|使用配种计算器的正向或反向模式确认当前亲子关系。|比较候选路径的长度和显示的实用评分因素，不要自动把最短路径视为最佳。|选择目标被动技能并检查哪些候选亲代已经拥有；继承概率不在本指南范围内。|将计划结果放入队伍构建器，确认预期角色和覆盖后再执行配种路径。"),
  "zh-TW":breedingSteps("在帕魯圖鑑中選擇目標子代，並記下要測試的親代或子代。|使用配種計算器的正向或反向模式確認目前親子關係。|比較候選路徑的長度和顯示的實用評分因素，不要自動把最短路徑視為最佳。|選擇目標被動技能並檢查哪些候選親代已經擁有；繼承機率不在本指南範圍內。|將計畫結果放入隊伍建構器，確認預期角色和涵蓋範圍後再執行配種路徑。"),
  "fr-FR":breedingSteps("Choisissez l’enfant cible dans le catalogue des Pals et notez les parents ou enfants à tester.|Utilisez le calculateur d’élevage en mode direct ou inverse pour confirmer la relation parent-enfant actuelle.|Comparez la longueur des chemins candidats et les facteurs visibles du score pratique sans considérer automatiquement le plus court comme le meilleur.|Choisissez les compétences passives voulues et vérifiez quels parents candidats les possèdent déjà ; les chances d’héritage restent hors du périmètre de ce guide.|Placez le résultat prévu dans le créateur d’équipe et confirmez son rôle et sa couverture avant de lancer la chaîne."),
  "it-IT":breedingSteps("Scegli il figlio obiettivo nel catalogo dei Pal e annota i genitori o i figli da verificare.|Usa il calcolatore di riproduzione in modalità diretta o inversa per confermare la relazione genitore-figlio attuale.|Confronta la lunghezza dei percorsi candidati e i fattori visibili del punteggio pratico senza considerare automaticamente migliore il più breve.|Scegli le abilità passive desiderate e verifica quali genitori candidati le possiedono già; le probabilità di eredità restano fuori da questa guida.|Inserisci il risultato previsto nel team builder e conferma ruolo e copertura prima di avviare la catena."),
  "de-DE":breedingSteps("Wähle das Zielkind im Pal-Katalog und notiere die Eltern oder Kinder, die du prüfen möchtest.|Bestätige die aktuelle Eltern-Kind-Beziehung im Zuchtrechner vorwärts oder rückwärts.|Vergleiche Kandidatenpfade nach Länge und sichtbaren Faktoren der Praxiswertung; behandle den kürzesten Pfad nicht automatisch als besten.|Wähle gewünschte passive Fähigkeiten und prüfe, welche möglichen Eltern sie bereits besitzen; Vererbungschancen liegen außerhalb dieses Leitfadens.|Setze das geplante Ergebnis in den Teamplaner und bestätige Rolle und Abdeckung, bevor du die Kette beginnst."),
  "es-ES":breedingSteps("Elige la cría objetivo en el catálogo de Pals y anota los padres o crías que quieres comprobar.|Usa la calculadora de cría en modo directo o inverso para confirmar la relación actual entre padres y cría.|Compara las rutas candidatas por longitud y factores visibles de puntuación práctica; no consideres automáticamente mejor la más corta.|Elige las habilidades pasivas deseadas y comprueba qué padres candidatos ya las tienen; las probabilidades de herencia quedan fuera de esta guía.|Coloca el resultado previsto en el creador de equipos y confirma su función y cobertura antes de iniciar la cadena."),
  "es-419":breedingSteps("Elige la cría objetivo en el catálogo de Pals y anota los padres o crías que quieres revisar.|Usa la calculadora de cría en modo directo o inverso para confirmar la relación actual entre padres y cría.|Compara las rutas candidatas por longitud y factores visibles de puntuación práctica; no consideres automáticamente mejor la más corta.|Elige las habilidades pasivas deseadas y revisa qué padres candidatos ya las tienen; las probabilidades de herencia quedan fuera de esta guía.|Coloca el resultado previsto en el creador de equipos y confirma su función y cobertura antes de iniciar la cadena."),
  "pt-BR":breedingSteps("Escolha o filhote alvo no catálogo de Pals e anote os pais ou filhotes que deseja verificar.|Use a calculadora de reprodução no modo direto ou inverso para confirmar a relação atual entre pais e filhote.|Compare os caminhos candidatos pelo tamanho e pelos fatores visíveis da pontuação prática; não trate automaticamente o mais curto como o melhor.|Escolha as habilidades passivas desejadas e confira quais pais candidatos já as possuem; as chances de herança ficam fora deste guia.|Coloque o resultado planejado no criador de equipes e confirme sua função e cobertura antes de iniciar a cadeia."),
  "ru-RU":breedingSteps("Выберите целевого потомка в каталоге Палов и отметьте родителей или потомков для проверки.|Используйте калькулятор разведения в прямом или обратном режиме, чтобы подтвердить текущую связь родителей и потомка.|Сравните пути по длине и видимым факторам практической оценки; не считайте кратчайший путь автоматически лучшим.|Выберите нужные пассивные навыки и проверьте, у каких возможных родителей они уже есть; вероятность наследования не входит в этот гайд.|Добавьте планируемый результат в конструктор команды и подтвердите роль и покрытие до начала цепочки."),
  "id-ID":breedingSteps("Pilih anak target di katalog Pal dan catat induk atau anak yang ingin diperiksa.|Gunakan kalkulator breeding dalam mode maju atau balik untuk memastikan hubungan induk-anak saat ini.|Bandingkan panjang jalur kandidat dan faktor skor praktis yang terlihat; jangan otomatis menganggap jalur terpendek sebagai yang terbaik.|Pilih skill pasif yang diinginkan dan periksa induk kandidat yang sudah memilikinya; peluang pewarisan berada di luar panduan ini.|Masukkan hasil rencana ke team builder dan pastikan peran serta cakupannya sebelum memulai rantai."),
  "th-TH":breedingSteps("เลือกพัลลูกเป้าหมายในแค็ตตาล็อกและจดพ่อแม่หรือลูกที่ต้องการตรวจสอบ|ใช้เครื่องคำนวณผสมพันธุ์แบบไปข้างหน้าหรือย้อนกลับเพื่อยืนยันความสัมพันธ์พ่อแม่กับลูกในปัจจุบัน|เปรียบเทียบความยาวเส้นทางและปัจจัยคะแนนใช้งานที่แสดง โดยไม่ถือว่าเส้นทางสั้นที่สุดดีที่สุดโดยอัตโนมัติ|เลือกสกิลติดตัวที่ต้องการและตรวจสอบพ่อแม่ที่เป็นตัวเลือกว่ามีอยู่แล้วหรือไม่ โอกาสสืบทอดอยู่นอกขอบเขตคู่มือนี้|ใส่ผลลัพธ์ที่วางแผนไว้ในเครื่องมือจัดทีมและยืนยันบทบาทกับความครอบคลุมก่อนเริ่มสายผสม"),
  "tr-TR":breedingSteps("Pal kataloğunda hedef yavruyu seçin ve kontrol edeceğiniz ebeveynleri veya yavruları not edin.|Güncel ebeveyn-yavru ilişkisini doğrulamak için üretme hesaplayıcısını ileri veya ters modda kullanın.|Aday yolları uzunluk ve görünen pratik puan etkenleriyle karşılaştırın; en kısa yolu otomatik olarak en iyi saymayın.|İstenen pasif becerileri seçin ve hangi aday ebeveynlerde bulunduğunu kontrol edin; kalıtım olasılıkları bu rehberin dışındadır.|Planlanan sonucu takım oluşturucuya ekleyip zincire başlamadan önce rolünü ve kapsamını doğrulayın."),
  "vi-VN":breedingSteps("Chọn Pal con mục tiêu trong danh mục và ghi lại cha mẹ hoặc con muốn kiểm tra.|Dùng công cụ tính phối giống theo chiều thuận hoặc ngược để xác nhận quan hệ cha mẹ-con hiện tại.|So sánh độ dài đường đi và các yếu tố điểm thực dụng hiển thị; không tự động coi đường ngắn nhất là tốt nhất.|Chọn kỹ năng bị động mong muốn và kiểm tra cha mẹ ứng viên nào đã có; xác suất di truyền nằm ngoài phạm vi hướng dẫn này.|Đưa kết quả dự kiến vào công cụ dựng đội và xác nhận vai trò cùng độ bao phủ trước khi bắt đầu chuỗi."),
  "pl-PL":breedingSteps("Wybierz docelowego potomka w katalogu Pali i zapisz rodziców lub potomków do sprawdzenia.|Użyj kalkulatora hodowli w trybie prostym lub odwrotnym, aby potwierdzić bieżącą relację rodzic-potomek.|Porównaj długość możliwych ścieżek i widoczne czynniki oceny praktycznej; nie uznawaj automatycznie najkrótszej za najlepszą.|Wybierz pożądane umiejętności pasywne i sprawdź, którzy rodzice już je mają; szanse dziedziczenia są poza zakresem poradnika.|Umieść planowany wynik w kreatorze drużyny i potwierdź rolę oraz pokrycie przed rozpoczęciem łańcucha."),
};
export const guideBreedingStepLabelsProvenance=Object.fromEntries(Object.keys(guideBreedingStepLabels).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;

const baseSteps=(values:string)=>{const steps=values.split("|");if(steps.length!==5)throw new Error("Base guide needs five specific steps");return steps};
export const guideBaseStepLabels:Record<Locale,readonly string[]>={
  "en-US":baseSteps("Choose the base goal, required work roles, minimum levels, and team limit before selecting Pals.|Compare Pals by the required work suitability and keep only candidates that cover the planned roles.|Review the structures that support each job and confirm their progression requirements before committing the layout.|Calculate direct and expanded material demand, and stop at any recipe choice that still needs your decision.|Use the item catalog to confirm remaining inputs, categories, and recipe links before spending resources."),
  "ko-KR":baseSteps("팰을 고르기 전에 거점 목표, 필요한 작업 역할, 최소 레벨과 팀 제한을 정하세요.|필요한 작업 적성을 기준으로 팰을 비교하고 계획한 역할을 담당할 후보만 남기세요.|배치를 확정하기 전에 각 작업을 지원하는 건축물과 진행 요구 사항을 확인하세요.|직접 재료와 확장 재료 수요를 계산하고 사용자가 골라야 하는 레시피가 남으면 그 지점에서 멈추세요.|자원을 쓰기 전에 아이템 도감에서 남은 입력값, 분류와 레시피 링크를 최종 확인하세요."),
  "ja-JP":baseSteps("パルを選ぶ前に拠点の目的、必要な作業役、最低レベル、チーム上限を決めます。|必要な作業適性でパルを比較し、計画した役割を満たす候補だけを残します。|配置を確定する前に各作業を支える建築物と進行要件を確認します。|直接材料と展開後の材料需要を計算し、選択が必要なレシピでは処理を止めます。|資源を使う前にアイテム図鑑で残りの入力、分類、レシピへのリンクを確認します。"),
  "zh-CN":baseSteps("选择帕鲁前，先确定据点目标、所需工作角色、最低等级和队伍上限。|按所需工作适应性比较帕鲁，只保留能覆盖计划角色的候选。|确定布局前，检查支持各项工作的建筑及其进度要求。|计算直接和展开后的材料需求，遇到仍需你选择的配方时停止展开。|投入资源前，在物品图鉴中确认剩余输入、分类和配方链接。"),
  "zh-TW":baseSteps("選擇帕魯前，先確定據點目標、所需工作角色、最低等級和隊伍上限。|按所需工作適應性比較帕魯，只保留能涵蓋計畫角色的候選。|確定配置前，檢查支援各項工作的建築及其進度要求。|計算直接和展開後的材料需求，遇到仍需你選擇的配方時停止展開。|投入資源前，在物品圖鑑中確認剩餘輸入、分類和配方連結。"),
  "fr-FR":baseSteps("Définissez l’objectif de la base, les rôles requis, les niveaux minimums et la limite d’équipe avant de choisir les Pals.|Comparez les Pals selon les aptitudes de travail requises et ne gardez que ceux qui couvrent les rôles prévus.|Examinez les structures qui prennent en charge chaque tâche et confirmez leurs conditions de progression avant d’arrêter l’aménagement.|Calculez la demande directe et développée en matériaux, puis arrêtez-vous lorsqu’un choix de recette vous revient.|Confirmez les entrées restantes, les catégories et les liens de recettes dans le catalogue d’objets avant de dépenser des ressources."),
  "it-IT":baseSteps("Definisci l’obiettivo della base, i ruoli richiesti, i livelli minimi e il limite della squadra prima di scegliere i Pal.|Confronta i Pal per l’idoneità al lavoro richiesta e conserva solo i candidati che coprono i ruoli previsti.|Controlla le strutture che supportano ogni attività e conferma i requisiti di progressione prima di fissare la disposizione.|Calcola la domanda diretta ed espansa di materiali e fermati quando resta una ricetta da scegliere.|Conferma nel catalogo oggetti gli input rimanenti, le categorie e i collegamenti alle ricette prima di spendere risorse."),
  "de-DE":baseSteps("Lege Basisziel, benötigte Arbeitsrollen, Mindeststufen und Teamlimit fest, bevor du Pals auswählst.|Vergleiche Pals nach der benötigten Arbeitseignung und behalte nur Kandidaten, die die geplanten Rollen abdecken.|Prüfe die Gebäude für jede Aufgabe und bestätige ihre Fortschrittsanforderungen, bevor du das Layout festlegst.|Berechne direkten und erweiterten Materialbedarf und stoppe bei Rezepten, die noch deine Auswahl benötigen.|Bestätige verbleibende Eingaben, Kategorien und Rezeptverknüpfungen im Gegenstandskatalog, bevor du Ressourcen ausgibst."),
  "es-ES":baseSteps("Define el objetivo de la base, los trabajos necesarios, los niveles mínimos y el límite del equipo antes de elegir Pals.|Compara los Pals por la aptitud laboral necesaria y conserva solo los candidatos que cubran los trabajos previstos.|Revisa las estructuras que sostienen cada tarea y confirma sus requisitos de progresión antes de fijar la distribución.|Calcula la demanda directa y ampliada de materiales y detente ante cualquier receta que aún debas elegir.|Confirma en el catálogo de objetos las entradas restantes, las categorías y los enlaces de recetas antes de gastar recursos."),
  "es-419":baseSteps("Define el objetivo de la base, los trabajos necesarios, los niveles mínimos y el límite del equipo antes de elegir Pals.|Compara los Pals por la aptitud laboral necesaria y conserva solo los candidatos que cubran los trabajos previstos.|Revisa las estructuras que sostienen cada tarea y confirma sus requisitos de progreso antes de fijar la distribución.|Calcula la demanda directa y ampliada de materiales y detente ante cualquier receta que aún debas elegir.|Confirma en el catálogo de objetos las entradas restantes, las categorías y los enlaces de recetas antes de gastar recursos."),
  "pt-BR":baseSteps("Defina o objetivo da base, os trabalhos necessários, os níveis mínimos e o limite da equipe antes de escolher Pals.|Compare os Pals pela aptidão de trabalho necessária e mantenha apenas candidatos que cubram as funções planejadas.|Revise as estruturas que sustentam cada tarefa e confirme os requisitos de progressão antes de fechar o layout.|Calcule a demanda direta e expandida de materiais e pare quando ainda houver uma receita para você escolher.|Confirme no catálogo de itens as entradas restantes, categorias e links de receitas antes de gastar recursos."),
  "ru-RU":baseSteps("Определите цель базы, нужные рабочие роли, минимальные уровни и лимит команды до выбора Палов.|Сравните Палов по нужной пригодности к работе и оставьте кандидатов, покрывающих запланированные роли.|Проверьте постройки для каждой задачи и их требования прогресса до утверждения планировки.|Рассчитайте прямую и развёрнутую потребность в материалах и остановитесь, если рецепт всё ещё требует вашего выбора.|До расходования ресурсов подтвердите оставшиеся входные данные, категории и связи рецептов в каталоге предметов."),
  "id-ID":baseSteps("Tentukan tujuan base, peran kerja, level minimum, dan batas tim sebelum memilih Pal.|Bandingkan Pal berdasarkan work suitability yang dibutuhkan dan simpan hanya kandidat yang mencakup peran rencana.|Tinjau struktur yang mendukung setiap pekerjaan dan pastikan syarat progresnya sebelum menetapkan tata letak.|Hitung kebutuhan bahan langsung dan terurai, lalu berhenti pada resep yang masih memerlukan pilihan Anda.|Pastikan input tersisa, kategori, dan tautan resep di katalog item sebelum memakai sumber daya."),
  "th-TH":baseSteps("กำหนดเป้าหมายฐาน บทบาทงาน ระดับขั้นต่ำ และขีดจำกัดทีมก่อนเลือกพัล|เปรียบเทียบพัลตามความถนัดงานที่ต้องการและเก็บเฉพาะตัวเลือกที่ครอบคลุมบทบาทตามแผน|ตรวจสอบสิ่งปลูกสร้างที่รองรับแต่ละงานและข้อกำหนดความคืบหน้าก่อนยืนยันผัง|คำนวณความต้องการวัสดุโดยตรงและแบบขยาย แล้วหยุดเมื่อยังมีสูตรที่ต้องเลือกเอง|ยืนยันข้อมูลที่เหลือ หมวดหมู่ และลิงก์สูตรในแค็ตตาล็อกไอเทมก่อนใช้ทรัพยากร"),
  "tr-TR":baseSteps("Pal seçmeden önce üs hedefini, gerekli iş rollerini, asgari seviyeleri ve takım sınırını belirleyin.|Palları gerekli iş uygunluğuna göre karşılaştırın ve yalnızca planlanan rolleri kapsayan adayları tutun.|Yerleşimi kesinleştirmeden önce her işi destekleyen yapıları ve ilerleme gereksinimlerini inceleyin.|Doğrudan ve genişletilmiş malzeme ihtiyacını hesaplayın; seçiminizi gerektiren tarifte durun.|Kaynak harcamadan önce eşya kataloğunda kalan girdileri, kategorileri ve tarif bağlantılarını doğrulayın."),
  "vi-VN":baseSteps("Xác định mục tiêu căn cứ, vai trò công việc, cấp tối thiểu và giới hạn đội trước khi chọn Pal.|So sánh Pal theo khả năng làm việc cần thiết và chỉ giữ ứng viên đáp ứng các vai trò đã định.|Xem lại công trình hỗ trợ từng việc và xác nhận yêu cầu tiến trình trước khi chốt bố cục.|Tính nhu cầu vật liệu trực tiếp và mở rộng, rồi dừng tại công thức vẫn cần bạn lựa chọn.|Xác nhận dữ liệu còn lại, danh mục và liên kết công thức trong danh mục vật phẩm trước khi dùng tài nguyên."),
  "pl-PL":baseSteps("Określ cel bazy, wymagane role pracy, poziomy minimalne i limit drużyny przed wyborem Pali.|Porównaj Pale według wymaganej przydatności do pracy i zachowaj tylko kandydatów pokrywających planowane role.|Sprawdź budowle wspierające każde zadanie i ich wymagania postępu przed zatwierdzeniem układu.|Oblicz bezpośrednie i rozwinięte zapotrzebowanie na materiały, zatrzymując się przy recepturze wymagającej wyboru.|Przed wydaniem zasobów potwierdź pozostałe dane, kategorie i powiązania receptur w katalogu przedmiotów."),
};
export const guideBaseStepLabelsProvenance=Object.fromEntries(Object.keys(guideBaseStepLabels).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;

const combatSteps=(values:string)=>{const steps=values.split("|");if(steps.length!==5)throw new Error("Combat guide needs five specific steps");return steps};
export const guideCombatStepLabels:Record<Locale,readonly string[]>={
  "en-US":combatSteps("Choose the attacking element and one or two defending elements, then compare the verified element-scaling stage without treating it as total final damage.|Compare candidate active skills by their current element, power, and cooldown data without inventing a performance tier.|Enter the observed Pal stats and use the verified IV ranges; keep an ambiguous result as a range instead of choosing one value.|Match each health condition to the available treatment information and leave unavailable details unestimated.|Add the planned Pals to the team builder and inspect element, work, and duplicate coverage; unavailable purpose weights are not a ranking."),
  "ko-KR":combatSteps("공격 속성과 방어 속성 한두 개를 고른 뒤 검증된 속성 스케일링 단계를 비교하세요. 이 값은 최종 총 피해가 아닙니다.|현재 속성, 위력과 쿨다운 데이터로 액티브 스킬 후보를 비교하되 성능 티어를 만들지 마세요.|관찰한 팰 능력치를 입력하고 검증된 IV 범위를 사용하세요. 결과가 모호하면 한 값으로 고르지 말고 범위로 유지하세요.|각 건강 상태를 제공되는 치료 정보와 연결하고 제공되지 않는 세부 정보는 추정하지 마세요.|계획한 팰을 팀 빌더에 추가해 속성·작업·중복 커버리지를 확인하세요. 제공되지 않는 목적별 가중치는 순위가 아닙니다."),
  "ja-JP":combatSteps("攻撃属性と一つまたは二つの防御属性を選び、検証済みの属性スケーリング段階を比較します。これは最終総ダメージではありません。|現在の属性、威力、クールダウンでアクティブスキル候補を比較し、性能ティアは作りません。|観測したパルの能力値を入力して検証済みIV範囲を使い、曖昧な結果は一つに決めず範囲のままにします。|各健康状態を利用できる治療情報と対応させ、提供されない詳細は推測しません。|計画したパルをチームビルダーに追加し、属性・作業・重複の範囲を確認します。利用できない目的別重みは順位ではありません。"),
  "zh-CN":combatSteps("选择攻击属性和一到两个防御属性，比较已验证的属性缩放阶段；不要将其视为最终总伤害。|按当前属性、威力和冷却数据比较主动技能候选，不虚构性能等级。|输入观察到的帕鲁能力值并使用已验证的IV范围；结果有歧义时保留范围，不强选单值。|将每种健康状态与可用治疗信息对应，不估算未提供的细节。|把计划中的帕鲁加入队伍构建器，检查属性、工作和重复覆盖；不可用的目的权重不是排名。"),
  "zh-TW":combatSteps("選擇攻擊屬性和一到兩個防禦屬性，比較已驗證的屬性縮放階段；不要將其視為最終總傷害。|按目前屬性、威力和冷卻資料比較主動技能候選，不虛構效能等級。|輸入觀察到的帕魯能力值並使用已驗證的IV範圍；結果有歧義時保留範圍，不強選單值。|將每種健康狀態與可用治療資訊對應，不估算未提供的細節。|把計畫中的帕魯加入隊伍建構器，檢查屬性、工作和重複涵蓋；不可用的目的權重不是排名。"),
  "fr-FR":combatSteps("Choisissez l’élément attaquant et un ou deux éléments défenseurs, puis comparez l’étape vérifiée de mise à l’échelle sans la confondre avec les dégâts finaux totaux.|Comparez les compétences actives candidates selon leurs données actuelles d’élément, de puissance et de recharge sans inventer de palier de performance.|Saisissez les statistiques observées du Pal et utilisez les plages d’IV vérifiées ; conservez un résultat ambigu sous forme de plage.|Associez chaque état de santé aux informations de traitement disponibles et n’estimez pas les détails absents.|Ajoutez les Pals prévus au créateur d’équipe et vérifiez la couverture des éléments, du travail et des doublons ; les poids d’objectif indisponibles ne constituent pas un classement."),
  "it-IT":combatSteps("Scegli l’elemento d’attacco e uno o due elementi di difesa, quindi confronta la fase verificata di scaling senza considerarla il danno finale totale.|Confronta le abilità attive candidate usando i dati attuali di elemento, potenza e ricarica senza inventare fasce di prestazione.|Inserisci le statistiche osservate del Pal e usa gli intervalli IV verificati; mantieni un risultato ambiguo come intervallo.|Abbina ogni condizione di salute alle informazioni di trattamento disponibili senza stimare i dettagli mancanti.|Aggiungi i Pal previsti al team builder e controlla copertura di elementi, lavoro e duplicati; i pesi di scopo non disponibili non sono una classifica."),
  "de-DE":combatSteps("Wähle das Angriffselement und ein oder zwei Verteidigungselemente und vergleiche die geprüfte Elementskalierung, ohne sie als gesamten Endschaden zu behandeln.|Vergleiche aktive Fähigkeiten anhand aktueller Element-, Stärke- und Abklingdaten, ohne Leistungsstufen zu erfinden.|Gib beobachtete Pal-Werte ein und nutze die geprüften IV-Bereiche; belasse mehrdeutige Ergebnisse als Bereich.|Ordne jedem Gesundheitszustand die verfügbaren Behandlungsinformationen zu und schätze fehlende Details nicht.|Füge geplante Pals zum Teamplaner hinzu und prüfe Element-, Arbeits- und Überschneidungsabdeckung; nicht verfügbare Zweckgewichte sind keine Rangliste."),
  "es-ES":combatSteps("Elige el elemento atacante y uno o dos defensores y compara la fase verificada de escalado elemental sin tratarla como daño final total.|Compara habilidades activas por sus datos actuales de elemento, potencia y recarga sin inventar niveles de rendimiento.|Introduce las estadísticas observadas del Pal y usa los intervalos de IV verificados; conserva los resultados ambiguos como intervalos.|Relaciona cada estado de salud con la información de tratamiento disponible y no estimes los detalles ausentes.|Añade los Pals previstos al creador de equipos y revisa la cobertura de elementos, trabajos y duplicados; los pesos de propósito no disponibles no son una clasificación."),
  "es-419":combatSteps("Elige el elemento atacante y uno o dos defensores y compara la fase verificada de escalado elemental sin tratarla como daño final total.|Compara habilidades activas por sus datos actuales de elemento, potencia y enfriamiento sin inventar niveles de rendimiento.|Ingresa las estadísticas observadas del Pal y usa los rangos de IV verificados; conserva los resultados ambiguos como rangos.|Relaciona cada estado de salud con la información de tratamiento disponible y no estimes los detalles ausentes.|Agrega los Pals previstos al creador de equipos y revisa la cobertura de elementos, trabajos y duplicados; los pesos de propósito no disponibles no son una clasificación."),
  "pt-BR":combatSteps("Escolha o elemento atacante e um ou dois defensores e compare a etapa verificada de escala elemental sem tratá-la como dano final total.|Compare habilidades ativas pelos dados atuais de elemento, poder e recarga sem inventar níveis de desempenho.|Insira os atributos observados do Pal e use os intervalos de IV verificados; mantenha resultados ambíguos como intervalos.|Relacione cada condição de saúde às informações de tratamento disponíveis e não estime detalhes ausentes.|Adicione os Pals planejados ao criador de equipes e confira a cobertura de elementos, trabalhos e duplicatas; pesos de objetivo indisponíveis não são um ranking."),
  "ru-RU":combatSteps("Выберите атакующий и один или два защищающихся элемента, затем сравните проверенный этап масштабирования, не считая его полным итоговым уроном.|Сравните активные навыки по текущим данным элемента, силы и перезарядки, не создавая уровни эффективности.|Введите наблюдаемые характеристики Пала и используйте проверенные диапазоны IV; неоднозначный результат оставляйте диапазоном.|Сопоставьте каждое состояние здоровья с доступным лечением и не оценивайте отсутствующие детали.|Добавьте планируемых Палов в конструктор команды и проверьте покрытие элементов, работ и дубликатов; недоступные веса целей не являются рейтингом."),
  "id-ID":combatSteps("Pilih elemen penyerang dan satu atau dua elemen bertahan, lalu bandingkan tahap skala elemen terverifikasi tanpa menganggapnya sebagai total damage akhir.|Bandingkan kandidat skill aktif berdasarkan data elemen, power, dan cooldown saat ini tanpa membuat tier performa.|Masukkan statistik Pal yang diamati dan gunakan rentang IV terverifikasi; pertahankan hasil ambigu sebagai rentang.|Cocokkan setiap kondisi kesehatan dengan informasi perawatan yang tersedia dan jangan perkirakan detail yang tidak tersedia.|Tambahkan Pal rencana ke team builder dan periksa cakupan elemen, kerja, dan duplikasi; bobot tujuan yang tidak tersedia bukan peringkat."),
  "th-TH":combatSteps("เลือกธาตุโจมตีและธาตุป้องกันหนึ่งหรือสองธาตุ แล้วเปรียบเทียบขั้นการปรับสเกลธาตุที่ตรวจสอบแล้วโดยไม่ถือเป็นความเสียหายสุดท้ายทั้งหมด|เปรียบเทียบสกิลแอ็กทีฟจากข้อมูลธาตุ พลัง และคูลดาวน์ปัจจุบันโดยไม่สร้างระดับประสิทธิภาพ|กรอกค่าสถานะพัลที่สังเกตและใช้ช่วง IV ที่ตรวจสอบแล้ว หากผลไม่ชัดเจนให้คงเป็นช่วง|จับคู่สถานะสุขภาพแต่ละอย่างกับข้อมูลการรักษาที่มีและไม่ประมาณรายละเอียดที่ไม่มี|เพิ่มพัลที่วางแผนไว้ในเครื่องมือจัดทีมและตรวจสอบความครอบคลุมของธาตุ งาน และความซ้ำ น้ำหนักตามวัตถุประสงค์ที่ไม่มีไม่ใช่อันดับ"),
  "tr-TR":combatSteps("Saldırı elementini ve bir veya iki savunma elementini seçip doğrulanmış element ölçekleme aşamasını karşılaştırın; bunu toplam son hasar saymayın.|Aktif beceri adaylarını güncel element, güç ve bekleme süresi verileriyle karşılaştırın; performans kademesi uydurmayın.|Gözlenen Pal değerlerini girip doğrulanmış IV aralıklarını kullanın; belirsiz sonucu tek değere indirmeyin.|Her sağlık durumunu mevcut tedavi bilgisiyle eşleştirin ve bulunmayan ayrıntıları tahmin etmeyin.|Planlanan Palları takım oluşturucuya ekleyip element, iş ve tekrar kapsamını inceleyin; mevcut olmayan amaç ağırlıkları sıralama değildir."),
  "vi-VN":combatSteps("Chọn nguyên tố tấn công và một hoặc hai nguyên tố phòng thủ, rồi so sánh giai đoạn tỷ lệ nguyên tố đã xác minh mà không coi đó là tổng sát thương cuối.|So sánh kỹ năng chủ động theo dữ liệu nguyên tố, sức mạnh và hồi chiêu hiện tại mà không tự tạo bậc hiệu suất.|Nhập chỉ số Pal quan sát được và dùng khoảng IV đã xác minh; giữ kết quả mơ hồ dưới dạng khoảng.|Ghép từng tình trạng sức khỏe với thông tin điều trị hiện có và không ước tính chi tiết còn thiếu.|Thêm Pal dự kiến vào công cụ dựng đội và kiểm tra độ bao phủ nguyên tố, công việc và trùng lặp; trọng số mục đích không có không phải là xếp hạng."),
  "pl-PL":combatSteps("Wybierz żywioł ataku oraz jeden lub dwa żywioły obrony i porównaj zweryfikowany etap skalowania, nie traktując go jako całkowitych obrażeń końcowych.|Porównaj aktywne umiejętności według bieżących danych żywiołu, mocy i czasu odnowienia bez tworzenia poziomów wydajności.|Wprowadź zaobserwowane statystyki Pala i użyj zweryfikowanych zakresów IV; niejednoznaczny wynik pozostaw jako zakres.|Dopasuj każdy stan zdrowia do dostępnych informacji o leczeniu i nie szacuj brakujących szczegółów.|Dodaj planowane Pale do kreatora drużyny i sprawdź pokrycie żywiołów, pracy i duplikatów; niedostępne wagi celu nie są rankingiem."),
};
export const guideCombatStepLabelsProvenance=Object.fromEntries(Object.keys(guideCombatStepLabels).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;
const onboardingSteps=(gettingStarted:string,returningPlayer:string)=>{const first=gettingStarted.split("|"),second=returningPlayer.split("|");if(first.length!==5||second.length!==4)throw new Error("Onboarding guides need five and four specific steps");return {"getting-started":first,"returning-player":second} as const};
export const guideOnboardingStepLabels:Record<Locale,Readonly<Record<"getting-started"|"returning-player",readonly string[]>>>={
  "en-US":onboardingSteps("Choose a first destination with the map filters and accessible result list, keeping dense layers narrowed to the markers you need.|Compare Pals by their current elements and work suitability, and choose candidates for the first roles without inventing a performance tier.|Review the technology order, unlocks, and prerequisites so the next target is reachable before spending points or materials.|Set the essential work roles, minimum levels, and team limit in the base planner, then inspect the generated candidates.|Select the exact crafting recipe, calculate direct and expanded material demand, and stop where multiple recipes still require your choice.","Review the current quest catalog, objectives, and reward links, then make your own revisit list.|Compare technology prerequisites, unlocks, and dependents before committing saved points or materials.|Inspect expedition stages and reward candidates without inferring probabilities that are not provided.|Rebuild your destination shortlist from the current map filters and result list instead of relying on remembered locations."),
  "ko-KR":onboardingSteps("지도 필터와 접근 가능한 결과 목록에서 첫 목적지를 고르고, 밀집된 레이어는 필요한 마커만 남기세요.|현재 속성과 작업 적성을 기준으로 팰을 비교하고, 임의의 성능 등급 없이 첫 역할 후보를 고르세요.|포인트나 재료를 쓰기 전에 기술 순서, 해금 항목, 선행 조건을 확인하여 다음 목표에 도달할 수 있는지 점검하세요.|거점 플래너에서 필수 작업 역할, 최소 레벨, 팀 제한을 설정하고 생성된 후보를 확인하세요.|정확한 제작법을 선택해 직접·확장 재료 수요를 계산하고, 여러 제작법 중 선택이 필요한 지점에서는 확장을 멈추세요.","현재 퀘스트 목록과 목표·보상 연결을 확인한 뒤 직접 다시 살펴볼 목록을 만드세요.|모아 둔 포인트나 재료를 쓰기 전에 기술의 선행 조건, 해금 항목, 후속 기술을 비교하세요.|제공되지 않은 확률을 추론하지 말고 원정 단계와 보상 후보를 확인하세요.|기억에 의존하지 말고 현재 지도 필터와 결과 목록에서 목적지 후보를 다시 구성하세요."),
  "ja-JP":onboardingSteps("マップのフィルターと利用しやすい結果一覧で最初の目的地を選び、密集したレイヤーは必要なマーカーだけに絞ります。|現在の属性と作業適性でパルを比較し、独自の性能ランクを作らずに最初の役割候補を選びます。|ポイントや素材を使う前に、テクノロジーの順序、アンロック、前提条件を確認して次の目標に到達できるか確かめます。|拠点プランナーで必要な作業役割、最低レベル、チーム上限を設定し、生成された候補を確認します。|使用するレシピを明示して直接・展開後の素材需要を計算し、複数レシピから選択が必要な箇所では展開を止めます。","現在のクエスト一覧、目標、報酬リンクを確認し、自分で再訪リストを作ります。|保存していたポイントや素材を使う前に、テクノロジーの前提条件、アンロック、後続項目を比較します。|提示されていない確率を推測せず、遠征の段階と報酬候補を確認します。|記憶した場所に頼らず、現在のマップフィルターと結果一覧から目的地候補を作り直します。"),
  "zh-CN":onboardingSteps("使用地图筛选器和无障碍结果列表选择第一个目的地，并把密集图层缩小到所需标记。|按当前属性和工作适应性比较帕鲁，在不虚构性能等级的情况下选择首批岗位候选。|花费科技点或材料前查看科技顺序、解锁内容和前置条件，确认下一个目标可以达成。|在据点规划器中设置必要工作、最低等级和队伍上限，然后检查生成的候选。|选择确切配方，计算直接及展开后的材料需求；遇到多个有效配方时停止并由你选择。","查看当前任务目录、目标和奖励链接，再制作自己的重访清单。|投入已保存的科技点或材料前，比较科技前置条件、解锁内容和后续项目。|查看远征阶段和奖励候选，不推断未提供的概率。|不要依赖记忆中的位置，使用当前地图筛选器和结果列表重新建立目的地候选。"),
  "zh-TW":onboardingSteps("使用地圖篩選器與無障礙結果清單選擇第一個目的地，並將密集圖層縮小到所需標記。|依目前屬性與工作適性比較帕魯，不自創效能等級，選出首批職務候選。|花費科技點或材料前檢查科技順序、解鎖內容與前置條件，確認下一個目標可以達成。|在據點規劃器中設定必要工作、最低等級與隊伍上限，再檢查產生的候選。|選擇確切配方，計算直接與展開後的材料需求；遇到多個有效配方時停止並由你選擇。","查看目前任務目錄、目標與獎勵連結，再建立自己的重訪清單。|投入已保存的科技點或材料前，比較科技前置條件、解鎖內容與後續項目。|查看遠征階段與獎勵候選，不推斷未提供的機率。|不要依賴記憶中的位置，使用目前地圖篩選器與結果清單重新建立目的地候選。"),
  "fr-FR":onboardingSteps("Choisissez une première destination avec les filtres de carte et la liste de résultats accessible, en limitant les couches denses aux marqueurs utiles.|Comparez les Pals selon leurs éléments et aptitudes au travail actuels, puis choisissez les premiers rôles sans inventer de palier de performance.|Vérifiez l’ordre des technologies, les déblocages et les prérequis afin que le prochain objectif soit accessible avant de dépenser points ou matériaux.|Définissez les rôles essentiels, les niveaux minimaux et la limite d’équipe dans le planificateur de base, puis examinez les candidats générés.|Choisissez la recette exacte, calculez les besoins directs et développés, puis arrêtez-vous lorsqu’un choix entre plusieurs recettes reste nécessaire.","Consultez le catalogue actuel des quêtes, leurs objectifs et leurs récompenses, puis créez votre propre liste à revisiter.|Comparez les prérequis, déblocages et dépendances des technologies avant d’engager vos points ou matériaux conservés.|Examinez les étapes d’expédition et les récompenses possibles sans déduire de probabilités non fournies.|Recréez votre liste de destinations avec les filtres et résultats actuels de la carte plutôt qu’avec vos souvenirs."),
  "it-IT":onboardingSteps("Scegli una prima destinazione con i filtri della mappa e l’elenco accessibile dei risultati, limitando i livelli densi ai soli indicatori necessari.|Confronta i Pal per elemento e attitudine al lavoro attuali e scegli i candidati per i primi ruoli senza inventare fasce di prestazione.|Controlla ordine, sblocchi e prerequisiti delle tecnologie prima di spendere punti o materiali, così che il prossimo obiettivo sia raggiungibile.|Imposta ruoli essenziali, livelli minimi e limite della squadra nel pianificatore della base, quindi esamina i candidati generati.|Scegli la ricetta esatta, calcola la richiesta diretta ed espansa di materiali e fermati dove più ricette richiedono ancora una scelta.","Consulta il catalogo attuale di missioni, obiettivi e collegamenti alle ricompense, quindi crea il tuo elenco da rivedere.|Confronta prerequisiti, sblocchi e dipendenze delle tecnologie prima di usare punti o materiali conservati.|Esamina le fasi delle spedizioni e le ricompense candidate senza dedurre probabilità non fornite.|Ricostruisci l’elenco delle destinazioni con i filtri e i risultati attuali della mappa invece di affidarti ai luoghi ricordati."),
  "de-DE":onboardingSteps("Wähle mit den Kartenfiltern und der zugänglichen Ergebnisliste ein erstes Ziel und begrenze dichte Ebenen auf die benötigten Markierungen.|Vergleiche Pals nach ihren aktuellen Elementen und Arbeitseignungen und wähle Kandidaten für die ersten Rollen, ohne Leistungsstufen zu erfinden.|Prüfe Technologiereihenfolge, Freischaltungen und Voraussetzungen, bevor du Punkte oder Materialien ausgibst, damit das nächste Ziel erreichbar ist.|Lege im Basisplaner notwendige Arbeitsrollen, Mindeststufen und das Teamlimit fest und prüfe anschließend die erzeugten Kandidaten.|Wähle das genaue Rezept, berechne direkten und erweiterten Materialbedarf und stoppe, wenn mehrere Rezepte noch deine Entscheidung verlangen.","Prüfe den aktuellen Questkatalog samt Zielen und Belohnungsverknüpfungen und erstelle danach deine eigene Wiederkehrliste.|Vergleiche Voraussetzungen, Freischaltungen und abhängige Technologien, bevor du gesparte Punkte oder Materialien einsetzt.|Prüfe Expeditionsstufen und mögliche Belohnungen, ohne nicht angegebene Wahrscheinlichkeiten abzuleiten.|Erstelle deine Zielliste mit den aktuellen Kartenfiltern und Ergebnissen neu, statt dich auf erinnerte Orte zu verlassen."),
  "es-ES":onboardingSteps("Elige un primer destino con los filtros del mapa y la lista de resultados accesible, limitando las capas densas a los marcadores necesarios.|Compara los Pals por sus elementos y aptitudes laborales actuales y elige candidatos para los primeros puestos sin inventar niveles de rendimiento.|Revisa el orden, los desbloqueos y los requisitos de tecnología antes de gastar puntos o materiales para que el siguiente objetivo sea alcanzable.|Configura los trabajos esenciales, los niveles mínimos y el límite del equipo en el planificador de base y revisa los candidatos generados.|Elige la receta exacta, calcula la demanda directa y ampliada de materiales y detente cuando varias recetas aún requieran tu elección.","Revisa el catálogo actual de misiones, sus objetivos y enlaces de recompensas, y crea tu propia lista para volver.|Compara requisitos, desbloqueos y tecnologías dependientes antes de usar puntos o materiales guardados.|Examina las fases de expedición y las posibles recompensas sin deducir probabilidades que no se proporcionan.|Reconstruye tu lista de destinos con los filtros y resultados actuales del mapa en vez de confiar en ubicaciones recordadas."),
  "es-419":onboardingSteps("Elige un primer destino con los filtros del mapa y la lista accesible de resultados, limitando las capas densas a los marcadores necesarios.|Compara los Pals por sus elementos y aptitudes de trabajo actuales y elige candidatos para los primeros roles sin inventar niveles de rendimiento.|Revisa el orden, los desbloqueos y los requisitos de tecnología antes de gastar puntos o materiales para que el siguiente objetivo sea alcanzable.|Configura los trabajos esenciales, los niveles mínimos y el límite del equipo en el planificador de base y revisa los candidatos generados.|Elige la receta exacta, calcula la demanda directa y ampliada de materiales y detente cuando varias recetas aún requieran tu elección.","Revisa el catálogo actual de misiones, sus objetivos y enlaces de recompensas, y crea tu propia lista para volver.|Compara requisitos, desbloqueos y tecnologías dependientes antes de usar puntos o materiales guardados.|Revisa las etapas de expedición y las recompensas posibles sin inferir probabilidades que no se proporcionan.|Reconstruye tu lista de destinos con los filtros y resultados actuales del mapa en vez de confiar en ubicaciones recordadas."),
  "pt-BR":onboardingSteps("Escolha um primeiro destino com os filtros do mapa e a lista acessível de resultados, limitando camadas densas aos marcadores necessários.|Compare os Pals por elementos e aptidões de trabalho atuais e escolha candidatos para as primeiras funções sem inventar níveis de desempenho.|Revise a ordem, os desbloqueios e os pré-requisitos de tecnologia antes de gastar pontos ou materiais para garantir que o próximo objetivo seja alcançável.|Defina trabalhos essenciais, níveis mínimos e limite da equipe no planejador de base e examine os candidatos gerados.|Escolha a receita exata, calcule a demanda direta e expandida de materiais e pare quando várias receitas ainda exigirem sua escolha.","Revise o catálogo atual de missões, seus objetivos e links de recompensas e crie sua própria lista para revisitar.|Compare pré-requisitos, desbloqueios e tecnologias dependentes antes de usar pontos ou materiais guardados.|Examine as etapas de expedição e as possíveis recompensas sem inferir probabilidades não fornecidas.|Refaça sua lista de destinos com os filtros e resultados atuais do mapa em vez de depender de locais lembrados."),
  "ru-RU":onboardingSteps("Выберите первую цель с помощью фильтров карты и доступного списка результатов, ограничив плотные слои только нужными метками.|Сравните Палов по их текущим стихиям и пригодности к работе и выберите кандидатов на первые роли без выдуманных уровней эффективности.|Проверьте порядок технологий, открытия и требования до траты очков или материалов, чтобы следующая цель была достижима.|Задайте в планировщике базы необходимые рабочие роли, минимальные уровни и лимит команды, затем проверьте предложенных кандидатов.|Выберите точный рецепт, рассчитайте прямую и развёрнутую потребность в материалах и остановитесь там, где выбор между рецептами остаётся за вами.","Просмотрите текущий каталог заданий, цели и связи с наградами, затем составьте собственный список для повторного посещения.|Сравните требования, открытия и зависимые технологии до использования сохранённых очков или материалов.|Изучите этапы экспедиций и возможные награды, не выводя отсутствующие вероятности.|Составьте список целей заново по текущим фильтрам и результатам карты, а не по запомнившимся местам."),
  "id-ID":onboardingSteps("Pilih tujuan pertama dengan filter peta dan daftar hasil yang mudah diakses, serta batasi lapisan padat pada penanda yang diperlukan.|Bandingkan Pal berdasarkan elemen dan work suitability saat ini, lalu pilih kandidat untuk peran awal tanpa membuat tier performa.|Tinjau urutan teknologi, unlock, dan prasyarat sebelum memakai poin atau bahan agar target berikutnya dapat dicapai.|Atur peran kerja penting, level minimum, dan batas tim di perencana base, lalu periksa kandidat yang dihasilkan.|Pilih resep yang tepat, hitung kebutuhan bahan langsung dan terurai, lalu berhenti ketika beberapa resep masih memerlukan pilihan Anda.","Tinjau katalog quest saat ini, objektif, dan tautan hadiah, lalu buat daftar kunjungan ulang Anda sendiri.|Bandingkan prasyarat, unlock, dan teknologi lanjutan sebelum memakai poin atau bahan yang disimpan.|Periksa tahap ekspedisi dan kandidat hadiah tanpa menyimpulkan probabilitas yang tidak tersedia.|Susun ulang daftar tujuan dari filter dan hasil peta saat ini, bukan dari lokasi yang diingat."),
  "th-TH":onboardingSteps("เลือกจุดหมายแรกด้วยตัวกรองแผนที่และรายการผลลัพธ์ที่เข้าถึงได้ โดยจำกัดเลเยอร์ที่หนาแน่นให้เหลือเฉพาะหมุดที่ต้องการ|เปรียบเทียบ Pal ตามธาตุและความถนัดงานปัจจุบัน แล้วเลือกผู้สมัครสำหรับบทบาทแรกโดยไม่สร้างระดับประสิทธิภาพขึ้นเอง|ตรวจสอบลำดับเทคโนโลยี สิ่งที่ปลดล็อก และข้อกำหนดก่อนใช้แต้ม หรือวัตถุดิบ เพื่อให้เป้าหมายถัดไปเข้าถึงได้|กำหนดบทบาทงานที่จำเป็น เลเวลขั้นต่ำ และขีดจำกัดทีมในเครื่องมือวางแผนฐาน แล้วตรวจสอบผู้สมัครที่สร้างขึ้น|เลือกสูตรที่แน่นอน คำนวณวัตถุดิบโดยตรงและแบบขยาย และหยุดเมื่อมีหลายสูตรที่ยังต้องให้คุณเลือก","ตรวจสอบรายการเควสต์ เป้าหมาย และลิงก์รางวัลปัจจุบัน แล้วทำรายการที่คุณต้องการกลับไปดูเอง|เปรียบเทียบข้อกำหนด สิ่งที่ปลดล็อก และเทคโนโลยีที่ต่อเนื่องก่อนใช้แต้ม หรือวัตถุดิบที่เก็บไว้|ตรวจสอบขั้นของการสำรวจและรางวัลที่เป็นไปได้ โดยไม่อนุมานความน่าจะเป็นที่ไม่ได้ระบุ|สร้างรายชื่อจุดหมายใหม่จากตัวกรองและผลลัพธ์แผนที่ปัจจุบัน แทนการพึ่งพาตำแหน่งที่จำได้"),
  "tr-TR":onboardingSteps("Harita filtreleri ve erişilebilir sonuç listesiyle ilk hedefi seçin; yoğun katmanları yalnızca gereken işaretlerle sınırlandırın.|Palları güncel elementleri ve iş uygunluklarıyla karşılaştırın; performans kademesi uydurmadan ilk roller için aday seçin.|Puan veya malzeme harcamadan önce teknoloji sırasını, açılanları ve ön koşulları inceleyerek sonraki hedefin erişilebilir olduğunu doğrulayın.|Üs planlayıcıda gerekli iş rollerini, asgari seviyeleri ve takım sınırını belirleyip üretilen adayları inceleyin.|Kesin tarifi seçin, doğrudan ve genişletilmiş malzeme ihtiyacını hesaplayın ve birden çok tarif seçiminizi gerektirdiğinde durun.","Güncel görev kataloğunu, hedefleri ve ödül bağlantılarını inceleyip kendi yeniden ziyaret listenizi oluşturun.|Biriktirilmiş puan veya malzemeleri kullanmadan önce teknoloji ön koşullarını, açılanları ve bağımlı teknolojileri karşılaştırın.|Verilmeyen olasılıkları çıkarsamadan keşif aşamalarını ve olası ödülleri inceleyin.|Hatırlanan konumlara güvenmek yerine güncel harita filtreleri ve sonuçlarından hedef listenizi yeniden oluşturun."),
  "vi-VN":onboardingSteps("Chọn điểm đến đầu tiên bằng bộ lọc bản đồ và danh sách kết quả dễ tiếp cận, đồng thời thu hẹp các lớp dày đặc về những dấu mốc cần thiết.|So sánh Pal theo nguyên tố và khả năng làm việc hiện tại, rồi chọn ứng viên cho các vai trò đầu tiên mà không tự đặt hạng hiệu suất.|Xem thứ tự công nghệ, nội dung mở khóa và điều kiện trước khi dùng điểm hoặc vật liệu để bảo đảm mục tiêu tiếp theo có thể đạt được.|Đặt vai trò công việc thiết yếu, cấp tối thiểu và giới hạn đội trong công cụ lập kế hoạch căn cứ, rồi xem các ứng viên được tạo.|Chọn đúng công thức, tính nhu cầu vật liệu trực tiếp và mở rộng, rồi dừng ở nơi nhiều công thức vẫn cần bạn lựa chọn.","Xem danh mục nhiệm vụ hiện tại, mục tiêu và liên kết phần thưởng, rồi tự tạo danh sách cần xem lại.|So sánh điều kiện, nội dung mở khóa và công nghệ phụ thuộc trước khi dùng điểm hoặc vật liệu đã giữ lại.|Xem các giai đoạn viễn chinh và phần thưởng có thể có mà không suy diễn xác suất không được cung cấp.|Tạo lại danh sách điểm đến từ bộ lọc và kết quả bản đồ hiện tại thay vì dựa vào vị trí đã nhớ."),
  "pl-PL":onboardingSteps("Wybierz pierwszy cel za pomocą filtrów mapy i dostępnej listy wyników, ograniczając gęste warstwy do potrzebnych znaczników.|Porównaj Pale według bieżących żywiołów i przydatności do pracy, a następnie wybierz kandydatów do pierwszych ról bez wymyślania poziomów wydajności.|Sprawdź kolejność technologii, odblokowania i wymagania przed wydaniem punktów lub materiałów, aby następny cel był osiągalny.|Ustaw w planerze bazy niezbędne role pracy, minimalne poziomy i limit drużyny, a następnie sprawdź wygenerowanych kandydatów.|Wybierz dokładną recepturę, oblicz bezpośrednie i rozwinięte zapotrzebowanie na materiały i zatrzymaj się, gdy kilka receptur nadal wymaga twojego wyboru.","Przejrzyj aktualny katalog zadań, cele i powiązania nagród, a następnie utwórz własną listę do ponownego sprawdzenia.|Porównaj wymagania, odblokowania i technologie zależne przed użyciem zachowanych punktów lub materiałów.|Sprawdź etapy ekspedycji i możliwe nagrody bez wnioskowania o niepodanych prawdopodobieństwach.|Zbuduj listę celów ponownie z aktualnych filtrów i wyników mapy, zamiast polegać na zapamiętanych miejscach."),
};
export const guideOnboardingStepLabelsProvenance=Object.fromEntries(Object.keys(guideOnboardingStepLabels).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;
export const guideSpecificSteps=(locale:Locale,id:GuideId)=>id==="getting-started"||id==="returning-player"?guideOnboardingStepLabels[locale][id]:id==="breeding"?guideBreedingStepLabels[locale]:id==="base"?guideBaseStepLabels[locale]:id==="combat"?guideCombatStepLabels[locale]:guideSpecificStepLabels[locale][id];

export type GuideStructureCopy={problem:string;preparation:string;preparationIntro:string;procedure:string;result:string;resultIntro:string;stepAction:string;confirm:string;coverage:string;coverageIntro:string;entries:string};

export const guideMetricKindLabels:Record<Locale,Record<GuideMetricKind,string>>={
  "en-US":{locations:"map points",pals:"Pals",entries:"catalog entries",recipes:"recipes",combinations:"breeding combinations",skills:"skills","work-roles":"work roles",settings:"supported settings",conditions:"health conditions"},
  "ko-KR":{locations:"지도 지점",pals:"팰",entries:"도감 항목",recipes:"레시피",combinations:"교배 조합",skills:"스킬","work-roles":"작업 역할",settings:"지원 설정",conditions:"건강 상태"},
  "ja-JP":{locations:"マップ地点",pals:"パル",entries:"カタログ項目",recipes:"レシピ",combinations:"配合組み合わせ",skills:"スキル","work-roles":"作業役割",settings:"対応設定",conditions:"健康状態"},
  "zh-CN":{locations:"地图点位",pals:"帕鲁",entries:"图鉴条目",recipes:"配方",combinations:"配种组合",skills:"技能","work-roles":"工作角色",settings:"支持的设置",conditions:"健康状态"},
  "zh-TW":{locations:"地圖點位",pals:"帕魯",entries:"圖鑑條目",recipes:"配方",combinations:"配種組合",skills:"技能","work-roles":"工作角色",settings:"支援設定",conditions:"健康狀態"},
  "fr-FR":{locations:"points de carte",pals:"Pals",entries:"entrées du catalogue",recipes:"recettes",combinations:"combinaisons d’élevage",skills:"compétences","work-roles":"rôles de travail",settings:"paramètres pris en charge",conditions:"états de santé"},
  "it-IT":{locations:"punti mappa",pals:"Pal",entries:"voci del catalogo",recipes:"ricette",combinations:"combinazioni di riproduzione",skills:"abilità","work-roles":"ruoli di lavoro",settings:"impostazioni supportate",conditions:"condizioni di salute"},
  "de-DE":{locations:"Kartenpunkte",pals:"Pals",entries:"Katalogeinträge",recipes:"Rezepte",combinations:"Zuchtkombinationen",skills:"Fähigkeiten","work-roles":"Arbeitsrollen",settings:"unterstützte Einstellungen",conditions:"Gesundheitszustände"},
  "es-ES":{locations:"puntos del mapa",pals:"Pals",entries:"entradas del catálogo",recipes:"recetas",combinations:"combinaciones de cría",skills:"habilidades","work-roles":"roles de trabajo",settings:"ajustes compatibles",conditions:"estados de salud"},
  "es-419":{locations:"puntos del mapa",pals:"Pals",entries:"entradas del catálogo",recipes:"recetas",combinations:"combinaciones de cría",skills:"habilidades","work-roles":"roles de trabajo",settings:"ajustes compatibles",conditions:"estados de salud"},
  "pt-BR":{locations:"pontos do mapa",pals:"Pals",entries:"entradas do catálogo",recipes:"receitas",combinations:"combinações de reprodução",skills:"habilidades","work-roles":"funções de trabalho",settings:"configurações compatíveis",conditions:"condições de saúde"},
  "ru-RU":{locations:"точек карты",pals:"Палов",entries:"записей каталога",recipes:"рецептов",combinations:"комбинаций разведения",skills:"навыков","work-roles":"рабочих ролей",settings:"поддерживаемых настроек",conditions:"состояний здоровья"},
  "id-ID":{locations:"titik peta",pals:"Pal",entries:"entri katalog",recipes:"resep",combinations:"kombinasi breeding",skills:"skill","work-roles":"peran kerja",settings:"pengaturan yang didukung",conditions:"kondisi kesehatan"},
  "th-TH":{locations:"จุดบนแผนที่",pals:"พัล",entries:"รายการแค็ตตาล็อก",recipes:"สูตร",combinations:"คู่ผสมพันธุ์",skills:"สกิล","work-roles":"บทบาทงาน",settings:"การตั้งค่าที่รองรับ",conditions:"สถานะสุขภาพ"},
  "tr-TR":{locations:"harita noktası",pals:"Pal",entries:"katalog kaydı",recipes:"tarif",combinations:"üretme kombinasyonu",skills:"beceri","work-roles":"iş rolü",settings:"desteklenen ayar",conditions:"sağlık durumu"},
  "vi-VN":{locations:"điểm bản đồ",pals:"Pal",entries:"mục danh mục",recipes:"công thức",combinations:"tổ hợp phối giống",skills:"kỹ năng","work-roles":"vai trò công việc",settings:"thiết lập được hỗ trợ",conditions:"tình trạng sức khỏe"},
  "pl-PL":{locations:"punktów mapy",pals:"Pali",entries:"wpisów katalogu",recipes:"receptur",combinations:"kombinacji hodowlanych",skills:"umiejętności","work-roles":"ról pracy",settings:"obsługiwanych ustawień",conditions:"stanów zdrowia"},
};

export const guideStructureCopy:Record<Locale,GuideStructureCopy>={
  "en-US":{problem:"Goal",preparation:"Before you start",preparationIntro:"Keep these verified tools open so each decision uses the current catalog.",procedure:"Step-by-step procedure",result:"Check the result",resultIntro:"Before you spend resources or apply changes, confirm each checkpoint.",stepAction:"Review the current information, make this decision, then continue.",confirm:"Confirmed: {name}",coverage:"Current verified coverage",coverageIntro:"These counts are generated from the same data used by the linked tools and update with them.",entries:"entries"},
  "ko-KR":{problem:"목표",preparation:"시작 전 준비",preparationIntro:"각 결정을 현재 데이터로 확인할 수 있도록 다음 검증된 도구를 준비하세요.",procedure:"단계별 절차",result:"결과 확인",resultIntro:"자원을 사용하거나 변경 사항을 적용하기 전에 각 항목을 확인하세요.",stepAction:"현재 정보를 검토하고 이 단계를 결정한 뒤 다음으로 진행하세요.",confirm:"확인 완료: {name}",coverage:"현재 검증 범위",coverageIntro:"이 수치는 연결된 도구와 동일한 데이터에서 자동 생성되며 함께 갱신됩니다.",entries:"개 항목"},
  "ja-JP":{problem:"目的",preparation:"始める前の準備",preparationIntro:"各判断を現在のデータで確認できるよう、検証済みツールを開いておきます。",procedure:"手順",result:"結果の確認",resultIntro:"資源を使う、または変更を適用する前に各項目を確認してください。",stepAction:"現在の情報を確認して判断し、次へ進みます。",confirm:"確認済み：{name}",coverage:"現在の検証範囲",coverageIntro:"この件数はリンク先と同じデータから自動生成され、同時に更新されます。",entries:"件"},
  "zh-CN":{problem:"目标",preparation:"开始前准备",preparationIntro:"打开这些已验证工具，确保每个决定都基于当前数据。",procedure:"分步流程",result:"检查结果",resultIntro:"消耗资源或应用更改前，请确认每个检查点。",stepAction:"查看当前信息，完成此项决定，然后继续。",confirm:"已确认：{name}",coverage:"当前验证范围",coverageIntro:"这些数量由链接工具使用的同一数据自动生成，并同步更新。",entries:"项"},
  "zh-TW":{problem:"目標",preparation:"開始前準備",preparationIntro:"開啟這些已驗證工具，確保每個決定都使用目前資料。",procedure:"逐步流程",result:"檢查結果",resultIntro:"花費資源或套用變更前，請確認每個檢查點。",stepAction:"檢視目前資訊，完成此項決定後再繼續。",confirm:"已確認：{name}",coverage:"目前驗證範圍",coverageIntro:"這些數量由連結工具使用的相同資料自動產生，並同步更新。",entries:"項"},
  "fr-FR":{problem:"Objectif",preparation:"Avant de commencer",preparationIntro:"Gardez ces outils vérifiés ouverts afin que chaque décision utilise le catalogue actuel.",procedure:"Procédure étape par étape",result:"Vérifier le résultat",resultIntro:"Avant de dépenser des ressources ou d’appliquer des changements, confirmez chaque point.",stepAction:"Consultez les informations actuelles, prenez cette décision, puis continuez.",confirm:"Confirmé : {name}",coverage:"Couverture vérifiée actuelle",coverageIntro:"Ces nombres sont générés depuis les mêmes données que les outils liés et sont mis à jour avec eux.",entries:"entrées"},
  "it-IT":{problem:"Obiettivo",preparation:"Prima di iniziare",preparationIntro:"Tieni aperti questi strumenti verificati affinché ogni decisione usi il catalogo attuale.",procedure:"Procedura passo passo",result:"Controlla il risultato",resultIntro:"Prima di spendere risorse o applicare modifiche, conferma ogni punto.",stepAction:"Controlla le informazioni attuali, prendi questa decisione e continua.",confirm:"Confermato: {name}",coverage:"Copertura verificata attuale",coverageIntro:"Questi conteggi sono generati dagli stessi dati degli strumenti collegati e si aggiornano con essi.",entries:"voci"},
  "de-DE":{problem:"Ziel",preparation:"Vor dem Start",preparationIntro:"Halte diese geprüften Werkzeuge offen, damit jede Entscheidung auf dem aktuellen Katalog beruht.",procedure:"Schritt-für-Schritt-Ablauf",result:"Ergebnis prüfen",resultIntro:"Bestätige jeden Punkt, bevor du Ressourcen ausgibst oder Änderungen anwendest.",stepAction:"Prüfe die aktuellen Informationen, triff diese Entscheidung und fahre fort.",confirm:"Bestätigt: {name}",coverage:"Aktuell geprüfter Umfang",coverageIntro:"Diese Zahlen werden aus denselben Daten wie die verknüpften Werkzeuge erzeugt und mit ihnen aktualisiert.",entries:"Einträge"},
  "es-ES":{problem:"Objetivo",preparation:"Antes de empezar",preparationIntro:"Mantén abiertas estas herramientas verificadas para que cada decisión use el catálogo actual.",procedure:"Procedimiento paso a paso",result:"Comprobar el resultado",resultIntro:"Antes de gastar recursos o aplicar cambios, confirma cada punto.",stepAction:"Revisa la información actual, toma esta decisión y continúa.",confirm:"Confirmado: {name}",coverage:"Cobertura verificada actual",coverageIntro:"Estas cantidades se generan con los mismos datos que usan las herramientas enlazadas y se actualizan con ellas.",entries:"entradas"},
  "es-419":{problem:"Objetivo",preparation:"Antes de empezar",preparationIntro:"Mantén abiertas estas herramientas verificadas para que cada decisión use el catálogo actual.",procedure:"Procedimiento paso a paso",result:"Comprobar el resultado",resultIntro:"Antes de gastar recursos o aplicar cambios, confirma cada punto.",stepAction:"Revisa la información actual, toma esta decisión y continúa.",confirm:"Confirmado: {name}",coverage:"Cobertura verificada actual",coverageIntro:"Estas cantidades se generan con los mismos datos que usan las herramientas enlazadas y se actualizan con ellas.",entries:"entradas"},
  "pt-BR":{problem:"Objetivo",preparation:"Antes de começar",preparationIntro:"Mantenha estas ferramentas verificadas abertas para que cada decisão use o catálogo atual.",procedure:"Procedimento passo a passo",result:"Verificar o resultado",resultIntro:"Antes de gastar recursos ou aplicar mudanças, confirme cada ponto.",stepAction:"Revise as informações atuais, tome esta decisão e continue.",confirm:"Confirmado: {name}",coverage:"Cobertura verificada atual",coverageIntro:"Estas contagens são geradas pelos mesmos dados das ferramentas vinculadas e atualizadas com elas.",entries:"entradas"},
  "ru-RU":{problem:"Цель",preparation:"Перед началом",preparationIntro:"Держите эти проверенные инструменты открытыми, чтобы решения опирались на актуальный каталог.",procedure:"Пошаговый порядок",result:"Проверка результата",resultIntro:"Перед расходом ресурсов или применением изменений подтвердите каждый пункт.",stepAction:"Проверьте актуальные сведения, примите решение и продолжайте.",confirm:"Подтверждено: {name}",coverage:"Текущий проверенный охват",coverageIntro:"Эти числа создаются из тех же данных, что и связанные инструменты, и обновляются вместе с ними.",entries:"записей"},
  "id-ID":{problem:"Tujuan",preparation:"Sebelum mulai",preparationIntro:"Biarkan alat terverifikasi ini terbuka agar setiap keputusan memakai katalog terkini.",procedure:"Prosedur langkah demi langkah",result:"Periksa hasil",resultIntro:"Sebelum memakai sumber daya atau menerapkan perubahan, pastikan setiap poin.",stepAction:"Tinjau informasi terkini, ambil keputusan ini, lalu lanjutkan.",confirm:"Dikonfirmasi: {name}",coverage:"Cakupan terverifikasi saat ini",coverageIntro:"Jumlah ini dibuat dari data yang sama dengan alat tertaut dan diperbarui bersamanya.",entries:"entri"},
  "th-TH":{problem:"เป้าหมาย",preparation:"ก่อนเริ่ม",preparationIntro:"เปิดเครื่องมือที่ตรวจสอบแล้วเหล่านี้ไว้ เพื่อให้ทุกการตัดสินใจใช้ข้อมูลปัจจุบัน",procedure:"ขั้นตอนการทำงาน",result:"ตรวจสอบผลลัพธ์",resultIntro:"ก่อนใช้ทรัพยากรหรือใช้การเปลี่ยนแปลง ให้ยืนยันแต่ละรายการ",stepAction:"ตรวจสอบข้อมูลปัจจุบัน ตัดสินใจในขั้นตอนนี้ แล้วจึงดำเนินการต่อ",confirm:"ยืนยันแล้ว: {name}",coverage:"ขอบเขตที่ตรวจสอบแล้วปัจจุบัน",coverageIntro:"จำนวนเหล่านี้สร้างจากข้อมูลเดียวกับเครื่องมือที่เชื่อมโยงและอัปเดตพร้อมกัน",entries:"รายการ"},
  "tr-TR":{problem:"Hedef",preparation:"Başlamadan önce",preparationIntro:"Her karar güncel kataloğu kullansın diye bu doğrulanmış araçları açık tutun.",procedure:"Adım adım işlem",result:"Sonucu kontrol et",resultIntro:"Kaynak harcamadan veya değişiklik uygulamadan önce her noktayı doğrulayın.",stepAction:"Güncel bilgileri inceleyin, bu kararı verin ve devam edin.",confirm:"Doğrulandı: {name}",coverage:"Güncel doğrulanmış kapsam",coverageIntro:"Bu sayılar bağlantılı araçlarla aynı verilerden üretilir ve onlarla birlikte güncellenir.",entries:"kayıt"},
  "vi-VN":{problem:"Mục tiêu",preparation:"Trước khi bắt đầu",preparationIntro:"Mở sẵn các công cụ đã xác minh để mọi quyết định dùng danh mục hiện tại.",procedure:"Quy trình từng bước",result:"Kiểm tra kết quả",resultIntro:"Trước khi dùng tài nguyên hoặc áp dụng thay đổi, hãy xác nhận từng mục.",stepAction:"Xem thông tin hiện tại, đưa ra quyết định ở bước này rồi tiếp tục.",confirm:"Đã xác nhận: {name}",coverage:"Phạm vi đã xác minh hiện tại",coverageIntro:"Các số lượng này được tạo từ cùng dữ liệu với công cụ liên kết và được cập nhật cùng nhau.",entries:"mục"},
  "pl-PL":{problem:"Cel",preparation:"Przed rozpoczęciem",preparationIntro:"Pozostaw te zweryfikowane narzędzia otwarte, aby każda decyzja korzystała z aktualnego katalogu.",procedure:"Procedura krok po kroku",result:"Sprawdź wynik",resultIntro:"Przed wydaniem zasobów lub zastosowaniem zmian potwierdź każdy punkt.",stepAction:"Sprawdź aktualne informacje, podejmij tę decyzję i przejdź dalej.",confirm:"Potwierdzono: {name}",coverage:"Aktualny zweryfikowany zakres",coverageIntro:"Te liczby są generowane z tych samych danych co połączone narzędzia i aktualizowane razem z nimi.",entries:"wpisów"},
};

type GuideText={title:string;description:string};
export type GuideCopy={
  hubTitle:string;hubDescription:string;eyebrow:string;workflow:string;workflowIntro:string;
  open:string;related:string;scope:string;scopeText:string;guides:Record<GuideId,GuideText>;
};

const make=(hubTitle:string,hubDescription:string,eyebrow:string,workflow:string,workflowIntro:string,open:string,related:string,scope:string,scopeText:string,values:string):GuideCopy=>{
  const parts=values.split("|");
  if(parts.length!==guideDefinitions.length*2)throw new Error(`Guide copy needs ${guideDefinitions.length*2} values`);
  return {hubTitle,hubDescription,eyebrow,workflow,workflowIntro,open,related,scope,scopeText,guides:Object.fromEntries(guideDefinitions.map((guide,index)=>[guide.id,{title:parts[index*2],description:parts[index*2+1]}])) as Record<GuideId,GuideText>};
};

export const guideCopy:Record<Locale,GuideCopy>={
  "en-US":make("Palworld guides","Task-focused workflows that connect the verified map, databases, calculators, and server tools.","Practical guide","Recommended workflow","Open each linked tool in order, confirm the current data, and keep the result beside your game.","Open workflow","Related tools","Accuracy boundary","These guides organize verified site data. Values or formulas that are not verified remain unavailable instead of being estimated.","First steps and first base|Use the map, Pal catalog, and base planner to choose a safe first route and cover essential work roles.|Returning-player checklist|Review quests, technology, and expeditions before spending resources after a major update.|Breeding fundamentals|Check current parent-to-child relationships and passive skills without treating a shortest path as the most practical route.|Goal-based base operations|Start from the work your base must perform, then connect Pal roles, crafting demand, and structures.|Dedicated server setup and backup|Prepare settings from the current official key inventory, validate warnings, and apply the file with a backup and restart plan.|Combat preparation|Compare verified element scaling, active skills, health conditions, and treatments before a difficult encounter."),
  "ko-KR":make("팰월드 가이드","검증된 지도, 데이터베이스, 계산기와 서버 도구를 실제 플레이 순서로 연결한 작업 중심 가이드입니다.","실전 가이드","권장 진행 순서","연결된 도구를 순서대로 열어 현재 데이터를 확인하고, 결과를 게임 옆에 두고 활용하세요.","워크플로 열기","관련 도구","정확도 범위","이 가이드는 사이트에서 검증된 정보를 정리합니다. 검증되지 않은 값이나 공식은 추정하지 않고 제공하지 않습니다.","첫 시작과 첫 거점|지도, 팰 도감과 거점 계산기로 안전한 첫 동선과 필수 작업 역할을 정리합니다.|복귀 플레이어 점검표|대규모 업데이트 뒤 자원을 쓰기 전에 퀘스트, 기술과 탐험을 확인합니다.|교배 기초|최단 경로를 가장 실용적인 경로로 오해하지 않도록 현재 부모-자식 관계와 패시브 스킬을 확인합니다.|목표 중심 거점 운영|거점에서 수행할 작업부터 정하고 팰 역할, 제작 수요와 건축물을 연결합니다.|전용 서버 설정과 백업|현재 공식 키 목록으로 설정을 만들고 경고를 검증한 뒤 백업과 재시작 계획에 따라 적용합니다.|전투 준비|어려운 전투 전에 검증된 속성 배율, 액티브 스킬, 건강 상태와 치료법을 비교합니다."),
  "ja-JP":make("Palworld ガイド","検証済みのマップ、データベース、計算機、サーバーツールを実際の手順でつなぐガイドです。","実践ガイド","推奨ワークフロー","リンク先を順番に開き、現在のデータを確認してゲーム中に参照してください。","ワークフローを開く","関連ツール","精度の範囲","検証済み情報のみを整理し、未検証の値や式は推測せず利用不可のままにします。","最初の一歩と最初の拠点|マップ、パル図鑑、拠点計画で安全な序盤ルートと必要な作業役を決めます。|復帰プレイヤーの確認項目|大型更新後に資源を使う前にクエスト、テクノロジー、探索を確認します。|配合の基本|最短経路を最も実用的な経路とせず、親子関係とパッシブスキルを確認します。|目的別の拠点運営|必要な作業からパルの役割、クラフト需要、建築物をつなげます。|専用サーバー設定とバックアップ|現在の公式キーで設定を作り、警告を確認してバックアップ後に適用します。|戦闘準備|難しい戦闘の前に属性倍率、アクティブスキル、健康状態と治療を比較します。"),
  "zh-CN":make("Palworld 指南","把已验证的地图、数据库、计算器和服务器工具连接成实际流程。","实用指南","推荐流程","按顺序打开链接工具，确认当前数据，并在游戏时参考结果。","打开流程","相关工具","准确性范围","指南只整理已验证的信息；未验证的数值或公式不会被估算。","初期步骤与首个据点|使用地图、帕鲁图鉴和据点规划器安排安全路线与必要岗位。|回归玩家检查表|大型更新后先检查任务、科技和探险，再投入资源。|配种基础|检查当前亲子关系和被动技能，不把最短路线称为最实用路线。|按目标运营据点|从据点需要的工作出发，连接帕鲁岗位、制作需求和建筑。|专用服务器设置与备份|按当前官方键生成设置，检查警告，并在备份后应用。|战斗准备|困难战斗前比较已验证的属性倍率、主动技能、健康状态与治疗。"),
  "zh-TW":make("Palworld 指南","把已驗證的地圖、資料庫、計算器與伺服器工具連成實際流程。","實用指南","建議流程","依序開啟連結工具，確認目前資料，並在遊戲時參考結果。","開啟流程","相關工具","準確性範圍","指南只整理已驗證資訊；未驗證的數值或公式不會被估算。","初期步驟與首個據點|使用地圖、帕魯圖鑑與據點規劃器安排安全路線和必要職務。|回歸玩家檢查表|大型更新後先檢查任務、科技與探險，再投入資源。|配種基礎|檢查目前親子關係與被動技能，不把最短路線稱為最實用路線。|依目標營運據點|從據點需要的工作出發，連結帕魯職務、製作需求與建築。|專用伺服器設定與備份|依目前官方鍵產生設定、檢查警告，並在備份後套用。|戰鬥準備|困難戰鬥前比較已驗證的屬性倍率、主動技能、健康狀態與治療。"),
  "fr-FR":make("Guides Palworld","Des parcours pratiques reliant la carte, les bases de données, les calculateurs et les outils serveur vérifiés.","Guide pratique","Parcours recommandé","Ouvrez chaque outil dans l’ordre, vérifiez les données actuelles et gardez le résultat à côté du jeu.","Ouvrir le parcours","Outils associés","Limite de précision","Ces guides organisent les données vérifiées. Les valeurs et formules non vérifiées ne sont pas estimées.","Premiers pas et première base|Utilisez la carte, le catalogue de Pals et le planificateur de base pour définir une route sûre et les rôles essentiels.|Liste de contrôle pour reprendre|Vérifiez les quêtes, technologies et expéditions avant de dépenser des ressources après une mise à jour majeure.|Principes de l’élevage|Vérifiez les liens parents-enfant et les compétences passives sans présenter le chemin le plus court comme le plus pratique.|Gestion d’une base par objectif|Partez du travail nécessaire puis reliez rôles des Pals, besoins de fabrication et structures.|Serveur dédié et sauvegarde|Créez les réglages avec les clés officielles actuelles, contrôlez les alertes et appliquez-les après sauvegarde.|Préparation au combat|Comparez les multiplicateurs élémentaires vérifiés, compétences actives, états de santé et soins."),
  "it-IT":make("Guide di Palworld","Flussi pratici che collegano mappa, database, calcolatori e strumenti server verificati.","Guida pratica","Flusso consigliato","Apri gli strumenti in ordine, controlla i dati attuali e tieni il risultato accanto al gioco.","Apri il flusso","Strumenti correlati","Limite di accuratezza","Le guide organizzano dati verificati; valori e formule non verificati non vengono stimati.","Primi passi e prima base|Usa mappa, catalogo Pal e pianificatore base per scegliere un percorso sicuro e i ruoli essenziali.|Controllo per chi ritorna|Controlla missioni, tecnologia e spedizioni prima di spendere risorse dopo un grande aggiornamento.|Fondamenti di allevamento|Controlla relazioni genitori-figli e abilità passive senza definire il percorso più breve come il più pratico.|Gestione della base per obiettivi|Parti dal lavoro necessario e collega ruoli dei Pal, richieste di creazione e strutture.|Server dedicato e backup|Crea le impostazioni dalle chiavi ufficiali attuali, controlla gli avvisi e applicale dopo il backup.|Preparazione al combattimento|Confronta moltiplicatori elementali verificati, abilità attive, condizioni di salute e cure."),
  "de-DE":make("Palworld-Guides","Praktische Abläufe, die verifizierte Karte, Datenbanken, Rechner und Serverwerkzeuge verbinden.","Praxis-Guide","Empfohlener Ablauf","Öffne die verknüpften Werkzeuge der Reihe nach, prüfe aktuelle Daten und nutze das Ergebnis beim Spielen.","Ablauf öffnen","Verwandte Werkzeuge","Genauigkeitsgrenze","Die Guides ordnen verifizierte Daten. Ungeprüfte Werte und Formeln werden nicht geschätzt.","Erste Schritte und erste Basis|Nutze Karte, Pal-Katalog und Basisplaner für eine sichere Route und wichtige Arbeitsrollen.|Checkliste für Rückkehrer|Prüfe Quests, Technologie und Expeditionen, bevor du nach einem großen Update Ressourcen ausgibst.|Zuchtgrundlagen|Prüfe Eltern-Kind-Beziehungen und passive Fähigkeiten, ohne den kürzesten Weg als praktischsten zu bezeichnen.|Zielorientierter Basisbetrieb|Beginne mit der benötigten Arbeit und verbinde Pal-Rollen, Herstellungsbedarf und Gebäude.|Dedicated Server und Sicherung|Erstelle Einstellungen mit aktuellen offiziellen Schlüsseln, prüfe Warnungen und wende sie nach einer Sicherung an.|Kampfvorbereitung|Vergleiche verifizierte Elementfaktoren, aktive Fähigkeiten, Gesundheitszustände und Behandlungen."),
  "es-ES":make("Guías de Palworld","Flujos prácticos que conectan el mapa, las bases de datos, las calculadoras y las herramientas de servidor verificadas.","Guía práctica","Flujo recomendado","Abre cada herramienta en orden, confirma los datos actuales y conserva el resultado junto al juego.","Abrir flujo","Herramientas relacionadas","Límite de precisión","Las guías organizan datos verificados; no estiman valores ni fórmulas sin verificar.","Primeros pasos y primera base|Usa el mapa, el catálogo de Pals y el planificador de base para elegir una ruta segura y cubrir trabajos esenciales.|Lista para jugadores que regresan|Revisa misiones, tecnología y expediciones antes de gastar recursos tras una gran actualización.|Fundamentos de crianza|Comprueba relaciones de padres e hijos y habilidades pasivas sin llamar más práctica a la ruta más corta.|Operación de base por objetivos|Empieza por el trabajo necesario y conecta roles de Pals, demanda de fabricación y estructuras.|Servidor dedicado y copias de seguridad|Crea ajustes con las claves oficiales actuales, valida avisos y aplícalos tras hacer una copia.|Preparación para el combate|Compara multiplicadores elementales verificados, habilidades activas, estados de salud y tratamientos."),
  "es-419":make("Guías de Palworld","Flujos prácticos que conectan el mapa, las bases de datos, las calculadoras y las herramientas de servidor verificadas.","Guía práctica","Flujo recomendado","Abre cada herramienta en orden, confirma los datos actuales y conserva el resultado junto al juego.","Abrir flujo","Herramientas relacionadas","Límite de precisión","Las guías organizan datos verificados; no estiman valores ni fórmulas sin verificar.","Primeros pasos y primera base|Usa el mapa, el catálogo de Pals y el planificador de base para elegir una ruta segura y cubrir trabajos esenciales.|Lista para jugadores que regresan|Revisa misiones, tecnología y expediciones antes de gastar recursos tras una gran actualización.|Fundamentos de crianza|Comprueba relaciones de padres e hijos y habilidades pasivas sin llamar más práctica a la ruta más corta.|Operación de base por objetivos|Empieza por el trabajo necesario y conecta roles de Pals, demanda de fabricación y estructuras.|Servidor dedicado y respaldos|Crea ajustes con las claves oficiales actuales, valida avisos y aplícalos después de respaldar.|Preparación para el combate|Compara multiplicadores elementales verificados, habilidades activas, estados de salud y tratamientos."),
  "pt-BR":make("Guias de Palworld","Fluxos práticos que conectam mapa, bancos de dados, calculadoras e ferramentas de servidor verificadas.","Guia prático","Fluxo recomendado","Abra cada ferramenta em ordem, confirme os dados atuais e mantenha o resultado ao lado do jogo.","Abrir fluxo","Ferramentas relacionadas","Limite de precisão","Os guias organizam dados verificados; valores e fórmulas não verificados não são estimados.","Primeiros passos e primeira base|Use o mapa, o catálogo de Pals e o planejador de base para escolher uma rota segura e cobrir trabalhos essenciais.|Checklist para quem retorna|Revise missões, tecnologia e expedições antes de gastar recursos após uma grande atualização.|Fundamentos de reprodução|Confira relações entre pais e filhos e habilidades passivas sem chamar o caminho mais curto de mais prático.|Operação da base por objetivo|Comece pelo trabalho necessário e conecte funções dos Pals, demanda de criação e estruturas.|Servidor dedicado e backup|Crie configurações com as chaves oficiais atuais, valide avisos e aplique após o backup.|Preparação para combate|Compare multiplicadores elementais verificados, habilidades ativas, condições de saúde e tratamentos."),
  "ru-RU":make("Руководства Palworld","Практические процессы, связывающие проверенные карту, базы данных, калькуляторы и серверные инструменты.","Практическое руководство","Рекомендуемый порядок","Открывайте инструменты по порядку, проверяйте актуальные данные и используйте результат во время игры.","Открыть процесс","Связанные инструменты","Граница точности","Руководства используют проверенные данные; непроверенные значения и формулы не оцениваются.","Первые шаги и первая база|Используйте карту, каталог Палов и планировщик базы для безопасного маршрута и основных работ.|Проверка для вернувшихся игроков|Проверьте задания, технологии и экспедиции до траты ресурсов после крупного обновления.|Основы разведения|Проверяйте связи родителей и потомков и пассивные навыки, не называя кратчайший путь самым практичным.|Работа базы по цели|Начните с нужной работы и свяжите роли Палов, производство и постройки.|Выделенный сервер и резервная копия|Создайте настройки по актуальным официальным ключам, проверьте предупреждения и примените после копирования.|Подготовка к бою|Сравните проверенные множители стихий, активные навыки, состояния здоровья и лечение."),
  "id-ID":make("Panduan Palworld","Alur praktis yang menghubungkan peta, basis data, kalkulator, dan alat server terverifikasi.","Panduan praktis","Alur yang disarankan","Buka alat tertaut secara berurutan, periksa data saat ini, dan gunakan hasilnya saat bermain.","Buka alur","Alat terkait","Batas akurasi","Panduan mengatur data terverifikasi; nilai dan rumus yang belum terverifikasi tidak diperkirakan.","Langkah awal dan base pertama|Gunakan peta, katalog Pal, dan perencana base untuk rute aman serta peran kerja penting.|Checklist pemain yang kembali|Periksa quest, teknologi, dan ekspedisi sebelum memakai sumber daya setelah pembaruan besar.|Dasar breeding|Periksa hubungan induk-anak dan skill pasif tanpa menyebut jalur terpendek sebagai yang paling praktis.|Operasi base berdasarkan tujuan|Mulai dari pekerjaan yang dibutuhkan lalu hubungkan peran Pal, kebutuhan crafting, dan struktur.|Server khusus dan cadangan|Buat pengaturan dari kunci resmi saat ini, periksa peringatan, lalu terapkan setelah mencadangkan.|Persiapan pertempuran|Bandingkan pengali elemen terverifikasi, skill aktif, kondisi kesehatan, dan perawatan."),
  "th-TH":make("คู่มือ Palworld","ขั้นตอนใช้งานที่เชื่อมแผนที่ ฐานข้อมูล เครื่องคำนวณ และเครื่องมือเซิร์ฟเวอร์ที่ตรวจสอบแล้ว","คู่มือใช้งาน","ลำดับที่แนะนำ","เปิดเครื่องมือที่เชื่อมโยงตามลำดับ ตรวจสอบข้อมูลปัจจุบัน และใช้ผลลัพธ์ระหว่างเล่น","เปิดขั้นตอน","เครื่องมือที่เกี่ยวข้อง","ขอบเขตความแม่นยำ","คู่มือนี้จัดข้อมูลที่ตรวจสอบแล้ว และไม่ประมาณค่าหรือสูตรที่ยังไม่ตรวจสอบ","เริ่มต้นและฐานแรก|ใช้แผนที่ รายการ Pal และตัววางแผนฐานเพื่อเลือกเส้นทางปลอดภัยและงานสำคัญ|รายการตรวจสอบสำหรับผู้กลับมา|ตรวจภารกิจ เทคโนโลยี และการสำรวจก่อนใช้ทรัพยากรหลังอัปเดตใหญ่|พื้นฐานการผสมพันธุ์|ตรวจความสัมพันธ์พ่อแม่กับลูกและสกิลติดตัว โดยไม่เรียกเส้นทางสั้นที่สุดว่าใช้งานดีที่สุด|การจัดการฐานตามเป้าหมาย|เริ่มจากงานที่ต้องทำ แล้วเชื่อมบทบาท Pal ความต้องการคราฟต์ และสิ่งปลูกสร้าง|เซิร์ฟเวอร์เฉพาะและการสำรอง|สร้างค่าจากคีย์ทางการปัจจุบัน ตรวจคำเตือน และใช้หลังสำรองข้อมูล|เตรียมการต่อสู้|เปรียบเทียบตัวคูณธาตุที่ตรวจสอบแล้ว สกิลใช้งาน สภาวะสุขภาพ และการรักษา"),
  "tr-TR":make("Palworld rehberleri","Doğrulanmış harita, veri tabanları, hesaplayıcılar ve sunucu araçlarını bağlayan pratik akışlar.","Pratik rehber","Önerilen akış","Bağlantılı araçları sırayla açın, güncel verileri doğrulayın ve sonucu oyun yanında kullanın.","Akışı aç","İlgili araçlar","Doğruluk sınırı","Rehberler doğrulanmış verileri düzenler; doğrulanmamış değer ve formüller tahmin edilmez.","İlk adımlar ve ilk üs|Güvenli rota ve temel işler için harita, Pal kataloğu ve üs planlayıcıyı kullanın.|Geri dönen oyuncu kontrolü|Büyük güncellemeden sonra kaynak harcamadan önce görevleri, teknolojiyi ve seferleri inceleyin.|Üretme temelleri|En kısa yolu en pratik saymadan ebeveyn-yavru ilişkilerini ve pasif becerileri kontrol edin.|Hedef odaklı üs işletimi|Gerekli işten başlayıp Pal rollerini, üretim talebini ve yapıları bağlayın.|Özel sunucu ve yedekleme|Güncel resmî anahtarlarla ayar oluşturun, uyarıları denetleyin ve yedekten sonra uygulayın.|Savaşa hazırlık|Doğrulanmış element çarpanlarını, aktif becerileri, sağlık durumlarını ve tedavileri karşılaştırın."),
  "vi-VN":make("Hướng dẫn Palworld","Quy trình thực tế kết nối bản đồ, cơ sở dữ liệu, công cụ tính và công cụ máy chủ đã xác minh.","Hướng dẫn thực tế","Quy trình đề xuất","Mở từng công cụ theo thứ tự, kiểm tra dữ liệu hiện tại và dùng kết quả khi chơi.","Mở quy trình","Công cụ liên quan","Giới hạn độ chính xác","Hướng dẫn sắp xếp dữ liệu đã xác minh; giá trị và công thức chưa xác minh không được ước tính.","Bước đầu và căn cứ đầu tiên|Dùng bản đồ, danh mục Pal và trình lập kế hoạch căn cứ để chọn tuyến an toàn và công việc thiết yếu.|Danh sách cho người chơi quay lại|Kiểm tra nhiệm vụ, công nghệ và thám hiểm trước khi dùng tài nguyên sau bản cập nhật lớn.|Cơ bản về phối giống|Kiểm tra quan hệ cha mẹ-con và kỹ năng bị động, không gọi đường ngắn nhất là thực tế nhất.|Vận hành căn cứ theo mục tiêu|Bắt đầu từ công việc cần làm rồi nối vai trò Pal, nhu cầu chế tạo và công trình.|Máy chủ riêng và sao lưu|Tạo thiết lập từ khóa chính thức hiện tại, kiểm tra cảnh báo và áp dụng sau khi sao lưu.|Chuẩn bị chiến đấu|So sánh hệ số nguyên tố đã xác minh, kỹ năng chủ động, tình trạng sức khỏe và điều trị."),
  "pl-PL":make("Poradniki Palworld","Praktyczne procesy łączące zweryfikowaną mapę, bazy danych, kalkulatory i narzędzia serwera.","Poradnik praktyczny","Zalecany proces","Otwieraj narzędzia po kolei, sprawdzaj aktualne dane i korzystaj z wyniku podczas gry.","Otwórz proces","Powiązane narzędzia","Granica dokładności","Poradniki porządkują zweryfikowane dane; niezweryfikowane wartości i wzory nie są szacowane.","Pierwsze kroki i pierwsza baza|Użyj mapy, katalogu Pali i planera bazy, aby wybrać bezpieczną trasę i ważne role pracy.|Lista dla powracających graczy|Sprawdź zadania, technologię i ekspedycje przed wydaniem zasobów po dużej aktualizacji.|Podstawy hodowli|Sprawdź relacje rodzic-potomek i umiejętności pasywne, nie nazywając najkrótszej drogi najbardziej praktyczną.|Baza według celu|Zacznij od potrzebnej pracy i połącz role Pali, zapotrzebowanie produkcji oraz budowle.|Serwer dedykowany i kopia|Utwórz ustawienia z aktualnych oficjalnych kluczy, sprawdź ostrzeżenia i zastosuj po wykonaniu kopii.|Przygotowanie do walki|Porównaj zweryfikowane mnożniki żywiołów, aktywne umiejętności, stany zdrowia i leczenie."),
};

export const guideCopyProvenance=Object.fromEntries(Object.keys(guideCopy).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;

export const guideRoute=(slug:string)=>`guides/${slug}`;
export const findGuide=(route:string)=>guideDefinitions.find(guide=>guideRoute(guide.slug)===route);
