import type {Locale} from "./config";

export type GuideId="getting-started"|"returning-player"|"breeding"|"base"|"server"|"combat";
export type GuideDefinition={id:GuideId;slug:GuideId;related:readonly string[];reviewTrigger:string};

export const guideDefinitions=[
  {id:"getting-started",slug:"getting-started",related:["map","pals","database/technology","calculators/base","calculators/crafting"],reviewTrigger:"major progression or map change"},
  {id:"returning-player",slug:"returning-player",related:["database/quests","database/technology","database/expeditions","map"],reviewTrigger:"major content update"},
  {id:"breeding",slug:"breeding",related:["pals","calculators/breeding","calculators/breeding-path","skills/passive","calculators/team-builder"],reviewTrigger:"breeding rule or Pal roster change"},
  {id:"base",slug:"base",related:["calculators/base","pals","database/structures","calculators/crafting","database"],reviewTrigger:"work suitability, recipe, or structure change"},
  {id:"server",slug:"server",related:["server-tools/settings-generator","calculators/base","database/structures","calculators/crafting"],reviewTrigger:"official server guide change"},
  {id:"combat",slug:"combat",related:["database/elements","skills/active","calculators/iv","database/health","calculators/team-builder"],reviewTrigger:"element, condition, or active-skill change"},
] as const satisfies readonly GuideDefinition[];

export type GuideStructureCopy={problem:string;preparation:string;preparationIntro:string;procedure:string;result:string;resultIntro:string;stepAction:string;confirm:string};

export const guideStructureCopy:Record<Locale,GuideStructureCopy>={
  "en-US":{problem:"Goal",preparation:"Before you start",preparationIntro:"Keep these verified tools open so each decision uses the current catalog.",procedure:"Step-by-step procedure",result:"Check the result",resultIntro:"Before you spend resources or apply changes, confirm each checkpoint.",stepAction:"Review the current information, make this decision, then continue.",confirm:"Confirmed: {name}"},
  "ko-KR":{problem:"목표",preparation:"시작 전 준비",preparationIntro:"각 결정을 현재 데이터로 확인할 수 있도록 다음 검증된 도구를 준비하세요.",procedure:"단계별 절차",result:"결과 확인",resultIntro:"자원을 사용하거나 변경 사항을 적용하기 전에 각 항목을 확인하세요.",stepAction:"현재 정보를 검토하고 이 단계를 결정한 뒤 다음으로 진행하세요.",confirm:"확인 완료: {name}"},
  "ja-JP":{problem:"目的",preparation:"始める前の準備",preparationIntro:"各判断を現在のデータで確認できるよう、検証済みツールを開いておきます。",procedure:"手順",result:"結果の確認",resultIntro:"資源を使う、または変更を適用する前に各項目を確認してください。",stepAction:"現在の情報を確認して判断し、次へ進みます。",confirm:"確認済み：{name}"},
  "zh-CN":{problem:"目标",preparation:"开始前准备",preparationIntro:"打开这些已验证工具，确保每个决定都基于当前数据。",procedure:"分步流程",result:"检查结果",resultIntro:"消耗资源或应用更改前，请确认每个检查点。",stepAction:"查看当前信息，完成此项决定，然后继续。",confirm:"已确认：{name}"},
  "zh-TW":{problem:"目標",preparation:"開始前準備",preparationIntro:"開啟這些已驗證工具，確保每個決定都使用目前資料。",procedure:"逐步流程",result:"檢查結果",resultIntro:"花費資源或套用變更前，請確認每個檢查點。",stepAction:"檢視目前資訊，完成此項決定後再繼續。",confirm:"已確認：{name}"},
  "fr-FR":{problem:"Objectif",preparation:"Avant de commencer",preparationIntro:"Gardez ces outils vérifiés ouverts afin que chaque décision utilise le catalogue actuel.",procedure:"Procédure étape par étape",result:"Vérifier le résultat",resultIntro:"Avant de dépenser des ressources ou d’appliquer des changements, confirmez chaque point.",stepAction:"Consultez les informations actuelles, prenez cette décision, puis continuez.",confirm:"Confirmé : {name}"},
  "it-IT":{problem:"Obiettivo",preparation:"Prima di iniziare",preparationIntro:"Tieni aperti questi strumenti verificati affinché ogni decisione usi il catalogo attuale.",procedure:"Procedura passo passo",result:"Controlla il risultato",resultIntro:"Prima di spendere risorse o applicare modifiche, conferma ogni punto.",stepAction:"Controlla le informazioni attuali, prendi questa decisione e continua.",confirm:"Confermato: {name}"},
  "de-DE":{problem:"Ziel",preparation:"Vor dem Start",preparationIntro:"Halte diese geprüften Werkzeuge offen, damit jede Entscheidung auf dem aktuellen Katalog beruht.",procedure:"Schritt-für-Schritt-Ablauf",result:"Ergebnis prüfen",resultIntro:"Bestätige jeden Punkt, bevor du Ressourcen ausgibst oder Änderungen anwendest.",stepAction:"Prüfe die aktuellen Informationen, triff diese Entscheidung und fahre fort.",confirm:"Bestätigt: {name}"},
  "es-ES":{problem:"Objetivo",preparation:"Antes de empezar",preparationIntro:"Mantén abiertas estas herramientas verificadas para que cada decisión use el catálogo actual.",procedure:"Procedimiento paso a paso",result:"Comprobar el resultado",resultIntro:"Antes de gastar recursos o aplicar cambios, confirma cada punto.",stepAction:"Revisa la información actual, toma esta decisión y continúa.",confirm:"Confirmado: {name}"},
  "es-419":{problem:"Objetivo",preparation:"Antes de empezar",preparationIntro:"Mantén abiertas estas herramientas verificadas para que cada decisión use el catálogo actual.",procedure:"Procedimiento paso a paso",result:"Comprobar el resultado",resultIntro:"Antes de gastar recursos o aplicar cambios, confirma cada punto.",stepAction:"Revisa la información actual, toma esta decisión y continúa.",confirm:"Confirmado: {name}"},
  "pt-BR":{problem:"Objetivo",preparation:"Antes de começar",preparationIntro:"Mantenha estas ferramentas verificadas abertas para que cada decisão use o catálogo atual.",procedure:"Procedimento passo a passo",result:"Verificar o resultado",resultIntro:"Antes de gastar recursos ou aplicar mudanças, confirme cada ponto.",stepAction:"Revise as informações atuais, tome esta decisão e continue.",confirm:"Confirmado: {name}"},
  "ru-RU":{problem:"Цель",preparation:"Перед началом",preparationIntro:"Держите эти проверенные инструменты открытыми, чтобы решения опирались на актуальный каталог.",procedure:"Пошаговый порядок",result:"Проверка результата",resultIntro:"Перед расходом ресурсов или применением изменений подтвердите каждый пункт.",stepAction:"Проверьте актуальные сведения, примите решение и продолжайте.",confirm:"Подтверждено: {name}"},
  "id-ID":{problem:"Tujuan",preparation:"Sebelum mulai",preparationIntro:"Biarkan alat terverifikasi ini terbuka agar setiap keputusan memakai katalog terkini.",procedure:"Prosedur langkah demi langkah",result:"Periksa hasil",resultIntro:"Sebelum memakai sumber daya atau menerapkan perubahan, pastikan setiap poin.",stepAction:"Tinjau informasi terkini, ambil keputusan ini, lalu lanjutkan.",confirm:"Dikonfirmasi: {name}"},
  "th-TH":{problem:"เป้าหมาย",preparation:"ก่อนเริ่ม",preparationIntro:"เปิดเครื่องมือที่ตรวจสอบแล้วเหล่านี้ไว้ เพื่อให้ทุกการตัดสินใจใช้ข้อมูลปัจจุบัน",procedure:"ขั้นตอนการทำงาน",result:"ตรวจสอบผลลัพธ์",resultIntro:"ก่อนใช้ทรัพยากรหรือใช้การเปลี่ยนแปลง ให้ยืนยันแต่ละรายการ",stepAction:"ตรวจสอบข้อมูลปัจจุบัน ตัดสินใจในขั้นตอนนี้ แล้วจึงดำเนินการต่อ",confirm:"ยืนยันแล้ว: {name}"},
  "tr-TR":{problem:"Hedef",preparation:"Başlamadan önce",preparationIntro:"Her karar güncel kataloğu kullansın diye bu doğrulanmış araçları açık tutun.",procedure:"Adım adım işlem",result:"Sonucu kontrol et",resultIntro:"Kaynak harcamadan veya değişiklik uygulamadan önce her noktayı doğrulayın.",stepAction:"Güncel bilgileri inceleyin, bu kararı verin ve devam edin.",confirm:"Doğrulandı: {name}"},
  "vi-VN":{problem:"Mục tiêu",preparation:"Trước khi bắt đầu",preparationIntro:"Mở sẵn các công cụ đã xác minh để mọi quyết định dùng danh mục hiện tại.",procedure:"Quy trình từng bước",result:"Kiểm tra kết quả",resultIntro:"Trước khi dùng tài nguyên hoặc áp dụng thay đổi, hãy xác nhận từng mục.",stepAction:"Xem thông tin hiện tại, đưa ra quyết định ở bước này rồi tiếp tục.",confirm:"Đã xác nhận: {name}"},
  "pl-PL":{problem:"Cel",preparation:"Przed rozpoczęciem",preparationIntro:"Pozostaw te zweryfikowane narzędzia otwarte, aby każda decyzja korzystała z aktualnego katalogu.",procedure:"Procedura krok po kroku",result:"Sprawdź wynik",resultIntro:"Przed wydaniem zasobów lub zastosowaniem zmian potwierdź każdy punkt.",stepAction:"Sprawdź aktualne informacje, podejmij tę decyzję i przejdź dalej.",confirm:"Potwierdzono: {name}"},
};

type GuideText={title:string;description:string};
export type GuideCopy={
  hubTitle:string;hubDescription:string;eyebrow:string;workflow:string;workflowIntro:string;
  open:string;related:string;scope:string;scopeText:string;guides:Record<GuideId,GuideText>;
};

const make=(hubTitle:string,hubDescription:string,eyebrow:string,workflow:string,workflowIntro:string,open:string,related:string,scope:string,scopeText:string,values:string):GuideCopy=>{
  const parts=values.split("|");
  if(parts.length!==guideDefinitions.length*2)throw new Error(`Guide copy needs ${guideDefinitions.length*2} values`);
  return {hubTitle,hubDescription,eyebrow,workflow,workflowIntro,open,related,scope,scopeText,guides:Object.fromEntries(guideDefinitions.map((guide,index)=>[guide.id,{title:parts[index*2],description:parts[index*2+1]}])) as Record<GuideId,GuideText>};
};

export const guideCopy:Record<Locale,GuideCopy>={
  "en-US":make("Palworld guides","Task-focused workflows that connect the verified map, databases, calculators, and server tools.","Practical guide","Recommended workflow","Open each linked tool in order, confirm the current data, and keep the result beside your game.","Open workflow","Related tools","Accuracy boundary","These guides organize verified site data. Values or formulas that are not verified remain unavailable instead of being estimated.","First steps and first base|Use the map, Pal catalog, and base planner to choose a safe first route and cover essential work roles.|Returning-player checklist|Review quests, technology, and expeditions before spending resources after a major update.|Breeding fundamentals|Check current parent-to-child relationships and passive skills without treating a shortest path as the most practical route.|Goal-based base operations|Start from the work your base must perform, then connect Pal roles, crafting demand, and structures.|Dedicated server setup and backup|Prepare settings from the current official key inventory, validate warnings, and apply the file with a backup and restart plan.|Combat preparation|Compare verified element scaling, active skills, health conditions, and treatments before a difficult encounter."),
  "ko-KR":make("팰월드 가이드","검증된 지도, 데이터베이스, 계산기와 서버 도구를 실제 플레이 순서로 연결한 작업 중심 가이드입니다.","실전 가이드","권장 진행 순서","연결된 도구를 순서대로 열어 현재 데이터를 확인하고, 결과를 게임 옆에 두고 활용하세요.","워크플로 열기","관련 도구","정확도 범위","이 가이드는 사이트에서 검증된 정보를 정리합니다. 검증되지 않은 값이나 공식은 추정하지 않고 제공하지 않습니다.","첫 시작과 첫 거점|지도, 팰 도감과 거점 계산기로 안전한 첫 동선과 필수 작업 역할을 정리합니다.|복귀 플레이어 점검표|대규모 업데이트 뒤 자원을 쓰기 전에 퀘스트, 기술과 탐험을 확인합니다.|교배 기초|최단 경로를 가장 실용적인 경로로 오해하지 않도록 현재 부모-자식 관계와 패시브 스킬을 확인합니다.|목표 중심 거점 운영|거점에서 수행할 작업부터 정하고 팰 역할, 제작 수요와 건축물을 연결합니다.|전용 서버 설정과 백업|현재 공식 키 목록으로 설정을 만들고 경고를 검증한 뒤 백업과 재시작 계획에 따라 적용합니다.|전투 준비|어려운 전투 전에 검증된 속성 배율, 액티브 스킬, 건강 상태와 치료법을 비교합니다."),
  "ja-JP":make("Palworld ガイド","検証済みのマップ、データベース、計算機、サーバーツールを実際の手順でつなぐガイドです。","実践ガイド","推奨ワークフロー","リンク先を順番に開き、現在のデータを確認してゲーム中に参照してください。","ワークフローを開く","関連ツール","精度の範囲","検証済み情報のみを整理し、未検証の値や式は推測せず利用不可のままにします。","最初の一歩と最初の拠点|マップ、パル図鑑、拠点計画で安全な序盤ルートと必要な作業役を決めます。|復帰プレイヤーの確認項目|大型更新後に資源を使う前にクエスト、テクノロジー、探索を確認します。|配合の基本|最短経路を最も実用的な経路とせず、親子関係とパッシブスキルを確認します。|目的別の拠点運営|必要な作業からパルの役割、クラフト需要、建築物をつなげます。|専用サーバー設定とバックアップ|現在の公式キーで設定を作り、警告を確認してバックアップ後に適用します。|戦闘準備|難しい戦闘の前に属性倍率、アクティブスキル、健康状態と治療を比較します。"),
  "zh-CN":make("Palworld 指南","把已验证的地图、数据库、计算器和服务器工具连接成实际流程。","实用指南","推荐流程","按顺序打开链接工具，确认当前数据，并在游戏时参考结果。","打开流程","相关工具","准确性范围","指南只整理已验证的信息；未验证的数值或公式不会被估算。","初期步骤与首个据点|使用地图、帕鲁图鉴和据点规划器安排安全路线与必要岗位。|回归玩家检查表|大型更新后先检查任务、科技和探险，再投入资源。|配种基础|检查当前亲子关系和被动技能，不把最短路线称为最实用路线。|按目标运营据点|从据点需要的工作出发，连接帕鲁岗位、制作需求和建筑。|专用服务器设置与备份|按当前官方键生成设置，检查警告，并在备份后应用。|战斗准备|困难战斗前比较已验证的属性倍率、主动技能、健康状态与治疗。"),
  "zh-TW":make("Palworld 指南","把已驗證的地圖、資料庫、計算器與伺服器工具連成實際流程。","實用指南","建議流程","依序開啟連結工具，確認目前資料，並在遊戲時參考結果。","開啟流程","相關工具","準確性範圍","指南只整理已驗證資訊；未驗證的數值或公式不會被估算。","初期步驟與首個據點|使用地圖、帕魯圖鑑與據點規劃器安排安全路線和必要職務。|回歸玩家檢查表|大型更新後先檢查任務、科技與探險，再投入資源。|配種基礎|檢查目前親子關係與被動技能，不把最短路線稱為最實用路線。|依目標營運據點|從據點需要的工作出發，連結帕魯職務、製作需求與建築。|專用伺服器設定與備份|依目前官方鍵產生設定、檢查警告，並在備份後套用。|戰鬥準備|困難戰鬥前比較已驗證的屬性倍率、主動技能、健康狀態與治療。"),
  "fr-FR":make("Guides Palworld","Des parcours pratiques reliant la carte, les bases de données, les calculateurs et les outils serveur vérifiés.","Guide pratique","Parcours recommandé","Ouvrez chaque outil dans l’ordre, vérifiez les données actuelles et gardez le résultat à côté du jeu.","Ouvrir le parcours","Outils associés","Limite de précision","Ces guides organisent les données vérifiées. Les valeurs et formules non vérifiées ne sont pas estimées.","Premiers pas et première base|Utilisez la carte, le catalogue de Pals et le planificateur de base pour définir une route sûre et les rôles essentiels.|Liste de contrôle pour reprendre|Vérifiez les quêtes, technologies et expéditions avant de dépenser des ressources après une mise à jour majeure.|Principes de l’élevage|Vérifiez les liens parents-enfant et les compétences passives sans présenter le chemin le plus court comme le plus pratique.|Gestion d’une base par objectif|Partez du travail nécessaire puis reliez rôles des Pals, besoins de fabrication et structures.|Serveur dédié et sauvegarde|Créez les réglages avec les clés officielles actuelles, contrôlez les alertes et appliquez-les après sauvegarde.|Préparation au combat|Comparez les multiplicateurs élémentaires vérifiés, compétences actives, états de santé et soins."),
  "it-IT":make("Guide di Palworld","Flussi pratici che collegano mappa, database, calcolatori e strumenti server verificati.","Guida pratica","Flusso consigliato","Apri gli strumenti in ordine, controlla i dati attuali e tieni il risultato accanto al gioco.","Apri il flusso","Strumenti correlati","Limite di accuratezza","Le guide organizzano dati verificati; valori e formule non verificati non vengono stimati.","Primi passi e prima base|Usa mappa, catalogo Pal e pianificatore base per scegliere un percorso sicuro e i ruoli essenziali.|Controllo per chi ritorna|Controlla missioni, tecnologia e spedizioni prima di spendere risorse dopo un grande aggiornamento.|Fondamenti di allevamento|Controlla relazioni genitori-figli e abilità passive senza definire il percorso più breve come il più pratico.|Gestione della base per obiettivi|Parti dal lavoro necessario e collega ruoli dei Pal, richieste di creazione e strutture.|Server dedicato e backup|Crea le impostazioni dalle chiavi ufficiali attuali, controlla gli avvisi e applicale dopo il backup.|Preparazione al combattimento|Confronta moltiplicatori elementali verificati, abilità attive, condizioni di salute e cure."),
  "de-DE":make("Palworld-Guides","Praktische Abläufe, die verifizierte Karte, Datenbanken, Rechner und Serverwerkzeuge verbinden.","Praxis-Guide","Empfohlener Ablauf","Öffne die verknüpften Werkzeuge der Reihe nach, prüfe aktuelle Daten und nutze das Ergebnis beim Spielen.","Ablauf öffnen","Verwandte Werkzeuge","Genauigkeitsgrenze","Die Guides ordnen verifizierte Daten. Ungeprüfte Werte und Formeln werden nicht geschätzt.","Erste Schritte und erste Basis|Nutze Karte, Pal-Katalog und Basisplaner für eine sichere Route und wichtige Arbeitsrollen.|Checkliste für Rückkehrer|Prüfe Quests, Technologie und Expeditionen, bevor du nach einem großen Update Ressourcen ausgibst.|Zuchtgrundlagen|Prüfe Eltern-Kind-Beziehungen und passive Fähigkeiten, ohne den kürzesten Weg als praktischsten zu bezeichnen.|Zielorientierter Basisbetrieb|Beginne mit der benötigten Arbeit und verbinde Pal-Rollen, Herstellungsbedarf und Gebäude.|Dedicated Server und Sicherung|Erstelle Einstellungen mit aktuellen offiziellen Schlüsseln, prüfe Warnungen und wende sie nach einer Sicherung an.|Kampfvorbereitung|Vergleiche verifizierte Elementfaktoren, aktive Fähigkeiten, Gesundheitszustände und Behandlungen."),
  "es-ES":make("Guías de Palworld","Flujos prácticos que conectan el mapa, las bases de datos, las calculadoras y las herramientas de servidor verificadas.","Guía práctica","Flujo recomendado","Abre cada herramienta en orden, confirma los datos actuales y conserva el resultado junto al juego.","Abrir flujo","Herramientas relacionadas","Límite de precisión","Las guías organizan datos verificados; no estiman valores ni fórmulas sin verificar.","Primeros pasos y primera base|Usa el mapa, el catálogo de Pals y el planificador de base para elegir una ruta segura y cubrir trabajos esenciales.|Lista para jugadores que regresan|Revisa misiones, tecnología y expediciones antes de gastar recursos tras una gran actualización.|Fundamentos de crianza|Comprueba relaciones de padres e hijos y habilidades pasivas sin llamar más práctica a la ruta más corta.|Operación de base por objetivos|Empieza por el trabajo necesario y conecta roles de Pals, demanda de fabricación y estructuras.|Servidor dedicado y copias de seguridad|Crea ajustes con las claves oficiales actuales, valida avisos y aplícalos tras hacer una copia.|Preparación para el combate|Compara multiplicadores elementales verificados, habilidades activas, estados de salud y tratamientos."),
  "es-419":make("Guías de Palworld","Flujos prácticos que conectan el mapa, las bases de datos, las calculadoras y las herramientas de servidor verificadas.","Guía práctica","Flujo recomendado","Abre cada herramienta en orden, confirma los datos actuales y conserva el resultado junto al juego.","Abrir flujo","Herramientas relacionadas","Límite de precisión","Las guías organizan datos verificados; no estiman valores ni fórmulas sin verificar.","Primeros pasos y primera base|Usa el mapa, el catálogo de Pals y el planificador de base para elegir una ruta segura y cubrir trabajos esenciales.|Lista para jugadores que regresan|Revisa misiones, tecnología y expediciones antes de gastar recursos tras una gran actualización.|Fundamentos de crianza|Comprueba relaciones de padres e hijos y habilidades pasivas sin llamar más práctica a la ruta más corta.|Operación de base por objetivos|Empieza por el trabajo necesario y conecta roles de Pals, demanda de fabricación y estructuras.|Servidor dedicado y respaldos|Crea ajustes con las claves oficiales actuales, valida avisos y aplícalos después de respaldar.|Preparación para el combate|Compara multiplicadores elementales verificados, habilidades activas, estados de salud y tratamientos."),
  "pt-BR":make("Guias de Palworld","Fluxos práticos que conectam mapa, bancos de dados, calculadoras e ferramentas de servidor verificadas.","Guia prático","Fluxo recomendado","Abra cada ferramenta em ordem, confirme os dados atuais e mantenha o resultado ao lado do jogo.","Abrir fluxo","Ferramentas relacionadas","Limite de precisão","Os guias organizam dados verificados; valores e fórmulas não verificados não são estimados.","Primeiros passos e primeira base|Use o mapa, o catálogo de Pals e o planejador de base para escolher uma rota segura e cobrir trabalhos essenciais.|Checklist para quem retorna|Revise missões, tecnologia e expedições antes de gastar recursos após uma grande atualização.|Fundamentos de reprodução|Confira relações entre pais e filhos e habilidades passivas sem chamar o caminho mais curto de mais prático.|Operação da base por objetivo|Comece pelo trabalho necessário e conecte funções dos Pals, demanda de criação e estruturas.|Servidor dedicado e backup|Crie configurações com as chaves oficiais atuais, valide avisos e aplique após o backup.|Preparação para combate|Compare multiplicadores elementais verificados, habilidades ativas, condições de saúde e tratamentos."),
  "ru-RU":make("Руководства Palworld","Практические процессы, связывающие проверенные карту, базы данных, калькуляторы и серверные инструменты.","Практическое руководство","Рекомендуемый порядок","Открывайте инструменты по порядку, проверяйте актуальные данные и используйте результат во время игры.","Открыть процесс","Связанные инструменты","Граница точности","Руководства используют проверенные данные; непроверенные значения и формулы не оцениваются.","Первые шаги и первая база|Используйте карту, каталог Палов и планировщик базы для безопасного маршрута и основных работ.|Проверка для вернувшихся игроков|Проверьте задания, технологии и экспедиции до траты ресурсов после крупного обновления.|Основы разведения|Проверяйте связи родителей и потомков и пассивные навыки, не называя кратчайший путь самым практичным.|Работа базы по цели|Начните с нужной работы и свяжите роли Палов, производство и постройки.|Выделенный сервер и резервная копия|Создайте настройки по актуальным официальным ключам, проверьте предупреждения и примените после копирования.|Подготовка к бою|Сравните проверенные множители стихий, активные навыки, состояния здоровья и лечение."),
  "id-ID":make("Panduan Palworld","Alur praktis yang menghubungkan peta, basis data, kalkulator, dan alat server terverifikasi.","Panduan praktis","Alur yang disarankan","Buka alat tertaut secara berurutan, periksa data saat ini, dan gunakan hasilnya saat bermain.","Buka alur","Alat terkait","Batas akurasi","Panduan mengatur data terverifikasi; nilai dan rumus yang belum terverifikasi tidak diperkirakan.","Langkah awal dan base pertama|Gunakan peta, katalog Pal, dan perencana base untuk rute aman serta peran kerja penting.|Checklist pemain yang kembali|Periksa quest, teknologi, dan ekspedisi sebelum memakai sumber daya setelah pembaruan besar.|Dasar breeding|Periksa hubungan induk-anak dan skill pasif tanpa menyebut jalur terpendek sebagai yang paling praktis.|Operasi base berdasarkan tujuan|Mulai dari pekerjaan yang dibutuhkan lalu hubungkan peran Pal, kebutuhan crafting, dan struktur.|Server khusus dan cadangan|Buat pengaturan dari kunci resmi saat ini, periksa peringatan, lalu terapkan setelah mencadangkan.|Persiapan pertempuran|Bandingkan pengali elemen terverifikasi, skill aktif, kondisi kesehatan, dan perawatan."),
  "th-TH":make("คู่มือ Palworld","ขั้นตอนใช้งานที่เชื่อมแผนที่ ฐานข้อมูล เครื่องคำนวณ และเครื่องมือเซิร์ฟเวอร์ที่ตรวจสอบแล้ว","คู่มือใช้งาน","ลำดับที่แนะนำ","เปิดเครื่องมือที่เชื่อมโยงตามลำดับ ตรวจสอบข้อมูลปัจจุบัน และใช้ผลลัพธ์ระหว่างเล่น","เปิดขั้นตอน","เครื่องมือที่เกี่ยวข้อง","ขอบเขตความแม่นยำ","คู่มือนี้จัดข้อมูลที่ตรวจสอบแล้ว และไม่ประมาณค่าหรือสูตรที่ยังไม่ตรวจสอบ","เริ่มต้นและฐานแรก|ใช้แผนที่ รายการ Pal และตัววางแผนฐานเพื่อเลือกเส้นทางปลอดภัยและงานสำคัญ|รายการตรวจสอบสำหรับผู้กลับมา|ตรวจภารกิจ เทคโนโลยี และการสำรวจก่อนใช้ทรัพยากรหลังอัปเดตใหญ่|พื้นฐานการผสมพันธุ์|ตรวจความสัมพันธ์พ่อแม่กับลูกและสกิลติดตัว โดยไม่เรียกเส้นทางสั้นที่สุดว่าใช้งานดีที่สุด|การจัดการฐานตามเป้าหมาย|เริ่มจากงานที่ต้องทำ แล้วเชื่อมบทบาท Pal ความต้องการคราฟต์ และสิ่งปลูกสร้าง|เซิร์ฟเวอร์เฉพาะและการสำรอง|สร้างค่าจากคีย์ทางการปัจจุบัน ตรวจคำเตือน และใช้หลังสำรองข้อมูล|เตรียมการต่อสู้|เปรียบเทียบตัวคูณธาตุที่ตรวจสอบแล้ว สกิลใช้งาน สภาวะสุขภาพ และการรักษา"),
  "tr-TR":make("Palworld rehberleri","Doğrulanmış harita, veri tabanları, hesaplayıcılar ve sunucu araçlarını bağlayan pratik akışlar.","Pratik rehber","Önerilen akış","Bağlantılı araçları sırayla açın, güncel verileri doğrulayın ve sonucu oyun yanında kullanın.","Akışı aç","İlgili araçlar","Doğruluk sınırı","Rehberler doğrulanmış verileri düzenler; doğrulanmamış değer ve formüller tahmin edilmez.","İlk adımlar ve ilk üs|Güvenli rota ve temel işler için harita, Pal kataloğu ve üs planlayıcıyı kullanın.|Geri dönen oyuncu kontrolü|Büyük güncellemeden sonra kaynak harcamadan önce görevleri, teknolojiyi ve seferleri inceleyin.|Üretme temelleri|En kısa yolu en pratik saymadan ebeveyn-yavru ilişkilerini ve pasif becerileri kontrol edin.|Hedef odaklı üs işletimi|Gerekli işten başlayıp Pal rollerini, üretim talebini ve yapıları bağlayın.|Özel sunucu ve yedekleme|Güncel resmî anahtarlarla ayar oluşturun, uyarıları denetleyin ve yedekten sonra uygulayın.|Savaşa hazırlık|Doğrulanmış element çarpanlarını, aktif becerileri, sağlık durumlarını ve tedavileri karşılaştırın."),
  "vi-VN":make("Hướng dẫn Palworld","Quy trình thực tế kết nối bản đồ, cơ sở dữ liệu, công cụ tính và công cụ máy chủ đã xác minh.","Hướng dẫn thực tế","Quy trình đề xuất","Mở từng công cụ theo thứ tự, kiểm tra dữ liệu hiện tại và dùng kết quả khi chơi.","Mở quy trình","Công cụ liên quan","Giới hạn độ chính xác","Hướng dẫn sắp xếp dữ liệu đã xác minh; giá trị và công thức chưa xác minh không được ước tính.","Bước đầu và căn cứ đầu tiên|Dùng bản đồ, danh mục Pal và trình lập kế hoạch căn cứ để chọn tuyến an toàn và công việc thiết yếu.|Danh sách cho người chơi quay lại|Kiểm tra nhiệm vụ, công nghệ và thám hiểm trước khi dùng tài nguyên sau bản cập nhật lớn.|Cơ bản về phối giống|Kiểm tra quan hệ cha mẹ-con và kỹ năng bị động, không gọi đường ngắn nhất là thực tế nhất.|Vận hành căn cứ theo mục tiêu|Bắt đầu từ công việc cần làm rồi nối vai trò Pal, nhu cầu chế tạo và công trình.|Máy chủ riêng và sao lưu|Tạo thiết lập từ khóa chính thức hiện tại, kiểm tra cảnh báo và áp dụng sau khi sao lưu.|Chuẩn bị chiến đấu|So sánh hệ số nguyên tố đã xác minh, kỹ năng chủ động, tình trạng sức khỏe và điều trị."),
  "pl-PL":make("Poradniki Palworld","Praktyczne procesy łączące zweryfikowaną mapę, bazy danych, kalkulatory i narzędzia serwera.","Poradnik praktyczny","Zalecany proces","Otwieraj narzędzia po kolei, sprawdzaj aktualne dane i korzystaj z wyniku podczas gry.","Otwórz proces","Powiązane narzędzia","Granica dokładności","Poradniki porządkują zweryfikowane dane; niezweryfikowane wartości i wzory nie są szacowane.","Pierwsze kroki i pierwsza baza|Użyj mapy, katalogu Pali i planera bazy, aby wybrać bezpieczną trasę i ważne role pracy.|Lista dla powracających graczy|Sprawdź zadania, technologię i ekspedycje przed wydaniem zasobów po dużej aktualizacji.|Podstawy hodowli|Sprawdź relacje rodzic-potomek i umiejętności pasywne, nie nazywając najkrótszej drogi najbardziej praktyczną.|Baza według celu|Zacznij od potrzebnej pracy i połącz role Pali, zapotrzebowanie produkcji oraz budowle.|Serwer dedykowany i kopia|Utwórz ustawienia z aktualnych oficjalnych kluczy, sprawdź ostrzeżenia i zastosuj po wykonaniu kopii.|Przygotowanie do walki|Porównaj zweryfikowane mnożniki żywiołów, aktywne umiejętności, stany zdrowia i leczenie."),
};

export const guideCopyProvenance=Object.fromEntries(Object.keys(guideCopy).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;

export const guideRoute=(slug:string)=>`guides/${slug}`;
export const findGuide=(route:string)=>guideDefinitions.find(guide=>guideRoute(guide.slug)===route);
