import type {Locale} from "./config";

export type GuideId="getting-started"|"returning-player"|"breeding"|"base"|"server"|"combat";
export type GuideMetricKind="locations"|"pals"|"entries"|"recipes"|"combinations"|"skills"|"work-roles"|"settings"|"conditions";
export type GuideStepKind="discover"|"compare"|"verify"|"plan";
export type GuideDefinition={id:GuideId;slug:GuideId;related:readonly string[];stepKinds:readonly GuideStepKind[];reviewTrigger:string};
export type GuideSnapshotData={meta:{schema:2;gameBuild:string;verification:"verified";localeCount:number;guideCount:number;metricCount:number};guides:Record<GuideId,{reviewTrigger:string;metrics:{route:string;kind:GuideMetricKind;count:number}[]}>};

export const guideDefinitions=[
  {id:"getting-started",slug:"getting-started",related:["map","pals","database/technology","calculators/base","calculators/crafting"],stepKinds:["discover","compare","verify","plan","plan"],reviewTrigger:"major progression or map change"},
  {id:"returning-player",slug:"returning-player",related:["database/quests","database/technology","database/expeditions","map"],stepKinds:["verify","verify","compare","discover"],reviewTrigger:"major content update"},
  {id:"breeding",slug:"breeding",related:["pals","calculators/breeding","calculators/breeding-path","skills/passive","calculators/team-builder"],stepKinds:["compare","verify","plan","compare","verify"],reviewTrigger:"breeding rule or Pal roster change"},
  {id:"base",slug:"base",related:["calculators/base","pals","database/structures","calculators/crafting","database"],stepKinds:["plan","compare","verify","plan","verify"],reviewTrigger:"work suitability, recipe, or structure change"},
  {id:"server",slug:"server",related:["server-tools/settings-generator","calculators/base","database/structures","calculators/crafting"],stepKinds:["verify","plan","verify","plan"],reviewTrigger:"official server guide change"},
  {id:"combat",slug:"combat",related:["database/elements","skills/active","calculators/iv","database/health","calculators/team-builder"],stepKinds:["compare","compare","verify","verify","plan"],reviewTrigger:"element, condition, or active-skill change"},
] as const satisfies readonly GuideDefinition[];

export const guideStepKindLabels:Record<Locale,Record<GuideStepKind,string>>={
  "en-US":{discover:"Find the relevant options and narrow the next stop.",compare:"Compare the current choices before selecting one.",verify:"Check the current constraints and confirm the checkpoint.",plan:"Record the requirements before committing resources."},
  "ko-KR":{discover:"관련 선택지를 찾아 다음 목적지를 좁히세요.",compare:"현재 선택지를 비교한 뒤 하나를 고르세요.",verify:"현재 조건을 점검하고 이 확인 지점을 완료하세요.",plan:"자원을 투입하기 전에 필요한 조건을 계획하세요."},
  "ja-JP":{discover:"関連する選択肢を探し、次の目的地を絞ります。",compare:"現在の選択肢を比較してから一つを選びます。",verify:"現在の条件を確認し、このチェックポイントを完了します。",plan:"資源を使う前に必要条件を計画します。"},
  "zh-CN":{discover:"查找相关选项并缩小下一站范围。",compare:"比较当前选项后再作选择。",verify:"检查当前限制并完成此检查点。",plan:"投入资源前先规划所需条件。"},
  "zh-TW":{discover:"查找相關選項並縮小下一站範圍。",compare:"比較目前選項後再作選擇。",verify:"檢查目前限制並完成此檢查點。",plan:"投入資源前先規劃所需條件。"},
  "fr-FR":{discover:"Repérez les options utiles et réduisez le choix de la prochaine étape.",compare:"Comparez les choix actuels avant d’en sélectionner un.",verify:"Vérifiez les contraintes actuelles et validez ce point de contrôle.",plan:"Notez les besoins avant d’engager des ressources."},
  "it-IT":{discover:"Trova le opzioni pertinenti e restringi la prossima tappa.",compare:"Confronta le scelte attuali prima di selezionarne una.",verify:"Controlla i vincoli attuali e completa questo punto di verifica.",plan:"Annota i requisiti prima di impegnare risorse."},
  "de-DE":{discover:"Finde passende Optionen und grenze das nächste Ziel ein.",compare:"Vergleiche die aktuellen Optionen, bevor du eine auswählst.",verify:"Prüfe die aktuellen Bedingungen und bestätige diesen Kontrollpunkt.",plan:"Halte die Anforderungen fest, bevor du Ressourcen einsetzt."},
  "es-ES":{discover:"Busca las opciones relevantes y concreta el siguiente destino.",compare:"Compara las opciones actuales antes de elegir una.",verify:"Revisa las condiciones actuales y confirma este punto de control.",plan:"Anota los requisitos antes de comprometer recursos."},
  "es-419":{discover:"Busca las opciones relevantes y define el siguiente destino.",compare:"Compara las opciones actuales antes de elegir una.",verify:"Revisa las condiciones actuales y confirma este punto de control.",plan:"Anota los requisitos antes de comprometer recursos."},
  "pt-BR":{discover:"Encontre as opções relevantes e restrinja o próximo destino.",compare:"Compare as opções atuais antes de escolher uma.",verify:"Confira as condições atuais e conclua este ponto de verificação.",plan:"Registre os requisitos antes de comprometer recursos."},
  "ru-RU":{discover:"Найдите подходящие варианты и сузьте выбор следующей цели.",compare:"Сравните текущие варианты, прежде чем выбрать один.",verify:"Проверьте текущие условия и завершите этот контрольный пункт.",plan:"Запишите требования до расходования ресурсов."},
  "id-ID":{discover:"Temukan opsi yang relevan dan persempit tujuan berikutnya.",compare:"Bandingkan pilihan saat ini sebelum memilih satu.",verify:"Periksa ketentuan saat ini dan selesaikan titik pemeriksaan ini.",plan:"Catat kebutuhan sebelum memakai sumber daya."},
  "th-TH":{discover:"ค้นหาตัวเลือกที่เกี่ยวข้องและจำกัดจุดหมายถัดไป",compare:"เปรียบเทียบตัวเลือกปัจจุบันก่อนเลือก",verify:"ตรวจสอบเงื่อนไขปัจจุบันและยืนยันจุดตรวจนี้",plan:"บันทึกข้อกำหนดก่อนใช้ทรัพยากร"},
  "tr-TR":{discover:"İlgili seçenekleri bulun ve sonraki hedefi daraltın.",compare:"Birini seçmeden önce güncel seçenekleri karşılaştırın.",verify:"Güncel koşulları kontrol edin ve bu kontrol noktasını tamamlayın.",plan:"Kaynak ayırmadan önce gereksinimleri kaydedin."},
  "vi-VN":{discover:"Tìm các lựa chọn liên quan và thu hẹp điểm đến tiếp theo.",compare:"So sánh các lựa chọn hiện tại trước khi chọn.",verify:"Kiểm tra điều kiện hiện tại và hoàn tất điểm kiểm tra này.",plan:"Ghi lại yêu cầu trước khi dùng tài nguyên."},
  "pl-PL":{discover:"Znajdź odpowiednie opcje i zawęź następny cel.",compare:"Porównaj aktualne opcje przed wybraniem jednej.",verify:"Sprawdź bieżące warunki i zakończ ten punkt kontrolny.",plan:"Zapisz wymagania przed przeznaczeniem zasobów."},
};

export const guidePreparationKindLabels:Record<Locale,Record<GuideStepKind,string>>={
  "en-US":{discover:"Set the area or target you want to explore.",compare:"List the options and the constraint that matters most.",verify:"Have the current input or state ready to check.",plan:"Write down the goal, available resources, and limits."},
  "ko-KR":{discover:"탐색할 지역이나 목표를 정해 두세요.",compare:"선택지와 가장 중요한 조건을 목록으로 만드세요.",verify:"확인할 현재 입력값이나 상태를 준비하세요.",plan:"목표, 사용 가능한 자원과 제한을 적어 두세요."},
  "ja-JP":{discover:"探索する地域や対象を決めておきます。",compare:"選択肢と最も重要な条件を一覧にします。",verify:"確認する現在の入力や状態を用意します。",plan:"目標、利用できる資源、制限を書き出します。"},
  "zh-CN":{discover:"先确定要探索的区域或目标。",compare:"列出选项和最重要的限制条件。",verify:"准备好要检查的当前输入或状态。",plan:"记下目标、可用资源和限制。"},
  "zh-TW":{discover:"先確定要探索的區域或目標。",compare:"列出選項和最重要的限制條件。",verify:"準備好要檢查的目前輸入或狀態。",plan:"記下目標、可用資源和限制。"},
  "fr-FR":{discover:"Définissez la zone ou la cible à explorer.",compare:"Listez les options et la contrainte la plus importante.",verify:"Préparez l’entrée ou l’état actuel à vérifier.",plan:"Notez l’objectif, les ressources disponibles et les limites."},
  "it-IT":{discover:"Definisci l’area o l’obiettivo da esplorare.",compare:"Elenca le opzioni e il vincolo più importante.",verify:"Prepara il dato o lo stato attuale da controllare.",plan:"Annota l’obiettivo, le risorse disponibili e i limiti."},
  "de-DE":{discover:"Lege das Gebiet oder Ziel für die Erkundung fest.",compare:"Liste die Optionen und die wichtigste Bedingung auf.",verify:"Halte die aktuelle Eingabe oder den Zustand zur Prüfung bereit.",plan:"Notiere Ziel, verfügbare Ressourcen und Grenzen."},
  "es-ES":{discover:"Define la zona o el objetivo que quieres explorar.",compare:"Enumera las opciones y la condición más importante.",verify:"Prepara la entrada o el estado actual que vas a comprobar.",plan:"Anota el objetivo, los recursos disponibles y los límites."},
  "es-419":{discover:"Define la zona o el objetivo que quieres explorar.",compare:"Enumera las opciones y la condición más importante.",verify:"Prepara la entrada o el estado actual que vas a revisar.",plan:"Anota el objetivo, los recursos disponibles y los límites."},
  "pt-BR":{discover:"Defina a área ou o objetivo que deseja explorar.",compare:"Liste as opções e a condição mais importante.",verify:"Prepare a entrada ou o estado atual que será verificado.",plan:"Anote o objetivo, os recursos disponíveis e os limites."},
  "ru-RU":{discover:"Определите область или цель для исследования.",compare:"Перечислите варианты и самое важное ограничение.",verify:"Подготовьте текущие данные или состояние для проверки.",plan:"Запишите цель, доступные ресурсы и ограничения."},
  "id-ID":{discover:"Tentukan area atau target yang ingin dijelajahi.",compare:"Daftarkan pilihan dan batasan yang paling penting.",verify:"Siapkan input atau status saat ini untuk diperiksa.",plan:"Catat tujuan, sumber daya yang tersedia, dan batasan."},
  "th-TH":{discover:"กำหนดพื้นที่หรือเป้าหมายที่ต้องการสำรวจ",compare:"จดตัวเลือกและเงื่อนไขที่สำคัญที่สุด",verify:"เตรียมข้อมูลหรือสถานะปัจจุบันที่จะตรวจสอบ",plan:"จดเป้าหมาย ทรัพยากรที่มี และข้อจำกัด"},
  "tr-TR":{discover:"Keşfetmek istediğiniz alanı veya hedefi belirleyin.",compare:"Seçenekleri ve en önemli koşulu listeleyin.",verify:"Kontrol edilecek güncel girdiyi veya durumu hazırlayın.",plan:"Hedefi, kullanılabilir kaynakları ve sınırları yazın."},
  "vi-VN":{discover:"Xác định khu vực hoặc mục tiêu muốn khám phá.",compare:"Liệt kê các lựa chọn và điều kiện quan trọng nhất.",verify:"Chuẩn bị dữ liệu hoặc trạng thái hiện tại cần kiểm tra.",plan:"Ghi lại mục tiêu, tài nguyên hiện có và giới hạn."},
  "pl-PL":{discover:"Określ obszar lub cel, który chcesz zbadać.",compare:"Wypisz opcje i najważniejszy warunek.",verify:"Przygotuj bieżące dane lub stan do sprawdzenia.",plan:"Zapisz cel, dostępne zasoby i ograniczenia."},
};

export const guideResultKindLabels:Record<Locale,Record<GuideStepKind,string>>={
  "en-US":{discover:"A next destination or shortlist is selected.",compare:"The selected option and its reason are recorded.",verify:"Constraints, warnings, and unavailable values have been checked.",plan:"Requirements and the next action are clear before resources are spent."},
  "ko-KR":{discover:"다음 목적지나 후보 목록을 선택했습니다.",compare:"선택한 항목과 선택 이유를 기록했습니다.",verify:"제약 조건, 경고와 제공 불가 값을 확인했습니다.",plan:"자원을 쓰기 전에 요구 사항과 다음 행동을 확정했습니다."},
  "ja-JP":{discover:"次の目的地または候補一覧を選びました。",compare:"選んだ項目とその理由を記録しました。",verify:"制約、警告、利用できない値を確認しました。",plan:"資源を使う前に要件と次の行動を確定しました。"},
  "zh-CN":{discover:"已选定下一目的地或候选清单。",compare:"已记录所选项目及其理由。",verify:"已检查限制、警告和不可用数值。",plan:"已在投入资源前明确要求和下一步行动。"},
  "zh-TW":{discover:"已選定下一目的地或候選清單。",compare:"已記錄所選項目及其理由。",verify:"已檢查限制、警告和不可用數值。",plan:"已在投入資源前明確要求和下一步行動。"},
  "fr-FR":{discover:"Une prochaine destination ou une liste restreinte est choisie.",compare:"L’option choisie et sa raison sont consignées.",verify:"Les contraintes, avertissements et valeurs indisponibles ont été vérifiés.",plan:"Les besoins et l’action suivante sont clairs avant toute dépense de ressources."},
  "it-IT":{discover:"È stata scelta la prossima destinazione o una lista ristretta.",compare:"L’opzione scelta e il motivo sono stati registrati.",verify:"Vincoli, avvisi e valori non disponibili sono stati controllati.",plan:"Requisiti e azione successiva sono chiari prima di spendere risorse."},
  "de-DE":{discover:"Ein nächstes Ziel oder eine engere Auswahl steht fest.",compare:"Die gewählte Option und der Grund sind festgehalten.",verify:"Bedingungen, Warnungen und nicht verfügbare Werte sind geprüft.",plan:"Anforderungen und nächster Schritt stehen vor dem Ressourceneinsatz fest."},
  "es-ES":{discover:"Se ha elegido el siguiente destino o una lista reducida.",compare:"Se han anotado la opción elegida y su motivo.",verify:"Se han revisado las condiciones, los avisos y los valores no disponibles.",plan:"Los requisitos y la siguiente acción están claros antes de gastar recursos."},
  "es-419":{discover:"Se eligió el siguiente destino o una lista reducida.",compare:"Se registraron la opción elegida y su motivo.",verify:"Se revisaron las condiciones, las advertencias y los valores no disponibles.",plan:"Los requisitos y la siguiente acción están claros antes de gastar recursos."},
  "pt-BR":{discover:"O próximo destino ou uma lista reduzida foi escolhido.",compare:"A opção escolhida e o motivo foram registrados.",verify:"Condições, avisos e valores indisponíveis foram verificados.",plan:"Os requisitos e a próxima ação estão claros antes de gastar recursos."},
  "ru-RU":{discover:"Выбрана следующая цель или сокращённый список.",compare:"Выбранный вариант и причина записаны.",verify:"Ограничения, предупреждения и недоступные значения проверены.",plan:"Требования и следующий шаг определены до расходования ресурсов."},
  "id-ID":{discover:"Tujuan berikutnya atau daftar pendek telah dipilih.",compare:"Pilihan dan alasannya telah dicatat.",verify:"Batasan, peringatan, dan nilai yang tidak tersedia telah diperiksa.",plan:"Kebutuhan dan tindakan berikutnya sudah jelas sebelum sumber daya dipakai."},
  "th-TH":{discover:"เลือกจุดหมายถัดไปหรือรายการตัวเลือกแล้ว",compare:"บันทึกตัวเลือกและเหตุผลที่เลือกแล้ว",verify:"ตรวจสอบข้อจำกัด คำเตือน และค่าที่ไม่พร้อมใช้งานแล้ว",plan:"กำหนดข้อกำหนดและการดำเนินการถัดไปก่อนใช้ทรัพยากรแล้ว"},
  "tr-TR":{discover:"Sonraki hedef veya kısa liste seçildi.",compare:"Seçilen seçenek ve nedeni kaydedildi.",verify:"Koşullar, uyarılar ve kullanılamayan değerler kontrol edildi.",plan:"Kaynak harcamadan önce gereksinimler ve sonraki işlem netleştirildi."},
  "vi-VN":{discover:"Đã chọn điểm đến tiếp theo hoặc danh sách rút gọn.",compare:"Đã ghi lại lựa chọn và lý do.",verify:"Đã kiểm tra điều kiện, cảnh báo và các giá trị không khả dụng.",plan:"Đã xác định yêu cầu và hành động tiếp theo trước khi dùng tài nguyên."},
  "pl-PL":{discover:"Wybrano następny cel lub krótką listę.",compare:"Zapisano wybraną opcję i jej uzasadnienie.",verify:"Sprawdzono warunki, ostrzeżenia i niedostępne wartości.",plan:"Wymagania i następne działanie są jasne przed wydaniem zasobów."},
};

export type GuideStructureCopy={problem:string;preparation:string;preparationIntro:string;procedure:string;result:string;resultIntro:string;stepAction:string;confirm:string;coverage:string;coverageIntro:string;entries:string};

export const guideMetricKindLabels:Record<Locale,Record<GuideMetricKind,string>>={
  "en-US":{locations:"map points",pals:"Pals",entries:"catalog entries",recipes:"recipes",combinations:"breeding combinations",skills:"skills","work-roles":"work roles",settings:"supported settings",conditions:"health conditions"},
  "ko-KR":{locations:"지도 지점",pals:"팰",entries:"도감 항목",recipes:"레시피",combinations:"교배 조합",skills:"스킬","work-roles":"작업 역할",settings:"지원 설정",conditions:"건강 상태"},
  "ja-JP":{locations:"マップ地点",pals:"パル",entries:"カタログ項目",recipes:"レシピ",combinations:"配合組み合わせ",skills:"スキル","work-roles":"作業役割",settings:"対応設定",conditions:"健康状態"},
  "zh-CN":{locations:"地图点位",pals:"帕鲁",entries:"图鉴条目",recipes:"配方",combinations:"配种组合",skills:"技能","work-roles":"工作角色",settings:"支持的设置",conditions:"健康状态"},
  "zh-TW":{locations:"地圖點位",pals:"帕魯",entries:"圖鑑條目",recipes:"配方",combinations:"配種組合",skills:"技能","work-roles":"工作角色",settings:"支援設定",conditions:"健康狀態"},
  "fr-FR":{locations:"points de carte",pals:"Pals",entries:"entrées du catalogue",recipes:"recettes",combinations:"combinaisons d’élevage",skills:"compétences","work-roles":"rôles de travail",settings:"paramètres pris en charge",conditions:"états de santé"},
  "it-IT":{locations:"punti mappa",pals:"Pal",entries:"voci del catalogo",recipes:"ricette",combinations:"combinazioni di riproduzione",skills:"abilità","work-roles":"ruoli di lavoro",settings:"impostazioni supportate",conditions:"condizioni di salute"},
  "de-DE":{locations:"Kartenpunkte",pals:"Pals",entries:"Katalogeinträge",recipes:"Rezepte",combinations:"Zuchtkombinationen",skills:"Fähigkeiten","work-roles":"Arbeitsrollen",settings:"unterstützte Einstellungen",conditions:"Gesundheitszustände"},
  "es-ES":{locations:"puntos del mapa",pals:"Pals",entries:"entradas del catálogo",recipes:"recetas",combinations:"combinaciones de cría",skills:"habilidades","work-roles":"roles de trabajo",settings:"ajustes compatibles",conditions:"estados de salud"},
  "es-419":{locations:"puntos del mapa",pals:"Pals",entries:"entradas del catálogo",recipes:"recetas",combinations:"combinaciones de cría",skills:"habilidades","work-roles":"roles de trabajo",settings:"ajustes compatibles",conditions:"estados de salud"},
  "pt-BR":{locations:"pontos do mapa",pals:"Pals",entries:"entradas do catálogo",recipes:"receitas",combinations:"combinações de reprodução",skills:"habilidades","work-roles":"funções de trabalho",settings:"configurações compatíveis",conditions:"condições de saúde"},
  "ru-RU":{locations:"точек карты",pals:"Палов",entries:"записей каталога",recipes:"рецептов",combinations:"комбинаций разведения",skills:"навыков","work-roles":"рабочих ролей",settings:"поддерживаемых настроек",conditions:"состояний здоровья"},
  "id-ID":{locations:"titik peta",pals:"Pal",entries:"entri katalog",recipes:"resep",combinations:"kombinasi breeding",skills:"skill","work-roles":"peran kerja",settings:"pengaturan yang didukung",conditions:"kondisi kesehatan"},
  "th-TH":{locations:"จุดบนแผนที่",pals:"พัล",entries:"รายการแค็ตตาล็อก",recipes:"สูตร",combinations:"คู่ผสมพันธุ์",skills:"สกิล","work-roles":"บทบาทงาน",settings:"การตั้งค่าที่รองรับ",conditions:"สถานะสุขภาพ"},
  "tr-TR":{locations:"harita noktası",pals:"Pal",entries:"katalog kaydı",recipes:"tarif",combinations:"üretme kombinasyonu",skills:"beceri","work-roles":"iş rolü",settings:"desteklenen ayar",conditions:"sağlık durumu"},
  "vi-VN":{locations:"điểm bản đồ",pals:"Pal",entries:"mục danh mục",recipes:"công thức",combinations:"tổ hợp phối giống",skills:"kỹ năng","work-roles":"vai trò công việc",settings:"thiết lập được hỗ trợ",conditions:"tình trạng sức khỏe"},
  "pl-PL":{locations:"punktów mapy",pals:"Pali",entries:"wpisów katalogu",recipes:"receptur",combinations:"kombinacji hodowlanych",skills:"umiejętności","work-roles":"ról pracy",settings:"obsługiwanych ustawień",conditions:"stanów zdrowia"},
};

export const guideStructureCopy:Record<Locale,GuideStructureCopy>={
  "en-US":{problem:"Goal",preparation:"Before you start",preparationIntro:"Keep these verified tools open so each decision uses the current catalog.",procedure:"Step-by-step procedure",result:"Check the result",resultIntro:"Before you spend resources or apply changes, confirm each checkpoint.",stepAction:"Review the current information, make this decision, then continue.",confirm:"Confirmed: {name}",coverage:"Current verified coverage",coverageIntro:"These counts are generated from the same data used by the linked tools and update with them.",entries:"entries"},
  "ko-KR":{problem:"목표",preparation:"시작 전 준비",preparationIntro:"각 결정을 현재 데이터로 확인할 수 있도록 다음 검증된 도구를 준비하세요.",procedure:"단계별 절차",result:"결과 확인",resultIntro:"자원을 사용하거나 변경 사항을 적용하기 전에 각 항목을 확인하세요.",stepAction:"현재 정보를 검토하고 이 단계를 결정한 뒤 다음으로 진행하세요.",confirm:"확인 완료: {name}",coverage:"현재 검증 범위",coverageIntro:"이 수치는 연결된 도구와 동일한 데이터에서 자동 생성되며 함께 갱신됩니다.",entries:"개 항목"},
  "ja-JP":{problem:"目的",preparation:"始める前の準備",preparationIntro:"各判断を現在のデータで確認できるよう、検証済みツールを開いておきます。",procedure:"手順",result:"結果の確認",resultIntro:"資源を使う、または変更を適用する前に各項目を確認してください。",stepAction:"現在の情報を確認して判断し、次へ進みます。",confirm:"確認済み：{name}",coverage:"現在の検証範囲",coverageIntro:"この件数はリンク先と同じデータから自動生成され、同時に更新されます。",entries:"件"},
  "zh-CN":{problem:"目标",preparation:"开始前准备",preparationIntro:"打开这些已验证工具，确保每个决定都基于当前数据。",procedure:"分步流程",result:"检查结果",resultIntro:"消耗资源或应用更改前，请确认每个检查点。",stepAction:"查看当前信息，完成此项决定，然后继续。",confirm:"已确认：{name}",coverage:"当前验证范围",coverageIntro:"这些数量由链接工具使用的同一数据自动生成，并同步更新。",entries:"项"},
  "zh-TW":{problem:"目標",preparation:"開始前準備",preparationIntro:"開啟這些已驗證工具，確保每個決定都使用目前資料。",procedure:"逐步流程",result:"檢查結果",resultIntro:"花費資源或套用變更前，請確認每個檢查點。",stepAction:"檢視目前資訊，完成此項決定後再繼續。",confirm:"已確認：{name}",coverage:"目前驗證範圍",coverageIntro:"這些數量由連結工具使用的相同資料自動產生，並同步更新。",entries:"項"},
  "fr-FR":{problem:"Objectif",preparation:"Avant de commencer",preparationIntro:"Gardez ces outils vérifiés ouverts afin que chaque décision utilise le catalogue actuel.",procedure:"Procédure étape par étape",result:"Vérifier le résultat",resultIntro:"Avant de dépenser des ressources ou d’appliquer des changements, confirmez chaque point.",stepAction:"Consultez les informations actuelles, prenez cette décision, puis continuez.",confirm:"Confirmé : {name}",coverage:"Couverture vérifiée actuelle",coverageIntro:"Ces nombres sont générés depuis les mêmes données que les outils liés et sont mis à jour avec eux.",entries:"entrées"},
  "it-IT":{problem:"Obiettivo",preparation:"Prima di iniziare",preparationIntro:"Tieni aperti questi strumenti verificati affinché ogni decisione usi il catalogo attuale.",procedure:"Procedura passo passo",result:"Controlla il risultato",resultIntro:"Prima di spendere risorse o applicare modifiche, conferma ogni punto.",stepAction:"Controlla le informazioni attuali, prendi questa decisione e continua.",confirm:"Confermato: {name}",coverage:"Copertura verificata attuale",coverageIntro:"Questi conteggi sono generati dagli stessi dati degli strumenti collegati e si aggiornano con essi.",entries:"voci"},
  "de-DE":{problem:"Ziel",preparation:"Vor dem Start",preparationIntro:"Halte diese geprüften Werkzeuge offen, damit jede Entscheidung auf dem aktuellen Katalog beruht.",procedure:"Schritt-für-Schritt-Ablauf",result:"Ergebnis prüfen",resultIntro:"Bestätige jeden Punkt, bevor du Ressourcen ausgibst oder Änderungen anwendest.",stepAction:"Prüfe die aktuellen Informationen, triff diese Entscheidung und fahre fort.",confirm:"Bestätigt: {name}",coverage:"Aktuell geprüfter Umfang",coverageIntro:"Diese Zahlen werden aus denselben Daten wie die verknüpften Werkzeuge erzeugt und mit ihnen aktualisiert.",entries:"Einträge"},
  "es-ES":{problem:"Objetivo",preparation:"Antes de empezar",preparationIntro:"Mantén abiertas estas herramientas verificadas para que cada decisión use el catálogo actual.",procedure:"Procedimiento paso a paso",result:"Comprobar el resultado",resultIntro:"Antes de gastar recursos o aplicar cambios, confirma cada punto.",stepAction:"Revisa la información actual, toma esta decisión y continúa.",confirm:"Confirmado: {name}",coverage:"Cobertura verificada actual",coverageIntro:"Estas cantidades se generan con los mismos datos que usan las herramientas enlazadas y se actualizan con ellas.",entries:"entradas"},
  "es-419":{problem:"Objetivo",preparation:"Antes de empezar",preparationIntro:"Mantén abiertas estas herramientas verificadas para que cada decisión use el catálogo actual.",procedure:"Procedimiento paso a paso",result:"Comprobar el resultado",resultIntro:"Antes de gastar recursos o aplicar cambios, confirma cada punto.",stepAction:"Revisa la información actual, toma esta decisión y continúa.",confirm:"Confirmado: {name}",coverage:"Cobertura verificada actual",coverageIntro:"Estas cantidades se generan con los mismos datos que usan las herramientas enlazadas y se actualizan con ellas.",entries:"entradas"},
  "pt-BR":{problem:"Objetivo",preparation:"Antes de começar",preparationIntro:"Mantenha estas ferramentas verificadas abertas para que cada decisão use o catálogo atual.",procedure:"Procedimento passo a passo",result:"Verificar o resultado",resultIntro:"Antes de gastar recursos ou aplicar mudanças, confirme cada ponto.",stepAction:"Revise as informações atuais, tome esta decisão e continue.",confirm:"Confirmado: {name}",coverage:"Cobertura verificada atual",coverageIntro:"Estas contagens são geradas pelos mesmos dados das ferramentas vinculadas e atualizadas com elas.",entries:"entradas"},
  "ru-RU":{problem:"Цель",preparation:"Перед началом",preparationIntro:"Держите эти проверенные инструменты открытыми, чтобы решения опирались на актуальный каталог.",procedure:"Пошаговый порядок",result:"Проверка результата",resultIntro:"Перед расходом ресурсов или применением изменений подтвердите каждый пункт.",stepAction:"Проверьте актуальные сведения, примите решение и продолжайте.",confirm:"Подтверждено: {name}",coverage:"Текущий проверенный охват",coverageIntro:"Эти числа создаются из тех же данных, что и связанные инструменты, и обновляются вместе с ними.",entries:"записей"},
  "id-ID":{problem:"Tujuan",preparation:"Sebelum mulai",preparationIntro:"Biarkan alat terverifikasi ini terbuka agar setiap keputusan memakai katalog terkini.",procedure:"Prosedur langkah demi langkah",result:"Periksa hasil",resultIntro:"Sebelum memakai sumber daya atau menerapkan perubahan, pastikan setiap poin.",stepAction:"Tinjau informasi terkini, ambil keputusan ini, lalu lanjutkan.",confirm:"Dikonfirmasi: {name}",coverage:"Cakupan terverifikasi saat ini",coverageIntro:"Jumlah ini dibuat dari data yang sama dengan alat tertaut dan diperbarui bersamanya.",entries:"entri"},
  "th-TH":{problem:"เป้าหมาย",preparation:"ก่อนเริ่ม",preparationIntro:"เปิดเครื่องมือที่ตรวจสอบแล้วเหล่านี้ไว้ เพื่อให้ทุกการตัดสินใจใช้ข้อมูลปัจจุบัน",procedure:"ขั้นตอนการทำงาน",result:"ตรวจสอบผลลัพธ์",resultIntro:"ก่อนใช้ทรัพยากรหรือใช้การเปลี่ยนแปลง ให้ยืนยันแต่ละรายการ",stepAction:"ตรวจสอบข้อมูลปัจจุบัน ตัดสินใจในขั้นตอนนี้ แล้วจึงดำเนินการต่อ",confirm:"ยืนยันแล้ว: {name}",coverage:"ขอบเขตที่ตรวจสอบแล้วปัจจุบัน",coverageIntro:"จำนวนเหล่านี้สร้างจากข้อมูลเดียวกับเครื่องมือที่เชื่อมโยงและอัปเดตพร้อมกัน",entries:"รายการ"},
  "tr-TR":{problem:"Hedef",preparation:"Başlamadan önce",preparationIntro:"Her karar güncel kataloğu kullansın diye bu doğrulanmış araçları açık tutun.",procedure:"Adım adım işlem",result:"Sonucu kontrol et",resultIntro:"Kaynak harcamadan veya değişiklik uygulamadan önce her noktayı doğrulayın.",stepAction:"Güncel bilgileri inceleyin, bu kararı verin ve devam edin.",confirm:"Doğrulandı: {name}",coverage:"Güncel doğrulanmış kapsam",coverageIntro:"Bu sayılar bağlantılı araçlarla aynı verilerden üretilir ve onlarla birlikte güncellenir.",entries:"kayıt"},
  "vi-VN":{problem:"Mục tiêu",preparation:"Trước khi bắt đầu",preparationIntro:"Mở sẵn các công cụ đã xác minh để mọi quyết định dùng danh mục hiện tại.",procedure:"Quy trình từng bước",result:"Kiểm tra kết quả",resultIntro:"Trước khi dùng tài nguyên hoặc áp dụng thay đổi, hãy xác nhận từng mục.",stepAction:"Xem thông tin hiện tại, đưa ra quyết định ở bước này rồi tiếp tục.",confirm:"Đã xác nhận: {name}",coverage:"Phạm vi đã xác minh hiện tại",coverageIntro:"Các số lượng này được tạo từ cùng dữ liệu với công cụ liên kết và được cập nhật cùng nhau.",entries:"mục"},
  "pl-PL":{problem:"Cel",preparation:"Przed rozpoczęciem",preparationIntro:"Pozostaw te zweryfikowane narzędzia otwarte, aby każda decyzja korzystała z aktualnego katalogu.",procedure:"Procedura krok po kroku",result:"Sprawdź wynik",resultIntro:"Przed wydaniem zasobów lub zastosowaniem zmian potwierdź każdy punkt.",stepAction:"Sprawdź aktualne informacje, podejmij tę decyzję i przejdź dalej.",confirm:"Potwierdzono: {name}",coverage:"Aktualny zweryfikowany zakres",coverageIntro:"Te liczby są generowane z tych samych danych co połączone narzędzia i aktualizowane razem z nimi.",entries:"wpisów"},
};

type GuideText={title:string;description:string};
export type GuideCopy={
  hubTitle:string;hubDescription:string;eyebrow:string;workflow:string;workflowIntro:string;
  open:string;related:string;scope:string;scopeText:string;guides:Record<GuideId,GuideText>;
};

const make=(hubTitle:string,hubDescription:string,eyebrow:string,workflow:string,workflowIntro:string,open:string,related:string,scope:string,scopeText:string,values:string):GuideCopy=>{
  const parts=values.split("|");
  if(parts.length!==guideDefinitions.length*2)throw new Error(`Guide copy needs ${guideDefinitions.length*2} values`);
  return {hubTitle,hubDescription,eyebrow,workflow,workflowIntro,open,related,scope,scopeText,guides:Object.fromEntries(guideDefinitions.map((guide,index)=>[guide.id,{title:parts[index*2],description:parts[index*2+1]}])) as Record<GuideId,GuideText>};
};

export const guideCopy:Record<Locale,GuideCopy>={
  "en-US":make("Palworld guides","Task-focused workflows that connect the verified map, databases, calculators, and server tools.","Practical guide","Recommended workflow","Open each linked tool in order, confirm the current data, and keep the result beside your game.","Open workflow","Related tools","Accuracy boundary","These guides organize verified site data. Values or formulas that are not verified remain unavailable instead of being estimated.","First steps and first base|Use the map, Pal catalog, and base planner to choose a safe first route and cover essential work roles.|Returning-player checklist|Review quests, technology, and expeditions before spending resources after a major update.|Breeding fundamentals|Check current parent-to-child relationships and passive skills without treating a shortest path as the most practical route.|Goal-based base operations|Start from the work your base must perform, then connect Pal roles, crafting demand, and structures.|Dedicated server setup and backup|Prepare settings from the current official key inventory, validate warnings, and apply the file with a backup and restart plan.|Combat preparation|Compare verified element scaling, active skills, health conditions, and treatments before a difficult encounter."),
  "ko-KR":make("팰월드 가이드","검증된 지도, 데이터베이스, 계산기와 서버 도구를 실제 플레이 순서로 연결한 작업 중심 가이드입니다.","실전 가이드","권장 진행 순서","연결된 도구를 순서대로 열어 현재 데이터를 확인하고, 결과를 게임 옆에 두고 활용하세요.","워크플로 열기","관련 도구","정확도 범위","이 가이드는 사이트에서 검증된 정보를 정리합니다. 검증되지 않은 값이나 공식은 추정하지 않고 제공하지 않습니다.","첫 시작과 첫 거점|지도, 팰 도감과 거점 계산기로 안전한 첫 동선과 필수 작업 역할을 정리합니다.|복귀 플레이어 점검표|대규모 업데이트 뒤 자원을 쓰기 전에 퀘스트, 기술과 탐험을 확인합니다.|교배 기초|최단 경로를 가장 실용적인 경로로 오해하지 않도록 현재 부모-자식 관계와 패시브 스킬을 확인합니다.|목표 중심 거점 운영|거점에서 수행할 작업부터 정하고 팰 역할, 제작 수요와 건축물을 연결합니다.|전용 서버 설정과 백업|현재 공식 키 목록으로 설정을 만들고 경고를 검증한 뒤 백업과 재시작 계획에 따라 적용합니다.|전투 준비|어려운 전투 전에 검증된 속성 배율, 액티브 스킬, 건강 상태와 치료법을 비교합니다."),
  "ja-JP":make("Palworld ガイド","検証済みのマップ、データベース、計算機、サーバーツールを実際の手順でつなぐガイドです。","実践ガイド","推奨ワークフロー","リンク先を順番に開き、現在のデータを確認してゲーム中に参照してください。","ワークフローを開く","関連ツール","精度の範囲","検証済み情報のみを整理し、未検証の値や式は推測せず利用不可のままにします。","最初の一歩と最初の拠点|マップ、パル図鑑、拠点計画で安全な序盤ルートと必要な作業役を決めます。|復帰プレイヤーの確認項目|大型更新後に資源を使う前にクエスト、テクノロジー、探索を確認します。|配合の基本|最短経路を最も実用的な経路とせず、親子関係とパッシブスキルを確認します。|目的別の拠点運営|必要な作業からパルの役割、クラフト需要、建築物をつなげます。|専用サーバー設定とバックアップ|現在の公式キーで設定を作り、警告を確認してバックアップ後に適用します。|戦闘準備|難しい戦闘の前に属性倍率、アクティブスキル、健康状態と治療を比較します。"),
  "zh-CN":make("Palworld 指南","把已验证的地图、数据库、计算器和服务器工具连接成实际流程。","实用指南","推荐流程","按顺序打开链接工具，确认当前数据，并在游戏时参考结果。","打开流程","相关工具","准确性范围","指南只整理已验证的信息；未验证的数值或公式不会被估算。","初期步骤与首个据点|使用地图、帕鲁图鉴和据点规划器安排安全路线与必要岗位。|回归玩家检查表|大型更新后先检查任务、科技和探险，再投入资源。|配种基础|检查当前亲子关系和被动技能，不把最短路线称为最实用路线。|按目标运营据点|从据点需要的工作出发，连接帕鲁岗位、制作需求和建筑。|专用服务器设置与备份|按当前官方键生成设置，检查警告，并在备份后应用。|战斗准备|困难战斗前比较已验证的属性倍率、主动技能、健康状态与治疗。"),
  "zh-TW":make("Palworld 指南","把已驗證的地圖、資料庫、計算器與伺服器工具連成實際流程。","實用指南","建議流程","依序開啟連結工具，確認目前資料，並在遊戲時參考結果。","開啟流程","相關工具","準確性範圍","指南只整理已驗證資訊；未驗證的數值或公式不會被估算。","初期步驟與首個據點|使用地圖、帕魯圖鑑與據點規劃器安排安全路線和必要職務。|回歸玩家檢查表|大型更新後先檢查任務、科技與探險，再投入資源。|配種基礎|檢查目前親子關係與被動技能，不把最短路線稱為最實用路線。|依目標營運據點|從據點需要的工作出發，連結帕魯職務、製作需求與建築。|專用伺服器設定與備份|依目前官方鍵產生設定、檢查警告，並在備份後套用。|戰鬥準備|困難戰鬥前比較已驗證的屬性倍率、主動技能、健康狀態與治療。"),
  "fr-FR":make("Guides Palworld","Des parcours pratiques reliant la carte, les bases de données, les calculateurs et les outils serveur vérifiés.","Guide pratique","Parcours recommandé","Ouvrez chaque outil dans l’ordre, vérifiez les données actuelles et gardez le résultat à côté du jeu.","Ouvrir le parcours","Outils associés","Limite de précision","Ces guides organisent les données vérifiées. Les valeurs et formules non vérifiées ne sont pas estimées.","Premiers pas et première base|Utilisez la carte, le catalogue de Pals et le planificateur de base pour définir une route sûre et les rôles essentiels.|Liste de contrôle pour reprendre|Vérifiez les quêtes, technologies et expéditions avant de dépenser des ressources après une mise à jour majeure.|Principes de l’élevage|Vérifiez les liens parents-enfant et les compétences passives sans présenter le chemin le plus court comme le plus pratique.|Gestion d’une base par objectif|Partez du travail nécessaire puis reliez rôles des Pals, besoins de fabrication et structures.|Serveur dédié et sauvegarde|Créez les réglages avec les clés officielles actuelles, contrôlez les alertes et appliquez-les après sauvegarde.|Préparation au combat|Comparez les multiplicateurs élémentaires vérifiés, compétences actives, états de santé et soins."),
  "it-IT":make("Guide di Palworld","Flussi pratici che collegano mappa, database, calcolatori e strumenti server verificati.","Guida pratica","Flusso consigliato","Apri gli strumenti in ordine, controlla i dati attuali e tieni il risultato accanto al gioco.","Apri il flusso","Strumenti correlati","Limite di accuratezza","Le guide organizzano dati verificati; valori e formule non verificati non vengono stimati.","Primi passi e prima base|Usa mappa, catalogo Pal e pianificatore base per scegliere un percorso sicuro e i ruoli essenziali.|Controllo per chi ritorna|Controlla missioni, tecnologia e spedizioni prima di spendere risorse dopo un grande aggiornamento.|Fondamenti di allevamento|Controlla relazioni genitori-figli e abilità passive senza definire il percorso più breve come il più pratico.|Gestione della base per obiettivi|Parti dal lavoro necessario e collega ruoli dei Pal, richieste di creazione e strutture.|Server dedicato e backup|Crea le impostazioni dalle chiavi ufficiali attuali, controlla gli avvisi e applicale dopo il backup.|Preparazione al combattimento|Confronta moltiplicatori elementali verificati, abilità attive, condizioni di salute e cure."),
  "de-DE":make("Palworld-Guides","Praktische Abläufe, die verifizierte Karte, Datenbanken, Rechner und Serverwerkzeuge verbinden.","Praxis-Guide","Empfohlener Ablauf","Öffne die verknüpften Werkzeuge der Reihe nach, prüfe aktuelle Daten und nutze das Ergebnis beim Spielen.","Ablauf öffnen","Verwandte Werkzeuge","Genauigkeitsgrenze","Die Guides ordnen verifizierte Daten. Ungeprüfte Werte und Formeln werden nicht geschätzt.","Erste Schritte und erste Basis|Nutze Karte, Pal-Katalog und Basisplaner für eine sichere Route und wichtige Arbeitsrollen.|Checkliste für Rückkehrer|Prüfe Quests, Technologie und Expeditionen, bevor du nach einem großen Update Ressourcen ausgibst.|Zuchtgrundlagen|Prüfe Eltern-Kind-Beziehungen und passive Fähigkeiten, ohne den kürzesten Weg als praktischsten zu bezeichnen.|Zielorientierter Basisbetrieb|Beginne mit der benötigten Arbeit und verbinde Pal-Rollen, Herstellungsbedarf und Gebäude.|Dedicated Server und Sicherung|Erstelle Einstellungen mit aktuellen offiziellen Schlüsseln, prüfe Warnungen und wende sie nach einer Sicherung an.|Kampfvorbereitung|Vergleiche verifizierte Elementfaktoren, aktive Fähigkeiten, Gesundheitszustände und Behandlungen."),
  "es-ES":make("Guías de Palworld","Flujos prácticos que conectan el mapa, las bases de datos, las calculadoras y las herramientas de servidor verificadas.","Guía práctica","Flujo recomendado","Abre cada herramienta en orden, confirma los datos actuales y conserva el resultado junto al juego.","Abrir flujo","Herramientas relacionadas","Límite de precisión","Las guías organizan datos verificados; no estiman valores ni fórmulas sin verificar.","Primeros pasos y primera base|Usa el mapa, el catálogo de Pals y el planificador de base para elegir una ruta segura y cubrir trabajos esenciales.|Lista para jugadores que regresan|Revisa misiones, tecnología y expediciones antes de gastar recursos tras una gran actualización.|Fundamentos de crianza|Comprueba relaciones de padres e hijos y habilidades pasivas sin llamar más práctica a la ruta más corta.|Operación de base por objetivos|Empieza por el trabajo necesario y conecta roles de Pals, demanda de fabricación y estructuras.|Servidor dedicado y copias de seguridad|Crea ajustes con las claves oficiales actuales, valida avisos y aplícalos tras hacer una copia.|Preparación para el combate|Compara multiplicadores elementales verificados, habilidades activas, estados de salud y tratamientos."),
  "es-419":make("Guías de Palworld","Flujos prácticos que conectan el mapa, las bases de datos, las calculadoras y las herramientas de servidor verificadas.","Guía práctica","Flujo recomendado","Abre cada herramienta en orden, confirma los datos actuales y conserva el resultado junto al juego.","Abrir flujo","Herramientas relacionadas","Límite de precisión","Las guías organizan datos verificados; no estiman valores ni fórmulas sin verificar.","Primeros pasos y primera base|Usa el mapa, el catálogo de Pals y el planificador de base para elegir una ruta segura y cubrir trabajos esenciales.|Lista para jugadores que regresan|Revisa misiones, tecnología y expediciones antes de gastar recursos tras una gran actualización.|Fundamentos de crianza|Comprueba relaciones de padres e hijos y habilidades pasivas sin llamar más práctica a la ruta más corta.|Operación de base por objetivos|Empieza por el trabajo necesario y conecta roles de Pals, demanda de fabricación y estructuras.|Servidor dedicado y respaldos|Crea ajustes con las claves oficiales actuales, valida avisos y aplícalos después de respaldar.|Preparación para el combate|Compara multiplicadores elementales verificados, habilidades activas, estados de salud y tratamientos."),
  "pt-BR":make("Guias de Palworld","Fluxos práticos que conectam mapa, bancos de dados, calculadoras e ferramentas de servidor verificadas.","Guia prático","Fluxo recomendado","Abra cada ferramenta em ordem, confirme os dados atuais e mantenha o resultado ao lado do jogo.","Abrir fluxo","Ferramentas relacionadas","Limite de precisão","Os guias organizam dados verificados; valores e fórmulas não verificados não são estimados.","Primeiros passos e primeira base|Use o mapa, o catálogo de Pals e o planejador de base para escolher uma rota segura e cobrir trabalhos essenciais.|Checklist para quem retorna|Revise missões, tecnologia e expedições antes de gastar recursos após uma grande atualização.|Fundamentos de reprodução|Confira relações entre pais e filhos e habilidades passivas sem chamar o caminho mais curto de mais prático.|Operação da base por objetivo|Comece pelo trabalho necessário e conecte funções dos Pals, demanda de criação e estruturas.|Servidor dedicado e backup|Crie configurações com as chaves oficiais atuais, valide avisos e aplique após o backup.|Preparação para combate|Compare multiplicadores elementais verificados, habilidades ativas, condições de saúde e tratamentos."),
  "ru-RU":make("Руководства Palworld","Практические процессы, связывающие проверенные карту, базы данных, калькуляторы и серверные инструменты.","Практическое руководство","Рекомендуемый порядок","Открывайте инструменты по порядку, проверяйте актуальные данные и используйте результат во время игры.","Открыть процесс","Связанные инструменты","Граница точности","Руководства используют проверенные данные; непроверенные значения и формулы не оцениваются.","Первые шаги и первая база|Используйте карту, каталог Палов и планировщик базы для безопасного маршрута и основных работ.|Проверка для вернувшихся игроков|Проверьте задания, технологии и экспедиции до траты ресурсов после крупного обновления.|Основы разведения|Проверяйте связи родителей и потомков и пассивные навыки, не называя кратчайший путь самым практичным.|Работа базы по цели|Начните с нужной работы и свяжите роли Палов, производство и постройки.|Выделенный сервер и резервная копия|Создайте настройки по актуальным официальным ключам, проверьте предупреждения и примените после копирования.|Подготовка к бою|Сравните проверенные множители стихий, активные навыки, состояния здоровья и лечение."),
  "id-ID":make("Panduan Palworld","Alur praktis yang menghubungkan peta, basis data, kalkulator, dan alat server terverifikasi.","Panduan praktis","Alur yang disarankan","Buka alat tertaut secara berurutan, periksa data saat ini, dan gunakan hasilnya saat bermain.","Buka alur","Alat terkait","Batas akurasi","Panduan mengatur data terverifikasi; nilai dan rumus yang belum terverifikasi tidak diperkirakan.","Langkah awal dan base pertama|Gunakan peta, katalog Pal, dan perencana base untuk rute aman serta peran kerja penting.|Checklist pemain yang kembali|Periksa quest, teknologi, dan ekspedisi sebelum memakai sumber daya setelah pembaruan besar.|Dasar breeding|Periksa hubungan induk-anak dan skill pasif tanpa menyebut jalur terpendek sebagai yang paling praktis.|Operasi base berdasarkan tujuan|Mulai dari pekerjaan yang dibutuhkan lalu hubungkan peran Pal, kebutuhan crafting, dan struktur.|Server khusus dan cadangan|Buat pengaturan dari kunci resmi saat ini, periksa peringatan, lalu terapkan setelah mencadangkan.|Persiapan pertempuran|Bandingkan pengali elemen terverifikasi, skill aktif, kondisi kesehatan, dan perawatan."),
  "th-TH":make("คู่มือ Palworld","ขั้นตอนใช้งานที่เชื่อมแผนที่ ฐานข้อมูล เครื่องคำนวณ และเครื่องมือเซิร์ฟเวอร์ที่ตรวจสอบแล้ว","คู่มือใช้งาน","ลำดับที่แนะนำ","เปิดเครื่องมือที่เชื่อมโยงตามลำดับ ตรวจสอบข้อมูลปัจจุบัน และใช้ผลลัพธ์ระหว่างเล่น","เปิดขั้นตอน","เครื่องมือที่เกี่ยวข้อง","ขอบเขตความแม่นยำ","คู่มือนี้จัดข้อมูลที่ตรวจสอบแล้ว และไม่ประมาณค่าหรือสูตรที่ยังไม่ตรวจสอบ","เริ่มต้นและฐานแรก|ใช้แผนที่ รายการ Pal และตัววางแผนฐานเพื่อเลือกเส้นทางปลอดภัยและงานสำคัญ|รายการตรวจสอบสำหรับผู้กลับมา|ตรวจภารกิจ เทคโนโลยี และการสำรวจก่อนใช้ทรัพยากรหลังอัปเดตใหญ่|พื้นฐานการผสมพันธุ์|ตรวจความสัมพันธ์พ่อแม่กับลูกและสกิลติดตัว โดยไม่เรียกเส้นทางสั้นที่สุดว่าใช้งานดีที่สุด|การจัดการฐานตามเป้าหมาย|เริ่มจากงานที่ต้องทำ แล้วเชื่อมบทบาท Pal ความต้องการคราฟต์ และสิ่งปลูกสร้าง|เซิร์ฟเวอร์เฉพาะและการสำรอง|สร้างค่าจากคีย์ทางการปัจจุบัน ตรวจคำเตือน และใช้หลังสำรองข้อมูล|เตรียมการต่อสู้|เปรียบเทียบตัวคูณธาตุที่ตรวจสอบแล้ว สกิลใช้งาน สภาวะสุขภาพ และการรักษา"),
  "tr-TR":make("Palworld rehberleri","Doğrulanmış harita, veri tabanları, hesaplayıcılar ve sunucu araçlarını bağlayan pratik akışlar.","Pratik rehber","Önerilen akış","Bağlantılı araçları sırayla açın, güncel verileri doğrulayın ve sonucu oyun yanında kullanın.","Akışı aç","İlgili araçlar","Doğruluk sınırı","Rehberler doğrulanmış verileri düzenler; doğrulanmamış değer ve formüller tahmin edilmez.","İlk adımlar ve ilk üs|Güvenli rota ve temel işler için harita, Pal kataloğu ve üs planlayıcıyı kullanın.|Geri dönen oyuncu kontrolü|Büyük güncellemeden sonra kaynak harcamadan önce görevleri, teknolojiyi ve seferleri inceleyin.|Üretme temelleri|En kısa yolu en pratik saymadan ebeveyn-yavru ilişkilerini ve pasif becerileri kontrol edin.|Hedef odaklı üs işletimi|Gerekli işten başlayıp Pal rollerini, üretim talebini ve yapıları bağlayın.|Özel sunucu ve yedekleme|Güncel resmî anahtarlarla ayar oluşturun, uyarıları denetleyin ve yedekten sonra uygulayın.|Savaşa hazırlık|Doğrulanmış element çarpanlarını, aktif becerileri, sağlık durumlarını ve tedavileri karşılaştırın."),
  "vi-VN":make("Hướng dẫn Palworld","Quy trình thực tế kết nối bản đồ, cơ sở dữ liệu, công cụ tính và công cụ máy chủ đã xác minh.","Hướng dẫn thực tế","Quy trình đề xuất","Mở từng công cụ theo thứ tự, kiểm tra dữ liệu hiện tại và dùng kết quả khi chơi.","Mở quy trình","Công cụ liên quan","Giới hạn độ chính xác","Hướng dẫn sắp xếp dữ liệu đã xác minh; giá trị và công thức chưa xác minh không được ước tính.","Bước đầu và căn cứ đầu tiên|Dùng bản đồ, danh mục Pal và trình lập kế hoạch căn cứ để chọn tuyến an toàn và công việc thiết yếu.|Danh sách cho người chơi quay lại|Kiểm tra nhiệm vụ, công nghệ và thám hiểm trước khi dùng tài nguyên sau bản cập nhật lớn.|Cơ bản về phối giống|Kiểm tra quan hệ cha mẹ-con và kỹ năng bị động, không gọi đường ngắn nhất là thực tế nhất.|Vận hành căn cứ theo mục tiêu|Bắt đầu từ công việc cần làm rồi nối vai trò Pal, nhu cầu chế tạo và công trình.|Máy chủ riêng và sao lưu|Tạo thiết lập từ khóa chính thức hiện tại, kiểm tra cảnh báo và áp dụng sau khi sao lưu.|Chuẩn bị chiến đấu|So sánh hệ số nguyên tố đã xác minh, kỹ năng chủ động, tình trạng sức khỏe và điều trị."),
  "pl-PL":make("Poradniki Palworld","Praktyczne procesy łączące zweryfikowaną mapę, bazy danych, kalkulatory i narzędzia serwera.","Poradnik praktyczny","Zalecany proces","Otwieraj narzędzia po kolei, sprawdzaj aktualne dane i korzystaj z wyniku podczas gry.","Otwórz proces","Powiązane narzędzia","Granica dokładności","Poradniki porządkują zweryfikowane dane; niezweryfikowane wartości i wzory nie są szacowane.","Pierwsze kroki i pierwsza baza|Użyj mapy, katalogu Pali i planera bazy, aby wybrać bezpieczną trasę i ważne role pracy.|Lista dla powracających graczy|Sprawdź zadania, technologię i ekspedycje przed wydaniem zasobów po dużej aktualizacji.|Podstawy hodowli|Sprawdź relacje rodzic-potomek i umiejętności pasywne, nie nazywając najkrótszej drogi najbardziej praktyczną.|Baza według celu|Zacznij od potrzebnej pracy i połącz role Pali, zapotrzebowanie produkcji oraz budowle.|Serwer dedykowany i kopia|Utwórz ustawienia z aktualnych oficjalnych kluczy, sprawdź ostrzeżenia i zastosuj po wykonaniu kopii.|Przygotowanie do walki|Porównaj zweryfikowane mnożniki żywiołów, aktywne umiejętności, stany zdrowia i leczenie."),
};

export const guideCopyProvenance=Object.fromEntries(Object.keys(guideCopy).map(locale=>[locale,"gpt"])) as Record<Locale,"gpt">;

export const guideRoute=(slug:string)=>`guides/${slug}`;
export const findGuide=(route:string)=>guideDefinitions.find(guide=>guideRoute(guide.slug)===route);
