import type {Locale} from "./config";

export type HealthCopy={title:string;intro:string;san:string;conditions:string;medicines:string;treatment:string;recipe:string;work:string;noHp:string;numericUnavailable:string;back:string;all:string;category:string;illness:string;injury:string;mental:string;eating:string;search:string;details:string};
const en:HealthCopy={title:"Pal Health",intro:"Understand SAN, verified conditions, the supplies that treat them, and each medicine recipe.",san:"SAN and recovery",conditions:"Conditions",medicines:"Medical supplies",treatment:"Treatment",recipe:"Recipe",work:"Work amount",noHp:"Medical supplies cure conditions but do not restore HP.",numericUnavailable:"Exact SAN thresholds and numeric penalties are not shown because they are not verified in the extracted behavior data.",back:"Back to Pal Health",all:"All",category:"Condition type",illness:"Illness",injury:"Injury",mental:"Mental",eating:"Eating",search:"Search conditions and medicines",details:"View details"};
export const healthCopy:Record<Locale,HealthCopy>={
  "en-US":en,
  "ko-KR":{title:"팰 건강",intro:"SAN의 의미와 확인된 질병·부상, 치료 약품, 제작 재료를 한곳에서 확인하세요.",san:"SAN과 회복",conditions:"질병 및 부상",medicines:"치료 약품",treatment:"치료 약품",recipe:"제작 재료",work:"작업량",noHp:"의약품은 상태 이상을 치료하지만 HP를 회복하지는 않습니다.",numericUnavailable:"정확한 SAN 발생 기준과 수치 패널티는 추출된 행동 데이터에서 직접 확인되지 않아 표시하지 않습니다.",back:"팰 건강으로 돌아가기",all:"전체",category:"상태 유형",illness:"질병",injury:"부상",mental:"정신",eating:"섭식",search:"질병과 약품 검색",details:"상세 보기"},
  "ja-JP":{...en,title:"パルの健康",intro:"SAN、確認済みの病気やケガ、治療薬、薬のレシピを確認できます。",san:"SANと回復",conditions:"状態異常",medicines:"医薬品",treatment:"治療薬",recipe:"レシピ",work:"作業量",noHp:"医薬品は状態異常を治療しますが、HPは回復しません。",numericUnavailable:"正確なSAN発生値と数値ペナルティは検証できていないため表示しません。",back:"パルの健康に戻る",all:"すべて",category:"状態の種類",illness:"病気",injury:"ケガ",mental:"精神",eating:"摂食",search:"状態異常と医薬品を検索",details:"詳細を見る"},
  "zh-CN":{...en,title:"帕鲁健康",intro:"查看SAN、已验证的疾病与伤势、治疗药品及配方。",san:"SAN与恢复",conditions:"异常状态",medicines:"药品",treatment:"治疗药品",recipe:"配方",work:"工作量",noHp:"药品可治疗异常状态，但不会恢复HP。",numericUnavailable:"由于尚未从行为数据中验证，暂不显示精确SAN阈值和数值惩罚。",back:"返回帕鲁健康",all:"全部",category:"状态类型",illness:"疾病",injury:"伤势",mental:"精神",eating:"饮食",search:"搜索状态和药品",details:"查看详情"},
  "zh-TW":{...en,title:"帕魯健康",intro:"查看SAN、已驗證的疾病與傷勢、治療藥品及配方。",san:"SAN與恢復",conditions:"異常狀態",medicines:"藥品",treatment:"治療藥品",recipe:"配方",work:"工作量",noHp:"藥品可治療異常狀態，但不會回復生命值。",numericUnavailable:"精確SAN門檻與數值懲罰尚未由行為資料驗證，因此不顯示。",back:"返回帕魯健康",all:"全部",category:"狀態類型",illness:"疾病",injury:"受傷",mental:"精神",eating:"飲食",search:"搜尋狀態與藥品",details:"查看詳情"},
  "de-DE":{...en,title:"Pal-Gesundheit",san:"SAN und Erholung",conditions:"Beschwerden",medicines:"Medizin",treatment:"Behandlung",recipe:"Rezept",work:"Arbeitsaufwand",all:"Alle",category:"Art",illness:"Krankheit",injury:"Verletzung",mental:"Psychisch",eating:"Ernährung",search:"Beschwerden und Medizin suchen",details:"Details"},
  "fr-FR":{...en,title:"Santé des Pals",san:"SAN et récupération",conditions:"Affections",medicines:"Médicaments",treatment:"Traitement",recipe:"Recette",work:"Travail",all:"Tout",category:"Type",illness:"Maladie",injury:"Blessure",mental:"Mental",eating:"Alimentation",search:"Rechercher affections et médicaments",details:"Voir les détails"},
  "it-IT":{...en,title:"Salute dei Pal",san:"SAN e recupero",conditions:"Condizioni",medicines:"Medicine",treatment:"Trattamento",recipe:"Ricetta",work:"Lavoro",all:"Tutte",category:"Tipo",illness:"Malattia",injury:"Lesione",mental:"Mentale",eating:"Alimentazione",search:"Cerca condizioni e medicine",details:"Dettagli"},
  "es-ES":{...en,title:"Salud de los Pals",san:"Cordura y recuperación",conditions:"Afecciones",medicines:"Medicinas",treatment:"Tratamiento",recipe:"Receta",work:"Trabajo",all:"Todas",category:"Tipo",illness:"Enfermedad",injury:"Lesión",mental:"Mental",eating:"Alimentación",search:"Buscar afecciones y medicinas",details:"Ver detalles"},
  "es-419":{...en,title:"Salud de los Pals",san:"Salud mental y recuperación",conditions:"Afecciones",medicines:"Medicinas",treatment:"Tratamiento",recipe:"Receta",work:"Trabajo",all:"Todas",category:"Tipo",illness:"Enfermedad",injury:"Lesión",mental:"Mental",eating:"Alimentación",search:"Buscar afecciones y medicinas",details:"Ver detalles"},
  "pt-BR":{...en,title:"Saúde dos Pals",san:"SAN e recuperação",conditions:"Condições",medicines:"Remédios",treatment:"Tratamento",recipe:"Receita",work:"Trabalho",all:"Todas",category:"Tipo",illness:"Doença",injury:"Ferimento",mental:"Mental",eating:"Alimentação",search:"Buscar condições e remédios",details:"Ver detalhes"},
  "ru-RU":{...en,title:"Здоровье Палов",san:"SAN и восстановление",conditions:"Состояния",medicines:"Медикаменты",treatment:"Лечение",recipe:"Рецепт",work:"Объём работы",all:"Все",category:"Тип",illness:"Болезнь",injury:"Травма",mental:"Психика",eating:"Питание",search:"Поиск состояний и лекарств",details:"Подробнее"},
  "id-ID":{...en,title:"Kesehatan Pal",san:"SAN dan pemulihan",conditions:"Kondisi",medicines:"Obat-obatan",treatment:"Pengobatan",recipe:"Resep",work:"Jumlah kerja",all:"Semua",category:"Jenis",illness:"Penyakit",injury:"Cedera",mental:"Mental",eating:"Makan",search:"Cari kondisi dan obat",details:"Lihat detail"},
  "th-TH":{...en,title:"สุขภาพพาล",san:"SAN และการฟื้นฟู",conditions:"อาการ",medicines:"เวชภัณฑ์",treatment:"การรักษา",recipe:"สูตร",work:"ปริมาณงาน",all:"ทั้งหมด",category:"ประเภท",illness:"โรค",injury:"บาดเจ็บ",mental:"จิตใจ",eating:"การกิน",search:"ค้นหาอาการและยา",details:"ดูรายละเอียด"},
  "tr-TR":{...en,title:"Pal Sağlığı",san:"SAN ve iyileşme",conditions:"Durumlar",medicines:"İlaçlar",treatment:"Tedavi",recipe:"Tarif",work:"İş miktarı",all:"Tümü",category:"Tür",illness:"Hastalık",injury:"Yaralanma",mental:"Zihinsel",eating:"Beslenme",search:"Durum ve ilaç ara",details:"Ayrıntılar"},
  "vi-VN":{...en,title:"Sức Khỏe Pal",san:"SAN và hồi phục",conditions:"Tình trạng",medicines:"Thuốc",treatment:"Điều trị",recipe:"Công thức",work:"Lượng công việc",all:"Tất cả",category:"Loại",illness:"Bệnh",injury:"Chấn thương",mental:"Tinh thần",eating:"Ăn uống",search:"Tìm tình trạng và thuốc",details:"Xem chi tiết"},
  "pl-PL":{...en,title:"Zdrowie Pali",san:"SAN i regeneracja",conditions:"Schorzenia",medicines:"Leki",treatment:"Leczenie",recipe:"Przepis",work:"Nakład pracy",all:"Wszystkie",category:"Typ",illness:"Choroba",injury:"Uraz",mental:"Psychika",eating:"Odżywianie",search:"Szukaj schorzeń i leków",details:"Szczegóły"}
};
export const healthCopyProvenance=Object.fromEntries(Object.keys(healthCopy).map(locale=>[locale,{title:"gpt",remaining:"gpt"}])) as unknown as Record<Locale,Record<string,"gpt">>;
