import type {IconName} from "./icons";
import type {HomeCopy} from "./home-i18n";
import type {HomeCatalogGroup,HomeQuickAction} from "./home-manifest";

const esc=(value:string)=>value.replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]!);

export type HomeRenderOptions={copy:HomeCopy;href:(route:string)=>string;renderIcon:(name:IconName)=>string;quickActions:readonly HomeQuickAction[];catalogGroups:readonly HomeCatalogGroup[];guideLabel?:string;adMarkup?:string};

export function renderHomeMarkup({copy,href,renderIcon,quickActions,catalogGroups,guideLabel,adMarkup=""}:HomeRenderOptions){
  const actionMarkup=quickActions.map(action=>{const text=copy.quickActions[action.id];return `<a class="home-action-card" href="${esc(href(action.path))}" data-link data-home-action="${action.id}"><span class="home-action-icon" aria-hidden="true">${renderIcon(action.icon)}</span><div><h3>${esc(text.title)}</h3><p>${esc(text.description)}</p></div><span class="home-card-arrow" aria-hidden="true">→</span></a>`}).join("");
  const catalogMarkup=catalogGroups.map(group=>{const text=copy.catalogGroups[group.id],links=group.links.map(link=>`<a href="${esc(href(link.path))}" data-link>${esc(copy.linkLabels[link.id as keyof typeof copy.linkLabels])}<span aria-hidden="true">→</span></a>`).join("");return `<article class="home-topic-card" data-home-group="${group.id}"><header><span class="home-topic-icon" aria-hidden="true">${renderIcon(group.icon)}</span><div><h3>${esc(text.title)}</h3><p>${esc(text.description)}</p></div></header><nav aria-label="${esc(text.title)}">${links}</nav></article>`}).join("");
  const adSection=adMarkup?`<section class="home-section home-ad">${adMarkup}</section>`:"",guideMarkup=guideLabel?`<p class="home-guides-link"><a class="button primary" href="${esc(href("guides"))}" data-link>${esc(guideLabel)} <span aria-hidden="true">→</span></a></p>`:"";
  return `<section class="home-hero"><div class="home-hero-copy"><p class="eyebrow">${esc(copy.eyebrow)}</p><h1>${esc(copy.title)}</h1><p class="lede">${esc(copy.description)}</p><button class="home-search-launcher" type="button" data-open-search aria-haspopup="dialog" aria-controls="global-search-dialog"><span class="home-search-icon" aria-hidden="true">${renderIcon("search")}</span><span><strong>${esc(copy.searchLabel)}</strong><small>${esc(copy.searchHint)}</small></span><kbd>/</kbd></button>${guideMarkup}</div><div class="home-hero-art" aria-hidden="true"><div class="home-orbit orbit-a"></div><div class="home-orbit orbit-b"></div><div class="home-island island-a"></div><div class="home-island island-b"></div><span class="home-art-pin pin-a">${renderIcon("pals")}</span><span class="home-art-pin pin-b">${renderIcon("map")}</span><span class="home-art-pin pin-c">${renderIcon("database")}</span></div></section><section class="home-section home-quick"><header class="home-section-heading"><div><p class="eyebrow">01</p><h2>${esc(copy.quickTitle)}</h2></div><p>${esc(copy.quickIntro)}</p></header><div class="home-action-grid">${actionMarkup}</div></section><section class="home-section home-catalog"><header class="home-section-heading"><div><p class="eyebrow">02</p><h2>${esc(copy.catalogTitle)}</h2></div><p>${esc(copy.catalogIntro)}</p></header><div class="home-topic-grid">${catalogMarkup}</div></section>${adSection}`;
}
