import type { Locale } from "./config";
const en = {
  skip:"Skip to content",home:"Home",map:"Map",pals:"Pals",calculators:"Calculators",database:"Database",guides:"Guides",server:"Server tools",search:"Search Pals",theme:"Theme",language:"Language",
  hero:"Verified Palworld data and practical tools",tagline:"Search official Pal names, compare stats and calculate breeding results from versioned game data.",openPals:"Browse Pals",openBreed:"Breeding calculator",
  verified:"Verified dataset",verifiedBody:"299 Pal IDs matched against local game build 24181527; 44,851 breeding rows passed integrity checks.",palDex:"Pal database",palDexBody:"Search official localized names, internal IDs, stats and work suitability.",breeding:"Breeding calculator",breedingBody:"Choose two parents and genders to find the resulting Pal, or choose a target to list verified parent pairs.",parentA:"Parent A",parentB:"Parent B",genderA:"Gender A",genderB:"Gender B",anyGender:"Any gender",male:"Male",female:"Female",targetPal:"Target Pal",findParents:"Find parents",result:"Result",choose:"Choose a Pal",noResult:"No verified result for this selection.",parentPairs:"Verified parent pairs",mapTitle:"Personal planning map",mapBody:"Create coordinate pins locally without sending routes or notes anywhere.",pinName:"Pin name",pinCategory:"Category",coordinateX:"X coordinate",coordinateY:"Y coordinate",addPin:"Add pin",remove:"Remove",pins:"Pins",noPins:"No personal pins yet.",localMapNote:"Personal pins are stored only in this browser. No unverified game locations are preloaded.",stats:"Stats",work:"Work suitability",hp:"HP",attack:"Attack",defense:"Defense",rarity:"Rarity",nocturnal:"Nocturnal",yes:"Yes",no:"No",dataVersion:"Data version",gameBuild:"Game build",results:"results",footer:"Only verified, versioned game facts are published.",coming:"This section is being prepared with verified game-file data.",serverTitle:"Server settings assistant",generate:"Generate INI",players:"Maximum players",workSpeed:"Work speed",pvp:"Enable PvP",backup:"Enable backups",copy:"Copy",privacy:"Privacy",consentTitle:"Privacy choices",consentBody:"Optional analytics and advertising stay off unless you allow them. Search text, map pins and server settings are never sent.",allow:"Allow optional services",decline:"Keep disabled",adReserved:"Advertisement space",itemDatabase:"Item database",itemDatabaseBody:"Search legal in-game items using official localized names and versioned game-file values.",searchItems:"Search items",openCrafting:"Open crafting calculator",rank:"Rank",stack:"Stack",weight:"Weight",price:"Price",crafting:"Crafting calculator",craftingBody:"Calculate direct and recursively expanded materials from verified game recipes. When a product has multiple recipes, the recipe ID shown below is used.",product:"Product",quantity:"Quantity",chooseRecipe:"Choose a recipe",ownedMaterials:"Owned materials (optional): one internal ID and amount per line, for example Wood=10.",workAmount:"Work",directMaterials:"Direct materials",expandedMaterials:"Expanded net materials"
};
export type Messages=typeof en;
const ko:Messages = {
  skip:"본문으로 건너뛰기",home:"홈",map:"지도",pals:"팰",calculators:"계산기",database:"데이터베이스",guides:"가이드",server:"서버 도구",search:"팰 검색",theme:"테마",language:"언어",
  hero:"검증된 Palworld 데이터와 실용 도구",tagline:"공식 팰 이름을 검색하고 능력치를 비교하며, 버전이 기록된 게임 데이터로 교배 결과를 계산하세요.",openPals:"팰 도감 보기",openBreed:"교배 계산기",
  verified:"검증된 데이터셋",verifiedBody:"팰 ID 299종을 로컬 게임 빌드 24181527과 대조했으며, 교배 결과 44,851건의 무결성을 확인했습니다.",palDex:"팰 도감",palDexBody:"공식 현지화 이름, 내부 ID, 능력치와 작업 적성을 검색합니다.",breeding:"교배 계산기",breedingBody:"부모 팰과 성별을 선택해 결과를 확인하거나, 목표 팰을 선택해 검증된 부모 조합을 역검색합니다.",parentA:"부모 A",parentB:"부모 B",genderA:"성별 A",genderB:"성별 B",anyGender:"성별 무관",male:"수컷",female:"암컷",targetPal:"목표 팰",findParents:"부모 조합 찾기",result:"결과",choose:"팰 선택",noResult:"이 선택에 해당하는 검증된 결과가 없습니다.",parentPairs:"검증된 부모 조합",mapTitle:"개인 탐험 지도",mapBody:"경로나 메모를 외부로 보내지 않고 좌표 핀을 직접 관리합니다.",pinName:"핀 이름",pinCategory:"분류",coordinateX:"X 좌표",coordinateY:"Y 좌표",addPin:"핀 추가",remove:"삭제",pins:"핀 목록",noPins:"저장된 개인 핀이 없습니다.",localMapNote:"개인 핀은 이 브라우저에만 저장됩니다. 검증되지 않은 게임 위치는 미리 표시하지 않습니다.",stats:"능력치",work:"작업 적성",hp:"체력",attack:"공격",defense:"방어",rarity:"희귀도",nocturnal:"야행성",yes:"예",no:"아니요",dataVersion:"데이터 버전",gameBuild:"게임 빌드",results:"개 결과",footer:"버전이 기록되고 검증된 게임 정보만 공개합니다.",coming:"게임 파일 데이터 검증과 함께 이 섹션을 준비하고 있습니다.",serverTitle:"서버 설정 도우미",generate:"INI 생성",players:"최대 인원",workSpeed:"작업 속도",pvp:"PvP 활성화",backup:"백업 활성화",copy:"복사",privacy:"개인정보 처리방침",consentTitle:"개인정보 선택",consentBody:"허용하기 전에는 선택적 분석 및 광고가 꺼져 있습니다. 검색어, 지도 핀, 서버 설정은 전송하지 않습니다.",allow:"선택 서비스 허용",decline:"비활성 상태 유지",adReserved:"광고 영역",itemDatabase:"아이템",itemDatabaseBody:"공식 현지화 이름과 버전이 기록된 게임 파일 수치로 실제 사용 가능한 아이템을 검색합니다.",searchItems:"아이템 검색",openCrafting:"제작 계산기 열기",rank:"랭크",stack:"최대 중첩",weight:"무게",price:"가격",crafting:"제작 계산기",craftingBody:"검증된 게임 제작식에서 직접 재료와 재귀 확장 재료를 계산합니다. 한 제품에 제작식이 여러 개면 아래 표시된 제작식 ID를 사용합니다.",product:"제작품",quantity:"수량",chooseRecipe:"제작식을 선택하세요",ownedMaterials:"보유 재료(선택): 한 줄에 내부 ID와 수량을 입력하세요. 예: Wood=10",workAmount:"작업량",directMaterials:"직접 재료",expandedMaterials:"보유량 반영 최종 재료"
};
const ja:Messages = {
  skip:"本文へ移動",home:"ホーム",map:"マップ",pals:"パル",calculators:"計算ツール",database:"データベース",guides:"ガイド",server:"サーバーツール",search:"パルを検索",theme:"テーマ",language:"言語",
  hero:"検証済みのPalworldデータと実用ツール",tagline:"公式のパル名を検索し、ステータスを比較し、バージョン管理されたゲームデータから配合結果を計算できます。",openPals:"パル図鑑を見る",openBreed:"配合計算ツール",
  verified:"検証済みデータセット",verifiedBody:"299件のパルIDをローカルゲームビルド24181527と照合し、44,851件の配合データの整合性を確認しました。",palDex:"パル図鑑",palDexBody:"公式ローカライズ名、内部ID、ステータス、作業適性を検索できます。",breeding:"配合計算ツール",breedingBody:"親パルと性別から結果を確認するか、目標のパルから検証済みの親の組み合わせを逆引きします。",parentA:"親A",parentB:"親B",genderA:"性別A",genderB:"性別B",anyGender:"性別不問",male:"オス",female:"メス",targetPal:"目標のパル",findParents:"親の組み合わせを検索",result:"結果",choose:"パルを選択",noResult:"この選択に該当する検証済みの結果はありません。",parentPairs:"検証済みの親の組み合わせ",
  mapTitle:"個人用探索マップ",mapBody:"ルートやメモを外部へ送信せず、座標ピンを端末内で管理できます。",pinName:"ピン名",pinCategory:"カテゴリ",coordinateX:"X座標",coordinateY:"Y座標",addPin:"ピンを追加",remove:"削除",pins:"ピン一覧",noPins:"個人用ピンはまだありません。",localMapNote:"個人用ピンはこのブラウザ内だけに保存されます。未検証のゲーム内地点は事前表示しません。",
  stats:"ステータス",work:"作業適性",hp:"HP",attack:"攻撃",defense:"防御",rarity:"レア度",nocturnal:"夜行性",yes:"はい",no:"いいえ",dataVersion:"データバージョン",gameBuild:"ゲームビルド",results:"件",footer:"バージョンが記録され、検証済みのゲーム情報のみを公開します。",coming:"このセクションはゲームファイルのデータ検証とともに準備中です。",serverTitle:"サーバー設定アシスタント",generate:"INIを生成",players:"最大プレイヤー数",workSpeed:"作業速度",pvp:"PvPを有効化",backup:"バックアップを有効化",copy:"コピー",privacy:"プライバシー",consentTitle:"プライバシー設定",consentBody:"許可するまで任意の分析と広告は無効です。検索語、マップピン、サーバー設定は送信されません。",allow:"任意サービスを許可",decline:"無効のままにする",adReserved:"広告スペース",
  itemDatabase:"アイテムデータベース",itemDatabaseBody:"公式ローカライズ名とバージョン管理されたゲームファイルの値から、ゲーム内で有効なアイテムを検索できます。",searchItems:"アイテムを検索",openCrafting:"クラフト計算ツールを開く",rank:"ランク",stack:"最大スタック",weight:"重量",price:"価格",crafting:"クラフト計算ツール",craftingBody:"検証済みのゲームレシピから直接素材と再帰展開した素材を計算します。同じ製品に複数のレシピがある場合は、下に表示されるレシピIDを使用します。",product:"製品",quantity:"数量",chooseRecipe:"レシピを選択",ownedMaterials:"所持素材（任意）：1行につき内部IDと数量を入力してください。例：Wood=10",workAmount:"作業量",directMaterials:"直接素材",expandedMaterials:"所持数を反映した最終素材"
};
const zhCN:Messages = {
  skip:"跳到正文",home:"首页",map:"地图",pals:"帕鲁",calculators:"计算器",database:"数据库",guides:"指南",server:"服务器工具",search:"搜索帕鲁",theme:"主题",language:"语言",
  hero:"经过验证的 Palworld 数据与实用工具",tagline:"搜索帕鲁官方名称、比较属性，并使用带版本记录的游戏数据计算配种结果。",openPals:"浏览帕鲁图鉴",openBreed:"配种计算器",verified:"已验证的数据集",verifiedBody:"已将299个帕鲁ID与本地游戏版本24181527核对，并通过44,851条配种数据的完整性检查。",palDex:"帕鲁图鉴",palDexBody:"搜索官方本地化名称、内部ID、属性和工作适应性。",breeding:"配种计算器",breedingBody:"选择两只亲代及其性别以查找结果，或选择目标帕鲁查看经过验证的亲代组合。",parentA:"亲代A",parentB:"亲代B",genderA:"性别A",genderB:"性别B",anyGender:"不限性别",male:"雄性",female:"雌性",targetPal:"目标帕鲁",findParents:"查找亲代",result:"结果",choose:"选择帕鲁",noResult:"此选择没有经过验证的结果。",parentPairs:"已验证的亲代组合",
  mapTitle:"个人探索地图",mapBody:"在本地创建坐标标记，不会将路线或备注发送到任何地方。",pinName:"标记名称",pinCategory:"分类",coordinateX:"X坐标",coordinateY:"Y坐标",addPin:"添加标记",remove:"删除",pins:"标记列表",noPins:"尚无个人标记。",localMapNote:"个人标记仅保存在此浏览器中，不会预先显示未经验证的游戏地点。",stats:"属性",work:"工作适应性",hp:"生命值",attack:"攻击",defense:"防御",rarity:"稀有度",nocturnal:"夜行性",yes:"是",no:"否",dataVersion:"数据版本",gameBuild:"游戏版本",results:"条结果",footer:"仅发布经过验证并记录版本的游戏信息。",coming:"此部分正在配合游戏文件数据验证进行准备。",serverTitle:"服务器设置助手",generate:"生成INI",players:"最大玩家数",workSpeed:"工作速度",pvp:"启用PvP",backup:"启用备份",copy:"复制",privacy:"隐私",consentTitle:"隐私选项",consentBody:"在您允许前，可选分析和广告保持关闭。搜索文字、地图标记和服务器设置绝不会被发送。",allow:"允许可选服务",decline:"保持关闭",adReserved:"广告区域",
  itemDatabase:"道具数据库",itemDatabaseBody:"使用官方本地化名称和带版本记录的游戏文件数值搜索游戏内有效道具。",searchItems:"搜索道具",openCrafting:"打开制作计算器",rank:"等级",stack:"最大堆叠",weight:"重量",price:"价格",crafting:"制作计算器",craftingBody:"根据经过验证的游戏配方计算直接材料和递归展开材料。若同一产品有多个配方，将使用下方显示的配方ID。",product:"产品",quantity:"数量",chooseRecipe:"选择配方",ownedMaterials:"已有材料（可选）：每行填写一个内部ID和数量，例如 Wood=10。",workAmount:"工作量",directMaterials:"直接材料",expandedMaterials:"扣除已有数量后的最终材料"
};
const zhTW:Messages = {
  skip:"跳至正文",home:"首頁",map:"地圖",pals:"帕魯",calculators:"計算器",database:"資料庫",guides:"指南",server:"伺服器工具",search:"搜尋帕魯",theme:"主題",language:"語言",
  hero:"經過驗證的 Palworld 資料與實用工具",tagline:"搜尋帕魯官方名稱、比較能力值，並使用附版本紀錄的遊戲資料計算配種結果。",openPals:"瀏覽帕魯圖鑑",openBreed:"配種計算器",verified:"已驗證的資料集",verifiedBody:"已將299個帕魯ID與本機遊戲組建24181527核對，並通過44,851筆配種資料的完整性檢查。",palDex:"帕魯圖鑑",palDexBody:"搜尋官方在地化名稱、內部ID、能力值與工作適應性。",breeding:"配種計算器",breedingBody:"選擇兩隻親代及其性別以查找結果，或選擇目標帕魯查看經過驗證的親代組合。",parentA:"親代A",parentB:"親代B",genderA:"性別A",genderB:"性別B",anyGender:"不限性別",male:"雄性",female:"雌性",targetPal:"目標帕魯",findParents:"查找親代",result:"結果",choose:"選擇帕魯",noResult:"此選擇沒有經過驗證的結果。",parentPairs:"已驗證的親代組合",
  mapTitle:"個人探索地圖",mapBody:"在本機建立座標標記，不會將路線或備註傳送至任何地方。",pinName:"標記名稱",pinCategory:"分類",coordinateX:"X座標",coordinateY:"Y座標",addPin:"新增標記",remove:"刪除",pins:"標記清單",noPins:"尚無個人標記。",localMapNote:"個人標記只會儲存在此瀏覽器中，不會預先顯示未經驗證的遊戲地點。",stats:"能力值",work:"工作適應性",hp:"生命值",attack:"攻擊",defense:"防禦",rarity:"稀有度",nocturnal:"夜行性",yes:"是",no:"否",dataVersion:"資料版本",gameBuild:"遊戲組建",results:"筆結果",footer:"只發布經過驗證並記錄版本的遊戲資訊。",coming:"此區段正配合遊戲檔案資料驗證進行準備。",serverTitle:"伺服器設定助手",generate:"產生INI",players:"玩家人數上限",workSpeed:"工作速度",pvp:"啟用PvP",backup:"啟用備份",copy:"複製",privacy:"隱私權",consentTitle:"隱私權選項",consentBody:"在您允許前，選用分析與廣告會保持關閉。搜尋文字、地圖標記及伺服器設定絕不會被傳送。",allow:"允許選用服務",decline:"保持關閉",adReserved:"廣告區域",
  itemDatabase:"道具資料庫",itemDatabaseBody:"使用官方在地化名稱和附版本紀錄的遊戲檔案數值搜尋遊戲內有效道具。",searchItems:"搜尋道具",openCrafting:"開啟製作計算器",rank:"等級",stack:"最大堆疊",weight:"重量",price:"價格",crafting:"製作計算器",craftingBody:"依據經過驗證的遊戲配方計算直接材料與遞迴展開材料。若同一產品有多個配方，將使用下方顯示的配方ID。",product:"產品",quantity:"數量",chooseRecipe:"選擇配方",ownedMaterials:"已有材料（選填）：每行填寫一個內部ID與數量，例如 Wood=10。",workAmount:"工作量",directMaterials:"直接材料",expandedMaterials:"扣除已有數量後的最終材料"
};
const fr:Messages = {
  skip:"Aller au contenu",home:"Accueil",map:"Carte",pals:"Pals",calculators:"Calculateurs",database:"Base de données",guides:"Guides",server:"Outils serveur",search:"Rechercher des Pals",theme:"Thème",language:"Langue",
  hero:"Données Palworld vérifiées et outils pratiques",tagline:"Recherchez les noms officiels des Pals, comparez leurs statistiques et calculez les résultats de reproduction à partir de données de jeu versionnées.",openPals:"Parcourir les Pals",openBreed:"Calculateur de reproduction",verified:"Jeu de données vérifié",verifiedBody:"299 ID de Pals ont été comparés à la version locale 24181527 et 44 851 résultats de reproduction ont passé les contrôles d’intégrité.",palDex:"Base des Pals",palDexBody:"Recherchez les noms officiels localisés, ID internes, statistiques et aptitudes au travail.",breeding:"Calculateur de reproduction",breedingBody:"Choisissez deux parents et leur sexe pour obtenir le Pal résultant, ou sélectionnez une cible pour afficher les couples vérifiés.",parentA:"Parent A",parentB:"Parent B",genderA:"Sexe A",genderB:"Sexe B",anyGender:"Tout sexe",male:"Mâle",female:"Femelle",targetPal:"Pal cible",findParents:"Trouver les parents",result:"Résultat",choose:"Choisir un Pal",noResult:"Aucun résultat vérifié pour cette sélection.",parentPairs:"Couples de parents vérifiés",
  mapTitle:"Carte d’exploration personnelle",mapBody:"Créez des repères de coordonnées localement sans transmettre vos itinéraires ni vos notes.",pinName:"Nom du repère",pinCategory:"Catégorie",coordinateX:"Coordonnée X",coordinateY:"Coordonnée Y",addPin:"Ajouter un repère",remove:"Supprimer",pins:"Repères",noPins:"Aucun repère personnel.",localMapNote:"Les repères personnels sont stockés uniquement dans ce navigateur. Aucun emplacement non vérifié n’est préchargé.",stats:"Statistiques",work:"Aptitudes au travail",hp:"PV",attack:"Attaque",defense:"Défense",rarity:"Rareté",nocturnal:"Nocturne",yes:"Oui",no:"Non",dataVersion:"Version des données",gameBuild:"Version du jeu",results:"résultats",footer:"Seules les informations de jeu vérifiées et versionnées sont publiées.",coming:"Cette section est en préparation avec des données vérifiées issues des fichiers du jeu.",serverTitle:"Assistant de configuration serveur",generate:"Générer l’INI",players:"Nombre maximal de joueurs",workSpeed:"Vitesse de travail",pvp:"Activer le JcJ",backup:"Activer les sauvegardes",copy:"Copier",privacy:"Confidentialité",consentTitle:"Choix de confidentialité",consentBody:"Les analyses et publicités facultatives restent désactivées sans votre accord. Les recherches, repères et paramètres serveur ne sont jamais transmis.",allow:"Autoriser les services facultatifs",decline:"Laisser désactivé",adReserved:"Espace publicitaire",
  itemDatabase:"Base de données des objets",itemDatabaseBody:"Recherchez les objets valides en jeu avec leurs noms officiels localisés et les valeurs versionnées des fichiers du jeu.",searchItems:"Rechercher des objets",openCrafting:"Ouvrir le calculateur de fabrication",rank:"Rang",stack:"Pile maximale",weight:"Poids",price:"Prix",crafting:"Calculateur de fabrication",craftingBody:"Calculez les matériaux directs et développés récursivement à partir des recettes vérifiées. Si un produit possède plusieurs recettes, l’ID affiché ci-dessous est utilisé.",product:"Produit",quantity:"Quantité",chooseRecipe:"Choisir une recette",ownedMaterials:"Matériaux possédés (facultatif) : un ID interne et une quantité par ligne, par exemple Wood=10.",workAmount:"Travail",directMaterials:"Matériaux directs",expandedMaterials:"Matériaux finaux après déduction du stock"
};
const it:Messages = {
  skip:"Vai al contenuto",home:"Home",map:"Mappa",pals:"Pal",calculators:"Calcolatori",database:"Database",guides:"Guide",server:"Strumenti server",search:"Cerca Pal",theme:"Tema",language:"Lingua",
  hero:"Dati Palworld verificati e strumenti pratici",tagline:"Cerca i nomi ufficiali dei Pal, confronta le statistiche e calcola i risultati di riproduzione usando dati di gioco con versione.",openPals:"Sfoglia i Pal",openBreed:"Calcolatore di riproduzione",verified:"Set di dati verificato",verifiedBody:"299 ID Pal sono stati confrontati con la build locale 24181527 e 44.851 risultati di riproduzione hanno superato i controlli di integrità.",palDex:"Database dei Pal",palDexBody:"Cerca nomi ufficiali localizzati, ID interni, statistiche e idoneità al lavoro.",breeding:"Calcolatore di riproduzione",breedingBody:"Scegli due genitori e i relativi sessi per trovare il Pal risultante, oppure seleziona un obiettivo per elencare le coppie verificate.",parentA:"Genitore A",parentB:"Genitore B",genderA:"Sesso A",genderB:"Sesso B",anyGender:"Qualsiasi sesso",male:"Maschio",female:"Femmina",targetPal:"Pal obiettivo",findParents:"Trova genitori",result:"Risultato",choose:"Scegli un Pal",noResult:"Nessun risultato verificato per questa selezione.",parentPairs:"Coppie di genitori verificate",
  mapTitle:"Mappa di esplorazione personale",mapBody:"Crea indicatori di coordinate in locale senza inviare percorsi o note.",pinName:"Nome indicatore",pinCategory:"Categoria",coordinateX:"Coordinata X",coordinateY:"Coordinata Y",addPin:"Aggiungi indicatore",remove:"Rimuovi",pins:"Indicatori",noPins:"Nessun indicatore personale.",localMapNote:"Gli indicatori personali vengono salvati solo in questo browser. Non vengono precaricate posizioni di gioco non verificate.",stats:"Statistiche",work:"Idoneità al lavoro",hp:"PV",attack:"Attacco",defense:"Difesa",rarity:"Rarità",nocturnal:"Notturno",yes:"Sì",no:"No",dataVersion:"Versione dati",gameBuild:"Build di gioco",results:"risultati",footer:"Vengono pubblicate solo informazioni di gioco verificate e con versione.",coming:"Questa sezione è in preparazione con dati verificati dai file di gioco.",serverTitle:"Assistente impostazioni server",generate:"Genera INI",players:"Giocatori massimi",workSpeed:"Velocità di lavoro",pvp:"Abilita PvP",backup:"Abilita backup",copy:"Copia",privacy:"Privacy",consentTitle:"Scelte sulla privacy",consentBody:"Analisi e pubblicità facoltative restano disattivate finché non le autorizzi. Ricerche, indicatori e impostazioni server non vengono mai inviati.",allow:"Consenti servizi facoltativi",decline:"Mantieni disattivati",adReserved:"Spazio pubblicitario",
  itemDatabase:"Database degli oggetti",itemDatabaseBody:"Cerca gli oggetti validi nel gioco usando i nomi ufficiali localizzati e i valori con versione estratti dai file di gioco.",searchItems:"Cerca oggetti",openCrafting:"Apri il calcolatore di creazione",rank:"Rango",stack:"Pila massima",weight:"Peso",price:"Prezzo",crafting:"Calcolatore di creazione",craftingBody:"Calcola i materiali diretti e quelli espansi ricorsivamente dalle ricette verificate. Se un prodotto ha più ricette, viene usato l’ID mostrato sotto.",product:"Prodotto",quantity:"Quantità",chooseRecipe:"Scegli una ricetta",ownedMaterials:"Materiali posseduti (facoltativo): un ID interno e una quantità per riga, ad esempio Wood=10.",workAmount:"Lavoro",directMaterials:"Materiali diretti",expandedMaterials:"Materiali finali al netto delle scorte"
};
const de:Messages = {
  skip:"Zum Inhalt springen",home:"Startseite",map:"Karte",pals:"Pals",calculators:"Rechner",database:"Datenbank",guides:"Leitfäden",server:"Serverwerkzeuge",search:"Pals suchen",theme:"Design",language:"Sprache",
  hero:"Geprüfte Palworld-Daten und praktische Werkzeuge",tagline:"Durchsuche offizielle Pal-Namen, vergleiche Werte und berechne Zuchtergebnisse mit versionierten Spieldaten.",openPals:"Pals durchsuchen",openBreed:"Zuchtrechner",verified:"Geprüfter Datensatz",verifiedBody:"299 Pal-IDs wurden mit dem lokalen Spiel-Build 24181527 abgeglichen; 44.851 Zuchtdatensätze bestanden die Integritätsprüfung.",palDex:"Pal-Datenbank",palDexBody:"Durchsuche offizielle lokalisierte Namen, interne IDs, Werte und Arbeitseignungen.",breeding:"Zuchtrechner",breedingBody:"Wähle zwei Eltern und ihre Geschlechter, um das Ergebnis zu finden, oder wähle ein Ziel-Pal für geprüfte Elternpaare.",parentA:"Elternteil A",parentB:"Elternteil B",genderA:"Geschlecht A",genderB:"Geschlecht B",anyGender:"Beliebiges Geschlecht",male:"Männlich",female:"Weiblich",targetPal:"Ziel-Pal",findParents:"Eltern finden",result:"Ergebnis",choose:"Pal auswählen",noResult:"Für diese Auswahl gibt es kein geprüftes Ergebnis.",parentPairs:"Geprüfte Elternpaare",
  mapTitle:"Persönliche Erkundungskarte",mapBody:"Erstelle Koordinatenmarkierungen lokal, ohne Routen oder Notizen zu übertragen.",pinName:"Markierungsname",pinCategory:"Kategorie",coordinateX:"X-Koordinate",coordinateY:"Y-Koordinate",addPin:"Markierung hinzufügen",remove:"Entfernen",pins:"Markierungen",noPins:"Noch keine persönlichen Markierungen.",localMapNote:"Persönliche Markierungen werden nur in diesem Browser gespeichert. Ungeprüfte Spielorte werden nicht vorgeladen.",stats:"Werte",work:"Arbeitseignung",hp:"LP",attack:"Angriff",defense:"Verteidigung",rarity:"Seltenheit",nocturnal:"Nachtaktiv",yes:"Ja",no:"Nein",dataVersion:"Datenversion",gameBuild:"Spiel-Build",results:"Ergebnisse",footer:"Veröffentlicht werden nur geprüfte, versionierte Spielinformationen.",coming:"Dieser Bereich wird mit geprüften Daten aus den Spieldateien vorbereitet.",serverTitle:"Assistent für Servereinstellungen",generate:"INI erzeugen",players:"Maximale Spielerzahl",workSpeed:"Arbeitsgeschwindigkeit",pvp:"PvP aktivieren",backup:"Sicherungen aktivieren",copy:"Kopieren",privacy:"Datenschutz",consentTitle:"Datenschutzauswahl",consentBody:"Optionale Analyse und Werbung bleiben ohne deine Zustimmung deaktiviert. Suchtexte, Kartenmarkierungen und Servereinstellungen werden nie übertragen.",allow:"Optionale Dienste erlauben",decline:"Deaktiviert lassen",adReserved:"Werbefläche",
  itemDatabase:"Gegenstandsdatenbank",itemDatabaseBody:"Durchsuche gültige Spielgegenstände anhand offizieller lokalisierter Namen und versionierter Werte aus den Spieldateien.",searchItems:"Gegenstände suchen",openCrafting:"Herstellungsrechner öffnen",rank:"Rang",stack:"Maximaler Stapel",weight:"Gewicht",price:"Preis",crafting:"Herstellungsrechner",craftingBody:"Berechne direkte und rekursiv aufgelöste Materialien aus geprüften Spielrezepten. Gibt es mehrere Rezepte, wird die unten angezeigte Rezept-ID verwendet.",product:"Produkt",quantity:"Menge",chooseRecipe:"Rezept auswählen",ownedMaterials:"Vorhandene Materialien (optional): eine interne ID und Menge pro Zeile, zum Beispiel Wood=10.",workAmount:"Arbeitsaufwand",directMaterials:"Direkte Materialien",expandedMaterials:"Endmaterialien nach Abzug des Bestands"
};
const esES:Messages = {
  skip:"Saltar al contenido",home:"Inicio",map:"Mapa",pals:"Pals",calculators:"Calculadoras",database:"Base de datos",guides:"Guías",server:"Herramientas del servidor",search:"Buscar Pals",theme:"Tema",language:"Idioma",
  hero:"Datos verificados de Palworld y herramientas prácticas",tagline:"Busca nombres oficiales de Pals, compara estadísticas y calcula resultados de cría con datos del juego versionados.",openPals:"Explorar Pals",openBreed:"Calculadora de cría",verified:"Conjunto de datos verificado",verifiedBody:"Se cotejaron 299 ID de Pals con la compilación local 24181527 y 44.851 registros de cría superaron las comprobaciones de integridad.",palDex:"Base de datos de Pals",palDexBody:"Busca nombres oficiales localizados, ID internos, estadísticas y aptitudes de trabajo.",breeding:"Calculadora de cría",breedingBody:"Elige dos progenitores y sus sexos para obtener el Pal resultante, o selecciona un objetivo para ver parejas verificadas.",parentA:"Progenitor A",parentB:"Progenitor B",genderA:"Sexo A",genderB:"Sexo B",anyGender:"Cualquier sexo",male:"Macho",female:"Hembra",targetPal:"Pal objetivo",findParents:"Buscar progenitores",result:"Resultado",choose:"Elige un Pal",noResult:"No hay resultados verificados para esta selección.",parentPairs:"Parejas de progenitores verificadas",
  mapTitle:"Mapa personal de exploración",mapBody:"Crea marcadores de coordenadas de forma local sin enviar rutas ni notas.",pinName:"Nombre del marcador",pinCategory:"Categoría",coordinateX:"Coordenada X",coordinateY:"Coordenada Y",addPin:"Añadir marcador",remove:"Eliminar",pins:"Marcadores",noPins:"Aún no hay marcadores personales.",localMapNote:"Los marcadores personales solo se guardan en este navegador. No se precargan ubicaciones del juego sin verificar.",stats:"Estadísticas",work:"Aptitud de trabajo",hp:"PS",attack:"Ataque",defense:"Defensa",rarity:"Rareza",nocturnal:"Nocturno",yes:"Sí",no:"No",dataVersion:"Versión de datos",gameBuild:"Compilación del juego",results:"resultados",footer:"Solo se publica información del juego verificada y versionada.",coming:"Esta sección se está preparando con datos verificados de los archivos del juego.",serverTitle:"Asistente de configuración del servidor",generate:"Generar INI",players:"Máximo de jugadores",workSpeed:"Velocidad de trabajo",pvp:"Activar JcJ",backup:"Activar copias de seguridad",copy:"Copiar",privacy:"Privacidad",consentTitle:"Opciones de privacidad",consentBody:"Los análisis y anuncios opcionales permanecen desactivados hasta que los permitas. Nunca se envían búsquedas, marcadores ni ajustes del servidor.",allow:"Permitir servicios opcionales",decline:"Mantener desactivados",adReserved:"Espacio publicitario",
  itemDatabase:"Base de datos de objetos",itemDatabaseBody:"Busca objetos válidos del juego mediante nombres oficiales localizados y valores versionados de los archivos del juego.",searchItems:"Buscar objetos",openCrafting:"Abrir calculadora de fabricación",rank:"Rango",stack:"Pila máxima",weight:"Peso",price:"Precio",crafting:"Calculadora de fabricación",craftingBody:"Calcula materiales directos y expandidos de forma recursiva a partir de recetas verificadas. Si un producto tiene varias recetas, se usa el ID mostrado abajo.",product:"Producto",quantity:"Cantidad",chooseRecipe:"Elige una receta",ownedMaterials:"Materiales disponibles (opcional): un ID interno y una cantidad por línea, por ejemplo Wood=10.",workAmount:"Trabajo",directMaterials:"Materiales directos",expandedMaterials:"Materiales finales tras descontar existencias"
};
const es419:Messages={...esES,skip:"Ir al contenido",calculators:"Calculadores",server:"Herramientas de servidor",tagline:"Busca nombres oficiales de Pals, compara estadísticas y calcula resultados de crianza con datos versionados del juego.",openBreed:"Calculador de crianza",breeding:"Calculador de crianza",breedingBody:"Elige dos padres y sus sexos para obtener el Pal resultante, o selecciona un objetivo para ver parejas verificadas.",parentA:"Padre A",parentB:"Padre B",findParents:"Buscar padres",parentPairs:"Parejas de padres verificadas",gameBuild:"Versión del juego",pvp:"Activar PvP",backup:"Activar respaldos",itemDatabaseBody:"Busca objetos válidos del juego con nombres oficiales localizados y valores versionados de los archivos del juego.",openCrafting:"Abrir calculador de fabricación",crafting:"Calculador de fabricación",ownedMaterials:"Materiales disponibles (opcional): un ID interno y una cantidad por línea, por ejemplo Wood=10.",expandedMaterials:"Materiales finales después de descontar existencias"};
const ptBR:Messages = {
  skip:"Ir para o conteúdo",home:"Início",map:"Mapa",pals:"Pals",calculators:"Calculadoras",database:"Banco de dados",guides:"Guias",server:"Ferramentas de servidor",search:"Buscar Pals",theme:"Tema",language:"Idioma",
  hero:"Dados verificados de Palworld e ferramentas práticas",tagline:"Busque nomes oficiais de Pals, compare atributos e calcule resultados de reprodução com dados versionados do jogo.",openPals:"Explorar Pals",openBreed:"Calculadora de reprodução",verified:"Conjunto de dados verificado",verifiedBody:"299 IDs de Pals foram comparados com a build local 24181527; 44.851 registros de reprodução passaram nas verificações de integridade.",palDex:"Banco de dados de Pals",palDexBody:"Busque nomes oficiais localizados, IDs internos, atributos e aptidões para trabalho.",breeding:"Calculadora de reprodução",breedingBody:"Escolha dois pais e seus sexos para encontrar o Pal resultante ou selecione um alvo para listar pares verificados.",parentA:"Progenitor A",parentB:"Progenitor B",genderA:"Sexo A",genderB:"Sexo B",anyGender:"Qualquer sexo",male:"Macho",female:"Fêmea",targetPal:"Pal alvo",findParents:"Encontrar progenitores",result:"Resultado",choose:"Escolha um Pal",noResult:"Não há resultado verificado para esta seleção.",parentPairs:"Pares de progenitores verificados",
  mapTitle:"Mapa pessoal de exploração",mapBody:"Crie marcadores de coordenadas localmente sem enviar rotas ou anotações.",pinName:"Nome do marcador",pinCategory:"Categoria",coordinateX:"Coordenada X",coordinateY:"Coordenada Y",addPin:"Adicionar marcador",remove:"Remover",pins:"Marcadores",noPins:"Ainda não há marcadores pessoais.",localMapNote:"Os marcadores pessoais ficam salvos apenas neste navegador. Locais não verificados do jogo não são pré-carregados.",stats:"Atributos",work:"Aptidão para trabalho",hp:"PV",attack:"Ataque",defense:"Defesa",rarity:"Raridade",nocturnal:"Noturno",yes:"Sim",no:"Não",dataVersion:"Versão dos dados",gameBuild:"Build do jogo",results:"resultados",footer:"Somente informações verificadas e versionadas do jogo são publicadas.",coming:"Esta seção está sendo preparada com dados verificados dos arquivos do jogo.",serverTitle:"Assistente de configurações do servidor",generate:"Gerar INI",players:"Máximo de jogadores",workSpeed:"Velocidade de trabalho",pvp:"Ativar PvP",backup:"Ativar backups",copy:"Copiar",privacy:"Privacidade",consentTitle:"Opções de privacidade",consentBody:"Análises e anúncios opcionais permanecem desativados até sua permissão. Buscas, marcadores e configurações do servidor nunca são enviados.",allow:"Permitir serviços opcionais",decline:"Manter desativados",adReserved:"Espaço publicitário",
  itemDatabase:"Banco de dados de itens",itemDatabaseBody:"Busque itens válidos no jogo pelos nomes oficiais localizados e valores versionados dos arquivos do jogo.",searchItems:"Buscar itens",openCrafting:"Abrir calculadora de fabricação",rank:"Categoria",stack:"Pilha máxima",weight:"Peso",price:"Preço",crafting:"Calculadora de fabricação",craftingBody:"Calcule materiais diretos e expandidos recursivamente usando receitas verificadas. Quando um produto tem várias receitas, o ID exibido abaixo é usado.",product:"Produto",quantity:"Quantidade",chooseRecipe:"Escolha uma receita",ownedMaterials:"Materiais disponíveis (opcional): um ID interno e uma quantidade por linha, por exemplo Wood=10.",workAmount:"Trabalho",directMaterials:"Materiais diretos",expandedMaterials:"Materiais finais após descontar o estoque"
};
const idID:Messages = {
  skip:"Lewati ke konten",home:"Beranda",map:"Peta",pals:"Pal",calculators:"Kalkulator",database:"Basis data",guides:"Panduan",server:"Alat server",search:"Cari Pal",theme:"Tema",language:"Bahasa",
  hero:"Data Palworld terverifikasi dan alat praktis",tagline:"Cari nama resmi Pal, bandingkan statistik, dan hitung hasil pengembangbiakan memakai data game berversi.",openPals:"Jelajahi Pal",openBreed:"Kalkulator pengembangbiakan",verified:"Set data terverifikasi",verifiedBody:"299 ID Pal dicocokkan dengan build game lokal 24181527; 44.851 baris pengembangbiakan lolos pemeriksaan integritas.",palDex:"Basis data Pal",palDexBody:"Cari nama resmi yang dilokalkan, ID internal, statistik, dan kecocokan kerja.",breeding:"Kalkulator pengembangbiakan",breedingBody:"Pilih dua induk beserta jenis kelaminnya untuk menemukan hasil, atau pilih Pal target untuk melihat pasangan induk terverifikasi.",parentA:"Induk A",parentB:"Induk B",genderA:"Jenis kelamin A",genderB:"Jenis kelamin B",anyGender:"Jenis kelamin apa pun",male:"Jantan",female:"Betina",targetPal:"Pal target",findParents:"Cari induk",result:"Hasil",choose:"Pilih Pal",noResult:"Tidak ada hasil terverifikasi untuk pilihan ini.",parentPairs:"Pasangan induk terverifikasi",
  mapTitle:"Peta penjelajahan pribadi",mapBody:"Buat penanda koordinat secara lokal tanpa mengirim rute atau catatan.",pinName:"Nama penanda",pinCategory:"Kategori",coordinateX:"Koordinat X",coordinateY:"Koordinat Y",addPin:"Tambah penanda",remove:"Hapus",pins:"Penanda",noPins:"Belum ada penanda pribadi.",localMapNote:"Penanda pribadi hanya disimpan di browser ini. Lokasi game yang belum diverifikasi tidak dimuat sebelumnya.",stats:"Statistik",work:"Kecocokan kerja",hp:"HP",attack:"Serangan",defense:"Pertahanan",rarity:"Kelangkaan",nocturnal:"Nokturnal",yes:"Ya",no:"Tidak",dataVersion:"Versi data",gameBuild:"Build game",results:"hasil",footer:"Hanya informasi game terverifikasi dan berversi yang diterbitkan.",coming:"Bagian ini sedang disiapkan dengan data terverifikasi dari file game.",serverTitle:"Asisten pengaturan server",generate:"Buat INI",players:"Pemain maksimum",workSpeed:"Kecepatan kerja",pvp:"Aktifkan PvP",backup:"Aktifkan cadangan",copy:"Salin",privacy:"Privasi",consentTitle:"Pilihan privasi",consentBody:"Analitik dan iklan opsional tetap nonaktif sampai Anda mengizinkannya. Teks pencarian, penanda, dan pengaturan server tidak pernah dikirim.",allow:"Izinkan layanan opsional",decline:"Tetap nonaktif",adReserved:"Ruang iklan",
  itemDatabase:"Basis data item",itemDatabaseBody:"Cari item game yang valid memakai nama resmi terlokalisasi dan nilai berversi dari file game.",searchItems:"Cari item",openCrafting:"Buka kalkulator pembuatan",rank:"Peringkat",stack:"Tumpukan maksimum",weight:"Berat",price:"Harga",crafting:"Kalkulator pembuatan",craftingBody:"Hitung bahan langsung dan bahan yang diuraikan secara rekursif dari resep terverifikasi. Jika produk memiliki beberapa resep, ID resep di bawah digunakan.",product:"Produk",quantity:"Jumlah",chooseRecipe:"Pilih resep",ownedMaterials:"Bahan yang dimiliki (opsional): satu ID internal dan jumlah per baris, misalnya Wood=10.",workAmount:"Beban kerja",directMaterials:"Bahan langsung",expandedMaterials:"Bahan akhir setelah stok dikurangi"
};
const ru:Messages = {
  skip:"Перейти к содержимому",home:"Главная",map:"Карта",pals:"Палы",calculators:"Калькуляторы",database:"База данных",guides:"Руководства",server:"Инструменты сервера",search:"Поиск Палов",theme:"Тема",language:"Язык",
  hero:"Проверенные данные Palworld и полезные инструменты",tagline:"Ищите официальные имена Палов, сравнивайте характеристики и рассчитывайте результаты разведения по версионным данным игры.",openPals:"Открыть базу Палов",openBreed:"Калькулятор разведения",verified:"Проверенный набор данных",verifiedBody:"299 ID Палов сверены с локальной сборкой 24181527; 44 851 строка разведения прошла проверку целостности.",palDex:"База Палов",palDexBody:"Ищите официальные локализованные имена, внутренние ID, характеристики и пригодность к работе.",breeding:"Калькулятор разведения",breedingBody:"Выберите двух родителей и их пол, чтобы узнать результат, либо выберите целевого Пала для просмотра проверенных пар.",parentA:"Родитель A",parentB:"Родитель B",genderA:"Пол A",genderB:"Пол B",anyGender:"Любой пол",male:"Самец",female:"Самка",targetPal:"Целевой Пал",findParents:"Найти родителей",result:"Результат",choose:"Выберите Пала",noResult:"Для этого выбора нет проверенного результата.",parentPairs:"Проверенные пары родителей",
  mapTitle:"Личная карта исследования",mapBody:"Создавайте координатные метки локально, не отправляя маршруты и заметки.",pinName:"Название метки",pinCategory:"Категория",coordinateX:"Координата X",coordinateY:"Координата Y",addPin:"Добавить метку",remove:"Удалить",pins:"Метки",noPins:"Личных меток пока нет.",localMapNote:"Личные метки хранятся только в этом браузере. Непроверенные игровые места заранее не загружаются.",stats:"Характеристики",work:"Пригодность к работе",hp:"ОЗ",attack:"Атака",defense:"Защита",rarity:"Редкость",nocturnal:"Ночной",yes:"Да",no:"Нет",dataVersion:"Версия данных",gameBuild:"Сборка игры",results:"результатов",footer:"Публикуется только проверенная игровая информация с указанием версии.",coming:"Этот раздел готовится на основе проверенных данных из файлов игры.",serverTitle:"Помощник настройки сервера",generate:"Создать INI",players:"Максимум игроков",workSpeed:"Скорость работы",pvp:"Включить PvP",backup:"Включить резервные копии",copy:"Копировать",privacy:"Конфиденциальность",consentTitle:"Настройки конфиденциальности",consentBody:"Необязательная аналитика и реклама отключены до вашего согласия. Поисковые запросы, метки и настройки сервера никогда не отправляются.",allow:"Разрешить необязательные службы",decline:"Оставить отключёнными",adReserved:"Место для рекламы",
  itemDatabase:"База предметов",itemDatabaseBody:"Ищите доступные в игре предметы по официальным локализованным именам и версионным значениям из файлов игры.",searchItems:"Поиск предметов",openCrafting:"Открыть калькулятор создания",rank:"Ранг",stack:"Максимум в стопке",weight:"Вес",price:"Цена",crafting:"Калькулятор создания",craftingBody:"Рассчитывайте прямые и рекурсивно развёрнутые материалы по проверенным рецептам. Если рецептов несколько, используется показанный ниже ID.",product:"Продукт",quantity:"Количество",chooseRecipe:"Выберите рецепт",ownedMaterials:"Имеющиеся материалы (необязательно): один внутренний ID и количество в строке, например Wood=10.",workAmount:"Объём работы",directMaterials:"Прямые материалы",expandedMaterials:"Итоговые материалы с учётом запасов"
};
const tr:Messages = {
  skip:"İçeriğe geç",home:"Ana sayfa",map:"Harita",pals:"Pallar",calculators:"Hesaplayıcılar",database:"Veritabanı",guides:"Rehberler",server:"Sunucu araçları",search:"Pal ara",theme:"Tema",language:"Dil",
  hero:"Doğrulanmış Palworld verileri ve kullanışlı araçlar",tagline:"Resmî Pal adlarını ara, özellikleri karşılaştır ve sürümlenmiş oyun verileriyle yetiştirme sonuçlarını hesapla.",openPals:"Pallara göz at",openBreed:"Yetiştirme hesaplayıcısı",verified:"Doğrulanmış veri kümesi",verifiedBody:"299 Pal kimliği yerel 24181527 oyun yapısıyla eşleştirildi; 44.851 yetiştirme satırı bütünlük kontrollerini geçti.",palDex:"Pal veritabanı",palDexBody:"Resmî yerelleştirilmiş adları, dahili kimlikleri, özellikleri ve çalışma uygunluklarını ara.",breeding:"Yetiştirme hesaplayıcısı",breedingBody:"Sonucu bulmak için iki ebeveyn ile cinsiyetlerini seç veya doğrulanmış ebeveyn çiftleri için hedef Pal seç.",parentA:"Ebeveyn A",parentB:"Ebeveyn B",genderA:"Cinsiyet A",genderB:"Cinsiyet B",anyGender:"Herhangi bir cinsiyet",male:"Erkek",female:"Dişi",targetPal:"Hedef Pal",findParents:"Ebeveynleri bul",result:"Sonuç",choose:"Pal seç",noResult:"Bu seçim için doğrulanmış sonuç yok.",parentPairs:"Doğrulanmış ebeveyn çiftleri",
  mapTitle:"Kişisel keşif haritası",mapBody:"Rotaları veya notları hiçbir yere göndermeden koordinat işaretlerini yerel olarak oluştur.",pinName:"İşaret adı",pinCategory:"Kategori",coordinateX:"X koordinatı",coordinateY:"Y koordinatı",addPin:"İşaret ekle",remove:"Kaldır",pins:"İşaretler",noPins:"Henüz kişisel işaret yok.",localMapNote:"Kişisel işaretler yalnızca bu tarayıcıda saklanır. Doğrulanmamış oyun konumları önceden yüklenmez.",stats:"Özellikler",work:"Çalışma uygunluğu",hp:"Can",attack:"Saldırı",defense:"Savunma",rarity:"Nadirlik",nocturnal:"Gececil",yes:"Evet",no:"Hayır",dataVersion:"Veri sürümü",gameBuild:"Oyun yapısı",results:"sonuç",footer:"Yalnızca doğrulanmış ve sürümlenmiş oyun bilgileri yayımlanır.",coming:"Bu bölüm, oyun dosyalarından doğrulanmış verilerle hazırlanıyor.",serverTitle:"Sunucu ayarları yardımcısı",generate:"INI oluştur",players:"Azami oyuncu",workSpeed:"Çalışma hızı",pvp:"PvP’yi etkinleştir",backup:"Yedekleri etkinleştir",copy:"Kopyala",privacy:"Gizlilik",consentTitle:"Gizlilik seçenekleri",consentBody:"İzin verene kadar isteğe bağlı analiz ve reklamlar kapalı kalır. Arama metni, harita işaretleri ve sunucu ayarları asla gönderilmez.",allow:"İsteğe bağlı hizmetlere izin ver",decline:"Kapalı tut",adReserved:"Reklam alanı",
  itemDatabase:"Eşya veritabanı",itemDatabaseBody:"Resmî yerelleştirilmiş adlar ve oyun dosyalarındaki sürümlenmiş değerlerle geçerli oyun eşyalarını ara.",searchItems:"Eşya ara",openCrafting:"Üretim hesaplayıcısını aç",rank:"Kademe",stack:"Azami yığın",weight:"Ağırlık",price:"Fiyat",crafting:"Üretim hesaplayıcısı",craftingBody:"Doğrulanmış tariflerden doğrudan ve özyinelemeli olarak açılmış malzemeleri hesapla. Bir ürünün birden çok tarifi varsa aşağıdaki tarif kimliği kullanılır.",product:"Ürün",quantity:"Miktar",chooseRecipe:"Tarif seç",ownedMaterials:"Mevcut malzemeler (isteğe bağlı): satır başına bir dahili kimlik ve miktar, örneğin Wood=10.",workAmount:"İş yükü",directMaterials:"Doğrudan malzemeler",expandedMaterials:"Stok düşüldükten sonraki nihai malzemeler"
};
const pl:Messages = {
  skip:"Przejdź do treści",home:"Strona główna",map:"Mapa",pals:"Pale",calculators:"Kalkulatory",database:"Baza danych",guides:"Poradniki",server:"Narzędzia serwera",search:"Szukaj Pali",theme:"Motyw",language:"Język",
  hero:"Zweryfikowane dane Palworld i praktyczne narzędzia",tagline:"Wyszukuj oficjalne nazwy Pali, porównuj statystyki i obliczaj wyniki hodowli na podstawie wersjonowanych danych gry.",openPals:"Przeglądaj Pale",openBreed:"Kalkulator hodowli",verified:"Zweryfikowany zestaw danych",verifiedBody:"299 ID Pali porównano z lokalną kompilacją 24181527; 44 851 wierszy hodowli przeszło kontrolę spójności.",palDex:"Baza Pali",palDexBody:"Wyszukuj oficjalne zlokalizowane nazwy, wewnętrzne ID, statystyki i przydatność do pracy.",breeding:"Kalkulator hodowli",breedingBody:"Wybierz dwoje rodziców i ich płeć, aby znaleźć wynik, lub wybierz docelowego Pala, aby zobaczyć zweryfikowane pary.",parentA:"Rodzic A",parentB:"Rodzic B",genderA:"Płeć A",genderB:"Płeć B",anyGender:"Dowolna płeć",male:"Samiec",female:"Samica",targetPal:"Docelowy Pal",findParents:"Znajdź rodziców",result:"Wynik",choose:"Wybierz Pala",noResult:"Brak zweryfikowanego wyniku dla tego wyboru.",parentPairs:"Zweryfikowane pary rodziców",
  mapTitle:"Osobista mapa eksploracji",mapBody:"Twórz znaczniki współrzędnych lokalnie, bez wysyłania tras ani notatek.",pinName:"Nazwa znacznika",pinCategory:"Kategoria",coordinateX:"Współrzędna X",coordinateY:"Współrzędna Y",addPin:"Dodaj znacznik",remove:"Usuń",pins:"Znaczniki",noPins:"Brak osobistych znaczników.",localMapNote:"Osobiste znaczniki są przechowywane tylko w tej przeglądarce. Niezweryfikowane miejsca w grze nie są wstępnie ładowane.",stats:"Statystyki",work:"Przydatność do pracy",hp:"PZ",attack:"Atak",defense:"Obrona",rarity:"Rzadkość",nocturnal:"Nocny",yes:"Tak",no:"Nie",dataVersion:"Wersja danych",gameBuild:"Kompilacja gry",results:"wyników",footer:"Publikowane są wyłącznie zweryfikowane i wersjonowane informacje o grze.",coming:"Ta sekcja jest przygotowywana na podstawie zweryfikowanych danych z plików gry.",serverTitle:"Asystent ustawień serwera",generate:"Utwórz INI",players:"Maksymalna liczba graczy",workSpeed:"Szybkość pracy",pvp:"Włącz PvP",backup:"Włącz kopie zapasowe",copy:"Kopiuj",privacy:"Prywatność",consentTitle:"Ustawienia prywatności",consentBody:"Opcjonalna analityka i reklamy pozostają wyłączone bez Twojej zgody. Wyszukiwania, znaczniki i ustawienia serwera nigdy nie są wysyłane.",allow:"Zezwól na usługi opcjonalne",decline:"Pozostaw wyłączone",adReserved:"Miejsce na reklamę",
  itemDatabase:"Baza przedmiotów",itemDatabaseBody:"Wyszukuj prawidłowe przedmioty w grze według oficjalnych zlokalizowanych nazw i wersjonowanych wartości z plików gry.",searchItems:"Szukaj przedmiotów",openCrafting:"Otwórz kalkulator wytwarzania",rank:"Ranga",stack:"Maksymalny stos",weight:"Waga",price:"Cena",crafting:"Kalkulator wytwarzania",craftingBody:"Obliczaj materiały bezpośrednie i rozwinięte rekurencyjnie na podstawie zweryfikowanych receptur. Przy wielu recepturach używany jest ID pokazany poniżej.",product:"Produkt",quantity:"Ilość",chooseRecipe:"Wybierz recepturę",ownedMaterials:"Posiadane materiały (opcjonalnie): jeden wewnętrzny ID i ilość w każdym wierszu, np. Wood=10.",workAmount:"Nakład pracy",directMaterials:"Materiały bezpośrednie",expandedMaterials:"Materiały końcowe po odjęciu zapasów"
};
const th:Messages = {
  skip:"ข้ามไปยังเนื้อหา",home:"หน้าหลัก",map:"แผนที่",pals:"พัล",calculators:"เครื่องคำนวณ",database:"ฐานข้อมูล",guides:"คู่มือ",server:"เครื่องมือเซิร์ฟเวอร์",search:"ค้นหาพัล",theme:"ธีม",language:"ภาษา",
  hero:"ข้อมูล Palworld ที่ตรวจสอบแล้วและเครื่องมือที่ใช้งานได้จริง",tagline:"ค้นหาชื่อพัลอย่างเป็นทางการ เปรียบเทียบค่าสถานะ และคำนวณผลการผสมพันธุ์จากข้อมูลเกมที่ระบุเวอร์ชัน",openPals:"เรียกดูพัล",openBreed:"เครื่องคำนวณการผสมพันธุ์",verified:"ชุดข้อมูลที่ตรวจสอบแล้ว",verifiedBody:"ตรวจสอบ ID พัล 299 รายการกับเกมบิลด์ 24181527 ในเครื่องแล้ว และข้อมูลการผสมพันธุ์ 44,851 แถวผ่านการตรวจสอบความถูกต้อง",palDex:"ฐานข้อมูลพัล",palDexBody:"ค้นหาชื่อแปลอย่างเป็นทางการ ID ภายใน ค่าสถานะ และความเหมาะสมในการทำงาน",breeding:"เครื่องคำนวณการผสมพันธุ์",breedingBody:"เลือกพ่อแม่สองตัวพร้อมเพศเพื่อหาพัลที่ได้ หรือเลือกพัลเป้าหมายเพื่อดูคู่พ่อแม่ที่ตรวจสอบแล้ว",parentA:"พ่อแม่ A",parentB:"พ่อแม่ B",genderA:"เพศ A",genderB:"เพศ B",anyGender:"เพศใดก็ได้",male:"ตัวผู้",female:"ตัวเมีย",targetPal:"พัลเป้าหมาย",findParents:"ค้นหาพ่อแม่",result:"ผลลัพธ์",choose:"เลือกพัล",noResult:"ไม่มีผลลัพธ์ที่ตรวจสอบแล้วสำหรับตัวเลือกนี้",parentPairs:"คู่พ่อแม่ที่ตรวจสอบแล้ว",
  mapTitle:"แผนที่สำรวจส่วนตัว",mapBody:"สร้างหมุดพิกัดไว้ในเครื่องโดยไม่ส่งเส้นทางหรือบันทึกออกไป",pinName:"ชื่อหมุด",pinCategory:"หมวดหมู่",coordinateX:"พิกัด X",coordinateY:"พิกัด Y",addPin:"เพิ่มหมุด",remove:"นำออก",pins:"หมุด",noPins:"ยังไม่มีหมุดส่วนตัว",localMapNote:"หมุดส่วนตัวจะบันทึกในเบราว์เซอร์นี้เท่านั้น และจะไม่โหลดตำแหน่งในเกมที่ยังไม่ได้ตรวจสอบไว้ล่วงหน้า",stats:"ค่าสถานะ",work:"ความเหมาะสมในการทำงาน",hp:"HP",attack:"โจมตี",defense:"ป้องกัน",rarity:"ความหายาก",nocturnal:"ออกหากินกลางคืน",yes:"ใช่",no:"ไม่",dataVersion:"เวอร์ชันข้อมูล",gameBuild:"เกมบิลด์",results:"ผลลัพธ์",footer:"เผยแพร่เฉพาะข้อมูลเกมที่ตรวจสอบและระบุเวอร์ชันแล้ว",coming:"ส่วนนี้กำลังจัดเตรียมด้วยข้อมูลที่ตรวจสอบจากไฟล์เกม",serverTitle:"ผู้ช่วยตั้งค่าเซิร์ฟเวอร์",generate:"สร้าง INI",players:"จำนวนผู้เล่นสูงสุด",workSpeed:"ความเร็วในการทำงาน",pvp:"เปิดใช้ PvP",backup:"เปิดใช้การสำรองข้อมูล",copy:"คัดลอก",privacy:"ความเป็นส่วนตัว",consentTitle:"ตัวเลือกความเป็นส่วนตัว",consentBody:"การวิเคราะห์และโฆษณาที่ไม่บังคับจะปิดอยู่จนกว่าคุณจะอนุญาต ระบบจะไม่ส่งข้อความค้นหา หมุดแผนที่ หรือการตั้งค่าเซิร์ฟเวอร์",allow:"อนุญาตบริการเสริม",decline:"ปิดต่อไป",adReserved:"พื้นที่โฆษณา",
  itemDatabase:"ฐานข้อมูลไอเทม",itemDatabaseBody:"ค้นหาไอเทมที่ใช้ได้ในเกมด้วยชื่อแปลอย่างเป็นทางการและค่าจากไฟล์เกมที่ระบุเวอร์ชัน",searchItems:"ค้นหาไอเทม",openCrafting:"เปิดเครื่องคำนวณการสร้าง",rank:"ระดับ",stack:"กองสูงสุด",weight:"น้ำหนัก",price:"ราคา",crafting:"เครื่องคำนวณการสร้าง",craftingBody:"คำนวณวัตถุดิบโดยตรงและวัตถุดิบที่ขยายแบบวนซ้ำจากสูตรที่ตรวจสอบแล้ว หากผลิตภัณฑ์มีหลายสูตร จะใช้ ID สูตรที่แสดงด้านล่าง",product:"ผลิตภัณฑ์",quantity:"จำนวน",chooseRecipe:"เลือกสูตร",ownedMaterials:"วัตถุดิบที่มี (ไม่บังคับ): ใส่ ID ภายในและจำนวนหนึ่งรายการต่อบรรทัด เช่น Wood=10",workAmount:"ปริมาณงาน",directMaterials:"วัตถุดิบโดยตรง",expandedMaterials:"วัตถุดิบสุดท้ายหลังหักของที่มี"
};
const vi:Messages = {
  skip:"Chuyển đến nội dung",home:"Trang chủ",map:"Bản đồ",pals:"Pal",calculators:"Công cụ tính",database:"Cơ sở dữ liệu",guides:"Hướng dẫn",server:"Công cụ máy chủ",search:"Tìm Pal",theme:"Giao diện",language:"Ngôn ngữ",
  hero:"Dữ liệu Palworld đã xác minh và công cụ thiết thực",tagline:"Tìm tên Pal chính thức, so sánh chỉ số và tính kết quả phối giống bằng dữ liệu trò chơi có phiên bản.",openPals:"Duyệt Pal",openBreed:"Công cụ tính phối giống",verified:"Bộ dữ liệu đã xác minh",verifiedBody:"299 ID Pal đã được đối chiếu với bản dựng cục bộ 24181527; 44.851 dòng phối giống đã vượt qua kiểm tra tính toàn vẹn.",palDex:"Cơ sở dữ liệu Pal",palDexBody:"Tìm tên bản địa hóa chính thức, ID nội bộ, chỉ số và khả năng làm việc.",breeding:"Công cụ tính phối giống",breedingBody:"Chọn hai Pal bố mẹ cùng giới tính để tìm kết quả, hoặc chọn Pal mục tiêu để xem các cặp bố mẹ đã xác minh.",parentA:"Bố mẹ A",parentB:"Bố mẹ B",genderA:"Giới tính A",genderB:"Giới tính B",anyGender:"Bất kỳ giới tính",male:"Đực",female:"Cái",targetPal:"Pal mục tiêu",findParents:"Tìm bố mẹ",result:"Kết quả",choose:"Chọn Pal",noResult:"Không có kết quả đã xác minh cho lựa chọn này.",parentPairs:"Cặp bố mẹ đã xác minh",
  mapTitle:"Bản đồ khám phá cá nhân",mapBody:"Tạo ghim tọa độ cục bộ mà không gửi tuyến đường hay ghi chú đi đâu.",pinName:"Tên ghim",pinCategory:"Danh mục",coordinateX:"Tọa độ X",coordinateY:"Tọa độ Y",addPin:"Thêm ghim",remove:"Xóa",pins:"Ghim",noPins:"Chưa có ghim cá nhân.",localMapNote:"Ghim cá nhân chỉ được lưu trong trình duyệt này. Các địa điểm trò chơi chưa xác minh không được tải sẵn.",stats:"Chỉ số",work:"Khả năng làm việc",hp:"HP",attack:"Tấn công",defense:"Phòng thủ",rarity:"Độ hiếm",nocturnal:"Hoạt động ban đêm",yes:"Có",no:"Không",dataVersion:"Phiên bản dữ liệu",gameBuild:"Bản dựng trò chơi",results:"kết quả",footer:"Chỉ thông tin trò chơi đã xác minh và có phiên bản mới được công bố.",coming:"Phần này đang được chuẩn bị bằng dữ liệu đã xác minh từ tệp trò chơi.",serverTitle:"Trợ lý cài đặt máy chủ",generate:"Tạo INI",players:"Số người chơi tối đa",workSpeed:"Tốc độ làm việc",pvp:"Bật PvP",backup:"Bật sao lưu",copy:"Sao chép",privacy:"Quyền riêng tư",consentTitle:"Lựa chọn quyền riêng tư",consentBody:"Phân tích và quảng cáo tùy chọn được tắt cho đến khi bạn cho phép. Nội dung tìm kiếm, ghim bản đồ và cài đặt máy chủ không bao giờ được gửi đi.",allow:"Cho phép dịch vụ tùy chọn",decline:"Tiếp tục tắt",adReserved:"Không gian quảng cáo",
  itemDatabase:"Cơ sở dữ liệu vật phẩm",itemDatabaseBody:"Tìm các vật phẩm hợp lệ trong trò chơi bằng tên bản địa hóa chính thức và giá trị có phiên bản từ tệp trò chơi.",searchItems:"Tìm vật phẩm",openCrafting:"Mở công cụ tính chế tạo",rank:"Hạng",stack:"Xếp chồng tối đa",weight:"Trọng lượng",price:"Giá",crafting:"Công cụ tính chế tạo",craftingBody:"Tính vật liệu trực tiếp và vật liệu được khai triển đệ quy từ các công thức đã xác minh. Nếu một sản phẩm có nhiều công thức, ID hiển thị bên dưới sẽ được dùng.",product:"Sản phẩm",quantity:"Số lượng",chooseRecipe:"Chọn công thức",ownedMaterials:"Vật liệu đang có (tùy chọn): một ID nội bộ và số lượng trên mỗi dòng, ví dụ Wood=10.",workAmount:"Khối lượng công việc",directMaterials:"Vật liệu trực tiếp",expandedMaterials:"Vật liệu cuối cùng sau khi trừ kho"
};
export const messageCatalogs:Partial<Record<Locale,Messages>>={"en-US":en,"ko-KR":ko,"ja-JP":ja,"zh-CN":zhCN,"zh-TW":zhTW,"fr-FR":fr,"it-IT":it,"de-DE":de,"es-ES":esES,"es-419":es419,"pt-BR":ptBR,"id-ID":idID,"ru-RU":ru,"tr-TR":tr,"pl-PL":pl,"th-TH":th,"vi-VN":vi};
const publicVerifiedBody:Record<Locale,string>={
  "en-US":"299 Pal IDs and 44,851 breeding rows were checked against the current installed game files.",
  "ko-KR":"팰 ID 299종과 교배 결과 44,851건을 현재 설치된 게임 파일과 대조했습니다.",
  "ja-JP":"299件のパルIDと44,851件の配合データを、現在インストールされているゲームファイルと照合しました。",
  "zh-CN":"已将299个帕鲁ID和44,851条配种数据与当前安装的游戏文件进行核对。",
  "zh-TW":"已將299個帕魯ID和44,851筆配種資料與目前安裝的遊戲檔案進行核對。",
  "fr-FR":"299 ID de Pals et 44 851 données de reproduction ont été vérifiés à partir des fichiers du jeu actuellement installés.",
  "it-IT":"299 ID Pal e 44.851 dati di riproduzione sono stati verificati con i file di gioco attualmente installati.",
  "de-DE":"299 Pal-IDs und 44.851 Zuchtdatensätze wurden mit den aktuell installierten Spieldateien abgeglichen.",
  "es-ES":"Se cotejaron 299 ID de Pals y 44.851 datos de cría con los archivos del juego instalados actualmente.",
  "pt-BR":"299 IDs de Pals e 44.851 dados de reprodução foram verificados com os arquivos do jogo instalados atualmente.",
  "ru-RU":"299 идентификаторов Палов и 44 851 строк разведения сверены с установленными файлами игры.",
  "id-ID":"299 ID Pal dan 44.851 data pengembangbiakan telah dicocokkan dengan file game yang terpasang saat ini.",
  "es-419":"Se cotejaron 299 ID de Pals y 44,851 datos de crianza con los archivos del juego instalados actualmente.",
  "th-TH":"ตรวจสอบ ID พัล 299 รายการและข้อมูลการผสมพันธุ์ 44,851 แถวกับไฟล์เกมที่ติดตั้งอยู่ในปัจจุบันแล้ว",
  "tr-TR":"299 Pal kimliği ve 44.851 yetiştirme verisi, şu anda yüklü olan oyun dosyalarıyla karşılaştırıldı.",
  "vi-VN":"299 ID Pal và 44.851 dữ liệu phối giống đã được đối chiếu với các tệp trò chơi hiện được cài đặt.",
  "pl-PL":"299 identyfikatorów Pali i 44 851 rekordów hodowli sprawdzono na podstawie aktualnie zainstalowanych plików gry."
};
export function messages(locale:Locale):Messages { const catalog=messageCatalogs[locale]||en;return {...catalog,verifiedBody:publicVerifiedBody[locale]}; }
export const translationProvenance:Record<Locale,"reviewed"|"gpt"|"fallback"> = {"en-US":"reviewed","ko-KR":"reviewed","ja-JP":"gpt","zh-CN":"gpt","zh-TW":"gpt","fr-FR":"gpt","it-IT":"gpt","de-DE":"gpt","es-ES":"gpt","pt-BR":"gpt","ru-RU":"gpt","id-ID":"gpt","es-419":"gpt","th-TH":"gpt","tr-TR":"gpt","vi-VN":"gpt","pl-PL":"gpt"};
