import type {Locale} from "./config";
type Copy={title:string;intro:string;pal:string;level:string;stars:string;friendship:string;observed:string;soul:string;possibleIv:string;displayRange:string;unique:string;range:string;impossible:string;enter:string;limitations:string;limitationsBody:string;verifiedNote:string};
const en:Copy={title:"Pal IV calculator",intro:"Enter the displayed stats to find every IV value that can produce them after level, condensation, Soul enhancement, and friendship rounding.",pal:"Pal",level:"Level",stars:"Condensation stars",friendship:"Friendship rank",observed:"Displayed value",soul:"Soul enhancement",possibleIv:"Possible IV",displayRange:"Possible displayed range",unique:"Exact",range:"Range",impossible:"No IV from 0 to 100 produces this value.",enter:"Enter a displayed value to calculate its IV range.",limitations:"Verified scope",limitationsBody:"Use values without passive-skill, food, Alpha, Lucky, raid, or other temporary modifiers. Those modifier orders are not yet verified and are not guessed here.",verifiedNote:"The calculation and rounding order passed two independent live sessions, all 299 Pals, and 82,734 stat comparisons."};
export const ivCopy:Record<Locale,Copy>={
  "en-US":en,
  "ko-KR":{title:"팰 IV 계산기",intro:"표시 능력치를 입력하면 레벨·농축·영혼 강화·친밀도 반올림을 거쳐 가능한 모든 IV를 찾습니다.",pal:"팰",level:"레벨",stars:"농축 별",friendship:"친밀도 랭크",observed:"표시 수치",soul:"영혼 강화",possibleIv:"가능한 IV",displayRange:"가능한 표시 범위",unique:"확정",range:"범위",impossible:"IV 0~100 중 이 수치를 만드는 값이 없습니다.",enter:"표시 수치를 입력하면 IV 범위를 계산합니다.",limitations:"검증 범위",limitationsBody:"패시브 스킬, 음식, 알파, 희귀, 레이드 또는 임시 보정이 없는 수치를 사용하세요. 해당 보정 순서는 아직 검증되지 않아 추측하지 않습니다.",verifiedNote:"계산 및 반올림 순서는 독립 실시간 세션 2회, 팰 299종, 능력치 대조 82,734건을 통과했습니다."},
  "ja-JP":{...en,title:"パル個体値計算機",intro:"表示ステータスから、レベル・濃縮・ソウル強化・親密度の丸めを含む全ての個体値候補を求めます。",pal:"パル",level:"レベル",stars:"濃縮スター",friendship:"親密度ランク",observed:"表示値",soul:"ソウル強化",possibleIv:"個体値候補",displayRange:"表示可能範囲",unique:"確定",range:"範囲",impossible:"個体値0～100ではこの値になりません。",enter:"表示値を入力すると候補範囲を計算します。",limitations:"検証範囲",limitationsBody:"パッシブ、食事、アルファ、ラッキー、レイド、一時補正のない値を使用してください。未検証の補正順序は推測しません。",verifiedNote:"計算と丸め順序は、独立した実行2回、全299種、82,734件の照合で検証済みです。"},
  "zh-CN":{...en,title:"帕鲁个体值计算器",intro:"输入面板属性，找出经过等级、浓缩、灵魂强化和亲密度舍入后所有可能的个体值。",pal:"帕鲁",level:"等级",stars:"浓缩星级",friendship:"亲密度等级",observed:"面板数值",soul:"灵魂强化",possibleIv:"可能的个体值",displayRange:"可能的面板范围",unique:"确定值",range:"范围",impossible:"个体值0至100均无法得到该数值。",enter:"输入面板数值以计算个体值范围。",limitations:"已验证范围",limitationsBody:"请使用不含被动、食物、阿尔法、闪光、突袭或临时加成的数值。未验证的加成顺序不会被猜测。",verifiedNote:"计算与舍入顺序通过2次独立实时会话、299种帕鲁及82,734次数值核对。"},
  "zh-TW":{...en,title:"帕魯個體值計算器",intro:"輸入面板數值，找出經過等級、濃縮、靈魂強化與親密度捨入後所有可能的個體值。",pal:"帕魯",level:"等級",stars:"濃縮星級",friendship:"親密度等級",observed:"面板數值",soul:"靈魂強化",possibleIv:"可能的個體值",displayRange:"可能的面板範圍",unique:"確定值",range:"範圍",impossible:"個體值0至100皆無法得到此數值。",enter:"輸入面板數值以計算個體值範圍。",limitations:"已驗證範圍",limitationsBody:"請使用不含被動、食物、阿爾法、閃光、團隊戰或暫時加成的數值。未驗證的加成順序不會被猜測。",verifiedNote:"計算與捨入順序已通過2次獨立即時工作階段、299種帕魯與82,734次數值核對。"},
  "fr-FR":{...en,title:"Calculateur d’IV des Pals",pal:"Pal",level:"Niveau",stars:"Étoiles de condensation",friendship:"Rang d’amitié",observed:"Valeur affichée",soul:"Renforcement d’âme",possibleIv:"IV possibles",displayRange:"Plage affichable",unique:"Exact",range:"Plage",impossible:"Aucun IV de 0 à 100 ne produit cette valeur.",enter:"Saisissez une valeur affichée pour calculer les IV.",limitations:"Périmètre vérifié",limitationsBody:"Utilisez des valeurs sans passif, nourriture, Alpha, Lucky, raid ni bonus temporaire. Les ordres non vérifiés ne sont pas estimés.",verifiedNote:"Ordre et arrondis vérifiés par deux sessions indépendantes, 299 Pals et 82 734 comparaisons."},
  "it-IT":{...en,title:"Calcolatore IV dei Pal",pal:"Pal",level:"Livello",stars:"Stelle condensazione",friendship:"Rango amicizia",observed:"Valore mostrato",soul:"Potenziamento anima",possibleIv:"IV possibili",displayRange:"Intervallo mostrabile",unique:"Esatto",range:"Intervallo",impossible:"Nessun IV da 0 a 100 produce questo valore.",enter:"Inserisci un valore mostrato per calcolare gli IV.",limitations:"Ambito verificato",limitationsBody:"Usa valori senza passive, cibo, Alpha, Lucky, raid o bonus temporanei. Gli ordini non verificati non vengono stimati.",verifiedNote:"Ordine e arrotondamenti verificati con due sessioni indipendenti, 299 Pal e 82.734 confronti."},
  "de-DE":{...en,title:"Pal-IV-Rechner",pal:"Pal",level:"Stufe",stars:"Kondensierungssterne",friendship:"Freundschaftsrang",observed:"Angezeigter Wert",soul:"Seelenverstärkung",possibleIv:"Mögliche IV",displayRange:"Möglicher Anzeigebereich",unique:"Eindeutig",range:"Bereich",impossible:"Kein IV von 0 bis 100 ergibt diesen Wert.",enter:"Anzeigewert eingeben, um den IV-Bereich zu berechnen.",limitations:"Geprüfter Umfang",limitationsBody:"Werte ohne Passiva, Nahrung, Alpha, Lucky, Raid- oder temporäre Boni verwenden. Ungeprüfte Reihenfolgen werden nicht geschätzt.",verifiedNote:"Reihenfolge und Rundung wurden in zwei unabhängigen Sitzungen, mit 299 Pals und 82.734 Vergleichen geprüft."},
  "es-ES":{...en,title:"Calculadora de IV de Pals",pal:"Pal",level:"Nivel",stars:"Estrellas de condensación",friendship:"Rango de amistad",observed:"Valor mostrado",soul:"Mejora de alma",possibleIv:"IV posibles",displayRange:"Rango mostrable",unique:"Exacto",range:"Rango",impossible:"Ningún IV de 0 a 100 produce este valor.",enter:"Introduce un valor mostrado para calcular los IV.",limitations:"Ámbito verificado",limitationsBody:"Usa valores sin pasivas, comida, Alfa, Lucky, incursión ni bonos temporales. No se estiman órdenes sin verificar.",verifiedNote:"Orden y redondeo verificados en dos sesiones independientes, 299 Pals y 82.734 comparaciones."},
  "es-419":{...en,title:"Calculadora de IV de Pals",pal:"Pal",level:"Nivel",stars:"Estrellas de condensación",friendship:"Rango de amistad",observed:"Valor mostrado",soul:"Mejora de alma",possibleIv:"IV posibles",displayRange:"Rango mostrable",unique:"Exacto",range:"Rango",impossible:"Ningún IV de 0 a 100 produce este valor.",enter:"Ingresa un valor mostrado para calcular los IV.",limitations:"Alcance verificado",limitationsBody:"Usa valores sin pasivas, comida, Alfa, Lucky, incursión ni bonos temporales. No se estiman órdenes sin verificar.",verifiedNote:"Orden y redondeo verificados en dos sesiones independientes, 299 Pals y 82,734 comparaciones."},
  "pt-BR":{...en,title:"Calculadora de IV dos Pals",pal:"Pal",level:"Nível",stars:"Estrelas de condensação",friendship:"Rank de amizade",observed:"Valor exibido",soul:"Aprimoramento de alma",possibleIv:"IV possíveis",displayRange:"Faixa exibível",unique:"Exato",range:"Faixa",impossible:"Nenhum IV de 0 a 100 produz esse valor.",enter:"Informe um valor exibido para calcular os IVs.",limitations:"Escopo verificado",limitationsBody:"Use valores sem passivas, comida, Alpha, Lucky, raid ou bônus temporários. Ordens não verificadas não são estimadas.",verifiedNote:"Ordem e arredondamento verificados em duas sessões independentes, 299 Pals e 82.734 comparações."},
  "ru-RU":{...en,title:"Калькулятор IV Палов",pal:"Пал",level:"Уровень",stars:"Звёзды конденсации",friendship:"Ранг дружбы",observed:"Отображаемое значение",soul:"Усиление души",possibleIv:"Возможные IV",displayRange:"Возможный диапазон",unique:"Точно",range:"Диапазон",impossible:"Ни один IV от 0 до 100 не даёт это значение.",enter:"Введите отображаемое значение для расчёта IV.",limitations:"Проверенная область",limitationsBody:"Используйте значения без пассивов, еды, Альфы, Lucky, рейдовых и временных бонусов. Непроверенный порядок не угадывается.",verifiedNote:"Порядок и округление проверены двумя независимыми сессиями, 299 Палами и 82 734 сравнениями."},
  "id-ID":{...en,title:"Kalkulator IV Pal",pal:"Pal",level:"Level",stars:"Bintang kondensasi",friendship:"Peringkat persahabatan",observed:"Nilai yang tampil",soul:"Penguatan jiwa",possibleIv:"IV yang mungkin",displayRange:"Rentang tampilan",unique:"Tepat",range:"Rentang",impossible:"Tidak ada IV 0 sampai 100 yang menghasilkan nilai ini.",enter:"Masukkan nilai tampilan untuk menghitung IV.",limitations:"Cakupan terverifikasi",limitationsBody:"Gunakan nilai tanpa pasif, makanan, Alpha, Lucky, raid, atau bonus sementara. Urutan yang belum terverifikasi tidak ditebak.",verifiedNote:"Urutan dan pembulatan lolos dua sesi independen, 299 Pal, dan 82.734 perbandingan."},
  "th-TH":{...en,title:"เครื่องคำนวณ IV ของพัล",pal:"พัล",level:"เลเวล",stars:"ดาวควบแน่น",friendship:"ระดับมิตรภาพ",observed:"ค่าที่แสดง",soul:"เสริมพลังวิญญาณ",possibleIv:"IV ที่เป็นไปได้",displayRange:"ช่วงค่าที่แสดงได้",unique:"ค่าที่แน่นอน",range:"ช่วง",impossible:"ไม่มี IV ตั้งแต่ 0 ถึง 100 ที่ให้ค่านี้",enter:"กรอกค่าที่แสดงเพื่อคำนวณช่วง IV",limitations:"ขอบเขตที่ตรวจสอบแล้ว",limitationsBody:"ใช้ค่าที่ไม่มีพาสซีฟ อาหาร อัลฟา Lucky เรด หรือโบนัสชั่วคราว ลำดับที่ยังไม่ตรวจสอบจะไม่ถูกคาดเดา",verifiedNote:"ลำดับและการปัดเศษผ่านการตรวจสอบ 2 เซสชันอิสระ พัล 299 ชนิด และการเทียบค่า 82,734 ครั้ง"},
  "tr-TR":{...en,title:"Pal IV hesaplayıcısı",pal:"Pal",level:"Seviye",stars:"Yoğunlaştırma yıldızı",friendship:"Dostluk rütbesi",observed:"Görünen değer",soul:"Ruh güçlendirmesi",possibleIv:"Olası IV",displayRange:"Görülebilen aralık",unique:"Kesin",range:"Aralık",impossible:"0 ile 100 arasında hiçbir IV bu değeri üretmiyor.",enter:"IV aralığını hesaplamak için görünen değeri gir.",limitations:"Doğrulanan kapsam",limitationsBody:"Pasif, yemek, Alpha, Lucky, baskın veya geçici bonus içermeyen değerleri kullan. Doğrulanmayan sıralar tahmin edilmez.",verifiedNote:"Sıra ve yuvarlama iki bağımsız oturum, 299 Pal ve 82.734 karşılaştırmayla doğrulandı."},
  "vi-VN":{...en,title:"Máy tính IV Pal",pal:"Pal",level:"Cấp",stars:"Sao cô đặc",friendship:"Hạng thân thiết",observed:"Chỉ số hiển thị",soul:"Cường hóa linh hồn",possibleIv:"IV có thể",displayRange:"Khoảng hiển thị",unique:"Chính xác",range:"Khoảng",impossible:"Không có IV từ 0 đến 100 tạo ra giá trị này.",enter:"Nhập chỉ số hiển thị để tính khoảng IV.",limitations:"Phạm vi đã xác minh",limitationsBody:"Dùng chỉ số không có nội tại, thức ăn, Alpha, Lucky, raid hoặc hiệu ứng tạm thời. Không đoán thứ tự chưa xác minh.",verifiedNote:"Thứ tự và làm tròn đã qua hai phiên độc lập, 299 Pal và 82.734 phép đối chiếu."},
  "pl-PL":{...en,title:"Kalkulator IV Pali",pal:"Pal",level:"Poziom",stars:"Gwiazdy kondensacji",friendship:"Ranga przyjaźni",observed:"Wyświetlana wartość",soul:"Wzmocnienie duszy",possibleIv:"Możliwe IV",displayRange:"Możliwy zakres",unique:"Dokładnie",range:"Zakres",impossible:"Żadne IV od 0 do 100 nie daje tej wartości.",enter:"Wpisz wyświetlaną wartość, aby obliczyć IV.",limitations:"Zweryfikowany zakres",limitationsBody:"Użyj wartości bez pasywów, jedzenia, Alpha, Lucky, rajdu i premii czasowych. Niezweryfikowane kolejności nie są zgadywane.",verifiedNote:"Kolejność i zaokrąglenia sprawdzono w dwóch niezależnych sesjach, dla 299 Pali i 82 734 porównań."}
};
