import "./styles.css";
import { defaultLocale, localeLabels, locales, localizePath, resolveLocale, site, type Locale } from "./config";
import { messages, type Messages } from "./i18n";
import { buildServerIni, expandRecipe, type Recipe } from "./data";
import { findBreedingResult, findParentPairs, type BreedingRow, type Gender } from "./breeding";

type Work=Record<string,number>;
type Pal={i:number;id:string;dex:number;variant:boolean;names:Record<Locale,string>;power:number;rarity:number;size:string;nocturnal:boolean;hp:number;attack:number;defense:number;work:Work;image?:boolean};
type PalData={meta:{gameBuild:string;sourceDbVersion:string;palCount:number;breedingCount:number;localIdMatchCount:number};pals:Pal[];pairs:BreedingRow[]};
type Item={id:string;names:Record<Locale,string>;type:string;subtype:string;rank:number;rarity:number;maxStack:number;weight:number;price:number;image?:boolean};
type ItemRecipe={id:string;productId:string;output:number;workAmount:number;ingredients:{itemId:string;count:number}[];energyType:string;energyAmount:number};
type ItemData={meta:{gameBuild:string;itemCount:number;recipeCount:number;localeCount:number;caseCorrections:string[]};items:Item[];recipes:ItemRecipe[];map:{minX:number;minY:number;maxX:number;maxY:number;width:number;height:number}};
type MapPin={id:string;name:string;category:string;x:number;y:number};
type BossMarker={id:string;category:"boss";palId:string;x:number;y:number;levelMin:number;levelMax:number;radius:number};
type HabitatMarker={id:string;category:"habitat";x:number;y:number;radius:number;pals:{palId:string;levelMin:number;levelMax:number}[]};
type MapData={meta:{gameBuild:string;bossCount:number;habitatCount:number};bosses:BossMarker[];habitats:HabitatMarker[]};
const app=document.querySelector<HTMLDivElement>("#app")!;
let locale=resolveLocale(location.pathname),m=messages(locale),data:PalData|null=null,itemData:ItemData|null=null,mapData:MapData|null=null,itemLoading=false,palLoading=false,mapLoading=false;
const trackedInteractions=new Set<string>();
let lastTrackedPage="";
const esc=(v:string)=>v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));
const route=()=>{const p=location.pathname.split("/").filter(Boolean);return locales.includes(p[0] as Locale)?`/${p.slice(1).join("/")}`.replace(/\/$/,"")||"/":"/"};
const href=(p:string)=>localizePath(locale,p);
const palName=(p:Pal)=>p.names[locale]||p.names[defaultLocale];
const itemName=(item:Item)=>item.names[locale]||item.names[defaultLocale];

function setMeta(title:string,description=m.tagline){document.documentElement.lang=locale;document.title=`${title} · ${site.name}`;document.querySelectorAll("[data-dynamic-meta]").forEach(n=>n.remove());const canonical=`${site.origin}${href(route())}`;for(const [tag,attrs] of [["meta",{name:"description",content:description}],["link",{rel:"canonical",href:canonical}],["meta",{property:"og:title",content:document.title}],["meta",{property:"og:description",content:description}],["meta",{property:"og:url",content:canonical}],["meta",{name:"twitter:card",content:"summary"}]] as const){const el=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));el.setAttribute("data-dynamic-meta","true");document.head.append(el)}for(const loc of locales){const el=document.createElement("link");el.rel="alternate";el.hreflang=loc;el.href=`${site.origin}${localizePath(loc,route())}`;el.dataset.dynamicMeta="true";document.head.append(el)}const alternate=document.createElement("link");alternate.rel="alternate";alternate.hreflang="x-default";alternate.href=`${site.origin}${localizePath(defaultLocale,route())}`;alternate.dataset.dynamicMeta="true";document.head.append(alternate)}
function header(){const nav:[keyof Messages,string][]=[["home","/"],["map","/map"],["pals","/pals"],["calculators","/calculators/breeding"],["database","/database"],["server","/server-tools/settings-generator"]];return `<header class="site-header"><a class="brand" href="${href("/")}" data-link><span class="brand-mark">P</span><span>${site.name}</span></a><nav aria-label="${m.home}">${nav.map(([k,p])=>`<a href="${href(p)}" data-link class="${route()===p?"active":""}">${m[k]}</a>`).join("")}</nav><div class="header-actions"><select id="locale" aria-label="${m.language}">${locales.map(l=>`<option value="${l}" ${l===locale?"selected":""}>${localeLabels[l]}</option>`).join("")}</select><button class="icon-button" id="theme" aria-label="${m.theme}">◐</button></div></header>`}
function footer(){return `<footer><div><strong>${site.name}</strong><p>${m.footer}</p></div></footer>`}
function consentBanner(){if(!(site.analyticsId||site.adsenseClient)||localStorage.getItem("pw-consent"))return "";return `<aside class="consent" aria-label="${m.consentTitle}"><div><strong>${m.consentTitle}</strong><p>${m.consentBody}</p></div><button class="button primary" data-consent="allow">${m.allow}</button><button class="button" data-consent="decline">${m.decline}</button></aside>`}
function hero(title:string,body:string){const build=data?.meta.gameBuild||itemData?.meta.gameBuild,summary=data?`${data.meta.palCount.toLocaleString(locale)} Pals · ${data.meta.breedingCount.toLocaleString(locale)} ${m.results}`:itemData?`${m.itemDatabase}: ${itemData.meta.itemCount.toLocaleString(locale)} · ${m.crafting}: ${itemData.meta.recipeCount.toLocaleString(locale)}`:"";return `<section class="page-hero"><p class="eyebrow">${m.verified}</p><h1>${title}</h1><p>${body}</p>${build?`<div class="data-banner"><span>✓</span><div><strong>${m.gameBuild} ${build}</strong><br><small>${summary}</small></div></div>`:""}</section>`}
function home(){setMeta(m.home);return `<section class="hero"><div class="hero-copy"><p class="eyebrow">${m.verified}</p><h1>${m.hero}</h1><p class="lede">${m.tagline}</p><div class="hero-actions"><a class="button primary" href="${href("/pals")}" data-link>${m.openPals}</a><a class="button" href="${href("/calculators/breeding")}" data-link>${m.openBreed}</a></div><dl class="version-strip"><div><dt>${m.gameBuild}</dt><dd>${site.gameBuild}</dd></div><div><dt>${m.dataVersion}</dt><dd>${site.gameVersion}</dd></div></dl></div><div class="hero-art" aria-hidden="true"><div class="orbital one"></div><div class="orbital two"></div><div class="island i1"></div><div class="island i2"></div></div></section><section class="section"><div class="notice"><strong>${m.verified}</strong><p>${m.verifiedBody}</p></div>${site.adsenseClient&&site.adsenseContentSlot?`<div class="ad-slot" aria-label="${m.adReserved}" data-ad-slot="${esc(site.adsenseContentSlot)}">${m.adReserved}</div>`:""}</section>`}
function palCard(p:Pal){const work=Object.entries(p.work).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,4);return `<article class="pal-card" data-pal="${esc(`${palName(p)} ${p.id} ${p.dex}`.toLocaleLowerCase(locale))}">${p.image?`<img class="entity-image pal-image" src="/assets/pals/${encodeURIComponent(p.id)}.png" alt="${esc(palName(p))}" loading="lazy" width="160" height="160">`:""}<div class="pal-card-body"><div class="pal-number">#${p.dex}${p.variant?"B":""}</div><h2>${esc(palName(p))}</h2><code>${esc(p.id)}</code><dl class="pal-stats"><div><dt>${m.hp}</dt><dd>${p.hp}</dd></div><div><dt>${m.attack}</dt><dd>${p.attack}</dd></div><div><dt>${m.defense}</dt><dd>${p.defense}</dd></div><div><dt>${m.rarity}</dt><dd>${p.rarity}</dd></div></dl><p class="work-tags">${work.map(([k,v])=>`<span>${k} ${v}</span>`).join("")}</p></div></article>`}
function palsPage(){setMeta(m.pals,m.palDexBody);const sorted=[...(data?.pals||[])].sort((a,b)=>new Intl.Collator(locale,{numeric:true}).compare(palName(a),palName(b))||a.id.localeCompare(b.id));return `${hero(m.palDex,m.palDexBody)}<section class="section"><div class="search-row"><label class="collection-search">${m.search}<input id="pal-search" type="search" autocomplete="off"></label><button class="button search-clear" data-clear-search="pal" aria-label="${m.remove}">×</button></div><p id="pal-count" role="status">${sorted.length.toLocaleString(locale)} ${m.results}</p><p id="pal-empty" class="empty-compact" hidden>${m.noResult}</p><div class="pal-grid">${sorted.map(palCard).join("")}</div></section>`}
function itemCard(item:Item){return `<article class="item-card" data-item="${esc(`${itemName(item)} ${item.id} ${item.type} ${item.subtype}`.toLocaleLowerCase(locale))}"><div class="item-card-head">${item.image?`<img class="entity-image item-image" src="/assets/items/${encodeURIComponent(item.id)}.webp" alt="${esc(itemName(item))}" loading="lazy" width="96" height="96">`:`<span class="item-image item-fallback" aria-hidden="true">◇</span>`}<div><h2>${esc(itemName(item))}</h2><code>${esc(item.id)}</code></div></div><p class="work-tags"><span>${esc(item.type)}</span><span>${esc(item.subtype)}</span></p><dl class="item-stats"><div><dt>${m.rank}</dt><dd>${item.rank}</dd></div><div><dt>${m.rarity}</dt><dd>${item.rarity}</dd></div><div><dt>${m.stack}</dt><dd>${item.maxStack.toLocaleString(locale)}</dd></div><div><dt>${m.weight}</dt><dd>${item.weight.toLocaleString(locale)}</dd></div><div><dt>${m.price}</dt><dd>${item.price.toLocaleString(locale)}</dd></div></dl></article>`}
function databasePage(){setMeta(m.itemDatabase,m.itemDatabaseBody);const sorted=[...(itemData?.items||[])].sort((a,b)=>new Intl.Collator(locale,{numeric:true}).compare(itemName(a),itemName(b))||a.id.localeCompare(b.id));return `${hero(m.itemDatabase,m.itemDatabaseBody)}<section class="section"><p><a class="button primary" href="${href("/calculators/crafting")}" data-link>${m.openCrafting}</a></p><div class="search-row"><label class="collection-search">${m.searchItems}<input id="item-search" type="search" autocomplete="off"></label><button class="button search-clear" data-clear-search="item" aria-label="${m.remove}">×</button></div><p id="item-count" role="status">${sorted.length.toLocaleString(locale)} ${m.results}</p><p id="item-empty" class="empty-compact" hidden>${m.noResult}</p><div class="item-grid">${sorted.map(itemCard).join("")}</div></section>`}
function itemOptions(){const byId=new Map(itemData?.items.map(item=>[item.id,item])||[]);return `<option value="">${m.chooseRecipe}</option>${[...(itemData?.recipes||[])].sort((a,b)=>new Intl.Collator(locale,{numeric:true}).compare(itemName(byId.get(a.productId)!),itemName(byId.get(b.productId)!))||a.id.localeCompare(b.id)).map(recipe=>`<option value="${esc(recipe.id)}">${esc(itemName(byId.get(recipe.productId)!))} [${esc(recipe.id)}]</option>`).join("")}`}
function craftingPage(){setMeta(m.crafting);return `${hero(m.crafting,m.craftingBody)}<section class="calculator panel wide"><div class="craft-form"><label>${m.product}<select id="craft-product">${itemOptions()}</select></label><label>${m.quantity}<input id="craft-quantity" type="number" min="1" max="999999" value="1"></label></div><p class="notice">${m.ownedMaterials}</p><textarea id="craft-owned" class="owned-input" aria-label="${m.ownedMaterials}" placeholder="Wood=10&#10;Stone=5"></textarea><div id="craft-output" aria-live="polite" class="craft-output">${m.noResult}</div></section>`}
function options(){return `<option value="">${m.choose}</option>${[...(data?.pals||[])].sort((a,b)=>new Intl.Collator(locale,{numeric:true}).compare(palName(a),palName(b))).map(p=>`<option value="${p.i}">#${p.dex}${p.variant?"B":""} ${esc(palName(p))}</option>`).join("")}`}
function genderOptions(){return `<option value="WILDCARD">${m.anyGender}</option><option value="MALE">${m.male}</option><option value="FEMALE">${m.female}</option>`}
function breedingPage(){setMeta(m.breeding);return `${hero(m.breeding,m.breedingBody)}<section class="calculator panel wide"><div class="breed-grid"><label>${m.parentA}<select id="parent-a">${options()}</select></label><label>${m.genderA}<select id="gender-a">${genderOptions()}</select></label><label>${m.parentB}<select id="parent-b">${options()}</select></label><label>${m.genderB}<select id="gender-b">${genderOptions()}</select></label><div class="breed-output"><span>${m.result}</span><output id="breed-result">—</output></div></div><hr><div class="reverse-breed"><label>${m.targetPal}<select id="target-pal">${options()}</select></label><div><h2>${m.parentPairs}</h2><div id="parent-pairs" class="pair-list" aria-live="polite">${m.noResult}</div></div></div><p class="notice">${m.breedingBody}</p></section>`}
function loadPins():MapPin[]{try{const parsed=JSON.parse(localStorage.getItem("pw-map-pins")||"[]");return Array.isArray(parsed)?parsed.filter(p=>typeof p?.id==="string"&&typeof p?.name==="string"&&Number.isFinite(p?.x)&&Number.isFinite(p?.y)):[]}catch{return[]}}
function mapPage(){setMeta(m.map);const bounds=itemData?.map||{minX:-1099400,minY:-724400,maxX:349400,maxY:724400},palsById=new Map(data?.pals.map(p=>[p.id,p])||[]),left=(x:number)=>(x-bounds.minX)/(bounds.maxX-bounds.minX)*100,top=(y:number)=>(bounds.maxY-y)/(bounds.maxY-bounds.minY)*100;const bosses=mapData?.bosses||[];return `${hero(m.mapTitle,m.mapBody)}<section class="map-layout"><aside class="panel map-filters"><h2>${m.map}</h2><label class="check"><input id="boss-layer" type="checkbox" checked>BOSS</label><label>${m.pals}<select id="habitat-pal"><option value="">${m.choose}</option>${[...(data?.pals||[])].sort((a,b)=>new Intl.Collator(locale).compare(palName(a),palName(b))).map(p=>`<option value="${esc(p.id)}">${esc(palName(p))}</option>`).join("")}</select></label><p class="notice">${m.localMapNote}</p></aside><div class="map-stage"><div class="map-controls"><button type="button" data-map-zoom="in" aria-label="${m.map} +">+</button><button type="button" data-map-zoom="out" aria-label="${m.map} −">−</button><button type="button" data-map-zoom="reset" aria-label="${m.remove}">↺</button></div><div class="map-viewport" tabindex="0" aria-label="${m.mapTitle}"><div class="planning-map" id="planning-map">${bosses.map(marker=>{const pal=palsById.get(marker.palId);if(!pal)return"";return `<button class="game-marker boss-marker" style="left:${left(marker.x)}%;top:${top(marker.y)}%" data-map-category="boss" title="${esc(palName(pal))} · Lv. ${marker.levelMin}">${pal.image?`<img src="/assets/pals/${encodeURIComponent(pal.id)}.png" alt="">`:"★"}</button>`}).join("")}<div id="habitat-layer"></div></div></div></div><aside class="panel map-results"><h2>${m.results}</h2><div id="map-result-list">${bosses.map(marker=>{const pal=palsById.get(marker.palId);return pal?`<article class="map-result" data-map-result="boss"><strong>${esc(palName(pal))}</strong><small>Lv. ${marker.levelMin} · ${Math.round(marker.x)}, ${Math.round(marker.y)}</small></article>`:""}).join("")}</div></aside></section>`}
function serverPage(){setMeta(m.server);return `${hero(m.serverTitle,m.footer)}<section class="tool-layout server"><form class="panel" id="server-form"><label>${m.players}<input name="players" type="number" min="1" max="32" value="32"></label><label class="check"><input name="pvp" type="checkbox">${m.pvp}</label><label class="check"><input name="backup" type="checkbox" checked>${m.backup}</label><button class="button primary">${m.generate}</button></form><div class="panel output-panel"><textarea id="ini-output" aria-label="INI output" readonly></textarea><button class="button" id="copy-ini">${m.copy}</button></div></section>`}
function placeholder(title:string){setMeta(title);return `${hero(title,m.coming)}<section class="section"><div class="empty-large"><span>◇</span><p>${m.coming}</p></div></section>`}
function content(){switch(route()){case"/":return home();case"/pals":return palsPage();case"/calculators":case"/calculators/breeding":return breedingPage();case"/calculators/crafting":return craftingPage();case"/server-tools/settings-generator":return serverPage();case"/map":return mapPage();case"/database":return databasePage();default:return placeholder("404")}}
type AnalyticsParams=Record<string,string|number|boolean>;
function trackEvent(name:string,params:AnalyticsParams={}){if(localStorage.getItem("pw-consent")!=="granted")return;const win=window as Window&{gtag?:(...args:unknown[])=>void};win.gtag?.("event",name,params)}
function trackOnce(key:string,name:string,params:AnalyticsParams={}){if(trackedInteractions.has(key))return;trackedInteractions.add(key);trackEvent(name,params)}
function trackPageView(){if(localStorage.getItem("pw-consent")!=="granted")return;const pagePath=location.pathname;if(pagePath===lastTrackedPage)return;lastTrackedPage=pagePath;trackEvent("page_view",{page_path:pagePath,locale})}
function bind(){
  document.querySelectorAll<HTMLAnchorElement>("a[data-link]").forEach(a=>a.onclick=e=>{e.preventDefault();history.pushState({},"",a.href);render();scrollTo(0,0)});
  document.querySelector<HTMLSelectElement>("#locale")?.addEventListener("change",e=>{const next=(e.target as HTMLSelectElement).value as Locale;trackEvent("language_change",{locale:next});localStorage.setItem("pw-locale",next);location.href=localizePath(next,route())});
  document.querySelector("#theme")?.addEventListener("click",()=>{const now=localStorage.getItem("pw-theme")||"system",next=now==="system"?"light":now==="light"?"dark":"system";if(next==="system")localStorage.removeItem("pw-theme");else localStorage.setItem("pw-theme",next);document.documentElement.dataset.theme=next;trackEvent("theme_change",{theme:next})});
  const filterCollection=(kind:"pal"|"item")=>{const input=document.querySelector<HTMLInputElement>(`#${kind}-search`);if(!input)return;const q=input.value.trim().toLocaleLowerCase(locale);let count=0;document.querySelectorAll<HTMLElement>(`.${kind}-card`).forEach(card=>{const show=!q||card.dataset[kind]?.includes(q);card.hidden=!show;if(show)count++});document.querySelector(`#${kind}-count`)!.textContent=`${count.toLocaleString(locale)} ${m.results}`;const empty=document.querySelector<HTMLElement>(`#${kind}-empty`);if(empty)empty.hidden=count!==0};
  const search=document.querySelector<HTMLInputElement>("#pal-search");search?.addEventListener("input",()=>{filterCollection("pal");if(search.value.trim())trackOnce("search:pal","collection_search",{collection:"pal"})});
  const itemSearch=document.querySelector<HTMLInputElement>("#item-search");itemSearch?.addEventListener("input",()=>{filterCollection("item");if(itemSearch.value.trim())trackOnce("search:item","collection_search",{collection:"item"})});
  document.querySelectorAll<HTMLButtonElement>("[data-clear-search]").forEach(button=>button.addEventListener("click",()=>{const kind=button.dataset.clearSearch as "pal"|"item",input=document.querySelector<HTMLInputElement>(`#${kind}-search`);if(!input)return;input.value="";filterCollection(kind);input.focus()}));
  const calculateCraft=()=>{const recipeId=document.querySelector<HTMLSelectElement>("#craft-product")?.value,quantity=Math.max(1,Math.floor(Number(document.querySelector<HTMLInputElement>("#craft-quantity")?.value)||1)),output=document.querySelector<HTMLElement>("#craft-output");if(!recipeId||!output||!itemData){if(output)output.textContent=m.noResult;return}const selected=itemData.recipes.find(recipe=>recipe.id===recipeId);if(!selected){output.textContent=m.noResult;return}const product=selected.productId,recipeCounts=new Map<string,number>();for(const recipe of itemData.recipes)recipeCounts.set(recipe.productId,(recipeCounts.get(recipe.productId)||0)+1);const recipesByProduct=new Map<string,ItemRecipe>();for(const recipe of itemData.recipes)if(recipeCounts.get(recipe.productId)===1)recipesByProduct.set(recipe.productId,recipe);recipesByProduct.set(product,selected);const owned:Record<string,number>={};for(const line of (document.querySelector<HTMLTextAreaElement>("#craft-owned")?.value||"").split(/\r?\n/)){const [id,amount]=line.split("=").map(v=>v.trim());if(id&&Number.isFinite(Number(amount))&&Number(amount)>=0)owned[id]=Number(amount)}const recipes:Record<string,Recipe>=Object.fromEntries([...recipesByProduct].map(([id,r])=>[id,{id:r.id,output:r.output,ingredients:Object.fromEntries(r.ingredients.map(i=>[i.itemId,i.count]))}]));try{const totals=expandRecipe(product,quantity,recipes,owned),byId=new Map(itemData.items.map(item=>[item.id,item])),crafts=Math.ceil(quantity/selected.output);output.innerHTML=`<h2>${esc(itemName(byId.get(product)!))} × ${quantity.toLocaleString(locale)}</h2><p><code>${esc(selected.id)}</code> · ${m.workAmount} ${(selected.workAmount*crafts).toLocaleString(locale)}</p><h3>${m.directMaterials}</h3><ul>${selected.ingredients.map(i=>`<li>${esc(itemName(byId.get(i.itemId)!))}: ${(i.count*crafts).toLocaleString(locale)}</li>`).join("")}</ul><h3>${m.expandedMaterials}</h3><ul>${Object.entries(totals).sort(([a],[b])=>new Intl.Collator(locale).compare(itemName(byId.get(a)!),itemName(byId.get(b)!))||a.localeCompare(b)).map(([id,count])=>`<li>${esc(itemName(byId.get(id)!))}: ${count.toLocaleString(locale)}</li>`).join("")}</ul>`}catch(error){output.textContent=error instanceof Error?error.message:m.noResult}};
  ["#craft-product","#craft-quantity","#craft-owned"].forEach(selector=>document.querySelector(selector)?.addEventListener(selector==="#craft-owned"?"input":"change",()=>{calculateCraft();if(document.querySelector<HTMLSelectElement>("#craft-product")?.value)trackOnce("calculator:crafting","calculator_use",{tool:"crafting"})}));
  const selected=(id:string)=>document.querySelector<HTMLSelectElement>(id)?.value||"";
  const breed=()=>{const av=Number(selected("#parent-a")),bv=Number(selected("#parent-b")),ga=selected("#gender-a") as Gender,gb=selected("#gender-b") as Gender,out=document.querySelector<HTMLOutputElement>("#breed-result");if(!out||!selected("#parent-a")||!selected("#parent-b")){if(out)out.textContent="—";return}const child=data?findBreedingResult(data.pairs,av,bv,ga,gb):undefined;out.textContent=child!==undefined?palName(data!.pals[child]):m.noResult};
  ["#parent-a","#parent-b","#gender-a","#gender-b"].forEach(s=>document.querySelector(s)?.addEventListener("change",()=>{breed();if(selected("#parent-a")&&selected("#parent-b"))trackOnce("calculator:breeding","calculator_use",{tool:"breeding_forward"})}));
  document.querySelector("#target-pal")?.addEventListener("change",()=>{const target=Number(selected("#target-pal")),out=document.querySelector("#parent-pairs")!;if(!selected("#target-pal")){out.textContent=m.noResult;return}const rows=data?findParentPairs(data.pairs,target):[];out.innerHTML=rows.map(r=>`<div><span>${esc(palName(data!.pals[r[0]]))}${r[3]!=="WILDCARD"?` (${r[3]==="MALE"?m.male:m.female})`:""}</span><b>×</b><span>${esc(palName(data!.pals[r[1]]))}${r[4]!=="WILDCARD"?` (${r[4]==="MALE"?m.male:m.female})`:""}</span></div>`).join("")||m.noResult;trackOnce("calculator:breeding_reverse","calculator_use",{tool:"breeding_reverse"})});
  const pinForm=document.querySelector<HTMLFormElement>("#pin-form");pinForm?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(pinForm),x=Number(f.get("x")),y=Number(f.get("y")),bounds=itemData?.map;if(!bounds||!Number.isFinite(x)||!Number.isFinite(y)||x<bounds.minX||x>bounds.maxX||y<bounds.minY||y>bounds.maxY)return;const pins=loadPins();pins.push({id:crypto.randomUUID(),name:String(f.get("name")||"").trim(),category:String(f.get("category")||"").trim(),x,y});localStorage.setItem("pw-map-pins",JSON.stringify(pins));trackEvent("map_pin_change",{action:"add"});render()});
  document.querySelectorAll<HTMLButtonElement>("[data-remove-pin]").forEach(button=>button.addEventListener("click",()=>{localStorage.setItem("pw-map-pins",JSON.stringify(loadPins().filter(p=>p.id!==button.dataset.removePin)));trackEvent("map_pin_change",{action:"remove"});render()}));
  let mapScale=1;
  const map=document.querySelector<HTMLElement>("#planning-map"),viewport=document.querySelector<HTMLElement>(".map-viewport"),bossLayer=document.querySelector<HTMLInputElement>("#boss-layer"),habitatSelect=document.querySelector<HTMLSelectElement>("#habitat-pal");
  const applyMapScale=()=>{if(map)map.style.transform=`scale(${mapScale})`};
  document.querySelectorAll<HTMLButtonElement>("[data-map-zoom]").forEach(button=>button.addEventListener("click",()=>{const action=button.dataset.mapZoom;mapScale=action==="in"?Math.min(4,mapScale+.5):action==="out"?Math.max(1,mapScale-.5):1;applyMapScale()}));
  viewport?.addEventListener("wheel",event=>{event.preventDefault();mapScale=Math.max(1,Math.min(4,mapScale+(event.deltaY<0?.25:-.25)));applyMapScale()},{passive:false});
  bossLayer?.addEventListener("change",()=>{document.querySelectorAll<HTMLElement>("[data-map-category='boss'],[data-map-result='boss']").forEach(node=>node.hidden=!bossLayer.checked);trackEvent("map_layer_toggle",{layer:"boss",enabled:bossLayer.checked})});
  habitatSelect?.addEventListener("change",()=>{const palId=habitatSelect.value,layer=document.querySelector<HTMLElement>("#habitat-layer"),results=document.querySelector<HTMLElement>("#map-result-list"),bounds=itemData?.map,pal=data?.pals.find(entry=>entry.id===palId);if(!layer||!results||!bounds)return;layer.innerHTML="";results.querySelectorAll("[data-map-result='habitat']").forEach(node=>node.remove());if(!palId||!pal)return;const left=(x:number)=>(x-bounds.minX)/(bounds.maxX-bounds.minX)*100,top=(y:number)=>(bounds.maxY-y)/(bounds.maxY-bounds.minY)*100,regions=(mapData?.habitats||[]).filter(region=>region.pals.some(entry=>entry.palId===palId));for(const region of regions){const levels=region.pals.find(entry=>entry.palId===palId)!;layer.insertAdjacentHTML("beforeend",`<span class="habitat-region" style="left:${left(region.x)}%;top:${top(region.y)}%" title="${esc(palName(pal))} · Lv. ${levels.levelMin}–${levels.levelMax}"></span>`);results.insertAdjacentHTML("beforeend",`<article class="map-result" data-map-result="habitat"><strong>${esc(palName(pal))}</strong><small>Lv. ${levels.levelMin}–${levels.levelMax} · ${Math.round(region.x)}, ${Math.round(region.y)}</small></article>`)}trackEvent("map_layer_toggle",{layer:"habitat",enabled:true})});
  document.querySelectorAll<HTMLButtonElement>("[data-consent]").forEach(button=>button.addEventListener("click",()=>{const granted=button.dataset.consent==="allow";localStorage.setItem("pw-consent",granted?"granted":"denied");render();initIntegrations();if(granted)trackEvent("consent_update",{analytics_storage:"granted"})}));
  const form=document.querySelector<HTMLFormElement>("#server-form");form?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(form);document.querySelector<HTMLTextAreaElement>("#ini-output")!.value=buildServerIni({players:Number(f.get("players")),pvp:f.has("pvp"),backup:f.has("backup")});trackOnce("tool:server","tool_use",{tool:"server_settings"})});
  document.querySelector("#copy-ini")?.addEventListener("click",()=>{navigator.clipboard.writeText(document.querySelector<HTMLTextAreaElement>("#ini-output")!.value);trackEvent("tool_action",{tool:"server_settings",action:"copy"})});
}
function initIntegrations(){if(localStorage.getItem("pw-consent")!=="granted")return;if(site.analyticsId&&!document.querySelector("script[data-palworld-ga]")){const script=document.createElement("script");script.async=true;script.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(site.analyticsId)}`;script.dataset.palworldGa="true";document.head.append(script);const win=window as Window&{dataLayer?:unknown[][];gtag?:(...args:unknown[])=>void};win.dataLayer=win.dataLayer||[];win.gtag=(...args)=>win.dataLayer!.push(args);win.gtag("js",new Date());win.gtag("config",site.analyticsId,{send_page_view:false});trackPageView()}if(import.meta.env.PROD&&site.adsenseClient&&!document.querySelector("script[data-palworld-ads]")){const script=document.createElement("script");script.async=true;script.crossOrigin="anonymous";script.src=`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(site.adsenseClient)}`;script.dataset.palworldAds="true";document.head.append(script)}}
function ensureItemData(){if(itemData||itemLoading)return;itemLoading=true;fetch("/data/items.json").then(r=>{if(!r.ok)throw new Error(`Item data load ${r.status}`);return r.json()}).then((loaded:ItemData)=>{if(loaded.meta.gameBuild!==site.gameBuild||loaded.meta.localeCount!==locales.length||loaded.meta.itemCount!==loaded.items.length||loaded.meta.recipeCount!==loaded.recipes.length)throw new Error("Item dataset verification mismatch");itemData=loaded;render()}).catch(error=>console.error(error)).finally(()=>{itemLoading=false})}
function ensurePalData(){if(data||palLoading)return;palLoading=true;fetch("/data/pals.json").then(r=>{if(!r.ok)throw new Error(`Data load ${r.status}`);return r.json()}).then((loaded:PalData)=>{if(loaded.meta.gameBuild!==site.gameBuild||loaded.meta.localIdMatchCount!==loaded.meta.palCount)throw new Error("Dataset verification mismatch");data=loaded;render()}).catch(error=>console.error(error)).finally(()=>{palLoading=false})}
function ensureMapData(){if(mapData||mapLoading)return;mapLoading=true;fetch("/data/map-markers.json").then(r=>{if(!r.ok)throw new Error(`Map data load ${r.status}`);return r.json()}).then((loaded:MapData)=>{if(loaded.meta.gameBuild!==site.gameBuild||loaded.meta.bossCount!==loaded.bosses.length||loaded.meta.habitatCount!==loaded.habitats.length)throw new Error("Map dataset verification mismatch");mapData=loaded;render()}).catch(error=>console.error(error)).finally(()=>{mapLoading=false})}
function render(){locale=resolveLocale(location.pathname);m=messages(locale);app.innerHTML=`<a class="skip-link" href="#main">${m.skip}</a>${header()}<main id="main">${content()}</main>${footer()}${consentBanner()}`;bind();trackPageView();const current=route();if(["/map","/database","/calculators/crafting"].includes(current))ensureItemData();if(["/map","/pals","/calculators","/calculators/breeding"].includes(current))ensurePalData();if(current==="/map")ensureMapData()}
window.addEventListener("popstate",render);render();
initIntegrations();
