import type { Locale } from "./config";

type MapLabels={location:string;collectible:string;npcGroup:string;resource:string;activity:string;egg:string;skillFruit:string;treasure:string;npc:string;merchant:string;palMerchant:string;fishing:string;randomEvent:string;dungeon:string;bounty:string;collectibleShrine:string;palStatue:string};
export const mapLayerLabels:Record<Locale,MapLabels>={
  "en-US":{location:"Locations",collectible:"Collectibles",npcGroup:"NPC",resource:"Resources",activity:"Activities",egg:"Pal eggs",skillFruit:"Skill fruit trees",treasure:"Treasure chests",npc:"NPCs",merchant:"Merchants",palMerchant:"Pal merchants",fishing:"Fishing spots",randomEvent:"Random events",dungeon:"Dungeons",bounty:"Wanted targets",collectibleShrine:"Collectible shrines",palStatue:"Pal statues"},
  "ko-KR":{location:"위치",collectible:"수집물",npcGroup:"NPC",resource:"자원",activity:"활동",egg:"팰 알",skillFruit:"기술 열매",treasure:"보물 상자",npc:"NPC",merchant:"상인",palMerchant:"팰 상인",fishing:"낚시 포인트",randomEvent:"랜덤 이벤트",dungeon:"던전",bounty:"현상수배범",collectibleShrine:"수집 제단",palStatue:"팰 조각상"},
  "ja-JP":{location:"場所",collectible:"収集物",npcGroup:"NPC",resource:"資源",activity:"アクティビティ",egg:"パルのタマゴ",skillFruit:"技の実の木",treasure:"宝箱",npc:"NPC",merchant:"商人",palMerchant:"パル商人",fishing:"釣り場",randomEvent:"ランダムイベント",dungeon:"ダンジョン",bounty:"指名手配犯",collectibleShrine:"収集の祠",palStatue:"パル像"},
  "zh-CN":{location:"位置",collectible:"收集品",npcGroup:"NPC",resource:"资源",activity:"活动",egg:"帕鲁蛋",skillFruit:"技能果实树",treasure:"宝箱",npc:"NPC",merchant:"商人",palMerchant:"帕鲁商人",fishing:"钓鱼点",randomEvent:"随机事件",dungeon:"地下城",bounty:"通缉目标",collectibleShrine:"收集神龛",palStatue:"帕鲁雕像"},
  "zh-TW":{location:"位置",collectible:"收集品",npcGroup:"NPC",resource:"資源",activity:"活動",egg:"帕魯蛋",skillFruit:"技能果實樹",treasure:"寶箱",npc:"NPC",merchant:"商人",palMerchant:"帕魯商人",fishing:"釣魚點",randomEvent:"隨機事件",dungeon:"地下城",bounty:"通緝目標",collectibleShrine:"收集神龕",palStatue:"帕魯雕像"},
  "de-DE":{location:"Orte",collectible:"Sammelobjekte",npcGroup:"NPC",resource:"Ressourcen",activity:"Aktivitäten",egg:"Pal-Eier",skillFruit:"Fähigkeitsfruchtbäume",treasure:"Schatztruhen",npc:"NPCs",merchant:"Händler",palMerchant:"Pal-Händler",fishing:"Angelplätze",randomEvent:"Zufallsereignisse",dungeon:"Dungeons",bounty:"Gesuchte Ziele",collectibleShrine:"Sammelschreine",palStatue:"Pal-Statuen"},
  "fr-FR":{location:"Lieux",collectible:"Objets à collectionner",npcGroup:"PNJ",resource:"Ressources",activity:"Activités",egg:"Œufs de Pal",skillFruit:"Arbres à fruits de compétence",treasure:"Coffres au trésor",npc:"PNJ",merchant:"Marchands",palMerchant:"Marchands de Pals",fishing:"Lieux de pêche",randomEvent:"Événements aléatoires",dungeon:"Donjons",bounty:"Cibles recherchées",collectibleShrine:"Sanctuaires à collectionner",palStatue:"Statues de Pal"},
  "it-IT":{location:"Luoghi",collectible:"Collezionabili",npcGroup:"PNG",resource:"Risorse",activity:"Attività",egg:"Uova di Pal",skillFruit:"Alberi dei frutti abilità",treasure:"Forzieri",npc:"PNG",merchant:"Mercanti",palMerchant:"Mercanti di Pal",fishing:"Punti di pesca",randomEvent:"Eventi casuali",dungeon:"Dungeon",bounty:"Ricercati",collectibleShrine:"Santuari collezionabili",palStatue:"Statue di Pal"},
  "es-ES":{location:"Ubicaciones",collectible:"Coleccionables",npcGroup:"PNJ",resource:"Recursos",activity:"Actividades",egg:"Huevos de Pal",skillFruit:"Árboles de frutos de habilidad",treasure:"Cofres del tesoro",npc:"PNJ",merchant:"Mercaderes",palMerchant:"Mercaderes de Pals",fishing:"Puntos de pesca",randomEvent:"Eventos aleatorios",dungeon:"Mazmorras",bounty:"Objetivos buscados",collectibleShrine:"Santuarios coleccionables",palStatue:"Estatuas de Pal"},
  "es-419":{location:"Ubicaciones",collectible:"Coleccionables",npcGroup:"NPC",resource:"Recursos",activity:"Actividades",egg:"Huevos de Pal",skillFruit:"Árboles de frutos de habilidad",treasure:"Cofres del tesoro",npc:"NPC",merchant:"Comerciantes",palMerchant:"Comerciantes de Pals",fishing:"Puntos de pesca",randomEvent:"Eventos aleatorios",dungeon:"Calabozos",bounty:"Objetivos buscados",collectibleShrine:"Santuarios coleccionables",palStatue:"Estatuas de Pal"},
  "pt-BR":{location:"Locais",collectible:"Colecionáveis",npcGroup:"NPC",resource:"Recursos",activity:"Atividades",egg:"Ovos de Pal",skillFruit:"Árvores de frutos de habilidade",treasure:"Baús de tesouro",npc:"NPCs",merchant:"Comerciantes",palMerchant:"Comerciantes de Pals",fishing:"Pontos de pesca",randomEvent:"Eventos aleatórios",dungeon:"Masmorras",bounty:"Alvos procurados",collectibleShrine:"Santuários colecionáveis",palStatue:"Estátuas de Pal"},
  "ru-RU":{location:"Места",collectible:"Коллекционные предметы",npcGroup:"NPC",resource:"Ресурсы",activity:"Активности",egg:"Яйца Палов",skillFruit:"Деревья плодов навыков",treasure:"Сундуки",npc:"NPC",merchant:"Торговцы",palMerchant:"Торговцы Палами",fishing:"Места рыбалки",randomEvent:"Случайные события",dungeon:"Подземелья",bounty:"Разыскиваемые цели",collectibleShrine:"Коллекционные святилища",palStatue:"Статуи Палов"},
  "id-ID":{location:"Lokasi",collectible:"Koleksi",npcGroup:"NPC",resource:"Sumber daya",activity:"Aktivitas",egg:"Telur Pal",skillFruit:"Pohon buah skill",treasure:"Peti harta",npc:"NPC",merchant:"Pedagang",palMerchant:"Pedagang Pal",fishing:"Tempat memancing",randomEvent:"Peristiwa acak",dungeon:"Dungeon",bounty:"Target buronan",collectibleShrine:"Kuil koleksi",palStatue:"Patung Pal"},
  "th-TH":{location:"สถานที่",collectible:"ของสะสม",npcGroup:"NPC",resource:"ทรัพยากร",activity:"กิจกรรม",egg:"ไข่พาล",skillFruit:"ต้นผลสกิล",treasure:"หีบสมบัติ",npc:"NPC",merchant:"พ่อค้า",palMerchant:"พ่อค้าพาล",fishing:"จุดตกปลา",randomEvent:"เหตุการณ์สุ่ม",dungeon:"ดันเจียน",bounty:"เป้าหมายค่าหัว",collectibleShrine:"ศาลของสะสม",palStatue:"รูปปั้นพาล"},
  "tr-TR":{location:"Konumlar",collectible:"Koleksiyonlar",npcGroup:"NPC",resource:"Kaynaklar",activity:"Etkinlikler",egg:"Pal yumurtaları",skillFruit:"Beceri meyvesi ağaçları",treasure:"Hazine sandıkları",npc:"NPC'ler",merchant:"Tüccarlar",palMerchant:"Pal tüccarları",fishing:"Balık tutma noktaları",randomEvent:"Rastgele etkinlikler",dungeon:"Zindanlar",bounty:"Aranan hedefler",collectibleShrine:"Koleksiyon tapınakları",palStatue:"Pal heykelleri"},
  "vi-VN":{location:"Địa điểm",collectible:"Vật phẩm sưu tầm",npcGroup:"NPC",resource:"Tài nguyên",activity:"Hoạt động",egg:"Trứng Pal",skillFruit:"Cây quả kỹ năng",treasure:"Rương báu",npc:"NPC",merchant:"Thương nhân",palMerchant:"Thương nhân Pal",fishing:"Điểm câu cá",randomEvent:"Sự kiện ngẫu nhiên",dungeon:"Hầm ngục",bounty:"Mục tiêu truy nã",collectibleShrine:"Đền sưu tầm",palStatue:"Tượng Pal"},
  "pl-PL":{location:"Miejsca",collectible:"Przedmioty kolekcjonerskie",npcGroup:"NPC",resource:"Zasoby",activity:"Aktywności",egg:"Jaja Pali",skillFruit:"Drzewa owoców umiejętności",treasure:"Skrzynie ze skarbami",npc:"NPC",merchant:"Kupcy",palMerchant:"Kupcy Pali",fishing:"Łowiska",randomEvent:"Losowe wydarzenia",dungeon:"Lochy",bounty:"Poszukiwane cele",collectibleShrine:"Kapliczki kolekcjonerskie",palStatue:"Posągi Pali"}
};
