import type {Locale} from "./config";

export type OwnedPalsCopy={title:string;intro:string;pal:string;male:string;female:string;unknown:string;stars:string;favorite:string;save:string;remove:string;useOwned:string;export:string;import:string;reset:string;empty:string;invalidImport:string;confirmReset:string;total:string};
export const ownedPalsCopyProvenance="gpt" as const;
const rows:Record<Locale,string[]>={
  "en-US":["Owned Pals","Keep a browser-only Pal ledger and reuse it in tools.","Pal","Male","Female","Unknown","Highest stars","Favorite","Save","Remove","Use owned Pals","Export","Import","Reset","No owned Pals saved.","The selected file has no valid Pal entries.","Reset every saved Pal?","Total"],
  "ko-KR":["보유 팰","브라우저에만 보유 팰을 저장하고 여러 도구에서 재사용합니다.","팰","수컷","암컷","미확인","최고 별","즐겨찾기","저장","삭제","보유 팰 사용","내보내기","가져오기","초기화","저장된 보유 팰이 없습니다.","선택한 파일에 유효한 팰 항목이 없습니다.","저장된 모든 팰을 초기화할까요?","합계"],
  "ja-JP":["所持パル","ブラウザー内だけに所持パルを保存し、各ツールで再利用します。","パル","オス","メス","不明","最高スター","お気に入り","保存","削除","所持パルを使用","書き出し","読み込み","リセット","保存された所持パルはありません。","選択したファイルに有効なパル項目がありません。","保存したパルをすべてリセットしますか？","合計"],
  "zh-CN":["拥有的帕鲁","仅在浏览器中保存帕鲁清单，并在工具间复用。","帕鲁","雄性","雌性","未知","最高星级","收藏","保存","删除","使用拥有的帕鲁","导出","导入","重置","尚未保存拥有的帕鲁。","所选文件中没有有效的帕鲁条目。","要重置所有已保存的帕鲁吗？","总计"],
  "zh-TW":["擁有的帕魯","僅在瀏覽器內儲存帕魯清單，並於工具間重複使用。","帕魯","雄性","雌性","未知","最高星級","收藏","儲存","刪除","使用擁有的帕魯","匯出","匯入","重設","尚未儲存擁有的帕魯。","所選檔案中沒有有效的帕魯項目。","要重設所有已儲存的帕魯嗎？","合計"],
  "fr-FR":["Pals possédés","Conservez une liste uniquement dans ce navigateur et réutilisez-la dans les outils.","Pal","Mâles","Femelles","Inconnu","Étoiles max.","Favori","Enregistrer","Retirer","Utiliser mes Pals","Exporter","Importer","Réinitialiser","Aucun Pal enregistré.","Le fichier ne contient aucune entrée de Pal valide.","Réinitialiser tous les Pals enregistrés ?","Total"],
  "it-IT":["Pal posseduti","Salva un elenco solo nel browser e riutilizzalo negli strumenti.","Pal","Maschi","Femmine","Sconosciuto","Stelle massime","Preferito","Salva","Rimuovi","Usa Pal posseduti","Esporta","Importa","Reimposta","Nessun Pal salvato.","Il file non contiene voci Pal valide.","Reimpostare tutti i Pal salvati?","Totale"],
  "de-DE":["Eigene Pals","Speichere eine Pal-Liste nur im Browser und verwende sie in Werkzeugen erneut.","Pal","Männlich","Weiblich","Unbekannt","Höchste Sterne","Favorit","Speichern","Entfernen","Eigene Pals verwenden","Exportieren","Importieren","Zurücksetzen","Keine eigenen Pals gespeichert.","Die Datei enthält keine gültigen Pal-Einträge.","Alle gespeicherten Pals zurücksetzen?","Gesamt"],
  "es-ES":["Pals disponibles","Guarda una lista solo en el navegador y reutilízala en las herramientas.","Pal","Machos","Hembras","Desconocido","Estrellas máximas","Favorito","Guardar","Eliminar","Usar mis Pals","Exportar","Importar","Restablecer","No hay Pals guardados.","El archivo no contiene entradas de Pal válidas.","¿Restablecer todos los Pals guardados?","Total"],
  "es-419":["Pals disponibles","Guarda una lista solo en el navegador y reutilízala en las herramientas.","Pal","Machos","Hembras","Desconocido","Estrellas máximas","Favorito","Guardar","Quitar","Usar mis Pals","Exportar","Importar","Restablecer","No hay Pals guardados.","El archivo no contiene entradas de Pal válidas.","¿Restablecer todos los Pals guardados?","Total"],
  "pt-BR":["Pals disponíveis","Salve uma lista apenas no navegador e reutilize-a nas ferramentas.","Pal","Machos","Fêmeas","Desconhecido","Máximo de estrelas","Favorito","Salvar","Remover","Usar meus Pals","Exportar","Importar","Redefinir","Nenhum Pal salvo.","O arquivo não contém entradas de Pal válidas.","Redefinir todos os Pals salvos?","Total"],
  "ru-RU":["Свои Палы","Храните список только в браузере и используйте его в разных инструментах.","Пал","Самцы","Самки","Неизвестно","Макс. звёзды","Избранное","Сохранить","Удалить","Использовать своих Палов","Экспорт","Импорт","Сбросить","Сохранённых Палов нет.","В файле нет допустимых записей Палов.","Сбросить всех сохранённых Палов?","Всего"],
  "id-ID":["Pal yang dimiliki","Simpan daftar hanya di browser dan gunakan kembali di berbagai alat.","Pal","Jantan","Betina","Tidak diketahui","Bintang tertinggi","Favorit","Simpan","Hapus","Gunakan Pal milik saya","Ekspor","Impor","Atur ulang","Belum ada Pal tersimpan.","File tidak memiliki entri Pal yang valid.","Atur ulang semua Pal tersimpan?","Total"],
  "th-TH":["พาลที่มี","บันทึกรายการไว้ในเบราว์เซอร์เท่านั้นและใช้ซ้ำในเครื่องมือต่าง ๆ","พาล","เพศผู้","เพศเมีย","ไม่ทราบ","ดาวสูงสุด","รายการโปรด","บันทึก","ลบ","ใช้พาลที่มี","ส่งออก","นำเข้า","รีเซ็ต","ยังไม่มีพาลที่บันทึกไว้","ไฟล์นี้ไม่มีรายการพาลที่ถูกต้อง","รีเซ็ตพาลที่บันทึกทั้งหมดหรือไม่","รวม"],
  "tr-TR":["Sahip olunan Pallar","Listeyi yalnızca tarayıcıda saklayın ve araçlarda yeniden kullanın.","Pal","Erkek","Dişi","Bilinmiyor","En yüksek yıldız","Favori","Kaydet","Kaldır","Sahip olduklarımı kullan","Dışa aktar","İçe aktar","Sıfırla","Kayıtlı Pal yok.","Dosyada geçerli Pal girdisi yok.","Tüm kayıtlı Palları sıfırla?","Toplam"],
  "vi-VN":["Pal đang sở hữu","Chỉ lưu danh sách trong trình duyệt và dùng lại giữa các công cụ.","Pal","Đực","Cái","Không rõ","Sao cao nhất","Yêu thích","Lưu","Xóa","Dùng Pal đang có","Xuất","Nhập","Đặt lại","Chưa lưu Pal nào.","Tệp không có mục Pal hợp lệ.","Đặt lại toàn bộ Pal đã lưu?","Tổng"],
  "pl-PL":["Posiadane Pale","Zapisuj listę wyłącznie w przeglądarce i używaj jej ponownie w narzędziach.","Pal","Samce","Samice","Nieznane","Najwyższe gwiazdki","Ulubiony","Zapisz","Usuń","Użyj posiadanych Pali","Eksportuj","Importuj","Resetuj","Brak zapisanych Pali.","Plik nie zawiera prawidłowych wpisów Pali.","Zresetować wszystkie zapisane Pale?","Razem"]
};
const keys=["title","intro","pal","male","female","unknown","stars","favorite","save","remove","useOwned","export","import","reset","empty","invalidImport","confirmReset","total"] as const;
export const ownedPalsCopy=Object.fromEntries(Object.entries(rows).map(([locale,values])=>[locale,Object.fromEntries(keys.map((key,index)=>[key,values[index]]))])) as Record<Locale,OwnedPalsCopy>;
