import type {Locale} from "./config";

export type PalProfileCopy={profile:string;movement:string;slowWalk:string;walk:string;run:string;rideSprint:string;transport:string;swim:string;swimDash:string;stamina:string;support:string;food:string;maleProbability:string;femaleProbability:string;sourceValueNote:string};
export const palProfileCopyProvenance="gpt" as const;

const rows:Record<Locale,string[]>={
  "en-US":["Verified profile","Movement","Slow walk","Walk","Run","Ride sprint","Transport","Swim","Swim dash","Stamina","Support","Food","Male probability","Female probability","These are source values. Actual behavior can also depend on skills, passives, equipment, and world settings."],
  "ko-KR":["검증된 프로필","이동","느린 걷기","걷기","달리기","탑승 질주","운반","수영","수영 질주","스태미나","지원","식사량","수컷 확률","암컷 확률","원본 수치이며 실제 동작은 스킬, 패시브, 장비, 월드 설정의 영향도 받을 수 있습니다."],
  "ja-JP":["検証済みプロフィール","移動","低速歩行","歩行","走行","ライドダッシュ","運搬","水泳","水泳ダッシュ","スタミナ","サポート","食事量","オス確率","メス確率","元の設定値です。実際の挙動はスキル、パッシブ、装備、ワールド設定の影響も受けます。"],
  "zh-CN":["已验证资料","移动","慢走","步行","奔跑","骑乘冲刺","搬运","游泳","游泳冲刺","耐力","辅助","食量","雄性概率","雌性概率","这些是原始数值，实际表现还可能受技能、被动、装备和世界设置影响。"],
  "zh-TW":["已驗證資料","移動","慢走","步行","奔跑","騎乘衝刺","搬運","游泳","游泳衝刺","耐力","支援","食量","雄性機率","雌性機率","這些是原始數值，實際表現還可能受技能、被動、裝備與世界設定影響。"],
  "fr-FR":["Profil vérifié","Déplacement","Marche lente","Marche","Course","Sprint monté","Transport","Nage","Sprint de nage","Endurance","Soutien","Alimentation","Probabilité mâle","Probabilité femelle","Valeurs de référence ; le comportement réel peut aussi dépendre des compétences, passifs, équipements et réglages du monde."],
  "it-IT":["Profilo verificato","Movimento","Camminata lenta","Camminata","Corsa","Scatto in sella","Trasporto","Nuoto","Scatto a nuoto","Resistenza","Supporto","Cibo","Probabilità maschio","Probabilità femmina","Sono valori di riferimento; il comportamento reale può dipendere anche da abilità, passive, equipaggiamento e impostazioni del mondo."],
  "de-DE":["Verifiziertes Profil","Fortbewegung","Langsames Gehen","Gehen","Laufen","Reitsprint","Transport","Schwimmen","Schwimmsprint","Ausdauer","Unterstützung","Nahrung","Männlich-Wahrscheinlichkeit","Weiblich-Wahrscheinlichkeit","Dies sind Ausgangswerte. Das tatsächliche Verhalten kann auch von Fähigkeiten, Passiva, Ausrüstung und Welteinstellungen abhängen."],
  "es-ES":["Perfil verificado","Movimiento","Paso lento","Paso","Carrera","Esprint montado","Transporte","Nado","Esprint al nadar","Resistencia","Apoyo","Comida","Probabilidad de macho","Probabilidad de hembra","Son valores de referencia; el comportamiento real también puede depender de habilidades, pasivas, equipo y ajustes del mundo."],
  "es-419":["Perfil verificado","Movimiento","Paso lento","Paso","Carrera","Esprint montado","Transporte","Nado","Esprint al nadar","Resistencia","Apoyo","Comida","Probabilidad de macho","Probabilidad de hembra","Son valores de referencia; el comportamiento real también puede depender de habilidades, pasivas, equipo y ajustes del mundo."],
  "pt-BR":["Perfil verificado","Movimento","Caminhada lenta","Caminhada","Corrida","Arrancada montado","Transporte","Natação","Arrancada na água","Vigor","Suporte","Alimentação","Probabilidade de macho","Probabilidade de fêmea","Estes são valores de referência; o comportamento real também pode depender de habilidades, passivas, equipamento e configurações do mundo."],
  "ru-RU":["Проверенный профиль","Движение","Медленный шаг","Ходьба","Бег","Рывок верхом","Переноска","Плавание","Рывок в воде","Выносливость","Поддержка","Питание","Вероятность самца","Вероятность самки","Это исходные значения. На фактическое поведение также могут влиять навыки, пассивные эффекты, снаряжение и настройки мира."],
  "id-ID":["Profil terverifikasi","Pergerakan","Jalan lambat","Berjalan","Berlari","Lari tunggangan","Mengangkut","Berenang","Lari renang","Stamina","Dukungan","Makanan","Peluang jantan","Peluang betina","Ini adalah nilai sumber; perilaku sebenarnya juga dapat dipengaruhi skill, pasif, perlengkapan, dan pengaturan dunia."],
  "th-TH":["ข้อมูลที่ตรวจสอบแล้ว","การเคลื่อนที่","เดินช้า","เดิน","วิ่ง","เร่งความเร็วขณะขี่","ขนส่ง","ว่ายน้ำ","เร่งความเร็วขณะว่ายน้ำ","พละกำลัง","สนับสนุน","อาหาร","โอกาสเพศผู้","โอกาสเพศเมีย","นี่คือค่าต้นทาง พฤติกรรมจริงอาจได้รับผลจากสกิล พาสซีฟ อุปกรณ์ และการตั้งค่าโลกด้วย"],
  "tr-TR":["Doğrulanmış profil","Hareket","Yavaş yürüme","Yürüme","Koşma","Binek deparı","Taşıma","Yüzme","Yüzme deparı","Dayanıklılık","Destek","Yemek","Erkek olasılığı","Dişi olasılığı","Bunlar kaynak değerlerdir; gerçek davranış becerilerden, pasiflerden, ekipmandan ve dünya ayarlarından da etkilenebilir."],
  "vi-VN":["Hồ sơ đã xác minh","Di chuyển","Đi chậm","Đi bộ","Chạy","Nước rút khi cưỡi","Vận chuyển","Bơi","Nước rút khi bơi","Thể lực","Hỗ trợ","Thức ăn","Tỷ lệ đực","Tỷ lệ cái","Đây là các giá trị nguồn; hành vi thực tế còn có thể chịu ảnh hưởng từ kỹ năng, nội tại, trang bị và cài đặt thế giới."],
  "pl-PL":["Zweryfikowany profil","Ruch","Powolny chód","Chód","Bieg","Sprint wierzchowca","Transport","Pływanie","Sprint w wodzie","Wytrzymałość","Wsparcie","Pożywienie","Szansa na samca","Szansa na samicę","Są to wartości źródłowe; na faktyczne działanie mogą też wpływać umiejętności, pasywy, wyposażenie i ustawienia świata."]
};

export const palProfileCopy=Object.fromEntries(Object.entries(rows).map(([locale,values])=>[locale,Object.fromEntries((["profile","movement","slowWalk","walk","run","rideSprint","transport","swim","swimDash","stamina","support","food","maleProbability","femaleProbability","sourceValueNote"] as const).map((key,index)=>[key,values[index]]))])) as Record<Locale,PalProfileCopy>;
