import type {Locale} from "./config";

type QuestCopy={title:string;intro:string;search:string;all:string;main:string;side:string;reset:string;details:string;objectives:string;rewards:string;experience:string;items:string;noObjectives:string;objectiveNotice:string;additionalUnavailable:string;previous:string;next:string;back:string;parallel:string;loadError:string;noResults:string;sequence:string};

export const questCopy:Record<Locale,QuestCopy>={
  "en-US":{title:"Quests",intro:"Browse the current main and side quests with official in-game text, authored order, objectives, and rewards.",search:"Search quests",all:"All quests",main:"Main quests",side:"Side quests",reset:"Reset",details:"View details",objectives:"Objectives",rewards:"Rewards",experience:"Experience",items:"Items",noObjectives:"No explicit objective text is available for this quest.",objectiveNotice:"Only objectives with explicit in-game text are shown.",additionalUnavailable:"An additional cosmetic reward exists, but its localized name is not yet verified.",previous:"Previous quests",next:"Next quests",back:"Back to quests",parallel:"Parallel objective",loadError:"Quest data could not be loaded.",noResults:"No quests match these filters.",sequence:"Quest"},
  "ko-KR":{title:"퀘스트",intro:"현재 메인·서브 퀘스트를 게임 내 공식 문구, 진행 순서, 목표, 보상과 함께 확인하세요.",search:"퀘스트 검색",all:"전체 퀘스트",main:"메인 퀘스트",side:"서브 퀘스트",reset:"초기화",details:"상세 보기",objectives:"목표",rewards:"보상",experience:"경험치",items:"아이템",noObjectives:"이 퀘스트에는 명시적으로 확인된 목표 문구가 없습니다.",objectiveNotice:"게임 내에 명시된 목표 문구만 표시합니다.",additionalUnavailable:"추가 외형 보상이 있지만 현지화된 명칭은 아직 검증되지 않았습니다.",previous:"이전 퀘스트",next:"다음 퀘스트",back:"퀘스트 목록으로",parallel:"병행 목표",loadError:"퀘스트 데이터를 불러오지 못했습니다.",noResults:"조건에 맞는 퀘스트가 없습니다.",sequence:"퀘스트"},
  "ja-JP":{title:"クエスト",intro:"現在のメイン・サブクエストを、ゲーム内の公式テキスト、順序、目標、報酬とともに確認できます。",search:"クエストを検索",all:"すべてのクエスト",main:"メインクエスト",side:"サブクエスト",reset:"リセット",details:"詳細を見る",objectives:"目標",rewards:"報酬",experience:"経験値",items:"アイテム",noObjectives:"このクエストには明示的に確認できる目標テキストがありません。",objectiveNotice:"ゲーム内で明示された目標テキストのみ表示します。",additionalUnavailable:"追加の外見報酬がありますが、ローカライズ名は未確認です。",previous:"前のクエスト",next:"次のクエスト",back:"クエスト一覧へ",parallel:"並行目標",loadError:"クエストデータを読み込めませんでした。",noResults:"条件に一致するクエストがありません。",sequence:"クエスト"},
  "zh-CN":{title:"任务",intro:"查看当前主线与支线任务的官方游戏文本、编排顺序、目标和奖励。",search:"搜索任务",all:"全部任务",main:"主线任务",side:"支线任务",reset:"重置",details:"查看详情",objectives:"目标",rewards:"奖励",experience:"经验值",items:"物品",noObjectives:"此任务没有可明确验证的目标文本。",objectiveNotice:"仅显示游戏中明确提供的目标文本。",additionalUnavailable:"存在额外外观奖励，但其本地化名称尚未验证。",previous:"前置任务",next:"后续任务",back:"返回任务列表",parallel:"并行目标",loadError:"无法加载任务数据。",noResults:"没有符合筛选条件的任务。",sequence:"任务"},
  "zh-TW":{title:"任務",intro:"查看目前主線與支線任務的官方遊戲文字、編排順序、目標和獎勵。",search:"搜尋任務",all:"全部任務",main:"主線任務",side:"支線任務",reset:"重設",details:"查看詳情",objectives:"目標",rewards:"獎勵",experience:"經驗值",items:"物品",noObjectives:"此任務沒有可明確驗證的目標文字。",objectiveNotice:"僅顯示遊戲中明確提供的目標文字。",additionalUnavailable:"存在額外外觀獎勵，但其本地化名稱尚未驗證。",previous:"前置任務",next:"後續任務",back:"返回任務列表",parallel:"並行目標",loadError:"無法載入任務資料。",noResults:"沒有符合篩選條件的任務。",sequence:"任務"},
  "fr-FR":{title:"Quêtes",intro:"Parcourez les quêtes principales et secondaires actuelles avec les textes officiels du jeu, leur ordre, leurs objectifs et leurs récompenses.",search:"Rechercher des quêtes",all:"Toutes les quêtes",main:"Quêtes principales",side:"Quêtes secondaires",reset:"Réinitialiser",details:"Voir les détails",objectives:"Objectifs",rewards:"Récompenses",experience:"Expérience",items:"Objets",noObjectives:"Aucun texte d’objectif explicite n’est disponible pour cette quête.",objectiveNotice:"Seuls les objectifs explicitement présents dans le jeu sont affichés.",additionalUnavailable:"Une récompense cosmétique supplémentaire existe, mais son nom localisé n’est pas encore vérifié.",previous:"Quêtes précédentes",next:"Quêtes suivantes",back:"Retour aux quêtes",parallel:"Objectif parallèle",loadError:"Impossible de charger les données de quête.",noResults:"Aucune quête ne correspond à ces filtres.",sequence:"Quête"},
  "it-IT":{title:"Missioni",intro:"Consulta le missioni principali e secondarie attuali con testi ufficiali, ordine, obiettivi e ricompense.",search:"Cerca missioni",all:"Tutte le missioni",main:"Missioni principali",side:"Missioni secondarie",reset:"Reimposta",details:"Vedi dettagli",objectives:"Obiettivi",rewards:"Ricompense",experience:"Esperienza",items:"Oggetti",noObjectives:"Per questa missione non è disponibile un testo obiettivo esplicito.",objectiveNotice:"Sono mostrati solo gli obiettivi esplicitamente presenti nel gioco.",additionalUnavailable:"Esiste una ricompensa estetica aggiuntiva, ma il nome localizzato non è ancora verificato.",previous:"Missioni precedenti",next:"Missioni successive",back:"Torna alle missioni",parallel:"Obiettivo parallelo",loadError:"Impossibile caricare i dati delle missioni.",noResults:"Nessuna missione corrisponde ai filtri.",sequence:"Missione"},
  "de-DE":{title:"Quests",intro:"Durchsuche aktuelle Haupt- und Nebenquests mit offiziellen Spieltexten, Reihenfolge, Zielen und Belohnungen.",search:"Quests suchen",all:"Alle Quests",main:"Hauptquests",side:"Nebenquests",reset:"Zurücksetzen",details:"Details ansehen",objectives:"Ziele",rewards:"Belohnungen",experience:"Erfahrung",items:"Gegenstände",noObjectives:"Für diese Quest ist kein ausdrücklich bestätigter Zieltext verfügbar.",objectiveNotice:"Es werden nur ausdrücklich im Spiel vorhandene Zieltexte angezeigt.",additionalUnavailable:"Es gibt eine zusätzliche kosmetische Belohnung, deren lokalisierter Name noch nicht bestätigt ist.",previous:"Vorherige Quests",next:"Nächste Quests",back:"Zurück zu den Quests",parallel:"Paralleles Ziel",loadError:"Questdaten konnten nicht geladen werden.",noResults:"Keine Quest entspricht diesen Filtern.",sequence:"Quest"},
  "es-ES":{title:"Misiones",intro:"Consulta las misiones principales y secundarias actuales con textos oficiales, orden, objetivos y recompensas.",search:"Buscar misiones",all:"Todas las misiones",main:"Misiones principales",side:"Misiones secundarias",reset:"Restablecer",details:"Ver detalles",objectives:"Objetivos",rewards:"Recompensas",experience:"Experiencia",items:"Objetos",noObjectives:"No hay texto de objetivo explícito disponible para esta misión.",objectiveNotice:"Solo se muestran los objetivos indicados explícitamente en el juego.",additionalUnavailable:"Existe una recompensa cosmética adicional, pero su nombre localizado aún no está verificado.",previous:"Misiones anteriores",next:"Misiones siguientes",back:"Volver a las misiones",parallel:"Objetivo paralelo",loadError:"No se pudieron cargar los datos de misiones.",noResults:"Ninguna misión coincide con los filtros.",sequence:"Misión"},
  "es-419":{title:"Misiones",intro:"Consulta las misiones principales y secundarias actuales con textos oficiales, orden, objetivos y recompensas.",search:"Buscar misiones",all:"Todas las misiones",main:"Misiones principales",side:"Misiones secundarias",reset:"Restablecer",details:"Ver detalles",objectives:"Objetivos",rewards:"Recompensas",experience:"Experiencia",items:"Objetos",noObjectives:"No hay texto de objetivo explícito disponible para esta misión.",objectiveNotice:"Solo se muestran los objetivos indicados explícitamente en el juego.",additionalUnavailable:"Existe una recompensa cosmética adicional, pero su nombre localizado aún no está verificado.",previous:"Misiones anteriores",next:"Misiones siguientes",back:"Volver a las misiones",parallel:"Objetivo paralelo",loadError:"No se pudieron cargar los datos de misiones.",noResults:"Ninguna misión coincide con los filtros.",sequence:"Misión"},
  "pt-BR":{title:"Missões",intro:"Consulte as missões principais e secundárias atuais com textos oficiais, ordem, objetivos e recompensas.",search:"Buscar missões",all:"Todas as missões",main:"Missões principais",side:"Missões secundárias",reset:"Redefinir",details:"Ver detalhes",objectives:"Objetivos",rewards:"Recompensas",experience:"Experiência",items:"Itens",noObjectives:"Não há texto de objetivo explicitamente verificado para esta missão.",objectiveNotice:"Apenas objetivos explicitamente presentes no jogo são exibidos.",additionalUnavailable:"Existe uma recompensa cosmética adicional, mas seu nome localizado ainda não foi verificado.",previous:"Missões anteriores",next:"Próximas missões",back:"Voltar às missões",parallel:"Objetivo paralelo",loadError:"Não foi possível carregar os dados das missões.",noResults:"Nenhuma missão corresponde aos filtros.",sequence:"Missão"},
  "ru-RU":{title:"Задания",intro:"Просматривайте актуальные основные и побочные задания с официальным текстом, порядком, целями и наградами.",search:"Поиск заданий",all:"Все задания",main:"Основные задания",side:"Побочные задания",reset:"Сбросить",details:"Подробнее",objectives:"Цели",rewards:"Награды",experience:"Опыт",items:"Предметы",noObjectives:"Для этого задания нет явно подтверждённого текста цели.",objectiveNotice:"Показаны только цели, явно указанные в игре.",additionalUnavailable:"Есть дополнительная косметическая награда, но её локализованное название ещё не проверено.",previous:"Предыдущие задания",next:"Следующие задания",back:"Назад к заданиям",parallel:"Параллельная цель",loadError:"Не удалось загрузить данные заданий.",noResults:"Нет заданий, соответствующих фильтрам.",sequence:"Задание"},
  "id-ID":{title:"Quest",intro:"Jelajahi quest utama dan sampingan terkini dengan teks resmi dalam game, urutan, objektif, dan hadiah.",search:"Cari quest",all:"Semua quest",main:"Quest utama",side:"Quest sampingan",reset:"Atur ulang",details:"Lihat detail",objectives:"Objektif",rewards:"Hadiah",experience:"Pengalaman",items:"Item",noObjectives:"Tidak ada teks objektif eksplisit yang tersedia untuk quest ini.",objectiveNotice:"Hanya objektif yang tertulis eksplisit dalam game yang ditampilkan.",additionalUnavailable:"Ada hadiah kosmetik tambahan, tetapi nama lokalnya belum diverifikasi.",previous:"Quest sebelumnya",next:"Quest berikutnya",back:"Kembali ke quest",parallel:"Objektif paralel",loadError:"Data quest tidak dapat dimuat.",noResults:"Tidak ada quest yang cocok dengan filter.",sequence:"Quest"},
  "th-TH":{title:"เควสต์",intro:"ดูเควสต์หลักและเควสต์รองปัจจุบัน พร้อมข้อความทางการในเกม ลำดับ เป้าหมาย และรางวัล",search:"ค้นหาเควสต์",all:"เควสต์ทั้งหมด",main:"เควสต์หลัก",side:"เควสต์รอง",reset:"รีเซ็ต",details:"ดูรายละเอียด",objectives:"เป้าหมาย",rewards:"รางวัล",experience:"ค่าประสบการณ์",items:"ไอเทม",noObjectives:"ไม่มีข้อความเป้าหมายที่ยืนยันอย่างชัดเจนสำหรับเควสต์นี้",objectiveNotice:"แสดงเฉพาะเป้าหมายที่ระบุไว้อย่างชัดเจนในเกม",additionalUnavailable:"มีรางวัลรูปลักษณ์เพิ่มเติม แต่ชื่อที่แปลแล้วยังไม่ได้รับการยืนยัน",previous:"เควสต์ก่อนหน้า",next:"เควสต์ถัดไป",back:"กลับไปยังเควสต์",parallel:"เป้าหมายคู่ขนาน",loadError:"ไม่สามารถโหลดข้อมูลเควสต์ได้",noResults:"ไม่มีเควสต์ที่ตรงกับตัวกรอง",sequence:"เควสต์"},
  "tr-TR":{title:"Görevler",intro:"Güncel ana ve yan görevleri resmî oyun metinleri, sıraları, hedefleri ve ödülleriyle incele.",search:"Görev ara",all:"Tüm görevler",main:"Ana görevler",side:"Yan görevler",reset:"Sıfırla",details:"Ayrıntıları gör",objectives:"Hedefler",rewards:"Ödüller",experience:"Deneyim",items:"Eşyalar",noObjectives:"Bu görev için açıkça doğrulanmış bir hedef metni yok.",objectiveNotice:"Yalnızca oyunda açıkça bulunan hedef metinleri gösterilir.",additionalUnavailable:"Ek bir kozmetik ödül var, ancak yerelleştirilmiş adı henüz doğrulanmadı.",previous:"Önceki görevler",next:"Sonraki görevler",back:"Görevlere dön",parallel:"Paralel hedef",loadError:"Görev verileri yüklenemedi.",noResults:"Filtrelerle eşleşen görev yok.",sequence:"Görev"},
  "vi-VN":{title:"Nhiệm vụ",intro:"Xem nhiệm vụ chính và phụ hiện tại cùng văn bản chính thức trong game, thứ tự, mục tiêu và phần thưởng.",search:"Tìm nhiệm vụ",all:"Tất cả nhiệm vụ",main:"Nhiệm vụ chính",side:"Nhiệm vụ phụ",reset:"Đặt lại",details:"Xem chi tiết",objectives:"Mục tiêu",rewards:"Phần thưởng",experience:"Kinh nghiệm",items:"Vật phẩm",noObjectives:"Nhiệm vụ này không có văn bản mục tiêu được xác nhận rõ ràng.",objectiveNotice:"Chỉ hiển thị mục tiêu được nêu rõ trong game.",additionalUnavailable:"Có phần thưởng ngoại hình bổ sung nhưng tên bản địa hóa chưa được xác minh.",previous:"Nhiệm vụ trước",next:"Nhiệm vụ tiếp theo",back:"Quay lại nhiệm vụ",parallel:"Mục tiêu song song",loadError:"Không thể tải dữ liệu nhiệm vụ.",noResults:"Không có nhiệm vụ phù hợp với bộ lọc.",sequence:"Nhiệm vụ"},
  "pl-PL":{title:"Zadania",intro:"Przeglądaj aktualne zadania główne i poboczne z oficjalnym tekstem gry, kolejnością, celami i nagrodami.",search:"Szukaj zadań",all:"Wszystkie zadania",main:"Zadania główne",side:"Zadania poboczne",reset:"Resetuj",details:"Zobacz szczegóły",objectives:"Cele",rewards:"Nagrody",experience:"Doświadczenie",items:"Przedmioty",noObjectives:"Dla tego zadania nie ma wyraźnie potwierdzonego tekstu celu.",objectiveNotice:"Wyświetlane są tylko cele wyraźnie podane w grze.",additionalUnavailable:"Istnieje dodatkowa nagroda kosmetyczna, ale jej zlokalizowana nazwa nie została jeszcze zweryfikowana.",previous:"Poprzednie zadania",next:"Następne zadania",back:"Wróć do zadań",parallel:"Cel równoległy",loadError:"Nie udało się wczytać danych zadań.",noResults:"Brak zadań pasujących do filtrów.",sequence:"Zadanie"}
};

export const questCopyProvenance:Record<Locale,"reviewed"|"gpt">={
  "en-US":"reviewed","ko-KR":"reviewed","zh-CN":"gpt","zh-TW":"gpt","ja-JP":"gpt","fr-FR":"gpt","it-IT":"gpt","de-DE":"gpt","es-ES":"gpt","pt-BR":"gpt","ru-RU":"gpt","id-ID":"gpt","es-419":"gpt","th-TH":"gpt","tr-TR":"gpt","vi-VN":"gpt","pl-PL":"gpt"
};
