import type { Locale } from "./config";

export type UiCopy={
  skillFruit:string;size:string;breedingPower:string;loading:string;worldTree:string;
  serverManagement:string;serverPerformance:string;serverFeatures:string;serverBalance:string;
  importExistingIni:string;importAndValidate:string;iniOutput:string;serverNotice:string;
  serverNamePlaceholder:string;serverDescriptionPlaceholder:string;passwordRequiredPlaceholder:string;adminPasswordPlaceholder:string;
  warningUnsupportedKey:string;warningBoolean:string;warningNumber:string;warningRange:string;
};

export const uiCopy:Record<Locale,UiCopy>={
  "en-US":{skillFruit:"Skill Fruit",size:"Size",breedingPower:"Breeding power",loading:"Loading…",worldTree:"World Tree",serverManagement:"Server management",serverPerformance:"Performance",serverFeatures:"Features",serverBalance:"Game balance",importExistingIni:"Import existing INI",importAndValidate:"Import and validate",iniOutput:"INI output",serverNotice:"Only settings documented by the official Palworld Server Guide are available. Blank fields are omitted and all content stays in this browser.",serverNamePlaceholder:"My Palworld Server",serverDescriptionPlaceholder:"Co-op Palworld server",passwordRequiredPlaceholder:"Enter only when required",adminPasswordPlaceholder:"Use a long unique password",warningUnsupportedKey:"Unsupported key ignored: {key}",warningBoolean:"{key} must be True or False.",warningNumber:"{key} must be a number.",warningRange:"{key} is outside the supported range."},
  "ko-KR":{skillFruit:"스킬 열매",size:"크기",breedingPower:"교배 수치",loading:"불러오는 중…",worldTree:"세계수",serverManagement:"서버 관리",serverPerformance:"성능",serverFeatures:"기능",serverBalance:"게임 밸런스",importExistingIni:"기존 INI 가져오기",importAndValidate:"가져와서 검증",iniOutput:"INI 출력",serverNotice:"공식 Palworld 서버 가이드에 문서화된 설정만 사용할 수 있습니다. 빈 필드는 제외되며 모든 내용은 이 브라우저에만 유지됩니다.",serverNamePlaceholder:"나의 Palworld 서버",serverDescriptionPlaceholder:"협동 Palworld 서버",passwordRequiredPlaceholder:"필요한 경우에만 입력",adminPasswordPlaceholder:"길고 고유한 비밀번호 사용",warningUnsupportedKey:"지원하지 않는 키를 무시했습니다: {key}",warningBoolean:"{key} 값은 True 또는 False여야 합니다.",warningNumber:"{key} 값은 숫자여야 합니다.",warningRange:"{key} 값이 지원 범위를 벗어났습니다."},
  "ja-JP":{skillFruit:"スキルフルーツ",size:"サイズ",breedingPower:"配合パワー",loading:"読み込み中…",worldTree:"世界樹",serverManagement:"サーバー管理",serverPerformance:"パフォーマンス",serverFeatures:"機能",serverBalance:"ゲームバランス",importExistingIni:"既存のINIを読み込む",importAndValidate:"読み込んで検証",iniOutput:"INI出力",serverNotice:"Palworld公式サーバーガイドに記載された設定のみ使用できます。空欄は省略され、すべての内容はこのブラウザー内に保持されます。",serverNamePlaceholder:"自分のPalworldサーバー",serverDescriptionPlaceholder:"協力プレイ用Palworldサーバー",passwordRequiredPlaceholder:"必要な場合のみ入力",adminPasswordPlaceholder:"長く固有のパスワードを使用",warningUnsupportedKey:"未対応のキーを無視しました: {key}",warningBoolean:"{key} は True または False である必要があります。",warningNumber:"{key} は数値である必要があります。",warningRange:"{key} は対応範囲外です。"},
  "zh-CN":{skillFruit:"技能果实",size:"体型",breedingPower:"配种数值",loading:"加载中…",worldTree:"世界树",serverManagement:"服务器管理",serverPerformance:"性能",serverFeatures:"功能",serverBalance:"游戏平衡",importExistingIni:"导入现有 INI",importAndValidate:"导入并验证",iniOutput:"INI 输出",serverNotice:"仅可使用 Palworld 官方服务器指南中记录的设置。空白字段会被省略，所有内容仅保留在此浏览器中。",serverNamePlaceholder:"我的 Palworld 服务器",serverDescriptionPlaceholder:"Palworld 合作服务器",passwordRequiredPlaceholder:"仅在需要时输入",adminPasswordPlaceholder:"使用较长且唯一的密码",warningUnsupportedKey:"已忽略不支持的键：{key}",warningBoolean:"{key} 必须为 True 或 False。",warningNumber:"{key} 必须为数字。",warningRange:"{key} 超出支持范围。"},
  "zh-TW":{skillFruit:"技能果實",size:"體型",breedingPower:"配種數值",loading:"載入中…",worldTree:"世界樹",serverManagement:"伺服器管理",serverPerformance:"效能",serverFeatures:"功能",serverBalance:"遊戲平衡",importExistingIni:"匯入現有 INI",importAndValidate:"匯入並驗證",iniOutput:"INI 輸出",serverNotice:"僅可使用 Palworld 官方伺服器指南中記載的設定。空白欄位會被省略，所有內容只會保留在此瀏覽器中。",serverNamePlaceholder:"我的 Palworld 伺服器",serverDescriptionPlaceholder:"Palworld 合作伺服器",passwordRequiredPlaceholder:"僅在需要時輸入",adminPasswordPlaceholder:"使用較長且唯一的密碼",warningUnsupportedKey:"已忽略不支援的鍵：{key}",warningBoolean:"{key} 必須為 True 或 False。",warningNumber:"{key} 必須為數字。",warningRange:"{key} 超出支援範圍。"},
  "fr-FR":{skillFruit:"Fruit de compétence",size:"Taille",breedingPower:"Puissance de reproduction",loading:"Chargement…",worldTree:"Arbre-Monde",serverManagement:"Gestion du serveur",serverPerformance:"Performances",serverFeatures:"Fonctionnalités",serverBalance:"Équilibrage du jeu",importExistingIni:"Importer un INI existant",importAndValidate:"Importer et valider",iniOutput:"Sortie INI",serverNotice:"Seuls les paramètres documentés dans le guide officiel des serveurs Palworld sont disponibles. Les champs vides sont omis et tout le contenu reste dans ce navigateur.",serverNamePlaceholder:"Mon serveur Palworld",serverDescriptionPlaceholder:"Serveur Palworld coopératif",passwordRequiredPlaceholder:"Saisir uniquement si nécessaire",adminPasswordPlaceholder:"Utiliser un mot de passe long et unique",warningUnsupportedKey:"Clé non prise en charge ignorée : {key}",warningBoolean:"{key} doit valoir True ou False.",warningNumber:"{key} doit être un nombre.",warningRange:"{key} est hors de la plage prise en charge."},
  "it-IT":{skillFruit:"Frutto abilità",size:"Taglia",breedingPower:"Potenza di riproduzione",loading:"Caricamento…",worldTree:"Albero del Mondo",serverManagement:"Gestione server",serverPerformance:"Prestazioni",serverFeatures:"Funzionalità",serverBalance:"Bilanciamento del gioco",importExistingIni:"Importa INI esistente",importAndValidate:"Importa e convalida",iniOutput:"Output INI",serverNotice:"Sono disponibili solo le impostazioni documentate nella guida ufficiale ai server di Palworld. I campi vuoti vengono omessi e tutti i contenuti restano in questo browser.",serverNamePlaceholder:"Il mio server Palworld",serverDescriptionPlaceholder:"Server Palworld cooperativo",passwordRequiredPlaceholder:"Inserisci solo se necessario",adminPasswordPlaceholder:"Usa una password lunga e univoca",warningUnsupportedKey:"Chiave non supportata ignorata: {key}",warningBoolean:"{key} deve essere True o False.",warningNumber:"{key} deve essere un numero.",warningRange:"{key} è fuori dall'intervallo supportato."},
  "de-DE":{skillFruit:"Fähigkeitsfrucht",size:"Größe",breedingPower:"Zuchtwert",loading:"Wird geladen…",worldTree:"Weltenbaum",serverManagement:"Serververwaltung",serverPerformance:"Leistung",serverFeatures:"Funktionen",serverBalance:"Spielbalance",importExistingIni:"Vorhandene INI importieren",importAndValidate:"Importieren und prüfen",iniOutput:"INI-Ausgabe",serverNotice:"Es sind nur Einstellungen verfügbar, die im offiziellen Palworld-Serverleitfaden dokumentiert sind. Leere Felder werden ausgelassen und alle Inhalte bleiben in diesem Browser.",serverNamePlaceholder:"Mein Palworld-Server",serverDescriptionPlaceholder:"Kooperativer Palworld-Server",passwordRequiredPlaceholder:"Nur bei Bedarf eingeben",adminPasswordPlaceholder:"Ein langes, eindeutiges Passwort verwenden",warningUnsupportedKey:"Nicht unterstützter Schlüssel ignoriert: {key}",warningBoolean:"{key} muss True oder False sein.",warningNumber:"{key} muss eine Zahl sein.",warningRange:"{key} liegt außerhalb des unterstützten Bereichs."},
  "es-ES":{skillFruit:"Fruta de habilidad",size:"Tamaño",breedingPower:"Poder de cría",loading:"Cargando…",worldTree:"Árbol del Mundo",serverManagement:"Gestión del servidor",serverPerformance:"Rendimiento",serverFeatures:"Funciones",serverBalance:"Equilibrio del juego",importExistingIni:"Importar INI existente",importAndValidate:"Importar y validar",iniOutput:"Salida INI",serverNotice:"Solo están disponibles los ajustes documentados en la guía oficial de servidores de Palworld. Los campos vacíos se omiten y todo el contenido permanece en este navegador.",serverNamePlaceholder:"Mi servidor de Palworld",serverDescriptionPlaceholder:"Servidor cooperativo de Palworld",passwordRequiredPlaceholder:"Introducir solo cuando sea necesario",adminPasswordPlaceholder:"Usa una contraseña larga y única",warningUnsupportedKey:"Se ignoró una clave no compatible: {key}",warningBoolean:"{key} debe ser True o False.",warningNumber:"{key} debe ser un número.",warningRange:"{key} está fuera del intervalo compatible."},
  "es-419":{skillFruit:"Fruta de habilidad",size:"Tamaño",breedingPower:"Poder de crianza",loading:"Cargando…",worldTree:"Árbol del Mundo",serverManagement:"Administración del servidor",serverPerformance:"Rendimiento",serverFeatures:"Funciones",serverBalance:"Balance del juego",importExistingIni:"Importar INI existente",importAndValidate:"Importar y validar",iniOutput:"Salida INI",serverNotice:"Solo están disponibles los ajustes documentados en la guía oficial de servidores de Palworld. Los campos vacíos se omiten y todo el contenido permanece en este navegador.",serverNamePlaceholder:"Mi servidor de Palworld",serverDescriptionPlaceholder:"Servidor cooperativo de Palworld",passwordRequiredPlaceholder:"Ingresar solo cuando sea necesario",adminPasswordPlaceholder:"Usa una contraseña larga y única",warningUnsupportedKey:"Se ignoró una clave no compatible: {key}",warningBoolean:"{key} debe ser True o False.",warningNumber:"{key} debe ser un número.",warningRange:"{key} está fuera del rango compatible."},
  "pt-BR":{skillFruit:"Fruta de habilidade",size:"Tamanho",breedingPower:"Poder de reprodução",loading:"Carregando…",worldTree:"Árvore do Mundo",serverManagement:"Gerenciamento do servidor",serverPerformance:"Desempenho",serverFeatures:"Recursos",serverBalance:"Equilíbrio do jogo",importExistingIni:"Importar INI existente",importAndValidate:"Importar e validar",iniOutput:"Saída INI",serverNotice:"Somente as configurações documentadas no Guia Oficial de Servidores do Palworld estão disponíveis. Campos em branco são omitidos e todo o conteúdo permanece neste navegador.",serverNamePlaceholder:"Meu servidor Palworld",serverDescriptionPlaceholder:"Servidor cooperativo de Palworld",passwordRequiredPlaceholder:"Insira somente quando necessário",adminPasswordPlaceholder:"Use uma senha longa e exclusiva",warningUnsupportedKey:"Chave não compatível ignorada: {key}",warningBoolean:"{key} deve ser True ou False.",warningNumber:"{key} deve ser um número.",warningRange:"{key} está fora do intervalo compatível."},
  "ru-RU":{skillFruit:"Плод навыка",size:"Размер",breedingPower:"Сила разведения",loading:"Загрузка…",worldTree:"Мировое древо",serverManagement:"Управление сервером",serverPerformance:"Производительность",serverFeatures:"Функции",serverBalance:"Баланс игры",importExistingIni:"Импортировать существующий INI",importAndValidate:"Импортировать и проверить",iniOutput:"Вывод INI",serverNotice:"Доступны только параметры, описанные в официальном руководстве по серверу Palworld. Пустые поля пропускаются, а все данные остаются в этом браузере.",serverNamePlaceholder:"Мой сервер Palworld",serverDescriptionPlaceholder:"Кооперативный сервер Palworld",passwordRequiredPlaceholder:"Вводите только при необходимости",adminPasswordPlaceholder:"Используйте длинный уникальный пароль",warningUnsupportedKey:"Неподдерживаемый ключ пропущен: {key}",warningBoolean:"Значение {key} должно быть True или False.",warningNumber:"Значение {key} должно быть числом.",warningRange:"Значение {key} находится вне поддерживаемого диапазона."},
  "id-ID":{skillFruit:"Buah Skill",size:"Ukuran",breedingPower:"Kekuatan pengembangbiakan",loading:"Memuat…",worldTree:"Pohon Dunia",serverManagement:"Pengelolaan server",serverPerformance:"Performa",serverFeatures:"Fitur",serverBalance:"Keseimbangan game",importExistingIni:"Impor INI yang ada",importAndValidate:"Impor dan validasi",iniOutput:"Keluaran INI",serverNotice:"Hanya pengaturan yang didokumentasikan dalam Panduan Server Palworld resmi yang tersedia. Kolom kosong diabaikan dan seluruh konten tetap berada di browser ini.",serverNamePlaceholder:"Server Palworld saya",serverDescriptionPlaceholder:"Server Palworld kooperatif",passwordRequiredPlaceholder:"Masukkan hanya jika diperlukan",adminPasswordPlaceholder:"Gunakan kata sandi panjang dan unik",warningUnsupportedKey:"Kunci yang tidak didukung diabaikan: {key}",warningBoolean:"{key} harus bernilai True atau False.",warningNumber:"{key} harus berupa angka.",warningRange:"{key} berada di luar rentang yang didukung."},
  "th-TH":{skillFruit:"ผลไม้สกิล",size:"ขนาด",breedingPower:"ค่าผสมพันธุ์",loading:"กำลังโหลด…",worldTree:"ต้นไม้โลก",serverManagement:"การจัดการเซิร์ฟเวอร์",serverPerformance:"ประสิทธิภาพ",serverFeatures:"ฟีเจอร์",serverBalance:"สมดุลเกม",importExistingIni:"นำเข้า INI ที่มีอยู่",importAndValidate:"นำเข้าและตรวจสอบ",iniOutput:"ผลลัพธ์ INI",serverNotice:"ใช้ได้เฉพาะการตั้งค่าที่ระบุไว้ในคู่มือเซิร์ฟเวอร์ Palworld อย่างเป็นทางการ ระบบจะละเว้นช่องว่างและเก็บเนื้อหาทั้งหมดไว้ในเบราว์เซอร์นี้เท่านั้น",serverNamePlaceholder:"เซิร์ฟเวอร์ Palworld ของฉัน",serverDescriptionPlaceholder:"เซิร์ฟเวอร์ Palworld แบบร่วมมือ",passwordRequiredPlaceholder:"กรอกเฉพาะเมื่อจำเป็น",adminPasswordPlaceholder:"ใช้รหัสผ่านที่ยาวและไม่ซ้ำ",warningUnsupportedKey:"ละเว้นคีย์ที่ไม่รองรับ: {key}",warningBoolean:"{key} ต้องเป็น True หรือ False",warningNumber:"{key} ต้องเป็นตัวเลข",warningRange:"{key} อยู่นอกช่วงที่รองรับ"},
  "tr-TR":{skillFruit:"Beceri Meyvesi",size:"Boyut",breedingPower:"Üreme gücü",loading:"Yükleniyor…",worldTree:"Dünya Ağacı",serverManagement:"Sunucu yönetimi",serverPerformance:"Performans",serverFeatures:"Özellikler",serverBalance:"Oyun dengesi",importExistingIni:"Mevcut INI dosyasını içe aktar",importAndValidate:"İçe aktar ve doğrula",iniOutput:"INI çıktısı",serverNotice:"Yalnızca resmî Palworld Sunucu Kılavuzu'nda belgelenen ayarlar kullanılabilir. Boş alanlar atlanır ve tüm içerik bu tarayıcıda kalır.",serverNamePlaceholder:"Palworld sunucum",serverDescriptionPlaceholder:"Eşli Palworld sunucusu",passwordRequiredPlaceholder:"Yalnızca gerektiğinde girin",adminPasswordPlaceholder:"Uzun ve benzersiz bir parola kullanın",warningUnsupportedKey:"Desteklenmeyen anahtar yok sayıldı: {key}",warningBoolean:"{key}, True veya False olmalıdır.",warningNumber:"{key} bir sayı olmalıdır.",warningRange:"{key} desteklenen aralığın dışında."},
  "vi-VN":{skillFruit:"Trái Kỹ năng",size:"Kích thước",breedingPower:"Chỉ số phối giống",loading:"Đang tải…",worldTree:"Cây Thế Giới",serverManagement:"Quản lý máy chủ",serverPerformance:"Hiệu năng",serverFeatures:"Tính năng",serverBalance:"Cân bằng trò chơi",importExistingIni:"Nhập INI hiện có",importAndValidate:"Nhập và xác thực",iniOutput:"Kết quả INI",serverNotice:"Chỉ có các cài đặt được ghi trong Hướng dẫn Máy chủ Palworld chính thức. Các trường trống sẽ bị bỏ qua và toàn bộ nội dung chỉ được giữ trong trình duyệt này.",serverNamePlaceholder:"Máy chủ Palworld của tôi",serverDescriptionPlaceholder:"Máy chủ Palworld hợp tác",passwordRequiredPlaceholder:"Chỉ nhập khi cần",adminPasswordPlaceholder:"Dùng mật khẩu dài và duy nhất",warningUnsupportedKey:"Đã bỏ qua khóa không được hỗ trợ: {key}",warningBoolean:"{key} phải là True hoặc False.",warningNumber:"{key} phải là một số.",warningRange:"{key} nằm ngoài phạm vi được hỗ trợ."},
  "pl-PL":{skillFruit:"Owoc umiejętności",size:"Rozmiar",breedingPower:"Siła hodowlana",loading:"Wczytywanie…",worldTree:"Drzewo Świata",serverManagement:"Zarządzanie serwerem",serverPerformance:"Wydajność",serverFeatures:"Funkcje",serverBalance:"Balans gry",importExistingIni:"Importuj istniejący plik INI",importAndValidate:"Importuj i sprawdź",iniOutput:"Dane wyjściowe INI",serverNotice:"Dostępne są tylko ustawienia opisane w oficjalnym przewodniku po serwerze Palworld. Puste pola są pomijane, a cała zawartość pozostaje w tej przeglądarce.",serverNamePlaceholder:"Mój serwer Palworld",serverDescriptionPlaceholder:"Kooperacyjny serwer Palworld",passwordRequiredPlaceholder:"Wprowadź tylko w razie potrzeby",adminPasswordPlaceholder:"Użyj długiego, unikalnego hasła",warningUnsupportedKey:"Pominięto nieobsługiwany klucz: {key}",warningBoolean:"{key} musi mieć wartość True lub False.",warningNumber:"{key} musi być liczbą.",warningRange:"{key} jest poza obsługiwanym zakresem."}
};

export const databaseItemTabLabels:Record<Locale,string>={
  "en-US":"Item database",
  "ko-KR":"아이템",
  "ja-JP":"アイテムデータベース",
  "zh-CN":"道具数据库",
  "zh-TW":"道具資料庫",
  "fr-FR":"Base de données des objets",
  "it-IT":"Database degli oggetti",
  "de-DE":"Gegenstandsdatenbank",
  "es-ES":"Base de datos de objetos",
  "es-419":"Base de datos de objetos",
  "pt-BR":"Banco de dados de itens",
  "ru-RU":"База предметов",
  "id-ID":"Basis data item",
  "th-TH":"ฐานข้อมูลไอเทม",
  "tr-TR":"Eşya veritabanı",
  "vi-VN":"Cơ sở dữ liệu vật phẩm",
  "pl-PL":"Baza przedmiotów"
};

export const itemFilterAllLabelsProvenance="gpt" as const;
export const itemFilterAllLabels:Record<Locale,string>={
  "en-US":"All",
  "ko-KR":"전체",
  "ja-JP":"すべて",
  "zh-CN":"全部",
  "zh-TW":"全部",
  "fr-FR":"Tous",
  "it-IT":"Tutti",
  "de-DE":"Alle",
  "es-ES":"Todos",
  "es-419":"Todos",
  "pt-BR":"Todos",
  "ru-RU":"Все",
  "id-ID":"Semua",
  "th-TH":"ทั้งหมด",
  "tr-TR":"Tümü",
  "vi-VN":"Tất cả",
  "pl-PL":"Wszystkie"
};

export function formatUiCopy(template:string,values:Record<string,string|number>){return template.replace(/\{(\w+)\}/g,(_,key)=>String(values[key]??`{${key}}`))}
